### ISSUE TITLE
VTU read error, VTK types > 68 (Lagrange)

### ISSUE THREAD

**Issue by chrishavlin** [nschloe/meshio#1003]
I've got a VTU file with VTK cell type 72 (`VTK_LAGRANGE_HEXAHEDRON`). When trying to load with `meshio`:

```
mP = meshio.read('solution-00002.0001.vtu')
```
I get the following error:

```
Traceback (most recent call last):
  File "load_with_meshio.py", line 6, in <module>
    mP = meshio.read(pFile)
  File "/home/chavlin/miniconda3/envs/yt_dev/lib/python3.7/site-packages/meshio/_helpers.py", line 69, in read
    return reader_map[file_format](filename)
  File "/home/chavlin/miniconda3/envs/yt_dev/lib/python3.7/site-packages/meshio/vtu/_vtu.py", line 630, in read
    reader = VtuReader(filename)
  File "/home/chavlin/miniconda3/envs/yt_dev/lib/python3.7/site-packages/meshio/vtu/_vtu.py", line 509, in __init__
    point_offsets, cells, cell_data_raw
  File "/home/chavlin/miniconda3/envs/yt_dev/lib/python3.7/site-packages/meshio/vtu/_vtu.py", line 233, in _organize_cells
    cdr,
  File "/home/chavlin/miniconda3/envs/yt_dev/lib/python3.7/site-packages/meshio/vtu/_vtu.py", line 99, in _cells_from_data
    n = num_nodes_per_cell[meshio_type]
KeyError: 'VTK_LAGRANGE_HEXAHEDRON'
```

Checking out the code in `_common.py` it seems that the new vtk types added to the  `vtk_to_meshio_type` dict do not have corresponding entries in `num_nodes_per_cell` (or `_topological_dimension`). So I suspect that any `vtu` file with cell types >=68 will also fail  as well. 

In my case with `VTK_LAGRANGE_HEXAHEDRON`, the cells have 27 nodes, so if I just change 

```
    72: "VTK_LAGRANGE_HEXAHEDRON",
```

in the `vtk_to_meshio_type` dict to use the existing `hexahedron27` `meshio` type:

```
    72: "hexahedron27",
```
I can load my vtu file. 

I can submit a PR to fix the `VTK_LAGRANGE_HEXAHEDRON` cell type (I would probably add a new `lagrange_hexahedron` `meshio` type rather than simply having it use `hexahedron27`?) but I'm not familiar with the other VTK cell types >=68 and it may make more sense to have a PR address all of them?

**Comment by nschloe** [comment]
As always, we need a mesh file to to reproduce the issue.

**Comment by nschloe** [comment]
The problem with lagrange types is that the number of nodes is variable. You cannot simply hardcode it as hex27.

**Comment by chrishavlin** [comment]
Oh right! Didn't attach a sample file... here it is:

[vtu_sample.zip](https://github.com/nschloe/meshio/files/5809378/vtu_sample.zip)

Note that the `vtu` is actually part of `pvtu` output. The zipped file includes just 2 of the `vtu` chunks listed in the `pvtu` file. I'm currently using meshio to read the individual `vtu` files and then I handle the assembly across `vtu` files, so the present issue is only related to  reading a single `vtu` file but the zipped file has the `pvtu` file in case there's useful info in there that I missed.

And yes, I forgot that the lagrange types could be any order... so not a simple fix as I initially thought. At least in the case of `VTK_LAGRANGE_HEXAHEDRON` the cells are restricted to 3D, so 8, 27, 64, etc. nodes per cell. Unless a cell can use different orders for each dimension? Hmm. Ok... so the way to go would be inferring the number of points per cell directly from the vtu file?

Looking through the vtu metadata, each mesh piece has `NumberOfPoints` and `NumberOfCells` attributes, which actually get used by the `VtuReader` (lines 431-437 of `vtu/_vtu.py`). So for the general  `LAGRANGE` elements at least, could we not calculate the number of points per cell as `NumberOfPoints/NumberOfCells` and pass that along to use if the `_common.num_nodes_per_cell` dict does not have an entry for the cell type? 

I'm happy to give it a go if this seems like the right approach :)

**Comment by nschloe** [comment]
> so the way to go would be inferring the number of points per cell directly from the vtu file?

Yes. The same thing happens for polygons, too. meshio fails in `_cells_from_data()`, where polygons ar already handles separately.

> could we not calculate the number of points per cell as NumberOfPoints/NumberOfCells

I think not. The cells aren't guaranteed to be of the same type. Check out the polygon implementation, perhaps it works just the same.

**Comment by chrishavlin** [comment]
The polygon implementation looks promising! I just tested it out on my vtu file and it seemed to just work as is (loads without error, the resulting sizes of the various pieces seems correct) so I'll spend some more time with it and see if I can put together a PR. Thanks for all the help!
