### ISSUE TITLE
reading point and element data from .mphtxt

### ISSUE THREAD

**Issue by DeepaMahm** [nschloe/meshio#1004]
Hi All,
I would like to know if meshio can be used to read data from .mphtxt mesh files generated from COMSOL.

**Comment by nschloe** [comment]
No. Feel free to PR if you need it, though!

**Comment by DeepaMahm** [comment]
Hi @nschloe 

Thanks a lot for the response.  I have shared a sample file [here ](https://github.com/DeepaMahm/misc/blob/master/sample.mphtxt) for your kind reference. Could you please let me know if 
it is possible to provide support for parsing the point and element data from this file?
