### ISSUE TITLE
meshio fails when number of cells is too high

### ISSUE THREAD

**Issue by gcorsi1** [nschloe/meshio#1008]
I'm using *pygmsh* to generate my meshes automatically on *FEniCS*. I generate them, use *meshio* to write them to file in the **XDMF** format, and then I'm able to read the mesh again and use it in a parallel run. Unfortunately I get an error when *meshio* is called to convert the gmsh file to XDMF.
I simplified the mesh here so that it's just two concentric cylinders.
The code that generates the mesh converts it is the following:
```python
import numpy
import pygmsh
import meshio

Rout = 0.025  # OUTER RADIUS
Rin = 0.01  # INNER RADIUS
lcar_out = 0.0025  # OUTER BOUNDARY lcar VALUE
Hout = 10.0  # OUTER CYLINDER HEIGHT

geom = pygmsh.built_in.Geometry()
v_ = geom.add_pipe(inner_radius=Rin, outer_radius=Rout, length=Hout, lcar=lcar_out)
geom.add_physical(v_)
msh = pygmsh.generate_mesh(geom, geo_filename="./result.geo")
# NOW CONVERT GMSH FILE TO XDMF WITH MESHIO
tetra_cells = None
for cell in msh.cells:
    if cell.type == "tetra":
        # Collect the individual meshes
        if tetra_cells is None:
            tetra_cells = cell.data
        else:
            tetra_cells = numpy.vstack((tetra_cells, cell.data))
tetra_mesh = meshio.Mesh(points=msh.points, cells={"tetra": tetra_cells})
meshio.write("file_tmp.xdmf", tetra_mesh)

```

What I get when running this code is the following error:

```
Info    : Done optimizing mesh (20.9307 s)
Info    : 965971 nodes 5586122 elements
Info    : Writing '/tmp/tmpgx5q433l.msh'...
Info    : Done writing '/tmp/tmpgx5q433l.msh'
Info    : Stopped on Wed Jan 27 22:13:46 2021
Traceback (most recent call last):
  File "../testmsh.py", line 37, in <module>
    msh = pygmsh.generate_mesh(geom, geo_filename="./result.geo")
  File "/gpfswork/rech/gpb/uch36vb/fenics-2019/venv3.7/lib64/python3.7/site-packages/pygmsh/helpers.py", line 137, in generate_mesh
    mesh = meshio.read(msh_filename)
  File "/gpfswork/rech/gpb/uch36vb/fenics-2019/venv3.7/lib64/python3.7/site-packages/meshio/_helpers.py", line 68, in read
    return reader_map[file_format](filename)
  File "/gpfswork/rech/gpb/uch36vb/fenics-2019/venv3.7/lib64/python3.7/site-packages/meshio/gmsh/main.py", line 19, in read
    mesh = read_buffer(f)
  File "/gpfswork/rech/gpb/uch36vb/fenics-2019/venv3.7/lib64/python3.7/site-packages/meshio/gmsh/main.py", line 49, in read_buffer
    return reader.read_buffer(f, is_ascii, data_size)
  File "/gpfswork/rech/gpb/uch36vb/fenics-2019/venv3.7/lib64/python3.7/site-packages/meshio/gmsh/_gmsh41.py", line 64, in read_buffer
    f, point_tags, physical_tags, is_ascii, data_size, field_data
  File "/gpfswork/rech/gpb/uch36vb/fenics-2019/venv3.7/lib64/python3.7/site-packages/meshio/gmsh/_gmsh41.py", line 210, in _read_elements
    (num_ele, -1)
ValueError: cannot reshape array of size 15789687 into shape (4730528,newaxis)
```

The thing I've noticed is that I can avoid the error by simply lowering the amount of cells in the mesh, changing the parameters. If for instance I change lcar_out=0.005  in place of lcar_out=0.0025 in the code, resulting in a coarser mesh at the outer boundary, the code runs fine, and the mesh is correctly written to file. These meshes are quite large, when it works the result is a mesh with millions of cells already, but I don't understand what is going wrong when I run the same code but with a higher number of elements. The gmsh version is 4.5.2,  pygmsh==6.1.1,  meshio==4.3.8.

**Comment by nschloe** [comment]
Could you try to simplify the code more? 5 lines is the goal! :)

**Comment by gcorsi1** [comment]
I updated my comment, indeed to reproduce the issue I could use the add_pipe function directly, simplifying things a bit. The error still happens when using meshio to convert to xdmf, if the mesh is too refined, e.g. for lcar_out = 0.0025 in the code.
When this parameter is increased in order to make the mesh coarser, the code works

**Comment by nschloe** [comment]
I just tried running the code and noticed that it's using an outdated API of pygmsh. Perhaps upgrading will some your problems.

**Comment by gdmcbain** [comment]
A short cut for
```python
tetra_cells = None
for cell in msh.cells:
    if cell.type == "tetra":
        # Collect the individual meshes
        if tetra_cells is None:
            tetra_cells = cell.data
        else:
            tetra_cells = numpy.vstack((tetra_cells, cell.data))
```
is
```python
tetra_cells = msh.cells_dict('tetra')
```
Actually even this is unnecessary since `msh` contains only tetrahedra thanks to the declaration of `v_` as physical.

I'm having a bit of trouble running the example with `lcar_out` small enough to show the problem on my hardware, but to clarify the problem (I'm suspecting it's not actually pygmsh<7), I'd split the script into two: one to generate `result.geo`,
```python
import pygmsh

Rout = 0.025  # OUTER RADIUS
Rin = 0.01  # INNER RADIUS
lcar_out = 0.005  # OUTER BOUNDARY lcar VALUE
Hout = 10.0  # OUTER CYLINDER HEIGHT

geom = pygmsh.built_in.Geometry()
v_ = geom.add_pipe(inner_radius=Rin, outer_radius=Rout, length=Hout, lcar=lcar_out)
geom.add_physical(v_)

with open("result.geo", "w") as fgeo:
    fgeo.write(geom.get_code())
```
one to read the resulting MSH 4.1 and write XDMF.
```python
import meshio

msh = meshio.read("result.msh")
print(msh)
tetra_mesh = meshio.Mesh(msh.points, {"tetra": msh.cells_dict["tetra"]})
print(tetra_mesh)
meshio.write("file_tmp.xdmf", tetra_mesh)
```
My hunch is that the first script will run fine, producing a [result.geo](https://github.com/nschloe/meshio/files/5923374/geo.zip) of 39 lines which is valid regardless of `lcar_out`.  Then the error is either in Gmsh turning the GEO into MSH 4.1 or meshio in turning the MSH 4.1 into XDMF; hard to say before Gmsh finishes&hellip;

**Comment by gdmcbain** [comment]
I've managed to rerun this at `lcar_out = 0.0025` but failed to reproduce the problem.  Using the two-step approach, I get a MSH 4.1 and an XDMF which both look O. K.; too big to attach here (well the XDMF is only 4.0K but the HDF5 is 82M; the MSH 4.1 is 228M). but here are the summaries:
```shell
meshio-info result.msh
```
gives
```
<meshio mesh object>
  Number of points: 965924
  Number of cells:
    tetra: 4730890
  Cell sets: gmsh:bounding_entities
  Point data: gmsh:dim_tags
  Cell data: gmsh:physical, gmsh:geometrical
```
and
```shell
meshio-info file_tmp.xdmf 
```
gives
```
<meshio mesh object>
  Number of points: 965924
  Number of cells:
    tetra: 4730890
```

I'm using `pip install pygmsh==6.1.1 meshio==4.3.8 h5py` with Python 3.9.1 on Ubuntu 20.04.2 LTS and Gmsh 4.7.1 from a docker image, [gdmcbain/gmsh:4.7.1.0](https://hub.docker.com/layers/gdmcbain/gmsh/4.7.1.0/images/sha256-64fc0a6049390d9a21b81f9627d486e3922c59f7d03aebba75faf5019ea2aaba?context=explore).

(I don't mean to endorse pinning pygmsh<7, just showing that it's not the fault here; for a clear rationale of pygmsh 7, see nschloe/pygmsh#380.)

**Comment by gcorsi1** [comment]
I honestly don't know what might cause the problem in my case but not in yours, for me it clearly arises when the number of cells starts to get very high, and pygmsh calls meshio

I also observed that switching to pygmsh 7.1.5, the call to meshio is done automatically and the mesh generation produces directly a meshio object. 

With this new pygmsh API the issue does not arise anymore, which is another conclusion that differs from what you found. Maybe the problem could be due to a specific combination of my installation/hardware?

**Comment by gdmcbain** [comment]
Does your Gmsh installation successfully turn the GEO (attached above) into MSH 4.1? Call like:
```shell
gmsh -3 result.geo
```

Note that Gmsh works very differently when used with its Python API compared to with its GEO code input.

Envoyé depuis ProtonMail mobile

-------- Message d'origine --------

**Comment by gcorsi1** [comment]
yes  (it's gmsh 4.5.2)
```
gmsh -3 result.geo
```
runs fine, even for mesh size 0.0025:
```
Info    : 3 ill-shaped tets are still in the mesh
Info    : 0.00 < quality < 0.10 :         3 elements
Info    : 0.10 < quality < 0.20 :         5 elements
Info    : 0.20 < quality < 0.30 :       106 elements
Info    : 0.30 < quality < 0.40 :     85276 elements
Info    : 0.40 < quality < 0.50 :    127637 elements
Info    : 0.50 < quality < 0.60 :    224815 elements
Info    : 0.60 < quality < 0.70 :    506456 elements
Info    : 0.70 < quality < 0.80 :   1167237 elements
Info    : 0.80 < quality < 0.90 :   1784992 elements
Info    : 0.90 < quality < 1.00 :    833549 elements
Info    : Done optimizing mesh (20.761 s)
Info    : 965971 nodes 5586122 elements
Info    : Writing 'result.msh'...
Info    : Done writing 'result.msh'
Info    : Stopped on Sun Feb  7 15:03:20 2021
```

**Comment by gdmcbain** [comment]
But then your meshio fails to read that MSH 4.1 and construct a `meshio.Mesh`?

**Comment by gcorsi1** [comment]
actually your script 

```
import meshio

msh = meshio.read("result.msh")
print(msh)
tetra_mesh = meshio.Mesh(msh.points, {"tetra": msh.cells_dict["tetra"]})
print(tetra_mesh)
meshio.write("file_tmp.xdmf", tetra_mesh)
```

runs with output
```<meshio mesh object>
  Number of points: 965969
  Number of cells:
    tetra: 4730528
  Cell data: gmsh:physical
<meshio mesh object>
  Number of points: 965969
  Number of cells:
    tetra: 4730528
```

So I guess it was something related to (old version) pygmsh calling meshio

**Comment by gdmcbain** [comment]
Hmm, but [recall](https://github.com/nschloe/meshio/issues/1008#issuecomment-773684236) that it works fine when

> I'm using pip install pygmsh==6.1.1 meshio==4.3.8 h5py with Python 3.9.1 on Ubuntu 20.04.2 LTS and Gmsh 4.7.1 from a docker image, gdmcbain/gmsh:4.7.1.0.

and 6.1.1 was your [original](https://github.com/nschloe/meshio/issues/1008#issue-795215575) pygmsh version.

**Comment by gcorsi1** [comment]
I am confused as to what caused the issue then, I think it was due to the particular installation in the HPC environment where I was running the case. However, updating to the latest available version of pygmsh/meshio solved the issue completely for me.
