### ISSUE TITLE
meshio-convert cannot use cgns mesh as input

### ISSUE THREAD

**Issue by yhaomin2007** [nschloe/meshio#1009]
Hi, i want to convert a cgns mesh into exodus mesh.
but it seems meshio-convert cannot take cgns as input. 

* Make sure to include a MINIMAL, COMPLETE EXAMPLE that can be copy-pasted and shows the
  bug.
* If you're having problems with a mesh, you can attach it as a zip file. Make it small!
* Use [GitHub markdown](https://guides.github.com/features/mastering-markdown/),
  especially triple-fences for code blocks.

**Comment by nschloe** [comment]
This is missing all necessary info, closing. Feel free to reopen with an MWE and a mesh.
