### ISSUE TITLE
BUG: VARLOCATION in _tecplot.py : _read_zone()

### ISSUE THREAD

**Issue by frankeye** [nschloe/meshio#1013]
For the code block beginning with:
`    # If zone contains VARLOCATION, process it and remove the key/value pair
`
the last line of block:
`line = line[:ivar] + line[i2 + 1 :]`
should instead be:
`line = line[:ivar] + line[i2 :]`

**Comment by keurfonluu** [comment]
May you provide a sample file for which the current reader doesn't work, but work with your fix?

**Comment by frankeye** [comment]
Yes, attached are two files, the _workaround named file will work because I inserted a dummy zone header entity at the end, so that the buggy-code's deletion of the extra character will not disrupt further parsing.  Reading the other attached file will trigger the "Zone type 'ZONETYPE' not found" exception. 

(P.S.: I've never liked Python's var[i:j] range indexing; a newbie would expect it to include the j (actually j+1) element)

[varlocation_bug.zip](https://github.com/nschloe/meshio/files/5974290/varlocation_bug.zip)

**Comment by frankeye** [comment]
Hi, oh duh! the fix you actually made addressed the root cause - my suggestion was nonsense :-) 
Thanks!
