### ISSUE TITLE
Tecplot reader: minor nits worth fixing?

### ISSUE THREAD

**Issue by frankeye** [nschloe/meshio#1015]
Hi, 
Thanks for gifting meshio to the rest of us!  
The capabilities and generality of the Tecplot reader are very impressive, yet there are a few simple nits that disrupt user flow from time to time.  I'll indicate two that are seemingly simple to fix, but more importantly I want to ask: are you amenable to receiving such suggestions?  I can understand if you are not :-)

Anyway, here are two.  Regarding Tecplot ascii file format, I make reference to: Tecplot Data Format Guide, Tecplot, Inc. (2020): [https://download.tecplot.com/360/current/360_data_format_guide.pdf](url)  Both points below pertain to Guide section 4-2.  

1. The reader presently does not ignore comment lines (lines which begin with '#'). 
2. With the present reader, the VARIABLES list of the file header must appear on one line, whereas the Guide indicates it can span multiple lines (as do many .dat files in the wild).  

Thanks!

**Comment by keurfonluu** [comment]
Hi,

I can look into that. It is usually easier for us to implement requested features when sample files are provided.

**Comment by frankeye** [comment]
Thanks!  Will close this, and open two new separate issues.
