### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by VKheyfets** [nschloe/meshio#102]
Hello,

I get a "Memory Error" when converting an ansys .msh to a vtu-binary. 

In fact, it's a 3d volume mesh, but the code output says: "number of triangles."

Is it possible that it's recognizing the wrong kind of mesh? 

Thank You,

Vitaly

**Comment by nschloe** [comment]
Certainly possible. With the mesh, it's impossible to properly debug though.

**Comment by nschloe** [comment]
Closing for lack of response. Feel free to reopen (ideally with a mesh that reproduces the problem).
