### ISSUE TITLE
empty meshes can be created but not processed

### ISSUE THREAD

**Issue by dominik-kern** [nschloe/meshio#1022]
I am afraid this is a pedantic issue, still it may be relevant for batch processing.
It is possible to create a mesh without cells, a _zero cell mesh_, but ``remove_orphaned_nodes`` and ``write`` exit with a (plausible) error: ``...ValueError: need at least one array to concatenate``

```
import meshio
import numpy
points=numpy.array([[0,0,0],[0,1,0],[1,1,0],[1,0,0]])
point_data={'point_tag': numpy.array([9,9,9,9])}
mesh=meshio.Mesh(points=points, point_data=point_data, cells=[])   # possible to create zero cell mesh
#mesh.remove_orphaned_nodes()    # fails on zero cell mesh
#mesh.write('zero_cell_mesh.vtu')   # fails on zero cell mesh
```

**Comment by nschloe** [comment]
That's a bug, for sure. I'll look into it.

**Comment by nschloe** [comment]
I've fixed this for a majority of formats. Maybe there are some left-overs; feel free reopen if you ever bump into one.

**Comment by duhd1993** [comment]
I run into this error. cells=[] can be written to vtk and paraview can read it. but meshio.read fails.
```
    meshio_type = vtk_to_meshio_type[types[start]]
                                     ~~~~~^^^^^^^
IndexError: index 0 is out of bounds for axis 0 with size 0

```
@nschloe
