### ISSUE TITLE
meshio-convert

### ISSUE THREAD

**Issue by ElisabethSuzanne** [nschloe/meshio#1040]
Hello, i want to convert a ply.file into a stl. file and i want to use the meshio bib. 

But i can't find any exaple how to use meshio-convert. 

THX!

**Comment by nschloe** [comment]
Have you tried looking at the first example in the main readme?

**Comment by ElisabethSuzanne** [comment]
i try this: 

input= meshio.read(os.path.join(path_modelle,'obj_000001.ply'))
output= meshio.read(os.path.join(path_modelle,'obj_000001.stl'))

meshio-convert    input.ply output.stl

but then i got an SyntaxError: invalid syntax error

**Comment by ElisabethSuzanne** [comment]
i tryed this : 

input= meshio.read(os.path.join(path_modelle,'obj_000001.ply'))

meshio-convert    input.ply (os.path.join(path_modelle,'obj_000001.stl')

but i got an SyntaxError: invalid syntax

**Comment by nschloe** [comment]
Note that `meshio-convert` is a command-line program, not a Python one.

**Comment by ElisabethSuzanne** [comment]
so i can't use it in my Python script?

**Comment by nschloe** [comment]
That's right.

**Comment by ElisabethSuzanne** [comment]
that makes sense... i tryed it in my anaconda prompt an it worked
