### ISSUE TITLE
Odd exit in NASTRAN reader

### ISSUE THREAD

**Issue by whophil** [nschloe/meshio#1041]
I have a BDF file which read fine with `meshio==4.3.1`, but does not with `4.3.10`. The regression seems to have been introduced with the merge of #988 

It seems the BDF file I was using was improperly formatted - it ends with `END BULK` instead of `ENDDATA`.

Nevertheless, when using 4.3.10 to read the improperly formatted file, the program would `exit(1)`, which doesn't seem like the right behavior. This should either raise a more informative error message, or just break out of the data reading loop entirely.

https://github.com/nschloe/meshio/blob/cdce0af7cafc9e72365bd4237605b4c58a1c6b0a/meshio/nastran/_nastran.py#L117-L123

[test.bdf.zip](https://github.com/nschloe/meshio/files/6086755/test.bdf.zip)

**Comment by nschloe** [comment]
>  the program would exit(1), which doesn't seem like the right behavior.

Absolutely. Looking at it right now.
