### ISSUE TITLE
XDMF-Timeseries Example from pypi raises Attribute Error

### ISSUE THREAD

**Issue by Batazai** [nschloe/meshio#1052]
Hi, 
I cannot tell how much I appreciate the package. Thanks!

The following code from the exampel section of the pypi website raises an AttributeError:

```python
import meshio
points = [
    [0.0, 0.0, 0.0],
    [0.0, 1.0, 0.0],
    [0.0, 0.0, 1.0],
]
cells = [("triangle", [[0, 1, 2]])]
filename = "./delete_me_xdmf_example.xdmf"
with meshio.xdmf.TimeSeriesWriter(filename) as writer:
    writer.write_points_cells(points, cells)
```
Meshio version: 4.3.8
From: conda-forge

Edits:
1. Add filename
2. Remove obviously not working solution suggestion

**Comment by gdmcbain** [comment]
Indeed, whereas 
```python
meshio.Mesh(points, cells)
```
is fine.

**Comment by gdmcbain** [comment]
```python
    writer.write_points_cells(np.array(points), [(t, np.array(c)) for t, c in cells])
```
is a makeshift, but I reckon this should be fixed&mdash;should be easy enough, I'll take a look.

**Comment by Batazai** [comment]
Super cool, thanks!
