### ISSUE TITLE
can meshio support vtu multiblock files (vtm)?

### ISSUE THREAD

**Issue by bigfooted** [nschloe/meshio#1058]
I'm interested in reading vtm multiblock files, which is basically a wrapper format for multiple vtu files.
An example is given below for a file with a single fluid zone and a number of edges. I am hoping that during conversion to other formats (I'm interested in writing the mesh to su2 format) we can then preserve the boundary information (the marker geometry).
Is there already some internal data storage structure that could support multiblock, so we could basically loop over the datasets in the vtm file, or is more effort involved?

```
<VTKFile type="vtkMultiBlockDataSet" version="1.0">
<vtkMultiBlockDataSet>
<Block name="Zone 0 (Incomp. Fluid)">
<Block name="Internal">
<DataSet name="Internal" file="config/zone_0/Internal.vtu"/>
</Block>
<Block name="Boundary">
<DataSet name="axis" file="config/zone_0/axis.vtu"/>
<DataSet name="gas_inlet" file="config/zone_0/gas_inlet.vtu"/>
<DataSet name="air_inlet" file="config/zone_0/air_inlet.vtu"/>
<DataSet name="outlet" file="config/zone_0/outlet.vtu"/>
<DataSet name="wall-component1-surface" file="config/zone_0/wall-component1-surface.vtu"/>
</Block>
</Block>
</vtkMultiBlockDataSet>
<FieldData>
<DataArray type='Float32' Name='TimeValue'>
0
</DataArray>
</FieldData>
</VTKFile>
```

**Comment by nschloe** [comment]
What's a "multiblock"?

**Comment by bigfooted** [comment]
So basically you have multiple meshes, for instance a fluid mesh for the fluid zone and a solid mesh for the solid zone. Also their solutions are stored separately, each in their own files, in my case vtu files. In the case of vtm, you can also store the boundaries as separate blocks, which can be very convenient for postprocessing.

**Comment by nschloe** [comment]
No, multiple meshes are not supported by meshio at the moment.

**Comment by bigfooted** [comment]
ok, thanks. I will work with an array of meshio meshes then and call meshio for each of the vtu files in the vtm.
