### ISSUE TITLE
MED to VTK cell_data ordering

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [nschloe/meshio#1060]
When converting from MED to VTK, the cell_data seems to have the wrong order.

In the following example, all tets are tagged with `9`, top surface triangles are tagged with `8`, bottom surface triangles are tagged with `7` and side surface triangles are tagged with `6`.

For tets (expected right, produced left):
![image](https://user-images.githubusercontent.com/40028739/112963802-060b2a80-9148-11eb-87e7-799654cccc9a.png)

For triangles (expected right, produced left):
![image](https://user-images.githubusercontent.com/40028739/112963944-26d38000-9148-11eb-8a40-97fbc80ae8df.png)

**How to reproduce**

```python
import meshio

mesh = meshio.read('mesh_cylinder.med')

# this produces the expected behaviour (XDMF)

meshio.Mesh(
    mesh.points,
    [mesh.cells[1]],
    cell_data={
        "f": [-1*mesh.cell_data["cell_tags"][1]],
        },
).write("foo_vol.xdmf")

meshio.Mesh(
    mesh.points,
    [mesh.cells[2]],
    cell_data={
        "f": [-1*mesh.cell_data["cell_tags"][2]],
        },
).write("foo_bound.xdmf")

# VTK export somehow shuffles the cells

meshio.Mesh(
    mesh.points,
    [mesh.cells[1]],
    cell_data={
        "f": [-1*mesh.cell_data["cell_tags"][1]],
        },
).write("foo_vol.vtk")

meshio.Mesh(
    mesh.points,
    [mesh.cells[2]],
    cell_data={
        "f": [-1*mesh.cell_data["cell_tags"][2]],
        },
).write("foo_bound.vtk")
```

[mesh_cylinder.zip](https://github.com/nschloe/meshio/files/6227810/mesh_cylinder.zip)

**Comment by nschloe** [comment]
This somehow got fixed along the way; it produces the correct results now.
