### ISSUE TITLE
Ansys Fluent msh ReadError

### ISSUE THREAD

**Issue by scarpma** [nschloe/meshio#1064]
Hi, I'm trying to open an msh file with a mesh of an aorta. The msh file has been produced by ANSA by exporting for Ansys Fluent solver. I tried with binary, ascii and hdf5 encoding.

The code I use is the following:

```python
import meshio
path = '/home/scarpma/Downloads/aorta46.msh'
a = meshio.read(path, file_format="ansys")
```
and the error I get is this:
```python
WARNING:root:Unknown index '37'. Skipping.

---------------------------------------------------------------------------
ReadError                                 Traceback (most recent call last)
<ipython-input-10-6a2ecf48c9a4> in <module>
      1 import meshio
      2 path = '/home/scarpma/Downloads/aorta46.msh'
----> 3 a = meshio.read(path, file_format="ansys")

~/miniconda3/lib/python3.6/site-packages/meshio/_helpers.py in read(filename, file_format)
     67         raise ReadError(msg)
     68 
---> 69     return reader_map[file_format](filename)
     70 
     71 

~/miniconda3/lib/python3.6/site-packages/meshio/ansys/_ansys.py in read(filename)
    336                 # points
    337                 pts, first_point_index_overall, last_point_index = _read_points(
--> 338                     f, line, first_point_index_overall, last_point_index
    339                 )
    340 

~/miniconda3/lib/python3.6/site-packages/meshio/ansys/_ansys.py in _read_points(f, line, first_point_index_overall, last_point_index)
     43 
     44     if len(a) <= 4:
---> 45         raise ReadError()
     46 
     47     first_point_index = a[1]

ReadError: 
```

Since the file is too big, I uploaded it to my [drive](https://drive.google.com/file/d/1BV9mZvETA7W7ToqK_FU5NsLzV6eNqdqY/view?usp=sharing).

@nschloe could you help me on this, please ? 

Thank you in advance !

**Comment by scarpma** [comment]
Anyone who might give some advice ? @nschloe  ?

**Comment by nschloe** [comment]
I've got no time for this right now unfortunately. Would review a PR though.

**Comment by scarpma** [comment]
> I've got no time for this right now unfortunately. Would review a PR though.

Ah, I see. Thank you anyway for your answer.

What is a PR ?

**Comment by nschloe** [comment]
> What is a PR ?

[pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests)

**Comment by nschloe** [comment]
The linked file is no longer available, so the issue cannot be reproduced anymore. Closing.

Feel free to reopen with a new link, or even better a _smaller_ example that can be attached to this issue.
