### ISSUE TITLE
Writing a polygon as vtu

### ISSUE THREAD

**Issue by ofbodur** [nschloe/meshio#1081]
Hi Meshio creators and users,

I am trying to save a data about 50 points, with connections from 0th to last, and closing the loop with the last connection, to write it as a polygon data to visualise in ParaView. Line works, but polygon, as you all know, is more fancy because it has a surface that you can color.

I got the following error during my attempts:

```
ValueError                                Traceback (most recent call last)
<ipython-input-96-39ae0bdb2ba4> in <module>()
     57         cells = {"polygon": myconnectivityNumpy}
     58         if(len(pointsToWrite)>3):
---> 59             meshio.write_points_cells(Root+'CoastlinesVTK/'+"Coastlines_%02d_Ma_Section_%02d.vtu"                                       %(Age,subductionNumber),pointsToWriteShaped[:-1],cells,file_format='vtu')
     60 
     61 #         STOP

/Users/omer/opt/anaconda2/lib/python2.7/site-packages/meshio/helpers.pyc in write_points_cells(filename, points, cells, point_data, cell_data, field_data, file_format, **kwargs)
    190         points, cells, point_data=point_data, cell_data=cell_data, field_data=field_data
    191     )
--> 192     return write(filename, mesh, file_format=file_format, **kwargs)
    193 
    194 

/Users/omer/opt/anaconda2/lib/python2.7/site-packages/meshio/helpers.pyc in write(filename, mesh, file_format, **kwargs)
    209     for key, value in mesh.cells.items():
    210         if key[:7] == "polygon":
--> 211             assert value.shape[1] == int(key[7:])
    212         else:
    213             assert value.shape[1] == num_nodes_per_cell[key]

ValueError: invalid literal for int() with base 10: ''
```

Any hint or help is greatly appreciated.
Best,

**Comment by nschloe** [comment]
MWE please.

**Comment by ofbodur** [comment]
> MWE please.

Sorry, I didn't get what it means. Maybe I'm too old to understand that abbrev. :)

**Comment by nschloe** [comment]
Minimal working example.

**Comment by ofbodur** [comment]
```
import meshio
import numpy as np


myconnectivity=[]
for myindex in arange(0,48,1):
    myCells=[0]*2
    myCells[0]=myindex
    myCells[1]=myindex+1
    myconnectivity.append(myCells)    

myconnectivity.append([len(pointsToWriteShaped)-2,0])

myconnectivityNumpy=np.asarray(myconnectivity)

# print(myconnectivityNumpy, "is my connectivity")

cells = {"polygon": myconnectivityNumpy}

meshio.write_points_cells(Root+'CoastlinesVTK/'+"Coastlines.vtu",pointsToWriteShaped[:-1],
                          cells,file_format='vtu')    


```

And, here is my data, pointsToWriteShaped[:-1],: (they are XYZ points in 3D cartesian space)

array([[-0.29115427,  0.71775546,  0.63250003],
       [-0.30036265,  0.7060863 ,  0.64126782],
       [-0.30409606,  0.700945  ,  0.64513696],
       [-0.31534298,  0.68880762,  0.65276556],
       [-0.31936499,  0.68298883,  0.65691115],
       [-0.32185804,  0.68021619,  0.65856916],
       [-0.32597405,  0.67374215,  0.66318355],
       [-0.32733004,  0.66996927,  0.66633041],
       [-0.32833396,  0.66334341,  0.6724376 ],
       [-0.32954595,  0.66187323,  0.67329287],
       [-0.33013418,  0.6612707 ,  0.67359668],
       [-0.33541015,  0.65872303,  0.67348646],
       [-0.3602656 ,  0.64509105,  0.67384437],
       [-0.37488464,  0.63865942,  0.67199378],
       [-0.37871475,  0.63653882,  0.67185822],
       [-0.37345041,  0.64531743,  0.66640844],
       [-0.36963045,  0.65006116,  0.66392305],
       [-0.36628194,  0.65505602,  0.66086243],
       [-0.36449269,  0.66019637,  0.65672356],
       [-0.36171483,  0.66239065,  0.65604954],
       [-0.35942133,  0.66512655,  0.65454028],
       [-0.35295507,  0.6690917 ,  0.6540176 ],
       [-0.34826828,  0.67158135,  0.65397836],
       [-0.3434968 ,  0.67566043,  0.6522982 ],
       [-0.33965622,  0.67952669,  0.65029004],
       [-0.33634103,  0.68393067,  0.6473898 ],
       [-0.33288107,  0.68987703,  0.64285292],
       [-0.33152839,  0.69375332,  0.63937099],
       [-0.32963313,  0.69949403,  0.63407421],
       [-0.32784575,  0.70641887,  0.62728745],
       [-0.32626996,  0.71084721,  0.62309241],
       [-0.32661822,  0.71632683,  0.6166007 ],
       [-0.33746294,  0.7468723 ,  0.57297515],
       [-0.34818638,  0.77303474,  0.53026742],
       [-0.3397486 ,  0.77421712,  0.53400256],
       [-0.32284275,  0.77503046,  0.54323139],
       [-0.29994038,  0.77802629,  0.55200622],
       [-0.28535784,  0.78069718,  0.55595217],
       [-0.27864964,  0.78294166,  0.55619847],
       [-0.26710968,  0.78564776,  0.55804123],
       [-0.26693251,  0.78565427,  0.55811683],
       [-0.27016424,  0.78251087,  0.5609706 ],
       [-0.27385785,  0.77911991,  0.56389187],
       [-0.27970288,  0.77301068,  0.56940388],
       [-0.28429897,  0.76534264,  0.57742942],
       [-0.28733688,  0.75392867,  0.59078683],
       [-0.28397916,  0.7392795 ,  0.61059123],
       [-0.28355493,  0.73195893,  0.61954235],
       [-0.28449148,  0.72641813,  0.62560475]])

**Comment by ofbodur** [comment]
and here is my cells:


{'polygon': array([[ 0,  1],
        [ 1,  2],
        [ 2,  3],
        [ 3,  4],
        [ 4,  5],
        [ 5,  6],
        [ 6,  7],
        [ 7,  8],
        [ 8,  9],
        [ 9, 10],
        [10, 11],
        [11, 12],
        [12, 13],
        [13, 14],
        [14, 15],
        [15, 16],
        [16, 17],
        [17, 18],
        [18, 19],
        [19, 20],
        [20, 21],
        [21, 22],
        [22, 23],
        [23, 24],
        [24, 25],
        [25, 26],
        [26, 27],
        [27, 28],
        [28, 29],
        [29, 30],
        [30, 31],
        [31, 32],
        [32, 33],
        [33, 34],
        [34, 35],
        [35, 36],
        [36, 37],
        [37, 38],
        [38, 39],
        [39, 40],
        [40, 41],
        [41, 42],
        [42, 43],
        [43, 44],
        [44, 45],
        [45, 46],
        [46, 47],
        [47, 48],
        [48,  0]])}

**Comment by nschloe** [comment]
Just supply some _minimal_ code that anyone can copy-and-paste to reproduce the error. It's usually a little bit of work to minimize the example, but I'm sure you can do it!

**Comment by ofbodur** [comment]
How about this one:


```
import meshio
import numpy as np

pointsToWriteShapedShort=([-0.29115427,  0.71775546,  0.63250003],
       [-0.30036265,  0.7060863 ,  0.64126782],
       [-0.30409606,  0.700945  ,  0.64513696],
       [-0.31534298,  0.68880762,  0.65276556],
       [-0.31936499,  0.68298883,  0.65691115],
       [-0.32185804,  0.68021619,  0.65856916],
       [-0.32597405,  0.67374215,  0.66318355],
       [-0.32733004,  0.66996927,  0.66633041],
       [-0.32833396,  0.66334341,  0.6724376 ])

myconnectivity=[]

for myindex in arange(0,8,1):
    myCells=[0]*2
    myCells[0]=myindex
    myCells[1]=myindex+1
    myconnectivity.append(myCells)    

myconnectivity.append([len(pointsToWriteShapedShort)-1,0])

print(myconnectivity)

myconnectivityNumpy=np.asarray(myconnectivity)

# print(myconnectivityNumpy, "is my connectivity")

cells = {"polygon": myconnectivityNumpy}

meshio.write_points_cells("Coastlines.vtu",pointsToWriteShapedShort,cells,file_format='vtu')    

```

**Comment by nschloe** [comment]
Have you tried copy-and-pasting it into a file?

**Comment by ofbodur** [comment]
> Have you tried copy-and-pasting it into a file?

Anyone who can open a Jupiter notebook in their computer and copy and paste my last comment will be able to produce the same error. Isn't that enough?

**Comment by ofbodur** [comment]
> > Have you tried copy-and-pasting it into a file?
> 
> Anyone who can open a Jupyter notebook in their computer and copy and paste my last comment will be able to produce the same error. Isn't that enough?

Assuming they have installed numpy and meshio.

**Comment by nschloe** [comment]
Now it works, thanks for editing.

**Comment by nschloe** [comment]
This works:
```
import meshio

pointsToWriteShapedShort = (
    [-0.29115427, 0.71775546, 0.63250003],
    [-0.30036265, 0.7060863, 0.64126782],
    [-0.30409606, 0.700945, 0.64513696],
    [-0.31534298, 0.68880762, 0.65276556],
    [-0.31936499, 0.68298883, 0.65691115],
    [-0.32185804, 0.68021619, 0.65856916],
    [-0.32597405, 0.67374215, 0.66318355],
    [-0.32733004, 0.66996927, 0.66633041],
    [-0.32833396, 0.66334341, 0.6724376],
)

cells = {"polygon9": [[0, 1, 2, 3, 4, 5, 6, 7, 8]]}

meshio.write_points_cells("Coastlines.vtu", pointsToWriteShapedShort, cells)
```
The issue was that "polygon" was missing the "9". The error message is now improved, too.

**Comment by ofbodur** [comment]
> This works:
> 
> ```python
> import meshio
> 
> pointsToWriteShapedShort = (
>     [-0.29115427, 0.71775546, 0.63250003],
>     [-0.30036265, 0.7060863, 0.64126782],
>     [-0.30409606, 0.700945, 0.64513696],
>     [-0.31534298, 0.68880762, 0.65276556],
>     [-0.31936499, 0.68298883, 0.65691115],
>     [-0.32185804, 0.68021619, 0.65856916],
>     [-0.32597405, 0.67374215, 0.66318355],
>     [-0.32733004, 0.66996927, 0.66633041],
>     [-0.32833396, 0.66334341, 0.6724376],
> )
> 
> cells = {"polygon9": [[0, 1, 2, 3, 4, 5, 6, 7, 8]]}
> 
> meshio.write_points_cells("Coastlines.vtu", pointsToWriteShapedShort, cells)
> ```
> 
> The error message is now improved, too.

I still get the following error:

`AttributeError: 'tuple' object has no attribute 'shape'
`

**Comment by ofbodur** [comment]
By the way, is 'polygon9' a new feature in meshio? The version I use seems not recognising.

**Comment by nschloe** [comment]
> By the way, is 'polygon9' a new feature in meshio? The version I use seems not recognising.

No, that's old. I've just released 4.3.13, maybe that'll solve your problems.

**Comment by ofbodur** [comment]
Thanks, it works now. Does meshio allow to create multiple polygons in a single file?

**Comment by nschloe** [comment]
Sure, it works just like any other cell:
```python
cells = {"polygon9": [
    [0, 1, 2, 3, 4, 5, 6, 7, 8],
    [0, 1, 2, 3, 4, 5, 6, 7, 8],
    # ...
]}
```
