### ISSUE TITLE
CGNS file can not be read by meshio

### ISSUE THREAD

**Issue by zgbj0000zc** [nschloe/meshio#1101]
Dear nschloe, I want use meshio to convert my *.cgns mesh to gmsh, but when I read my sphere.cgns, the output is 
```
Unable to open object (object 'Zone1' doesn't exist) 
```
My cgns mesh is export from pointwise, and I put it in the attachment. 
Please give me some advice, thank you. 
[sphere.zip](https://github.com/nschloe/meshio/files/6466218/sphere.zip)

**Comment by nschloe** [comment]
meshio's CGNS expectes `Zone1` in `Base`. This is not the case with your file, hence the failure.

**Comment by Lovis-spec** [comment]
Hello, 

I try to read .cgns with meshio too. What do you mean with "Zone1 in Base"?

Thank you!
