### ISSUE TITLE
XDMF Read Failing

### ISSUE THREAD

**Issue by lkuna24** [nschloe/meshio#1117]
I am not sure whats going on but for some reason Meshio is failing to read in the following XDMF:
```
<?xml version="1.0"?>
<!DOCTYPE Xdmf SYSTEM "Xdmf.dtd"[]>
<Xdmf xmlns:xi="http://www.w3.org/2003/XInclude" Version="2.2">
 <Domain>
  <Grid Name="micro" GridType="Uniform">
    <Topology TopologyType="3DCoRectMesh" Dimensions="550 150 140 "></Topology> 
    <Geometry Type="ORIGIN_DXDYDZ">
      <!-- Origin  Z, Y, X -->
      <DataItem Format="XML" Dimensions="3">0 0 0</DataItem>
      <!-- DxDyDz (Spacing/Resolution) Z, Y, X -->
      <DataItem Format="XML" Dimensions="3">5.000000e-06 5.000000e-06 5.000000e-06</DataItem> 
    </Geometry>
    <Attribute Name="gID" AttributeType="Scalar" Center="Cell">
      <DataItem Format="HDF" Dimensions="550 150 140" NumberType="Int" Precision="4" > 
CA3Dsingle1511_out.h5:micro/gID 
      </DataItem>
    </Attribute>
  </Grid>
 </Domain>
</Xdmf>

```

It throws the following errors at me, and I'm not sure how to proceed:

> Traceback (most recent call last):
> File "/usr/local/bin/meshio-convert", line 8, in sys.exit(convert())
> File "/usr/local/lib/python3.9/site-packages/meshio/_cli/_convert.py", line 15, in convert mesh = read(args.infile, file_format=args.input_format)
> File "/usr/local/lib/python3.9/site-packages/meshio/_helpers.py", line 69, in read return reader_mapfile_format
> File "/usr/local/lib/python3.9/site-packages/meshio/xdmf/main.py", line 29, in read return XdmfReader(filename).read()
> File "/usr/local/lib/python3.9/site-packages/meshio/xdmf/main.py", line 47, in read return self.read_xdmf2(root)
> File "/usr/local/lib/python3.9/site-packages/meshio/xdmf/main.py", line 165, in read_xdmf2 raise ReadError()
> meshio._exceptions.ReadError

I have attached the corresponding XDMF and h5 files which cause this error.  There is no timeseries component to this mesh.
Even just trying to read the file fails, but ultimately I would like to convert it to exodus.

[Meshio_XDMF_Fail.zip](https://github.com/nschloe/meshio/files/6599008/Meshio_XDMF_Fail.zip)

**Comment by nschloe** [comment]
The attached file is 500MB+. This is not minimal. Feel free to reopen with a small example.

**Comment by lkuna24** [comment]
Here is a much smaller example:

[Meshio_XDMF_Fail.zip](https://github.com/nschloe/meshio/files/6599970/Meshio_XDMF_Fail.zip)

**Comment by nschloe** [comment]
meshio doesn't support structured meshes, see https://github.com/nschloe/meshio/issues/404. I added a clearer error message:
```
meshio._exceptions.ReadError: Need exactly 1 data item in <Topology>, found 0.
Structured meshes are not supported, see <https://github.com/nschloe/meshio/issues/404>.
```
