### ISSUE TITLE
New Format: triangle

### ISSUE THREAD

**Issue by Spectre5** [nschloe/meshio#1126]
Add support for the strictly 2D triangle (and triangle6) mesh from https://www.cs.cmu.edu/~quake/triangle.html.  The format is very, very similar to TetGen, so that file would make an easier starting point.

Note though, that "triangle" uses a different node numbering than is used in the `meshio` wiki.

**Comment by nschloe** [comment]
Do you have any example files?

**Comment by Spectre5** [comment]
Here is the output of the provided example from the source code.  The zip file with name first_order is running `./triangle -z A.poly` and second_order is the result of `./triangle -zo2 A.poly` to create second order elements.  My understanding is that the .poly files would not be needed for `meshio`, but are included for completeness since it is a default output from the program.

[first_order.zip](https://github.com/nschloe/meshio/files/8550166/first_order.zip)
[second_order.zip](https://github.com/nschloe/meshio/files/8550167/second_order.zip)

**Comment by Spectre5** [comment]
Note that both [meshpy](https://github.com/inducer/meshpy) and [triangle](https://github.com/drufat/triangle) provide Python interfaces to triangle.

**Comment by nschloe** [comment]
Alright, will be part of the next release.
