### ISSUE TITLE
Problem when converting from .msh to .off

### ISSUE THREAD

**Issue by BiekeD** [nschloe/meshio#1131]
Hello,
When trying to convert a .msh file which I exported from Gmsh to a .off file, I get the following error
```
File "~\meshio\off\_off.py", line 68, in write
    f'OFF only supports triangle cells. Skipping {", ".join(skip)}.'
TypeError: sequence item 0: expected str instance, CellBlock found
```

I am using Python 3.8.8 and meshio 4.4.6.

A minimal working example that produces this error:
```python
import meshio

mesh = meshio.read('test_meshes/not_working_GUC_gmsh_v2.2.msh')
mesh.write('test_meshes/not_working_GUC_gmsh_v2.2.off')
```
I have added the msh file in a zip.

I also included a msh file which did work. The difference between them is that the working one is exported from the Netgen tool. However, we would like to move to Gmsh for our meshing, so it would be nice if the converting to .off would also work for those meshes.

Could this be fixed?
Thank you.

[test_meshes.zip](https://github.com/nschloe/meshio/files/6617928/test_meshes.zip)

**Comment by nschloe** [comment]
Fixed now.
