### ISSUE TITLE
TypeError: meshio does not support VTK type 6.

### ISSUE THREAD

**Issue by MaxMach** [nschloe/meshio#1143]
Hi,

I tried saving my mesh after extruding. Now I get the above error and could not find anything about it.

```
cloud = pv.PolyData(indexing3D)

meshvol = cloud.delaunay_2d(alpha=2.)
meshvol2 = meshvol.extrude([0, 0, 1.5], inplace=False, progress_bar=False)

pv.save_meshio("SCC_140_extruded.obj", meshvol2)
```

This is the "meshvol" object:
<bound method PolyData.is_all_triangles of PolyData (0x7f1b28ee5440)
  N Cells:	394483
  N Points:	198131
  X Bounds:	1.990e+02, 7.720e+02
  Y Bounds:	2.390e+02, 8.160e+02
  Z Bounds:	1.000e+00, 1.000e+00
  N Arrays:	0

and the "meshvol2" object (extruded):
<bound method PolyData.is_all_triangles of PolyData (0x7f1b28fe9ad0)
  N Cells:	790753
  N Points:	396262
  X Bounds:	1.990e+02, 7.720e+02
  Y Bounds:	2.390e+02, 8.160e+02
  Z Bounds:	1.000e+00, 2.500e+00
  N Arrays:	0

Thank you!
Max

**Comment by nschloe** [comment]
This issue seems to be accidentally created here. `PolyData` and `cloud.delaunay_2d` is nothing that meshio has any part in. Hard to tell, because the MWE is incomplete. Closing.

Feel free to reopen with a complete copy-and-pastable MWE if you feel this is a meshio issue after all.
