### ISSUE TITLE
Support for higher-order elements

### ISSUE THREAD

**Issue by garth-wells** [nschloe/meshio#116]
Any plans to support higher-order elements? I tried converting a 10-node tetrahedron from gmsh to XDMF, and got the error 
```
vtk_type = meshio_to_vtk_type[meshio_type]
KeyError: 'tetra10'
```

**Comment by nschloe** [comment]
In connection with #117, I'm not sure if VTK supports that. I see only `vtk.VTK_TETRA`, but maybe there's a way of attaching more data to such an object. In any case, a (small) test mesh would help.

**Comment by garth-wells** [comment]
```python
# Quadratic tetrahedron
tetPoints = vtk.vtkPoints()
tetPoints.SetNumberOfPoints(10)
```

**Comment by nschloe** [comment]
Do you also have a mesh to play around with?

**Comment by garth-wells** [comment]
Can be easily generated from gmsh using:
```
//+
SetFactory("OpenCASCADE");
Sphere(1) = {0.0, 0.0, 0, 0.5, -Pi/2, Pi/2, 2*Pi};
//+
Physical Volume("sphere") = {1};
```
Meshes I have at the moment are too big to post.

**Comment by nschloe** [comment]
Is your geometry complete? I'm getting the error message
```
Sphere 1 has to be defined using 2 points (center + any point) and not 7
```

**Comment by nschloe** [comment]
After upgrading to Gmsh 3, I could generate a mesh from the above geometry, but only ordinary triangles come out if this.

**Comment by nschloe** [comment]
A bunch of higher-order elements are supported now for various formats. I skipped some of the rare ones like quadratic wedges and pyramids for now, but I could add them later.
