### ISSUE TITLE
[BUG] Writing VTU files: AssertionError when setting header_type kwarg

### ISSUE THREAD

**Issue by rchensix** [nschloe/meshio#1162]
**Describe the bug**
During writing, if `header_type` kwarg is set, there is an assertion error in `meshio/src/meshio/vtu/_vtu.py`.

**To Reproduce**
`meshio.write_points_cells(..., header_type='UInt64')`
or
`mesh.write(..., header_type="UInt64")`

**Diagnose**
```
File "[redacted]/meshio/vtu/_vtu.py", line 617, in write
    assert header_type is not None
AssertionError
```

**Proposed fix**
Around line 614 of `meshio/src/meshio/vtu/_vtu.py`.
```
if header_type is None:
    header_type = "UInt32"
else:
    vtk_file.set("header_type", header_type)
# header_type = (
#     "UInt32" if header_type is None else vtk_file.set("header_type", header_type)
# )
assert header_type is not None
```

**Comment by nschloe** [comment]
Thanks, fixed now.
