### ISSUE TITLE
Test failure on s390x architecture

### ISSUE THREAD

**Issue by utkarsh2102** [nschloe/meshio#1168]
Hello,

Thanks for your work on this! 🎉 

However, whilst building this is Ubuntu, we saw that the tests are failing in the s390x architecture. Originally reported as https://bugs.launchpad.net/ubuntu/+source/python-meshio/+bug/1939057.

Pasting the contents of the bug report here as well:

https://autopkgtest.ubuntu.com/results/autopkgtest-impish/impish/s390x/p/python-meshio/20210731_000740_21465@/log.gz

Version 4.3.9-1 passes, but all tests for 4.3.11-1 and 4.4.6-1 fails on s390x with this error:

```
=================================== FAILURES ===================================
__________________________ test_stl[True-1e-08-mesh0] __________________________

mesh = <meshio mesh object>
  Number of points: 4
  Number of cells:
    triangle: 2
  Cell sets: grain0, grain1
binary = True, tol = 1e-08

    @pytest.mark.parametrize(
        "mesh",
        [
            # helpers.empty_mesh,
            helpers.tri_mesh
        ],
    )
    @pytest.mark.parametrize(
        "binary, tol",
        [
            (False, 1.0e-15),
            # binary STL only operates in single precision
            (True, 1.0e-8),
        ],
    )
    def test_stl(mesh, binary, tol):
        def writer(*args, **kwargs):
            return meshio.stl.write(*args, binary=binary, **kwargs)

> helpers.write_read(writer, meshio.stl.read, mesh, tol)

test/test_stl.py:26:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test/helpers.py:367: in write_read
    mesh = reader(p)
/usr/lib/python3/dist-packages/meshio/stl/_stl.py:40: in read
    out = _read_ascii(f)
/usr/lib/python3/dist-packages/meshio/stl/_stl.py:105: in _read_ascii
    data = iter_loadtxt(
/usr/lib/python3/dist-packages/meshio/stl/_stl.py:69: in iter_loadtxt
    data = np.fromiter(iter_func(), dtype=dtype)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def iter_func():
        items = None
        for _ in range(skiprows):
            try:
                next(infile)
            except StopIteration:
                raise ReadError("EOF Skipped too many rows")

        for line in infile:
> line = line.decode("utf-8").strip()
E UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 14: invalid start byte

/usr/lib/python3/dist-packages/meshio/stl/_stl.py:56: UnicodeDecodeError
=============================== warnings summary ===============================
```

Maybe tol = 1e-08 is hitting some data type issue on s390x?

**Comment by nschloe** [comment]
I don't have access to a s390x machine so I can't debug/fix this. If anyone has, let me know.

**Comment by utkarsh2102** [comment]
Hi @nschloe,

> I don't have access to a s390x machine so I can't debug/fix this. If anyone has, let me know.

There are free VMs available by IBM via https://developer.ibm.com/components/ibm-linuxone/gettingstarted.
Those are RH, but you can container anything onto them as needed.

**Comment by nschloe** [comment]
I'm getting a 404 on the link. Anyway, if you have access, why not debug and submit a PR? 😸

**Comment by utkarsh2102** [comment]
If only I had much idea what's going on :)

Anyway, updated the link; https://developer.ibm.com/components/ibm-linuxone/gettingstarted/
Hopefully, this would work this time.

**Comment by ginggs** [comment]
It looks like this was this was the offending commit in 4.3.10:
https://github.com/nschloe/meshio/pull/1033/commits/59a19d1da627efd469fc7be95904ffcd1931d650
