### ISSUE TITLE
VTK dependency

### ISSUE THREAD

**Issue by garth-wells** [nschloe/meshio#117]
(py)VTK is a pretty heavy-weight dependency, and at least for Ubuntu the package is Python 2 only.

Would it be possible to avoid the VTK dependency and still convert to VTK/XDMF? It would enhance portability.

**Comment by nschloe** [comment]
> (py)VTK is a pretty heavy-weight dependency, and at least for Ubuntu the package is Python 2 only.

That's right. The reason why XDMF/VTK/Exodus I/O is handled by VTK is that I don't have to implement/maintain anything except the interface. As developer, that's pretty compelling.

That being said, I wouldn't oppose a PR that pulls in a lighter weight VTK/XDMF alternative.

---
(Side note: I'm working to get VTK7 (with its Python 3 support) into Debian (see [here](https://ftp-master.debian.org/new/vtk7_7.1.1+dfsg1-1~exp1.html)), but considering the Debian import freeze for Ubuntu 17.10 this week, it won't be until spring that VTK is actually accessible through Python 3.)

**Comment by nschloe** [comment]
Alright, the dependency is now removed. This is probably the single best thing that ever happened to meshio; VTK had given me lots of trouble.

@garth-wells Probably there are still some rough edges here any there; it'd be great if you could play around with it and give some feedback.
