### ISSUE TITLE
Converting from .xdmf to .msh

### ISSUE THREAD

**Issue by keiyamamo** [nschloe/meshio#1179]
I converted xdmf file to msh file with meshio-convert command and I get the following warning. 

WARNING:root:Binary Gmsh needs c_size_t (got int32). Converting.

Gmsh managed to read converted msh file, but I’m not sure if I can just ignore the warning. 
Could you tell me what might cause the warning and how to fix it ?

**Comment by nschloe** [comment]
The data type in XDMF was int32, but Gmsh needed a different one, so meshio had to convert a large array in memory. If you have control over the array, you probably want to initialize it with the correct data type, but in your case, you can just ignore it.
