### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by giannoko** [nschloe/meshio#1180]
Hello,

By typing "meshio-convert test.msh test.vtk (or anything else)" I am getting the following error

Traceback (most recent call last):
  File "/usr/bin/meshio-convert", line 135, in <module>
    _main()
  File "/usr/bin/meshio-convert", line 14, in _main
    args = _parse_options()
  File "/usr/bin/meshio-convert", line 100, in _parse_options
    choices=meshio.input_filetypes,
AttributeError: module 'meshio' has no attribute 'input_filetypes'

**Comment by gdmcbain** [comment]
How has your meshio been installed? Since #1154, a couple of months ago, the hyphenated syntax has been replaced by subcommands; e.g.
```shell
meshio convert test.msh test.vtk
```

**Comment by giannoko** [comment]
Hello,

I have installed it via both apt-get and pip3. The command meshio-convert
is recognized by the machine but I get this error. The command meshio
convert is not recognized

**Comment by gdmcbain** [comment]
Ah, O. K., let's see.  On the main branch (under MS-Windows and Miniconda if that's relevant, which it shouldn't be) I get
> `meshio-convert` : The term 'meshio-convert' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.

whereas `meshio convert test.msh test.vtk` works fine.  (Actually I do get an &lsquo;Unsupported data type vtktypeint32&rsquo; output message, but I won't worry about that now. )  I can open the resulting `test.vtk` in ParaView 5.9.1.

With
```shell
conda create -n meshio pip
conda activate meshio
pip install meshio
```
both `meshio-convert` and `meshio convert` seem to work O. K.

Under Ubuntu 20.04.3 LTS (& again Miniconda), with pip-installed meshio 5.0.0 from PyPI, I get `meshio convert` but `meshio-convert` raises
> Command 'meshio-convert' not found, but can be installed with:
> `sudo apt install meshio-tools`

So there does seem to be some variation with operating system, which is surprising.   Hmm, not sure&hellip;sorry.

**Comment by nschloe** [comment]
Closing for lack of feedback. Assuming Geordie's answer fixed in the issue. Feel free to reopen if not.
