### ISSUE TITLE
vtk format issue since v4.4.6 when using with itk.js [BUG]

### ISSUE THREAD

**Issue by bweben** [nschloe/meshio#1182]
**Describe the bug**
We have a program which creates a med file. This med file is then converted via `meshio-convert` and loaded in a web application by using http://insightsoftwareconsortium.github.io/itk-js/ and https://kitware.github.io/vtk-js/index.html.
Since version 4.4.6 the following error appears:
![image](https://user-images.githubusercontent.com/10772590/133932425-30357d72-63f5-465f-8318-248c2c06f89b.png)

<details>
  <summary>Error in full - click to expand</summary>
  <pre>
  VTKLegacyFileReaderWasm.js:9 
        
       ERROR: In /VTK/IO/Legacy/vtkDataReader.cxx, line 2025
Module.printErr @ VM4 VTKLegacyFileReaderWasm.js:9
put_char @ VM4 VTKLegacyFileReaderWasm.js:9
write @ VM4 VTKLegacyFileReaderWasm.js:9
write @ VM4 VTKLegacyFileReaderWasm.js:9
doWritev @ VM4 VTKLegacyFileReaderWasm.js:9
_fd_write @ VM4 VTKLegacyFileReaderWasm.js:9
___wasi_fd_write @ VM4 VTKLegacyFileReaderWasm.js:9
$func15753 @ VM5 01c1f30a:1
$func15792 @ VM5 01c1f30a:1
$func15852 @ VM5 01c1f30a:1
$func16056 @ VM5 01c1f30a:1
$func59 @ VM5 01c1f30a:1
$func58 @ VM5 01c1f30a:1
$func89 @ VM5 01c1f30a:1
$func15101 @ VM5 01c1f30a:1
$func15102 @ VM5 01c1f30a:1
$func15122 @ VM5 01c1f30a:1
$func301 @ VM5 01c1f30a:1
$func297 @ VM5 01c1f30a:1
$func298 @ VM5 01c1f30a:1
$func422 @ VM5 01c1f30a:1
$func2610 @ VM5 01c1f30a:1
$func184 @ VM5 01c1f30a:1
$func2741 @ VM5 01c1f30a:1
$func2464 @ VM5 01c1f30a:1
$func2451 @ VM5 01c1f30a:1
$func2637 @ VM5 01c1f30a:1
$func2404 @ VM5 01c1f30a:1
$func2451 @ VM5 01c1f30a:1
$func2637 @ VM5 01c1f30a:1
$func2404 @ VM5 01c1f30a:1
$func2451 @ VM5 01c1f30a:1
$func2637 @ VM5 01c1f30a:1
$func2461 @ VM5 01c1f30a:1
$func2648 @ VM5 01c1f30a:1
$func2639 @ VM5 01c1f30a:1
$func2321 @ VM5 01c1f30a:1
$func2322 @ VM5 01c1f30a:1
$_main @ VM5 01c1f30a:1
callMain @ VM4 VTKLegacyFileReaderWasm.js:9
runPipelineEmscripten @ VM3 Pipeline.worker.js:1626
_callee2$ @ VM3 Pipeline.worker.js:1169
tryCatch @ VM3 Pipeline.worker.js:135
invoke @ VM3 Pipeline.worker.js:365
(anonymous) @ VM3 Pipeline.worker.js:190
asyncGeneratorStep @ VM3 Pipeline.worker.js:4
_next @ VM3 Pipeline.worker.js:26
(anonymous) @ VM3 Pipeline.worker.js:33
(anonymous) @ VM3 Pipeline.worker.js:22
_runPipeline @ VM3 Pipeline.worker.js:1260
runPipeline @ VM3 Pipeline.worker.js:1159
_callee$ @ VM3 Pipeline.worker.js:1295
tryCatch @ VM3 Pipeline.worker.js:135
invoke @ VM3 Pipeline.worker.js:365
(anonymous) @ VM3 Pipeline.worker.js:190
asyncGeneratorStep @ VM3 Pipeline.worker.js:4
_next @ VM3 Pipeline.worker.js:26
(anonymous) @ VM3 Pipeline.worker.js:33
(anonymous) @ VM3 Pipeline.worker.js:22
(anonymous) @ VM3 Pipeline.worker.js:1306
runFn @ VM3 Pipeline.worker.js:936
run @ VM3 Pipeline.worker.js:921
(anonymous) @ VM3 Pipeline.worker.js:957
Show 33 more frames

---

vtkUnstructuredGridReader (0x5c27e0): Unsupported data type: vtktypeint32
Module.printErr @ VM4 VTKLegacyFileReaderWasm.js:9
put_char @ VM4 VTKLegacyFileReaderWasm.js:9
write @ VM4 VTKLegacyFileReaderWasm.js:9
write @ VM4 VTKLegacyFileReaderWasm.js:9
doWritev @ VM4 VTKLegacyFileReaderWasm.js:9
_fd_write @ VM4 VTKLegacyFileReaderWasm.js:9
___wasi_fd_write @ VM4 VTKLegacyFileReaderWasm.js:9
$func15753 @ VM5 01c1f30a:1
$func15792 @ VM5 01c1f30a:1
$func15852 @ VM5 01c1f30a:1
$func16056 @ VM5 01c1f30a:1
$func59 @ VM5 01c1f30a:1
$func58 @ VM5 01c1f30a:1
$func89 @ VM5 01c1f30a:1
$func15101 @ VM5 01c1f30a:1
$func15102 @ VM5 01c1f30a:1
$func15122 @ VM5 01c1f30a:1
$func301 @ VM5 01c1f30a:1
$func297 @ VM5 01c1f30a:1
$func298 @ VM5 01c1f30a:1
$func422 @ VM5 01c1f30a:1
$func2610 @ VM5 01c1f30a:1
$func184 @ VM5 01c1f30a:1
$func2741 @ VM5 01c1f30a:1
$func2464 @ VM5 01c1f30a:1
$func2451 @ VM5 01c1f30a:1
$func2637 @ VM5 01c1f30a:1
$func2404 @ VM5 01c1f30a:1
$func2451 @ VM5 01c1f30a:1
$func2637 @ VM5 01c1f30a:1
$func2404 @ VM5 01c1f30a:1
$func2451 @ VM5 01c1f30a:1
$func2637 @ VM5 01c1f30a:1
$func2461 @ VM5 01c1f30a:1
$func2648 @ VM5 01c1f30a:1
$func2639 @ VM5 01c1f30a:1
$func2321 @ VM5 01c1f30a:1
$func2322 @ VM5 01c1f30a:1
$_main @ VM5 01c1f30a:1
callMain @ VM4 VTKLegacyFileReaderWasm.js:9
runPipelineEmscripten @ VM3 Pipeline.worker.js:1626
_callee2$ @ VM3 Pipeline.worker.js:1169
tryCatch @ VM3 Pipeline.worker.js:135
invoke @ VM3 Pipeline.worker.js:365
(anonymous) @ VM3 Pipeline.worker.js:190
asyncGeneratorStep @ VM3 Pipeline.worker.js:4
_next @ VM3 Pipeline.worker.js:26
(anonymous) @ VM3 Pipeline.worker.js:33
(anonymous) @ VM3 Pipeline.worker.js:22
_runPipeline @ VM3 Pipeline.worker.js:1260
runPipeline @ VM3 Pipeline.worker.js:1159
_callee$ @ VM3 Pipeline.worker.js:1295
tryCatch @ VM3 Pipeline.worker.js:135
invoke @ VM3 Pipeline.worker.js:365
(anonymous) @ VM3 Pipeline.worker.js:190
asyncGeneratorStep @ VM3 Pipeline.worker.js:4
_next @ VM3 Pipeline.worker.js:26
(anonymous) @ VM3 Pipeline.worker.js:33
(anonymous) @ VM3 Pipeline.worker.js:22
(anonymous) @ VM3 Pipeline.worker.js:1306
runFn @ VM3 Pipeline.worker.js:936
run @ VM3 Pipeline.worker.js:921
(anonymous) @ VM3 Pipeline.worker.js:957
Show 33 more frames

---
VTKLegacyFileReaderWasm.js:9 
        
       
Module.printErr @ VM4 VTKLegacyFileReaderWasm.js:9
put_char @ VM4 VTKLegacyFileReaderWasm.js:9
write @ VM4 VTKLegacyFileReaderWasm.js:9
write @ VM4 VTKLegacyFileReaderWasm.js:9
doWritev @ VM4 VTKLegacyFileReaderWasm.js:9
_fd_write @ VM4 VTKLegacyFileReaderWasm.js:9
___wasi_fd_write @ VM4 VTKLegacyFileReaderWasm.js:9
$func15753 @ VM5 01c1f30a:1
$func15792 @ VM5 01c1f30a:1
$func15852 @ VM5 01c1f30a:1
$func16056 @ VM5 01c1f30a:1
$func59 @ VM5 01c1f30a:1
$func58 @ VM5 01c1f30a:1
$func89 @ VM5 01c1f30a:1
$func15101 @ VM5 01c1f30a:1
$func15102 @ VM5 01c1f30a:1
$func15122 @ VM5 01c1f30a:1
$func301 @ VM5 01c1f30a:1
$func297 @ VM5 01c1f30a:1
$func298 @ VM5 01c1f30a:1
$func422 @ VM5 01c1f30a:1
$func2610 @ VM5 01c1f30a:1
$func184 @ VM5 01c1f30a:1
$func2741 @ VM5 01c1f30a:1
$func2464 @ VM5 01c1f30a:1
$func2451 @ VM5 01c1f30a:1
$func2637 @ VM5 01c1f30a:1
$func2404 @ VM5 01c1f30a:1
$func2451 @ VM5 01c1f30a:1
$func2637 @ VM5 01c1f30a:1
$func2404 @ VM5 01c1f30a:1
$func2451 @ VM5 01c1f30a:1
$func2637 @ VM5 01c1f30a:1
$func2461 @ VM5 01c1f30a:1
$func2648 @ VM5 01c1f30a:1
$func2639 @ VM5 01c1f30a:1
$func2321 @ VM5 01c1f30a:1
$func2322 @ VM5 01c1f30a:1
$_main @ VM5 01c1f30a:1
callMain @ VM4 VTKLegacyFileReaderWasm.js:9
runPipelineEmscripten @ VM3 Pipeline.worker.js:1626
_callee2$ @ VM3 Pipeline.worker.js:1169
tryCatch @ VM3 Pipeline.worker.js:135
invoke @ VM3 Pipeline.worker.js:365
(anonymous) @ VM3 Pipeline.worker.js:190
asyncGeneratorStep @ VM3 Pipeline.worker.js:4
_next @ VM3 Pipeline.worker.js:26
(anonymous) @ VM3 Pipeline.worker.js:33
(anonymous) @ VM3 Pipeline.worker.js:22
_runPipeline @ VM3 Pipeline.worker.js:1260
runPipeline @ VM3 Pipeline.worker.js:1159
_callee$ @ VM3 Pipeline.worker.js:1295
tryCatch @ VM3 Pipeline.worker.js:135
invoke @ VM3 Pipeline.worker.js:365
(anonymous) @ VM3 Pipeline.worker.js:190
asyncGeneratorStep @ VM3 Pipeline.worker.js:4
_next @ VM3 Pipeline.worker.js:26
(anonymous) @ VM3 Pipeline.worker.js:33
(anonymous) @ VM3 Pipeline.worker.js:22
(anonymous) @ VM3 Pipeline.worker.js:1306
runFn @ VM3 Pipeline.worker.js:936
run @ VM3 Pipeline.worker.js:921
(anonymous) @ VM3 Pipeline.worker.js:957
Show 33 more frames
  </pre>
</details>
Also I'm not sure if I'm understanding everything correctly as I'm fairly new to this whole topic - so if you do know some important tutorials / lessons whatever, please give me a hint. Thanks :)

**To Reproduce**
Sadly this involves a fairly large .vtk file or .med.

**Diagnose**
I may ask you to cut and paste the output of the following command.
```
pip freeze | grep meshio
```

**Did I help?**

If I was able to resolve your problem, consider [sponsoring](https://github.com/sponsors/nschloe) my work on meshio, or [buy me a coffee](https://ko-fi.com/nschloe) to say thanks.

**Comment by nschloe** [comment]
You're using an old version of meshio. Maybe updating fixes your issue. Other than that, there's not much we can do here. May as well be an issue with itk.js.

**Comment by bweben** [comment]
Thanks for your reply.
With version 4.4.5 it works, since version 4.4.6 it doesn't. Version 5.0.0 doesn't fix it either.

**Comment by nschloe** [comment]
Like I said, there's not much we can do here. Everything looks okay on the meshio side.

**Comment by bweben** [comment]
OK I will look with itk.js then. Thanks :)
