### ISSUE TITLE
VTK 4.0 format

### ISSUE THREAD

**Issue by ChaoW95** [nschloe/meshio#1185]
Is there a way to convert mesh to VTK 4.0 format?

**Comment by nschloe** [comment]
So far, just 4.2 and 5.1.

**Comment by ChaoW95** [comment]
> So far, just 4.2 and 5.1.

Thanks for your reply!
I am new to this meshio package.
Can you tell me how to convert mesh to VTK 4.2 format?
I know how to convert mesh in the command-line tool.
But it will only convert the mesh into VTK 5.1 format.

**Comment by nschloe** [comment]
```
meshio convert --help
```
It's called `vtk42` or something like that.
