### ISSUE TITLE
implement cgns format reader/writer

### ISSUE THREAD

**Issue by kayarre** [nschloe/meshio#120]
cgns file format
(https://cgns.github.io/)

**Comment by stgeke** [comment]
Are there any plans to support cgns anytime soon?

**Comment by nschloe** [comment]
@stgeke I'll be happy to review incoming PRs.

**Comment by nschloe** [comment]
Closing this one. If anyone needs this, I'll be happy to review PRs.

**Comment by nschloe** [comment]
There is basic support for CGNS in meshio now. It only works for _very_ limited use cases now, mostly because I couldn't find a format specification.
