### ISSUE TITLE
[BUG] Fail to read ply/vtk converted from pcd with PCL cmds

### ISSUE THREAD

**Issue by YuanWenqing** [nschloe/meshio#1209]
**Describe the bug**
After converting PointCloud file from .pcd to .ply/.vtk via PCL commands in MacOS, meshio fails to read the .ply/.vtk file. 
The original PointCloud data is a result of Line Scan Camera.
It seems meshio has some restricts about the data format, right?

~~~
# PLY
meshio._exceptions.ReadError: Expected `element vertex` or `element face` or `obj_info`, got `element camera 1`
# VTK
meshio._exceptions.ReadError: Only VTK 'UNSTRUCTURED_GRID', 'STRUCTURED_POINTS', 'STRUCTURED_GRID', 'RECTILINEAR_GRID' supported (not POLYDATA).
~~~

**To Reproduce**

test: [test.zip](https://github.com/nschloe/meshio/files/7458688/test.zip)

~~~
# ply
pcl_pcd2ply test.pcd test.ply
meshio info test.ply
# vtk
pcl_pcd2vtk test.pcd test.vtk
meshio info test.vtk
~~~

**Diagnose**
```
pcl: stable 1.11.1 (bottled), HEAD
meshio==5.0.2
```

**Comment by nschloe** [comment]
> It seems meshio has some restricts about the data format, right?

That's right, `POLYDATA` is not supported. See https://github.com/nschloe/meshio/issues/527.
