### ISSUE TITLE
Not loading all data from vtk file

### ISSUE THREAD

**Issue by timmyL17** [nschloe/meshio#121]
When loading the linked vtk file below with meshio.read, only some of the data is loaded. When viewing the file in paraview, there are 3 cell data fields: cauchy_strain, cauchy_stress, and mat_id. When loading with meshio.read, the cell_data only contains mat_id and cauchy_strain. cauchy_stress is missing for some reason.

https://drive.google.com/file/d/0B268R4ggA2GQMGdnNjNxZlhOMWM/view?usp=sharing

**Comment by nschloe** [comment]
Interesting! I'll look at it tomorrow.

**Comment by nschloe** [comment]
Perhaps this is a VTK issue; I've filed a bug at https://gitlab.kitware.com/vtk/vtk/issues/17109, let's see what comes out of that.

**Comment by timmyL17** [comment]
Possibly, although paraview uses the vtk library as well, right? Maybe that has an embedded version or something.

It seems that pyvtk reads this file correctly. That library might do its own parsing though, instead of relying on vtk.

**Comment by nschloe** [comment]
Fix released (1.8.15).
