### ISSUE TITLE
Could I use meshio to export a numpy array to vtk format?

### ISSUE THREAD

**Issue by alisheikholeslam** [nschloe/meshio#1213]
I have a problem relating to one of [SO questions](https://stackoverflow.com/questions/33771609/how-to-set-custom-timestep-values-for-a-series-of-legacy-vtk-files-in-paraview/69889294#69889294).

I have exported center and radius of some spheres into text files by ```numpy.savetxt``` for numpy arrays like ```np.array([[-1.250e-02,-3.749e-02,-1.250e-02,9.375e-03], [1.250e-02,-3.749e-02,-1.250e-02,9.375e-03],...])```; each file corresponds to each timesteps 0.001, 0.002, … . The output text files are as:
```
X,Y,Z,R
-1.250e-02,-3.749e-02,-1.250e-02,9.375e-03
1.250e-02,-3.749e-02,-1.250e-02,9.375e-03
-1.250e-02,-1.249e-02,-1.250e-02,9.375e-03
```
and then by using [the answer](https://stackoverflow.com/a/34120782/13394817), I do the question goal by these text files. But it will be very better to use *.vtk* formats instead of *.txt* formats duo to the reasons that I have mentioned in [the question](https://stackoverflow.com/a/69889294/13394817). These formats, i.e. vtk, vtu, vtp, and ..., have the ability to consider timesteps.
I have used meshio for my previous meshing and ..., but I don't know if it can export such numpy arrays in ***.vtk*** files. In such cases, other parameters such as radius and ... could be added to coordinates.
Could I use meshio to export such vtk files for polydata cases? How? I prefer using meshio instead other libraries such as PyScience and ... .
Thanks in advance.

**Comment by nschloe** [comment]
> but I don't know if it can export such numpy arrays in .vtk files

You can't. VTK is for meshes (i.e., point data plus cell data), not general data.
