### ISSUE TITLE
deduplicate fails tests on 32-bit systems

### ISSUE THREAD

**Issue by drew-parsons** [nschloe/meshio#1222]
**Describe the bug**

meshio 5.0.3 has started failing test_deduplicate_points in test_mesh.py on 32-bit systems. 5.0.2 was previously passing.
The error message on i386 (debian testing) is
```
=================================== FAILURES ===================================
___________________________ test_deduplicate_points ____________________________

    def test_deduplicate_points():
        points = np.array(
            [
                [0.0, 0.0],
                [1.0, 0.0],
                [1.0, 1.0],
                [1.0, 0.0],
                [1.0, 1.0],
                [2.0, 0.0],
            ]
        )
        point_data = {"a": [0.1, 0.2, 0.3, 0.4, 0.5, 0.6]}
        point_sets = {"b": [0, 4, 5]}
        cells = [[0, 1, 2], [3, 4, 5]]
        mesh = meshio.Mesh(
            points, {"triangle": cells}, point_data=point_data, point_sets=point_sets
        )
    
        num_removed_points = mesh.deduplicate_points(1.0e-10)
>       assert num_removed_points == 2
E       assert 3 == 2
E         +3
E         -2

tests/test_mesh.py:166: AssertionError
=========================== short test summary info ============================
FAILED tests/test_mesh.py::test_deduplicate_points - assert 3 == 2
=================== 1 failed, 743 passed, 3 skipped in 5.99s ===================
```
64-bit systems are passing fine. The problem seems to be in 32-bit systems, affecting both i386 and armhf.

Full test logs on debian testing:
https://ci.debian.net/data/autopkgtest/testing/i386/p/python-meshio/16934789/log.gz
https://ci.debian.net/data/autopkgtest/testing/armhf/p/python-meshio/16934767/log.gz
or debian unstable (using python 3.10):
https://ci.debian.net/data/autopkgtest/unstable/i386/p/python-meshio/16905482/log.gz
https://ci.debian.net/data/autopkgtest/unstable/armhf/p/python-meshio/16905481/log.gz

**To Reproduce**
On a 32-bit system,
```
pytest-3 -v tests/test_mesh.py
```

**Diagnose**
I may ask you to cut and paste the output of the following command.
```
$ pip freeze | grep meshio
meshio==5.0.3
```

**Comment by nschloe** [comment]
Don't worry too much about this; I'll remove all mesh manipulation routines from meshio soon.

**Comment by drew-parsons** [comment]
OK. I'll skip the test for now in that case.

**Comment by nschloe** [comment]
I removed the deduplication (and with it the npx dependency). Release still pending though.
