### ISSUE TITLE
No Windows (or Mac) testing

### ISSUE THREAD

**Issue by banesullivan** [nschloe/meshio#1225]
It concerns me that there is no CI testing for Windows (or Mac, but Windows is the one that really worries me):

https://github.com/nschloe/meshio/blob/9dc6b0b05c9606cad73ef11b8b7785dd9b9ea325/.github/workflows/ci.yml#L23

Meshio is a hard dependency of PyVista, and I think we should set up multiplatform tests for this. I know meshio is pure Python and minimalist and all that jazz, but things can still be different on Windows, especially when we're dealing with text encodings and reading files.

cc @tkoyama010 @adeak @akaszynski

**Comment by adeak** [comment]
Academically speaking, shouldn't our own (as in PyVista's) test suite ensure that functionality implemented via meshio works?

**Comment by banesullivan** [comment]
Theoretically, maybe? Practically, definitely not. We don't run through all the formats meshio supports so there's no way we can guarantee all of meshio's readers will actually work for PyVista user across platforms. I'll run a coverage on meshio with PyVista' unit tests locally right now to see

**Comment by nschloe** [comment]
Yeah, meshio should probably run the tests on other platforms, too.

**Comment by banesullivan** [comment]
It looks like this would be pretty simple to do, thought handling the `libhdf5-dev` `libnetcdf-dev` might be a pain. I could set up a CI to use conda to install those on Windows/Mac... I'll see if I can draft a PR real quick

**Comment by banesullivan** [comment]
Just because I said I would and I was curious how much PyVista's tests actually cover `meshio`, here are the results.

Total coverage: 15% [htmlcov.zip](https://github.com/nschloe/meshio/files/7621176/htmlcov.zip)

Note this is meshio version 4.4.6 because of https://github.com/pyvista/pyvista/issues/1898
