### ISSUE TITLE
[Feature request] In dolfin xml, allow to skip physical and geometrical data

### ISSUE THREAD

**Issue by massimiliano-leoni** [nschloe/meshio#123]
Title is self-explanatory: a flag to skip output of this complementary data would be convenient, speeding up the conversion and saving to delete them.

**Comment by nschloe** [comment]
I'm not sure if it's worth putting any effort in dolfin xml anymore. It's an outdated format, and if you're converting it you're doing the right thing. Once you're doing, you probably won't need it again, right? What do you think?

**Comment by massimiliano-leoni** [comment]
Actually I have a conversion pipeline like medit->gmsh->dolfin, but even if this weren't my final format, I would still waste time in the conversion step gmsh->dolfin waiting for `meshio` to produce data I don't need.

**Comment by nschloe** [comment]
Why to do you convert to dolfin XML?

**Comment by massimiliano-leoni** [comment]
Because I use dolfin-hpc :)

**Comment by nschloe** [comment]
Ah, and dolfin-hpc requires XML?

**Comment by massimiliano-leoni** [comment]
Actually, there's a very efficient binary format that we use, but you need to read in in another compatible format to convert to it, and the other compatible format is xml.

**Comment by nschloe** [comment]
> Actually, there's a very efficient binary format we use

![standards](https://user-images.githubusercontent.com/181628/30078469-9a3c14c6-927d-11e7-96c3-42380cc17b64.png)

;)

Alright, so your own code uses Dolfin XML for I/O which is why you need to convert your gmsh output, right? Hm, alright. Thinking about a way to handle this outside of meshio (so I don't have to maintain it), perhaps a few lines of Python would help. Something like
```
import meshio

points, cells, point_data, cell_data, field_data = meshio.read('test.gmsh')
# forget about point_data, cell_data, field_data and write it to xml
meshio.write('out.xml', points, cells)
```
Would this do the trick?

**Comment by massimiliano-leoni** [comment]
Hey, you are more fun than I expected :P

Thank you for the snippet ;)

**Comment by nschloe** [comment]
> Thank you for the snippet ;)

Let me tentatively close this issue, but by all means feel free to reopen. Hopefully we should be able to get something to work with the snippet though.
