### ISSUE TITLE
Commands in README.md

### ISSUE THREAD

**Issue by nailimixaM** [nschloe/meshio#1235]
**Describe the bug**
The README.md file describes the command line usage as:
```
meshio convert [file1] [file2]
```
but I think it should be
```
meshio-convert [file1] [file2]
```
as I get `meshio: command not found` with the first option. Same with the other meshio-* commands.

**To Reproduce**
```
pip install meshio
meshio convert
```

**Comment by nschloe** [comment]
You're probably using an old version of meshio.

**Comment by nailimixaM** [comment]
meshio==4.4.6 is the one returned by `pip install`, is this not the latest?

**Comment by nschloe** [comment]
5.1.something is the lastest.
