### ISSUE TITLE
Support additional `tetgen` file formats (`.face` / `.edge`)

### ISSUE THREAD

**Issue by stefsmeets** [nschloe/meshio#1248]
Hi, I would like to add support for two additional file formats within the `tetgen` submodule.

For my project, I'm particularly interested in `.edge` and `.face` files for line and triangle meshes:
https://wias-berlin.de/software/tetgen/fformats.html

The formats are very similar to the `.ele` file format. I already have a working patch for reading and writing, which I will submit a PR for.

**Comment by nschloe** [comment]
This works in the meshio rewrite. (Things are approached more generally here.)
