### ISSUE TITLE
[BUG] nastran fails to read (unmarked) continuation lines

### ISSUE THREAD

**Issue by eudoxos** [nschloe/meshio#1253]
**Describe the bug**
Nastran file cleaned by Medina discard continuation line of `CHEXA` and creates hexagons with 6 nodes only. I only received this file, so did not do the cleaning myself; I am also not sure how much is nastran (under)specified and whether this input is formally correct. Just saying that it exists and is produced by a reputable code. (Perhaps meshio could at least give a warning that some output was discarded?)

**To Reproduce**
I am copy-pasting a few first non-comment lines from the file in question:
```
CHEXA       1681       1    2185    2186    2207    2206    2605    2606
            2627    2626
CHEXA       1682       1    2186    2187    2208    2207    2606    2607
            2628    2627
CHEXA       1683       1    2187    2188    2209    2208    2607    2608
            2629    2628
CHEXA       1684       1    2188    2189    2210    2209    2608    2609
            2630    2629
CHEXA       1685       1    2189    2190    2211    2210    2609    2610
            2631    2630
CHEXA       1686       1    2190    2191    2212    2211    2610    2611
            2632    2631
CHEXA       1687       1    2191    2192    2213    2212    2611    2612
            2633    2632
```

I could work it around with `perl -pi -e's/^        /+       /' mesh.bdf` (github collapses several spaces into one in the regex), adding continuation marks instead of the leading whitespace.

**Diagnose**
```
$ pip freeze | grep meshio
meshio==5.2.2
```

**Did I help?**

If I was able to resolve your problem, consider [sponsoring](https://github.com/sponsors/nschloe) my work on meshio, or [buy me a coffee](https://ko-fi.com/nschloe) to say thanks.

**Comment by nschloe** [comment]
To reproduce, a small example file is needed. Feel free to reopen with one.
