### ISSUE TITLE
Legacy VTK format has undefined data formats in vtk_to_numpy_dtype_name

### ISSUE THREAD

**Issue by lahwaacz** [nschloe/meshio#1254]
The code for legacy VTK has these types in [vtk_to_numpy_dtype_name](https://github.com/nschloe/meshio/blob/main/src/meshio/vtk/_vtk_51.py#L22-L29):

```py
vtk_to_numpy_dtype_name = {
    "float": "float32",
    "double": "float64",
    "int": "int",
    "vtktypeint8": "int8",
    "vtktypeint16": "int16",
    "vtktypeint32": "int32",
    "vtktypeint64": "int64",
    "vtktypeuint8": "uint8",
    "vtktypeuint16": "uint16",
    "vtktypeuint32": "uint32",
    "vtktypeuint64": "uint64",
}
```

But out of these, VTK actually uses only `float`, `double`, `int`, `vtktypeint64` and `vtktypeuint64` (plus some more, like `unsigned int`). So if you write an array with e.g. `vtktypeint32`, VTK will give an unsupported data type error.

The relevant code in VTK is here: https://github.com/Kitware/VTK/blob/b9f028db9f801258d4c1c0c97716ea7a3c14c289/IO/Legacy/vtkDataReader.cxx#L1546-L1828

(I actually did not encounter this problem while using meshio, it might even be a non-issue in practical code paths. But I thought that I'd let you know...)

**Comment by nschloe** [comment]
The code looks quite a bit different now, and it got fixed somewhere along the way. Thanks for letting me know anyway!
