### ISSUE TITLE
Tests timeout on 32-bit architectures

### ISSUE THREAD

**Issue by ghisvail** [nschloe/meshio#126]
See the following Debian reproducibility logs for [i386](https://tests.reproducible-builds.org/debian/rb-pkg/unstable/i386/python-meshio.html) and [armhf](https://tests.reproducible-builds.org/debian/rb-pkg/unstable/armhf/python-meshio.html). Both ends with a timeout:
```
test/test_ansys.py ....Sat Oct  6 18:49:21 UTC 2018 - pbuilder was killed by timeout after 18h.
```

**Comment by nschloe** [comment]
Fixed via 2a5dd7c9b8d5c344c119d557d2d415d70e1710fb, fix released (1.8.16).

**Comment by ghisvail** [comment]
Thanks for the prompt fix. I don't remember whether I asked you already, but shall I add you to the Uploaders list of the Debian package so you can track it from your DDPO page?

**Comment by nschloe** [comment]
Yep, sure.
