### ISSUE TITLE
[BUG] GMSH ReadError

### ISSUE THREAD

**Issue by AeroDEmi** [nschloe/meshio#1266]
I have a .msh file from photoshop that I want to open with Meshio. I run the following code:
`import meshio
mesh = meshio.read('./bent.msh')`

and I get the following error:
ReadError: 

Is there any way to solve this?
I'l attach the .msh file

[bent.msh.zip](https://github.com/nschloe/meshio/files/7916364/bent.msh.zip)

**Comment by nschloe** [comment]
This file doesn't seem to be Gmsh, or any other known mesh format. Do you have more details?

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to reopen at any time!

**Comment by AeroDEmi** [comment]
Hi sorry for the delay, here are some more details: The mesh was created with photoshop with the Liquify Filter, it saves as .msh file.

I have not been able to open the mesh but from photoshop, it seems that it is not GMSH but do you know another way to open it?

**Comment by nschloe** [comment]
> do you know another way to open it?

No. If it's from Photoshop, I doubt it's in any way related to meshing.
