### ISSUE TITLE
VTK HDF5 format for unstructured grids

### ISSUE THREAD

**Issue by garth-wells** [nschloe/meshio#1273]
VTK has a HDF5 format for unstructured grids: https://kitware.github.io/vtk-examples/site/VTKFileFormats/#unstructured-grid.

It might be helpful to support given that XDMF is not really maintained, and the VTK-HDF5 storage looks a bit richer.

**Comment by nschloe** [comment]
I did not know that. Thanks for the hint!

**Comment by nschloe** [comment]
Will be part of the next release.

**Comment by mattfil** [comment]
Is this functionality already released? In current version (5.3.5) we can choose among "['abaqus', 'ansys', 'avsucd', 'cgns', 'dolfin-xml', 'exodus', 'flac3d', 'gmsh', 'gmsh22', 'h5m', 'hmf', 'mdpa', 'med', 'medit', 'nastran', 'netgen', 'neuroglancer', 'obj', 'off', 'permas', 'ply', 'stl', 'su2', 'svg', 'tecplot', 'tetgen', 'ugrid', 'vtk', 'vtk42', 'vtk51', 'vtu', 'wkt', 'xdmf']"
