### ISSUE TITLE
Meshio 4 issue - "finding triangular cells".

### ISSUE THREAD

**Issue by AfrAnio-Goncalves** [nschloe/meshio#1275]
![Captura de tela de 2022-01-31 22-56-02](https://user-images.githubusercontent.com/57040038/151902356-01ab08fd-68af-41ff-a735-f93d94512bd9.png)
Hi!
I have this 'TypeErro' when I run the code of the picture('list indices must be integers or slices, not str'), can you help me please?
this is my code
```python
import meshio
import numpy as np
import matplotlib.pyplot as plt
msh = meshio.read('backwardStep.msh')
X = msh.points[:,0]
Y = msh.points[:,1]
IEN = msh.cells['triangle']
IENbound = msh.cells['line']
IENboundTypeElem = list(msh.cell_data['line']['gmsh:physical'] - 1)
boundNames = list(msh.field_data.keys())
IENboundElem = [boundNames[elem] for elem in IENboundTypeElem]
npoints = len(X)
ne = IEN.shape[0]
```

**Comment by gdmcbain** [comment]
> IEN = msh.cells['triangle']

As of meshio 4, the `.cells` attribute is a list of cellblocks; hence the exception. There is a property for getting the, e.g., triangular cells:

https://github.com/nschloe/meshio/blob/582f3fea2164a843013053cd71fd68196a679439/src/meshio/_mesh.py#L253-L254

**Comment by gdmcbain** [comment]
P. S.:—A couple of notes on posting issues:

* A more descriptive title than "meshio issue" will help future users find this discussion; e.g. "finding triangular cells".
* Copied and pasted code iand exceptions are also easier to find than those in a screenshot.

**Comment by AfrAnio-Goncalves** [comment]
> > IEN = msh.cells['triangle']
> 
> As of meshio 4, the `.cells` attribute is a list of cellblocks; hence the exception. There is a property for getting the, e.g., triangular cells:
> 
> https://github.com/nschloe/meshio/blob/582f3fea2164a843013053cd71fd68196a679439/src/meshio/_mesh.py#L253-L254

Thanks,I will try this solution!
