### ISSUE TITLE
Converting a structured mesh with nodes and cells to vtk?

### ISSUE THREAD

**Issue by L4student** [nschloe/meshio#128]
Hi Nico,

May I know how to convert a structured mesh with an array of cells and nodes to a vtk file?
Let's say I have a mesh with `30x30x20` cells, so the arrays of cells and nodes are given as follows:
```
np.size(cellsarray) = (18000, 3)
np.size(nodesarray) = (20181, 3)
```
Thanks.

**Comment by nschloe** [comment]
The only data type for structured meshes I know of is VTK, that's why there is no such capability (yet?) in meshio. I could imagine that this would be useful though for I/O in Python.

If your mesh is structured though, why do you have a `cellsarray`?

**Comment by L4student** [comment]
That's true that for a structured mesh you don't really need, but I do have that information for any further mesh processing. I don't know the exact reason that information is being provided by the code I am looking at, but my guess is probably for use in some other part of that code. Anyways, I just want to be able to develop a vtk file if the above information is given for a structured grid. Thanks.

**Comment by nschloe** [comment]
> but I do have that information for any further mesh processing.

That's good then: You can just store it as an unstructured mesh. That's what meshio is all about anyways.

**Comment by L4student** [comment]
What command is used to do that? Any example that I can refer to? Thanks.

**Comment by nschloe** [comment]
Basically [the first example in the README](https://github.com/nschloe/meshio).

**Comment by L4student** [comment]
It's not clear what the pattern of the arguments should be. I saw that when I first came across meshio, and I believe, because of not knowing what pattern/shape those arguments actually follow led me to ask you this question. To figure that out I tried looking at the repository files, but I did not find the appropriate code that defines those arguments. Perhaps you can help clarify the definition and shape of those arguments? I have defined the shape of cells/nodes array above, but I am not sure whether I should just give them as it is. Also, are `point data` supposed to mean the `node data`?

**Comment by L4student** [comment]
Well, there is no help on the parameters inside the `meshio.write` function. I tried looking through the code and implemented the following, but it's giving me errors (whether I give the `cells` and `points` data as `numpy` arrays or `lists`)

```
points_float = np.reshape(np.array(grid.nodelist), np.product(np.array(grid.nxyz) + 1)*3, order='C')
cells_float = np.reshape(np.array(grid.celllist), np.product(grid.nxyz)*3, order='C')

points = np.array([int(i) for i in points_float])
cells = np.array([int(i) for i in cells_float])
meshio.write(name_pfmesh_vtk, points, cells)
```

**Comment by nschloe** [comment]
You're right, the documentation wasn't clear at all. I've updated the main readme, and hopefully things are a little more understandable now. The issue you had was that `cells` is a dictionary -- after all, there can be tets, triangles, lines, and other cells in one mesh.

**Comment by L4student** [comment]
Thanks for some info on those arguments. I am still getting an error, perhaps because it's not clear to me what are the values of the points and cells representing, i.e., are they sequential numbering for points and cells or they are the coordinate values? The values of cells and nodes that I am assigning for a grid with `30X30X20` cells are as follows:
```
points = np.array(list((x_vert, y_vert, z_vert))) # the array type and  size is float64 and (20181, 3)
cells = {'hexahedron': np.array(list((x_cell, y_cell, z_cell)))} # the array type and  size is float64 and (18000, 3)
```

The error I get when using the above values is:
```
assert cells[key].shape[1] == gmsh_io.num_nodes_per_cell[key]

AssertionError
```

**Comment by L4student** [comment]
The error seems to be suggesting that the number of values for each cell must be 8 (i.e. number of nodes per cell for hexahedron)...is that right? That would mean that the values you have used in that readme example are the node numbers and not coordinates. Although these are small things that may not be apparent to the developer, they are important to be able to use the code correctly. It's been a battle to get this code working because of lack of clarity of parameters and the nature of their values.

**Comment by nschloe** [comment]
The `points` array holds Cartesian coordinates, the `cells` dictionary holds indices into the `points` array. A hexahedron has 8 corners, so yes, those are 8 points of the mesh.

**Comment by nschloe** [comment]
I don't see and actionable tasks here right now. If this remains an issue, feel free to reopen though.

**Comment by godot11** [comment]
XDMF also supports structured grid. Considering that it's one of the best data format, and structured grids arise commonly while using Python (or anything FWIW), it may be a good idea to support this function.

As a minimal solution, there could at least be a method that converts a passed structured data into an unstructured dataset that meshio can process with the existing tools. I would think this is a fairly common use case.
