### ISSUE TITLE
Can't find `remove_lower_dimensional_cells` in recent versions of meshio

### ISSUE THREAD

**Issue by rbeucher** [nschloe/meshio#1280]
Hi @nschloe 

I have inherited some code that calls `remove_lower_dimensional_cells` pretty much every time it loads a mesh. 
Looks like that method is not on the mesh class anymore. I can't find when the change happened though.
I only had a quick look through the code but it is still needed? 

R

**Comment by nschloe** [comment]
Yeah, I took all mesh-manipulating routines out of meshio a while ago. Will publish a separate package with that soon.
