### ISSUE TITLE
[BUG] The function remove_orphaned_nodes has disappeared from the mesh class

### ISSUE THREAD

**Issue by baloe** [nschloe/meshio#1282]
**Describe the bug**
I used to be able to run `mesh.remove_orphaned_nodes() ` (formerly `mesh.prune()`) on a mesh class object, but this now raises an AttributeError.
I am a bit puzzled, because I don't see any reference to `remove_orphaned_nodes` being removed in the changelog.

**To Reproduce**
(example from from https://github.com/nschloe/meshio/issues/993)
```python
import meshio
mesh=meshio.read('t3.msh') # created by https://gitlab.onelab.info/gmsh/gmsh/-/raw/master/tutorials/python/t3.py
mesh.remove_orphaned_nodes()
mesh.write('t3_processed.vtu')
```

**Diagnose**

`conda list`:
```
# Name                    Version                   Build  Channel
meshio                    5.3.0              pyhd8ed1ab_0    conda-forge
```

`pip freeze | grep meshio`:
```
meshio @ file:///home/conda/feedstock_root/build_artifacts/meshio_1643072227861/work
```
No issue with `meshio 4.4.6`.

**Comment by baloe** [comment]
Okay, cool. Which one is the latest version that includes mesh manipulation?

**Comment by baloe** [comment]
< 5.3.5 I guess f0ea1083c2fb72d3fddebe1d12a7afa817c0ca6a

**Comment by nschloe** [comment]
I guess. Problem solved?

**Comment by baloe** [comment]
No, the issue persists with `5.2.6`, `5.0.5`, going back still ...

**Comment by baloe** [comment]
`5.0.0` is the one

**Comment by nschloe** [comment]
Thanks for looking it up.

**Comment by baloe** [comment]
> I've removed all mesh manipulation functions from meshio. Will release a separate package for that soon. 

Is it out, yet? Can I find it?

**Comment by dominik-kern** [comment]
> > I've removed all mesh manipulation functions from meshio. Will release a separate package for that soon.
> 
> Is it out, yet? Can I find it?

I am looking forward to this package, too.

**Comment by baloe** [comment]
Any news?
