### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'numpy.typing'      after installing 

### ISSUE THREAD

**Issue by saeed6991** [nschloe/meshio#1283]
Greetings,

right after installing meshio and trying to use it, this error pops up:
from numpy.typing import ArrayLike
ModuleNotFoundError: No module named 'numpy.typing'

Thanks in advance. :)

**Comment by nschloe** [comment]
You're using an outdated numpy version. Update to 1.20.0.

**Comment by saeed6991** [comment]
Thank you very much Mr. Schlömer, you have done awesome job! :)
