### ISSUE TITLE
[BUG] paraview plugin: 'meshio._helpers' has no attribute 'extension_to_filetype'

### ISSUE THREAD

**Issue by FIPE-System** [nschloe/meshio#1286]
**Describe the bug**
Error in import the modul into paraview.
paraview plugin: 'meshio._helpers' has no attribute '_extension_to_filetype'  like in issue #731

**To Reproduce**
Import the modul into paraview 5.9.1. MeshIO installed with python 3.8.12

**Diagnose**
the line 18 in paraview-meshio-plugin.py should be like 
``` python
# old: meshio_extensions = [ext[1:] for ext in meshio.extension_to_filetype.keys()]
meshio_extensions = [ext[1:] for ext in meshio.extension_to_filetypes.keys()]
```

There was a `s` missing in `extension_to_filetypes`.

**Comment by nschloe** [comment]
Thanks for the hint, fixed now!
