### ISSUE TITLE
Unable to read ply texture data

### ISSUE THREAD

**Issue by arpit15** [nschloe/meshio#1304]
**Describe the bug**
I am trying to load a `ply` mesh that has texture coordinates. I generated the textured mesh using meshlab. 

**To Reproduce**
```
import meshio
mesh = meshio.read("mymesh.ply")
```

**Did I help?**
I was able to resolve the problem by changing the [line 181](https://github.com/nschloe/meshio/blob/main/src/meshio/_mesh.py#L181) to the following
`if (data[k].size) != len(self.cells[k]):`

**Comment by nschloe** [comment]
This needs a mesh example so I can try it out.

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to comment/reopen at any time!
