### ISSUE TITLE
Add Netcdf with also it's variant Netcdf Ugrid (for unstructured data)

### ISSUE THREAD

**Issue by ccoulet** [nschloe/meshio#1309]
Good to have these new formats for mesh data as there are frequently used.
This is possible to use xarray to vreate netcdf file in python, so I think this could be quite easy to adapt meshio.

Regards

**Comment by nschloe** [comment]
NetCDF is a general data format, so that's not something to support here. I could look at ugrid though. Do you have some example files?

**Comment by nschloe** [comment]
Never mind, I figured it out. Will be part of the next release.

**Comment by MuellerSeb** [comment]
I can't find anything about this. Will this be part of the meshio-rewrite?

**Comment by nschloe** [comment]
Yep.
