### ISSUE TITLE
[BUG] vtu 2.2 format

### ISSUE THREAD

**Issue by andrewcorrigan** [nschloe/meshio#1322]
**Describe the bug**
The vtu reader fails for version 2.2 files (written out in some cases by vtk-9).  It raises an exception at:
```
            if version not in ["0.1", "1.0"]:
                raise ReadError(f"Unknown VTU file version '{version}'.")
```

**To Reproduce**

I've attached a small mesh file to reproduce.    [domain_00000000.vtu.zip](https://github.com/nschloe/meshio/files/8646136/domain_00000000.vtu.zip)

```
>>> import meshio
>>> m = meshio.read('domain_00000000.vtu')
Unknown VTU file version '2.2'.
Error: Couldn't read file domain_00000000.vtu as vtu
```

**Workaround**
If I simply tack on `"2.2"` to the list it works fine, at least for this simple mesh:
```
            if version not in ["0.1", "1.0", "2.2"]:
                raise ReadError(f"Unknown VTU file version '{version}'.")
```

```
>>> import meshio
>>> m = meshio.read('domain_00000000.vtu')
>>> m.points
array([[ 0.  , -0.  , -0.  ],
       [ 0.25,  0.  ,  0.  ],
       [ 0.25,  0.25,  0.  ],
       ...,
       [ 1.  ,  0.75,  1.  ],
       [ 1.  ,  1.  ,  1.  ],
       [ 0.75,  1.  ,  1.  ]], dtype=float32)
>>> m.cells
[<meshio CellBlock, type: VTK_LAGRANGE_HEXAHEDRON, num cells: 64, tags: []>]
>>> m.cells_dict
{'VTK_LAGRANGE_HEXAHEDRON': array([[  0,   1,   2,   3,   4,   5,   6,   7],
# ....
```

**Diagnose**

```
pip freeze | grep meshio 
meshio==5.3.4
```

**Did I help?**

I would be happy to submit a PR with the workaround above.   This should help meshio read at least certain version 2.2 files. 

(EDITED: I accidentally submitted prior to finishing typing this up)

**Comment by nschloe** [comment]
According to https://vtk.org/Wiki/VTK_XML_Formats, there is no such version `2.2`. Looks like a bug in the writer.

Anyway, this the issue does not occur in the upcoming version. (You'll just get a warning.)

**Comment by andrewcorrigan** [comment]
FYI, that wiki page is just out of date.   I found it mentioned in the VTK changelog for 9.1:

https://gitlab.kitware.com/vtk/vtk/-/blob/master/Documentation/release/9.1.md#data

A warning sounds good though, thanks.
