### ISSUE TITLE
VTK reader - AttributeError: 'NoneType' object has no attribute 'IsA'

### ISSUE THREAD

**Issue by haplav** [nschloe/meshio#134]
[annulus-20.exo.zip](https://github.com/nschloe/meshio/files/1418858/annulus-20.exo.zip)
We currently need an easy way to convert exodus files to the MED (Salome) format. One possibility we have come across is to convert exodus to gmsh using your tool meshio and then convert gmsh to med using GMSH.  But we have been not successful yet with the meshio part, see the error below. I attach the exodus file (distributed with PETSc); it's nevertheless the same with any other exodus file I tried. It's also the case for both Python 2.7.13 and 3.6.2.

Do you have any idea, what's the issue?

Thank you for this nice contribution to the community!

```
$ meshio-convert --input-format exodus --output-format gmsh-ascii annulus-20.exo bla.msh
Traceback (most recent call last):
  File "/opt/miniconda3/envs/p2/bin/meshio-convert", line 133, in <module>
    _main()
  File "/opt/miniconda3/envs/p2/bin/meshio-convert", line 16, in _main
    meshio.read(args.infile, file_format=args.input_format)
  File "/opt/miniconda3/envs/p2/lib/python2.7/site-packages/meshio/helpers.py", line 114, in read
    out = vtk_io.read('exodus', filename)
  File "/opt/miniconda3/envs/p2/lib/python2.7/site-packages/meshio/vtk_io.py", line 119, in read
    vtk_mesh = _read_exodusii_mesh(reader)
  File "/opt/miniconda3/envs/p2/lib/python2.7/site-packages/meshio/vtk_io.py", line 204, in _read_exodusii_mesh
    if sub_block.IsA('vtkUnstructuredGrid'):
AttributeError: 'NoneType' object has no attribute 'IsA'
```

**Comment by nschloe** [comment]
Released 1.8.17 with the fix. Enjoy!

Btw, if there is some interest in the MED/Salome format, I might add it to meshio as well. To probe this, we could open another issue request and see how many upvotes it gets.

**Comment by haplav** [comment]
It would be nice as it's maybe the only mesh format which can be loaded directly into a distributed mesh structure by PETSc.

For anybody familiar with PETSc: [DMPlexCreateMedFromFile()](http://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/DMPLEX/DMPlexCreateMedFromFile.html) function employs [DMPlexCreateFromCellListParallel()](http://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/DMPLEX/DMPlexCreateFromCellListParallel.html))

**Comment by haplav** [comment]
Opened https://github.com/nschloe/meshio/issues/137
