### ISSUE TITLE
support for MED/Salome format

### ISSUE THREAD

**Issue by haplav** [nschloe/meshio#137]
It would be nice to have support for MED/Salome format as it's maybe the only mesh format which can be loaded directly into a distributed mesh structure by PETSc.

For anybody familiar with PETSc: [DMPlexCreateMedFromFile()](http://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/DMPLEX/DMPlexCreateMedFromFile.html) function employs [DMPlexCreateFromCellListParallel()](http://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/DMPLEX/DMPlexCreateFromCellListParallel.html))

**Comment by nschloe** [comment]
Do you have an example mesh and a link to the mesh format specification?

**Comment by haplav** [comment]
Here is one med file with rather small 3D mesh: [cylinder.med.zip](https://github.com/nschloe/meshio/files/1437835/cylinder.med.zip). It's distributed together with PETSc. Is it sufficient? Note also that you can convert any gmsh file to med format by executing `gmsh -1 mesh.msh -format med -o mesh.med`. Regarding the format specification, I will look for it and come back to you.

**Comment by haplav** [comment]
[Here](http://docs.salome-platform.org/latest/dev/MEDCoupling/medloader.html) you can find documentation about the format and description of the API. They say their MEDCoupling library for MED file I/O is "fully written in C++ and wrapped in Python". So you could perhaps just call this API, at least for beginning - what do you think?

**Comment by nschloe** [comment]
> They say their MEDCoupling library for MED file I/O is "fully written in C++ and wrapped in Python

Yeah I've seen this too, but really that library is virtually inaccessible. You can download the source code or the 2GB binaries; no official distro packaging is available. Definitely not something to meshio can rely on.

I'm trying to get some understanding of the format, but it's hard without documentation. One reads that

> The official documentation of the MED-file format is available on-line (in French) in your SALOME installation at:
>
> ${MEDFILE_ROOT_DIR}/share/doc/html/index.html

Have you found this document anywhere?

**Comment by nschloe** [comment]
Alright, I've downloaded the sources and tried the code on as many meshes as possible -- it all seems fine now, MED (version 2)  is supported. I've tested some output files with gmsh.

That said, there will be many cases where the current code doesn't work, and the fact that they hide the specification doesn't make it easier. Anyways, feel free to open bugs if you encounter difficulties.

**Comment by haplav** [comment]
Thanks a lot! I appreciate your effort!
