### ISSUE TITLE
Physical groups .msh error

### ISSUE THREAD

**Issue by FrankFrank9** [nschloe/meshio#1388]
Hi,

when I write .gmsh file I lose all the informations about physical groups
If I use 
`Mesh.SaveAll = 1`
I cannot read the .msh file with meshio in python because of 

`ValueError: Incompatible cell data 'gmsh:physical'. 286 cell blocks, but 'gmsh:physical' has 19 blocks.`

Any idea on how to solve this issue?

**Comment by marie-cloet2000** [comment]
I have the same issue. How has this been solved?
