### ISSUE TITLE
Exodus converted to empty mesh

### ISSUE THREAD

**Issue by haplav** [nschloe/meshio#142]
Conversion of the [attached](https://github.com/nschloe/meshio/files/1457400/blockcylinder-50.exo.zip) file results into an empty mesh.

It seems this holds for arbitrary output format.
`meshio-convert --output-format vtk-ascii blockcylinder-50.exo blockcylinder-50.vtk`
even fails with
`ValueError: need at least one array to concatenate`

**Comment by nschloe** [comment]
Fix released.

**Comment by haplav** [comment]
Thanks!
