### ISSUE TITLE
MED conversion inverts cells

### ISSUE THREAD

**Issue by haplav** [nschloe/meshio#144]
It seems that meshio inverts cells when converting from/to MED.

[Here](https://github.com/nschloe/meshio/files/1467023/med-issue.zip) I attach an example. I first converted .msh to .med using meshio, then converted this by gmsh to .msh, and finally converted this back to .med by meshio.

The problem is obvious even from comparing the two gmsh-ascii files `doublet-tet.1.msh` and  `doublet-tet.3-gmsh-med-meshio-msh.msh`.

**Comment by nschloe** [comment]
To clarify: When doing
```
msh --meshio--> med --gmsh--> msh
```
the input and output meshes are different?

I've tried
```
msh --meshio--> med --meshio--> msh
```
The raw data from the med file is
```
[2 2 4 3 3 4 1 5]
```
which corresponds very well with the input gmsh file
```
[...] 2 4 3 1
[...] 2 3 4 5
```
and here input and output are the same. It's possible that the med-"standard" prescribes that the cells be read and written in reverse order, but I doubt that. Perhaps a bug in gmsh then?

**Comment by haplav** [comment]
Yes, for the sequence `msh --meshio--> med --gmsh--> msh`, the input and output differs as I described. Optically the med and the final msh from this pipeline looks the same in gmsh. For `msh --meshio--> med --meshio--> msh`, input and output is indeed the same - I thought that the second conversion applies the same inversion, so inversion of inversion results in a proper mesh.

But it's true it still could be a bug in gmsh. And it's quite likely - I realise gmsh must do something nasty because the [PETSc reader for gmsh inverts tetrahedra and hexahedra back](http://bitbucket.org/petsc/petsc/src/14574d893f69ed2dca85956bc1c88ee3c7a3a57a/src/dm/impls/plex/plexgmsh.c#plexgmsh.c-547) - so gmsh could do the same with med. Your `h5dump` argument is quite convincing.

For gmsh conversion, I use
```
gmsh -1 file.msh -format med -o file.med
```

**Comment by nschloe** [comment]
Nice job digging out the quirk in the PETSc reader.

Perhaps you can file a bug for gmsh [here](https://gitlab.onelab.info/gmsh/gmsh/issues). Mark me (my ID is `nschloe` there as well) and see what comes out of this. Starting from your simple msh file, doing the conversion with gmsh and checking the result with `h5dump` should be convincing.

**Comment by nschloe** [comment]
Any news on this?

**Comment by nschloe** [comment]
Closing for lack of response. Feel free to reopen at any time!
