### ISSUE TITLE
 fail to import the converted XDMF file into FEniCS

### ISSUE THREAD

**Issue by bingnotes** [nschloe/meshio#152]
```python
from fenics import *
mesh=Mesh()
XDMF = XDMFFile(mpi_comm_world(), "test.xdmf")
XDMF.read(mesh)
```
```
*** Error:   Unable to recognise cell type.
*** Reason:  Unknown value "".
```

**Comment by nschloe** [comment]
Uhm... How is this related to meshio? Does FEniCS use it under the hood?

**Comment by bingnotes** [comment]
For large mesh, I am trying to use meshio-convert to convert the MSH format to XDMF format that better to read for FEniCS.

**Comment by nschloe** [comment]
Okay. Maybe it's a FEniCS bug? Have you tried opening the file with another application, e.g., ParaView?

**Comment by bingnotes** [comment]
Yes, the converted XDMF file can be opened by ParaView.

**Comment by nschloe** [comment]
Doesn't it sound like a FEniCS bug then?

**Comment by bingnotes** [comment]
probably yes.

**Comment by nschloe** [comment]
Alright. It might still be a meshio bug, but let's close this one until we've heard from FEniCS.
