### ISSUE TITLE
Different element types should be returned by msh_io.py at the same time

### ISSUE THREAD

**Issue by nilswagner** [nschloe/meshio#16]
If tetrahedras and triangles are present in a msh file, only tetrahedra are returned by msh_io.py.

    if len(elems['tetrahedra']) > 0:
        cells = elems['tetrahedra']
    elif len(elems['triangles']) > 0:
        cells = elems['triangles']
    else:
        raise RuntimeError('Expected at least triangles.')

    return points, cells

An example msh file is attached, i.e. t2.msh
http://chunk.io/f/ff39b563d5a84431bf51255d3f7834e4

**Comment by nschloe** [comment]
This concerns every mesh type. Organizing the cells as a dictionary actually seems like a good idea here.

**Comment by nschloe** [comment]
Fixed in 1.0.1.
```
meshio-convert t2.msh t2.vtk
```
![t2](https://cloud.githubusercontent.com/assets/181628/11420199/e40ca9a4-942c-11e5-97de-0cb2a0e38a84.png)
