### ISSUE TITLE
Simple Example: writing to exodusii?

### ISSUE THREAD

**Issue by Chaztikov** [nschloe/meshio#166]
Hi again,

I'm trying to make a simple mesh (with two boundaries, for peridynamics) using pygmsh and meshio for use in libmesh.  I have the following code

from math import pi
import pygmsh
import pytest

from helpers import compute_volume
import meshio
import pygmsh

def test_ball(center=[0,0,0],r=1,rmax=1.1,lcar=0.1):
    geom = pygmsh.opencascade.Geometry(
      characteristic_length_min=lcar,
      characteristic_length_max=lcar*1.1,
      )

    ball1 = geom.add_ball([0.0, 0.0, 0.0], 1.0)#geom.add_ball(center, r)
    ball2 = geom.add_ball([0.0, 0.0, 0.0], 1.1)#geom.add_ball(center, rmax)
    union = geom.boolean_union([ball1,ball2])

    points, cells, point_data, cell_data, field_data = pygmsh.generate_mesh(geom)
    return points, cells

center=[0.,0.,0.]
r=1.
rmax=1.1
lcar=0.0001
points,cells = test_ball(r,rmax,lcar)
meshio.write('ball.e', points,cells)

meshio.exodus_io.write('ball.e', points,cells)

 I get the following error:

ball.e
ERROR! Unrecognized element type_str: EDGE
[0] ../src/mesh/exodusII_io_helper.C, line 2055, compiled Dec  5 2017 at 10:09:59

The beginning of the libmesh code is:

int main (int argc, char ** argv)
{
  LibMeshInit init (argc, argv);

  libMesh::out << "Running " << argv[0];
  for (int i=1; i<argc; i++)
    libMesh::out << " " << argv[i];
  libMesh::out << std::endl << std::endl;

  ReplicatedMesh mesh(init.comm() , ndim);
  std::cout<<input_mesh<<std::endl;
  mesh.read(InParams::input_mesh);
  mesh.print_info();

This approach seemed to work for a number of 2D cases using pygmsh.

**Comment by nschloe** [comment]
Sounds like a libmesh issue. Have you tried opening the mesh with any other tool yet?

**Comment by Chaztikov** [comment]
Yes, it seems to work without issue with paraview,
My guess is that one of the dictionary values ('EDGE'?) is named in a way
that libmesh doesn't recognize (perhaps if I rename 'EDGE' to 'EDGE3' this
will work?) I've asked Roy at libmesh as well.

**Comment by Chaztikov** [comment]
I hope this isn't poor etiquette, but here is John's answer at libmesh:
"

Looks like meshio is writing an Exodus file with "EDGE" elements, but we
don't have an equivalence set up for that string (see exodusII_io_helper.C
line 64). Adding the line

element_equivalence_map["EDGE"]  = EDGE2;

might fix the problem.
"

to avoid changing this, I tried renaming keys, this does not seem to work,
so I'll try his suggestion
[image: Inline image 1]

**Comment by nschloe** [comment]
Yup. I'd say libmesh should just skip over elements it doesn't know and perhaps show a warning about it. Anyhow: Not a meshio bug. :)
