### ISSUE TITLE
STL format

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/meshio#177]
Reading STL format was mentioned in nschloe/pygmsh#133; meshio currently doesn't claim to, but it would probably be pretty easy; similarly for writing.  It's not a very useful format but is widespread.

**Comment by gdmcbain** [comment]
I have had success in the past reading STL in Python using [stl](https://pypi.python.org/pypi/stl/0.0.3), though I think all I was doing was computing the bounding-box before passing the STL to [snappyHexMesh](https://cfd.direct/openfoam/user-guide/snappyHexMesh/), one of OpenFOAM's unstructured meshing utilities.

**Comment by nschloe** [comment]
I just checked out STL and suspect one problem: the points are given for each triangle individually. This means that edges and points of adjacent triangles are not automatically identified with each other. This defeats many applications.

Identifying the points will require some effort. Perhaps computing the minimal circumradius and taking a fraction of it as tolerance. Hm...

**Comment by gdmcbain** [comment]
Yes that's right. It's a horrible old-fashioned format. I think the designers were worried about having to keep an array of points in memory.
   One might be lucky and have each point referred to with identical coordinates in each triangle that it appears in, but very often this is not the case in STL found in the field, particularly STL generated by certain CAD programs.
 
Another nasty feature of this format is that it is so simple but lacking in a precise specification, so that it is usually generated howsoever. Like CSV. This demands flexibility of a reader. For example, the file sphere.stl distributed with the Gmsh sources foils the Python stl package that I referred to because its first line is

```
solid Created by Gmsh
```

It works if the second and third spaces are replaced by underscores. The [numpy-stl](http://numpy-stl.readthedocs.io/en/latest) package, on the other hand, doesn't mind. Some STL omits the name of the solid.

Other variations in compliance:
* The specification demands that the triangles between 'solid' and 'endsolid' form a closed surface (topological sphere) but many STL files are used to define surfaces with boundary loops, e.g. for boundary patches for snappyHexMesh.
* The specification wants exactly one 'solid', but many STL files contain several concatenated. Ditto.
* The specification wants everything in the first octant; i.e. all coordinates nonegative, but this is widely flouted.

These misfeatures defeat, as you say, many applications. The best thing a user could do would be to generate an alternative like GTS or OFF, but the format (again like CSV) stubbornly persists and the finite element analyst does often have to deal with it. On reflexion, I shouldn't have described reading it above as 'pretty easy'. 
   I don't think the stl or numpy-stl packages deal with the question of identifying coincident or nearly coincident points; they're not for finite element analysis.

**Comment by nschloe** [comment]
Fixed by #178.
