### ISSUE TITLE
CellData does not contain correct information on faces.

### ISSUE THREAD

**Issue by kayarre** [nschloe/meshio#181]
I have an issue when reading a vtu file into meshio where information is contained in the wrong cell.
The cell data should be assigned to the 2d cell and  not the 3d cell that the 2d cell is apart of.

I have a tubular volume mesh with walls. (it has quads, tri's, tetras, and wedges) where there is CellEntityId information on each cell type. volume=0, outer_wall=1, other boundaries=2-4
```
points, cells, point_data, cell_data, field_data = meshio.read(fn, file_format="vtu-binary")
```
I get the following unique ids:
```
In [11]: np.unique(cell_data['triangle']['CellEntityIds'])
Out[11]: array([0, 1], dtype=int32)

In [12]: np.unique(cell_data['quad']['CellEntityIds'])
Out[12]: array([0], dtype=int32)

In [13]: np.unique(cell_data['wedge']['CellEntityIds'])
Out[13]: array([0, 2, 3, 4], dtype=int32)

In [14]: np.unique(cell_data['tetra']['CellEntityIds'])
Out[14]: array([0, 2, 3, 4], dtype=int32)

but what I was expecting to get was
In [11]: np.unique(cell_data['triangle']['CellEntityIds'])
Out[11]: array([1, 2,3,4], dtype=int32)

In [12]: np.unique(cell_data['quad']['CellEntityIds'])
Out[12]: array([2,3,4], dtype=int32)

In [13]: np.unique(cell_data['wedge']['CellEntityIds'])
Out[13]: array([0], dtype=int32)

In [14]: np.unique(cell_data['tetra']['CellEntityIds'])
Out[14]: array([0], dtype=int32)
```
I can confirm the error by opening the file in paraview and thresholding on the celldata gives the correct surfaces.

[DSI020CALb_vmtk_decimate_trim_ext2_mesh.vtu.zip](https://github.com/nschloe/meshio/files/1620844/DSI020CALb_vmtk_decimate_trim_ext2_mesh.vtu.zip)

Thank you so much for sharing this software!

**Comment by nschloe** [comment]
Fixed by #182; thanks for the report.
