### ISSUE TITLE
handle cell and cell data together

### ISSUE THREAD

**Issue by nschloe** [nschloe/meshio#183]
meshio splits cell and cell data by cell type. This is not handled at the same time which causes bugs like #181.

TODO: Handle cell and cell data at the same time.

**Comment by carvalhoamc** [comment]
import pandas as pd
import meshio
import numpy as np

df_points = pd.read_csv('x1data_points.csv',names=['x','y','z'],delimiter=' ')
df_simplicies = pd.read_csv('x1data_simplices.csv',names=['x0','x1','x2','x3'],delimiter=' ',dtype='int')
df_properties = pd.read_csv('x1data_tetra_props.csv')
df_stats = pd.read_csv('x1data_tetra_stats.csv')
points = df_points.values
cells = df_simplicies.values
classes = df_properties.values
cells = {
    "tetra":cells
    }

cell_area = df_stats['area'].values
elements = list(cell_area)
keys = list(df_simplicies.index.values)
area_dictionary = dict(zip(keys,elements))
meshio.write_points_cells("x1data.vtk", points, cells,cell_data=area_dictionary)

Could you help me to solve last line? What is the cell_data format?
Thanks!

**Comment by nschloe** [comment]
@carvalhoamc Please don't hijack this issue. Open a new one.

**Comment by MuellerSeb** [comment]
Maybe it would be nice to have at least an extra cell_data array containing the element_ids in the order they appear in the input file, since this information is lost. But I guess this would result in a lot of work, since every reading and writing routine has to adopt that.

**Comment by MuellerSeb** [comment]
Or is the order of elements somehow preserved?

**Comment by nschloe** [comment]
Nah, order isn't preserved, at least not generally. The thing is that meshio always groups together cells of one type to make storage (and everything else) easier. Some mesh formats allow different cell types to be arbitrarily mixed. I'm not sure if we want to preserve that; it'd certainly require some tinkering.

**Comment by MuellerSeb** [comment]
I'd like to use it for [OGS5](https://github.com/ufz/ogs5) where additional cell data is stored separately with just an ID for the involved cells. ATM I just export the cell-ID as cell-data, to preserve it.

**Comment by nschloe** [comment]
Multiple restructurings have been going on since this bug has been opened, so let's just call it obsolete.
