### ISSUE TITLE
read nodal/cell data from med

### ISSUE THREAD

**Issue by tianyikillua** [nschloe/meshio#186]
I start to work on reading field (in general) data from a med file, as you can see [here](https://github.com/tianyikillua/meshio/commit/4106f66d0f1a44bdceaa3ae4082e2f6a0665b825).

Reading nodal field seems easy and should already work.

For reading cell field it may demand some work. The MED format is strongly influenced by Code_Aster, and they in general define "cell field" directly on gauss points. We can adopt the following approach

- for elements where lies only 1 gauss point (linear simplices, or reduced integration), simple (TODO);
- otherwise, we can just perform an arithmetic mean of all the values at the Gauss points inside one particular element.

In the latter case, `meshio` does not only "reading" but also some "computation"...it seems outside its scope. Hence we can also just neglect these fields when the number of Gauss points is larger than 1.

**Comment by nschloe** [comment]
Nice! You could first make a PR for nodal data, then for cell data if it's that much more complex.

Cell data can be anything stored "per cell", so I don't see nothing wrong storing a vector that keeps the data at whatever points MED prescribes. This could also be plugged into any other mesh format, just that the viewers wouldn't interpret the data as "values at Gauss points" but simply as vectors associated with cells. Never mind that I guess.

You're right: If you want to convert a MED file with such cell data to, e.g., VTU, and would like ParaView to show the data correctly, you'd have to do some transformation. I wouldn't mind doing that in the MED reader though, as an option. One could then use, e.g.,
```
meshio-convert in.med out.vtu
```
to get the 1-to-1 vector transformation, and
```
meshio-convert --translate-med-cell-data in.med out.vtu
```
to generate a single cell value from the Gauss-point values.

By the way, until now I haven't seen any description of the MED file online, so I'll have to rely on you to get it right. If you have a link to the standard, that would be great.

**Comment by tianyikillua** [comment]
I'll make a PR for the nodal data in the first place. I attach [here](https://github.com/nschloe/meshio/files/1639089/test-med-data.zip) a test MED file generated by a Code_Aster calculation.
```
points, cells, point_data, cell_data, field_data = meshio.read("test.rmed", file_format="med")
```
should give you a `point_data` containing three fields: the displacement, and stress/strain averaged at nodes (`SIGM_NOEU` and `EPSI_NOEU`) computed by Code_Aster.

Attention, the ordering for these symmetric 2nd order tensors is the following in MED
```
XX YY ZZ XY XZ YZ
```
However for VTU-like formats (to be read in ParaView), we should have
```
XX YY ZZ XY YZ XZ
```
Additional care is to be taken by the user and by the script `meshio-convert`.

I didn't find a detailed description of the MED format either. I just used [HDFView](https://www.hdfgroup.org/downloads/hdfview/)...

**Comment by nschloe** [comment]
Can this be closed now?
