### ISSUE TITLE
Error when reading in vtk files

### ISSUE THREAD

**Issue by r-maas** [nschloe/meshio#188]
After upgrading meshio to the latest version I suddenly got an error when reading in .vtk files. First error was from this line

https://github.com/nschloe/meshio/blob/6df849486c21fc5e353166701ee9de5ce15bb06f/meshio/vtk_io.py#L267

Changing it to

`dtype = vtk_to_numpy_dtype[data_type]`

Seemed to fix the problem. But I don't know if there was a reason for addign the , _

**Comment by nschloe** [comment]
Like my mum always says: Untested code is broken code. And lo and behold: [The line in question is untested](https://codecov.io/gh/nschloe/meshio/src/master/meshio/vtk_io.py#L267).

I'll fix this and make sure that the tests are extended to capture this in the future.

Thanks a lot for the hint!

**Comment by nschloe** [comment]
Alright, testing turns out to be more difficult for such `SCALARS` fields, I just simply fixed the bug for now. Check out 1.11.3, and thanks again for the report.

**Comment by r-maas** [comment]
Thanks for the quick fix Nico, new version works right away!
