### ISSUE TITLE
GMSH: physical and elementary tags in the `$Elements` section

### ISSUE THREAD

**Issue by dalcinl** [nschloe/meshio#197]
This is a piece of the Gmsh online docs: http://gmsh.info/doc/texinfo/gmsh.html#MSH-ASCII-file-format

> _number-of-tags_
gives the number of integer tags that follow for the n-th element. By default, the first tag is the number of the physical entity to which the element belongs; the second is the number of the elementary geometrical entity to which the element belongs; the third is the number of mesh partitions to which the element belongs, followed by the partition ids (negative partition ids indicate ghost cells). A zero tag is equivalent to no tag. Gmsh and most codes using the MSH 2 format require at least the first two tags (physical and elementary tags).

Please note the last sentence. At some point you modified the writer to not output the physical and elementary tags in the `$Elements` section. However, PETSc https://www.mcs.anl.gov/petsc/ expects these tags right there in the `$Elements` section. I beg you to revert this change, at this point `meshio` is basically unusable for me.

**Comment by dalcinl** [comment]
IMHO, your current writer misunderstand the intention of `$NodeData` and `$ElementData` sections. These sections are supposed to attach scalar or field data associated to nodes or cells, they have nothing to do with specifying the physical and elementary regions each entity is tagged with.

**Comment by nschloe** [comment]
Sounds like https://github.com/nschloe/meshio/issues/175.

**Comment by dalcinl** [comment]
Yes, it is related. However, note that I consider this issue a regression. A few months back, regions were encoded in output Gmsh files just fine. Now they are not, meshio is confusing node/cell data with regions.

**Comment by nschloe** [comment]
Yes, I get it now. You're saying your code used to work because previously, meshio always wrote physical and geometrical data out to a file, no matter if it was present in the input data or not, and it doesn't anymore. That's true. The reasoning behind this is to remove logic from meshio, and instead just write exactly what is given by the user.

What you could do here is to add the data yourself. Just
```python
meshio.write(..., cell_data={'triangle': {'physical': ..., 'geometrical': ...}})
```
Given the cited statement in gmsh docs, meshio could also issue a warning if those two fields aren't present.

**Comment by dalcinl** [comment]
No, I don't think your tip will work. Look at `_write_elements()`, `fcd` is an empty array, meshio currently does not dump the the physical and elementary tags. I expect many software out there to expect these tags to apply material coefficients or boundary conditions. This is certainly the case of PETSc-based codes. In other words, and IMHO, the right way to specify regions in Gmsh files is in the `$Element` section, the other `$XXXData` sections serve a different purpose (e.g, attach solution data for postprocessing with the Gmsh GUI).

Please try the following: Create a msh file natively with Gmsh. Next read and write back to a new file using meshio. Finally, open the new file with Gmsh GUI. You should notice that all region information is lost, and the Gmsh GUI is basically interpreting the `$ElementData` as a scalar solution field on cells, and all labels are lost (you can turn on labels visibility with Options -> Mesh (in the left pane) -> Visibility (top tab) and clicking on the "Surface labels" checkbox)

**Comment by nschloe** [comment]
Ah yes, you're right. meshio doesn't support regions at all now; whatever you'll put in `cell_data` will end up as `$ElementData`. Shall we discuss how to implement those in #175?

**Comment by nschloe** [comment]
Should be fixed now.
