### ISSUE TITLE
discussion: container class?

### ISSUE THREAD

**Issue by nschloe** [nschloe/meshio#198]
meshio returns quite a few data items right now, and there will be more. Perhaps it's time to think about some sort of container for them. Perhaps a dict or a custom class?

**Comment by gdmcbain** [comment]
On looking at the snippet for my class Mesh posted in #175, I thought that perhaps a [`namedtuple`](https://docs.python.org/3/library/collections.html?highlight=namedtuple#collections.namedtuple) would have sufficed.

There had been some talk of using these to return multiple values in SciPy and related projects; see, e.g., scipy/scipy#3991.

Later, I think that that idea was been superseded by another generic container class called [`Bunch`](https://gist.github.com/ev-br/a11e5a25a98c2b0115ed), as discussed in [scipy#3665](https://github.com/scipy/scipy/issues/3665#issuecomment-106085454).

There are a mixture of behaviours in SciPy 1.0.0, with functions returning:
* multiple values (i.e. plain tuples)
* namedtuples
* objects like Bunch, e.g. [`scipy.optimize.OptimizeResult`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.OptimizeResult.html#scipy.optimize.OptimizeResult)

OptimizeResult subclasses `dict`.

**Comment by nschloe** [comment]
Alright, there now is `Mesh` class. :fireworks:

**Comment by cbcoutinho** [comment]
This is really nice idea Nico, thanks for the implementation :thumbsup:
