### ISSUE TITLE
Error in conversion of .xml file to .stl file

### ISSUE THREAD

**Issue by OvJafri** [nschloe/meshio#203]
Hi there,
I am trying to convert my .xml mesh file(screen shot attached) to .stl file using meshio. The syntax that i use is as under

import meshio
meshio-convert mesh115.xml output.stl

**However i am getting error** 
  meshio-convert input.xml output.stl
                     ^
SyntaxError: invalid syntax

Please look into this matter. 
Best regards.
![1](https://user-images.githubusercontent.com/35419217/36312306-d3cdbbf6-134f-11e8-9aa4-19becf3c4205.JPG)

**Comment by nschloe** [comment]
Yeah I screen shot is no good, I'm not gonna type it all over to reproduce the error. I need the actual file, or even better: A smaller version of it that still reproduces the error.

**Comment by OvJafri** [comment]
yea right. (I did try to attach the file but somehow my mesh file was not getting attached earlier). Now i am have attached it. 
[mesh115_refined.xml.gz](https://github.com/nschloe/meshio/files/1731872/mesh115_refined.xml.gz)

**Comment by nschloe** [comment]
Works for me.
![f](https://user-images.githubusercontent.com/181628/36316168-e81807d0-1339-11e8-8c5e-1478bc29e4fd.png)

Perhaps upgrade?

**Comment by OvJafri** [comment]
upgrade what ?

**Comment by OvJafri** [comment]
Is this the .stl version ? that you have plotted

**Comment by OvJafri** [comment]
I am using python 2.7 and i installed meshio through  pip install -U meshio

**Comment by nschloe** [comment]
What version of meshio are you using? `meshio-convert -v`

**Comment by nschloe** [comment]
And what's the full error message?

**Comment by OvJafri** [comment]
I tried to install meshio again through pip install -U meshio
But now getting following error as i try to install:-
![image](https://user-images.githubusercontent.com/35419217/36317337-a0ca2be0-135e-11e8-87ce-3cdec7cc19cb.png)

**Comment by OvJafri** [comment]
When i tried the version command it says:-
![image](https://user-images.githubusercontent.com/35419217/36317437-e8f711c6-135e-11e8-8f66-14ba34fc3f0f.png)

**Comment by nschloe** [comment]
Instead of screenshotting from the command line, you can just copy and paste this and put it in triple dashes. See https://guides.github.com/features/mastering-markdown.

**Comment by nschloe** [comment]
Now I'm wondering how to convert at all if meshio isn't installed. :confused:

**Comment by OvJafri** [comment]
But when i use the following code:-

from dolfin import*
import meshio
import numpy as np

points = np.array([[0.0, 0.0, 0.0],[0.0, 1.0, 0.0],[0.0, 0.0, 1.0],])
cells = {'triangle': np.array([[0, 1, 2]]) }
meshio.write('foo1.vtk', points, cells,)

it works! .... means meshio is installed.

**Comment by OvJafri** [comment]
so to sum up , meshio is working for this simple sample code but not converting the mesh. There might be some version issue or may be something else and how to troubleshoot. I am running fenics latest version on docker through dolfinadjoint.

**Comment by nschloe** [comment]
Okay, I've corrected your post by inserting some dashed. It makes it more readable.

You original post says

> However i am getting error
> meshio-convert input.xml output.stl
> ^
> SyntaxError: invalid syntax

... Wait, did you try this is Python code? ...

**Comment by OvJafri** [comment]
will respond back in a while

**Comment by OvJafri** [comment]
yes , i tried in FEniCS environment

**Comment by gdmcbain** [comment]
`meshio-convert` is a shell command, not a Python function.  Type it in Bash.

The same functionality is available in Python with a combination of `meshio.read` and `meshio.write`, if required.

**Comment by OvJafri** [comment]
thanx! i have converted files to .stl using similar code that u have suggested (as under)
--------------------------------------------------------------------------------------
from dolfin import*
import meshio

points, cells, point_data, cell_data, field_data = meshio.read('mesh115.xml')
meshio.write('mesh_vent.msh', points, cells)
