### ISSUE TITLE
Clean artefacts generated by the tests

### ISSUE THREAD

**Issue by ghisvail** [nschloe/meshio#204]
Some [files](https://github.com/nschloe/meshio/blob/6df849486c21fc5e353166701ee9de5ce15bb06f/test/test_helpers.py#L10) are generated by the tests and may end up installed under `dist-packages` as reported in the [Debian BTS](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892019).

Please consider either generating these files in a temporary location, or remove them after the assertions are passed.

**Comment by nschloe** [comment]
Fixed in 1.11.8. Thanks for the report!

**Comment by ghisvail** [comment]
No problem. Thanks for the prompt fix.

Le 7 mars 2018 09:37, "Nico Schlömer" <notifications@github.com> a écrit :

Fixed in 1.11.8. Thanks for the report!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nschloe/meshio/issues/204#issuecomment-371080210>, or mute
the thread
