### ISSUE TITLE
KeyError: 'line' in ansys_io.py line 453, in write

### ISSUE THREAD

**Issue by ronaldtanner** [nschloe/meshio#208]
Using meshio 1.11.9 (python 3.4) gives me a keyerror when trying to convert a 2D gmesh file [model.zip](https://github.com/nschloe/meshio/files/1807202/model.zip) to ansys:
```
meshio-convert --input-format gmsh-ascii --output-format ansys-binary model.msh model.ansys
```

**Comment by nschloe** [comment]
That's because ANSYS files don't support `line` elements.

**Comment by nschloe** [comment]
Closing for lack of response. Feel free to reopen at any time.
