### ISSUE TITLE
Problem when writing Gmsh mesh with cell data

### ISSUE THREAD

**Issue by MarieHouillon** [nschloe/meshio#210]
Hello,

I'm using meshio to read and write Gmsh mesh files, and I encountered a problem when trying to handle Physical groups : the mesh file is correctly read, but when I try to write it again in a file in Gmsh format, the nodes and elements are not written in the file.

I attached an example : in.msh is the input file (containing two Physical groups) and out.msh is the output file generated by meshio.

Here is the code I used :

```
mesh = pygmsh.meshio.read("in.msh")
meshio.write("out.msh", mesh[0], mesh[1], cell_data=mesh[3], field_data=mesh[4])
```

Thanks in advance for your help.

[mesh.zip](https://github.com/nschloe/meshio/files/1853132/mesh.zip)

**Comment by nschloe** [comment]
Thanks for the report. There was indeed an issue about how cell data was written. Should be fixed now.
