### ISSUE TITLE
xdmf to gmsh hiccup

### ISSUE THREAD

**Issue by pGarlick** [nschloe/meshio#213]
Hi,

Using meshio 1.11.8 I have been able to convert xdmf files to gmsh format for post-processing FEniCS data.  Thank you very much for the fine utility.  

However, I needed to filter the generated files with _awk_ to remove the numpy array formatting of the data.  I used the command:
`$ meshio-convert --output-format gmsh-ascii mach_number.xdmf mach_number.msh`

Then,
`$ tail mach_number.msh`
produces:
```
1794 array([1.5010948], dtype=float32)
1795 array([0.41827482], dtype=float32)
1796 array([1.7710645], dtype=float32)
1797 array([0.42079014], dtype=float32)
1798 array([0.79673445], dtype=float32)
1799 array([1.5470289], dtype=float32)
1800 array([0.4292248], dtype=float32)
1801 array([1.5006031], dtype=float32)
1802 array([0.43062833], dtype=float32)
$EndNodeData
```

Gmsh produces an input error for this file.  After using _awk_ to remove the numpy formatting this becomes:
```
1794 1.5010948
1795 0.41827482
1796 1.7710645
1797 0.42079014
1798 0.79673445
1799 1.5470289
1800 0.4292248
1801 1.5006031
1802 0.43062833
$EndNodeData
```
which can then be read by Gmsh.

I can see that _xdmf_io.py_ has a function _numpy_to_xml_string_ but this is only used by the xdmfWriter class.  Could gmsh_io.py use the same function before writing the .msh file?

**Comment by nschloe** [comment]
I need a mesh so I can reproduce the error.

**Comment by nschloe** [comment]
Alright, fixed now. Grad 1.11.11. :tada:
