### ISSUE TITLE
Multiple output formats

### ISSUE THREAD

**Issue by massimiliano-leoni** [nschloe/meshio#218]
I think it would be convenient to be able to convert a mesh to more than output format in a single run. For example something like `meshio-convert mesh.msh mesh.vtu mesh.stl` would read an `msh` mesh and write the same mesh converted to `vtu` and `stl` formats.

**Comment by nschloe** [comment]
Looks to me that this can be easily achieved with one line of bash, something like
```bash
for ext in "vtu" "stl"; do meshio-convert mesh.msh mesh.$ext; done
```

**Comment by massimiliano-leoni** [comment]
It can [without the quotes though], but that implies reading the mesh twice, which takes time with big meshes.

**Comment by nschloe** [comment]
Fair enough. I wouldn't mind a PR then.

**Comment by massimiliano-leoni** [comment]
Who would... XD
