### ISSUE TITLE
vtk-binary floats is read as `<f8` but type is not valid when writting

### ISSUE THREAD

**Issue by panchagil** [nschloe/meshio#229]
When reading a vtk-binary files the dtype of floats is loaded as `<f8` but that type is nor recognized when trying to write.

``` python
points, cells, point_data, cell_data, field_data = meshio.read(in_file)
meshio.write(out_file, points, cells, point_data, cell_data, field_data)
``` 

``` bash
File "python3.4/site-packages/meshio/vtk_io.py", line 416, in _write_points
    len(points), numpy_to_vtk_dtype[points.dtype]
KeyError: dtype('>f8')
```
The change of dtype is done in this line,
https://github.com/nschloe/meshio/blob/d6f226a0993f6f8ecdebee258873bc2ddc80fcdb/meshio/vtk_io.py#L150

**Comment by nschloe** [comment]
I need the mesh and some code to reproduce this.
