### ISSUE TITLE
Medit correct whitespace parsing

### ISSUE THREAD

**Issue by leoschwarz** [nschloe/meshio#237]
I'll look into fixing this bug in the next days, however just documenting it here already.

I'm experiencing this trying to parse `tetgen` output in MEDIT mesh format, meshio seems to be more strict in regards to not accepting line breaks between certain items unlike MEDIT.

Example `.mesh` file which currently fails to parse: https://gist.github.com/leoschwarz/5e6fc03941d6fddf9bbd57d45fe4ef84 (You can reproduce this by invoking tetgen with [this surface](https://gist.github.com/leoschwarz/3ef49c07bf9f82a00a9aa74c6760bb53) mesh if you like.)

According to the description in the MEDIT technical record (https://www.ljll.math.upmc.fr/frey/publications/RT-0253.pdf section 7.2):

> The blanks, ”newline” or <CR> and tabs are considered as item separators. A comment line starts with the character # and ends at the end of the line. The comments are placed exclusively between the fields.

Note it says "item seperator" and not "fields". Now I'm not 100% certain how this is meant (it's not very explicit with the format definition), but in the wild there seems to be the interpretation that this can mean 

```
Dimension
3
```

is also valid.

**Comment by nschloe** [comment]
Right. When reading, meshio should be as liberal as possible. (And as strict as possible when writing.)
