### ISSUE TITLE
Interactive usage of meshio in notebook with fenics

### ISSUE THREAD

**Issue by GProtoZeroW** [nschloe/meshio#242]
usage issue:

I am wanting to know how to use `meshio` interactively in the jupyter notebook to take the results of a fenics simulation at any time and convert to the results to Exodus II or some other data struct that will work with YT. The answer I am hopeing for would mean I dont have to write the data to a `.xml` dolfin or VTK file first then read that back in and convert to another file, but instead work with live objects in the session.  

The example notebook where I have attempted this before finding meshio with all the docs is here https://github.com/GProtoZeroW/IssueNotebooks/blob/master/FENICS%20YT.ipynb; 
thanks

**Comment by nschloe** [comment]
Hi Steve,

please be more specific on what exactl you're trying to achieve.

**Comment by GProtoZeroW** [comment]
Read the notebook
but here is the jist of it
take a fenics output `u` which i believe is a dolfin xml and view it in yt where yt will read exodus II or a cell averaged see: http://yt-project.org/doc/examining/loading_data.html#unstructured-grid-data via meshio so without having to write any intermediate files. Also, I have tried converting both a  dolfin.xml and .vtu to exodus II (.e) file with error using meshio-convert in the terminal

**Comment by nschloe** [comment]
> Read the notebook

You cannot expect the maintainer of any package to read through your own code and try  to figure out what the problem is.

> take a fenics output u which i believe is a dolfin xml 

`u` is a FEniCS function, not a file.

> where yt will read exodus 

Err, where does Exodus come into play?

> Also, I have tried converting both a dolfin.xml and .vtu to exodus II (.e) file with error using meshio-convert in the terminal

If you're getting conversion errors, you need to open a separate bug with the mesh appended.

**Comment by GProtoZeroW** [comment]
Oky I have trolled github to have notebook postings to the issues. Trying to do copy and past code that is not interactive is dump. 

I need to have meshio read in a fenics object `u` wich I have saved to .pvd(.vtu) and to dolfin -xml  and then be able to have meshio ouput a format that will work with the python yt library (https://yt-project.org/) where according to there docs http://yt-project.org/doc/examining/loading_data.html#exodus-ii-data, http://yt-project.org/doc/examining/loading_data.html#generic-array-data, http://yt-project.org/doc/examining/loading_data.html#semi-structured-grid-data , http://yt-project.org/doc/visualizing/unstructured_mesh_rendering.html

wich all suggest that yt can read tetrahedral meshes but prefers quadrilateral and only does cell centred data and not mesh point data. So I have given you all this info because I have no idea how to get on mesh data to cell centred data that yt can work with, And ultimately what I want is not have to write any .pvd , .xml, ect but use meshio to grab the fenics object and convert that object to another object that yt will read in with no excessive file writing 


[FENICS_outputs.zip](https://github.com/nschloe/meshio/files/2005111/FENICS_outputs.zip)

**Comment by nschloe** [comment]
> I need to have meshio read in a fenics object u
> [...]
> but use meshio to grab the fenics object and convert that object to another object that yt will read 

meshio is independent of FEniCS so it will never spit out a "fenics object". This is the wrong tool for the task.

> and only does cell centred data

I don't know what "cell centered data" is supposed to be.

**Comment by nschloe** [comment]
> Read the yt docs on semi structured data for what cell centered date

No, sorry.
