### ISSUE TITLE
numpy.fromstring() is deprecated

### ISSUE THREAD

**Issue by multiwave** [nschloe/meshio#252]
As the DeprecatedWarning says please switch to using `numpy.frombuffer`

**Comment by nschloe** [comment]
I only see that the `sep` argument (which isn't used in meshio) is deprecated; cf. https://docs.scipy.org/doc/numpy/reference/generated/numpy.fromstring.html. What numpy version are you using?

**Comment by nschloe** [comment]
Ah wait, is the use _without_ `sep` deprecated? Playing around with it now.

**Comment by multiwave** [comment]
I get this output 

```
/tmp/buildbot/18446/venv/lib/python3.5/site-packages/meshio/gmsh_io.py:222: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  data = numpy.fromstring(f.read(num_bytes), dtype=dtype)
```

same for line 290, we are using numpy 1.14.4 (or the most current, buildbot creates a new virtualenv every time)

**Comment by nschloe** [comment]
Alright, fixed in master. Will be part of the next release. Thanks for the report!
