### ISSUE TITLE
How should we cite meshio?

### ISSUE THREAD

**Issue by nicoguaro** [nschloe/meshio#257]
I would like to include a citation to meshio, but I am not sure what is the preferred way.

**Comment by gdmcbain** [comment]
How about [Zenodo](https://zenodo.org/record/1173116#.WyBZla1anMU)? [DOI 10.5281/zenodo.1173115](https://dx.doi.org/10.5281/zenodo.1173115).

There's a badge at [meshio/README.md](https://github.com/nschloe/meshio/blob/master/README.md).

**Comment by nicoguaro** [comment]
I saw the badge, but this is the suggested citation

> Nico Schlömer, nilswagner, Tianyi Li, Chris Coutinho, Lisandro Dalcin, Geordie McBain, … Adrian Croucher. (2018, February 14). nschloe/meshio v1.11.7 (Version v1.11.7). Zenodo. http://doi.org/10.5281/zenodo.1173116

I don't mind the form of the citation, but old-school scholars might. That's why I was asking.

**Comment by nschloe** [comment]
If you want to clean this up, you could perhaps use something along the lines of

> Nico Schlömer et al. meshio v1.11.7. Zenodo. http://doi.org/10.5281/zenodo.1173116

You can be creative as long as you keep the DOI in there; this will allow other researchers get to back to exactly what you were doing.
