### ISSUE TITLE
Add lxml as dependency

### ISSUE THREAD

**Issue by garth-wells** [nschloe/meshio#264]
At least for converting to XDMF, meshio requires the `lxml` module.

**Comment by nschloe** [comment]
It's an optional dependency. Install with `pip3 install meshio[xml]` or
```
pip3 install meshio[all]
```

**Comment by jamadagni** [comment]
Hello. It is not clear that the LXML dependency is optional. I didn't install meshio alone but installed colorio from pip, and colorio 0.2.4 pulled in meshio 2.3.7 as dependency, and running the basic example given in the colorio readme to show the SRGB gamut of CIELAB raises the missing dependency error:

    In [1]: import colorio

    In [2]: colorio.show_srgb_gamut(colorio.CIELAB(), 'cielab.vtu')
    ---------------------------------------------------------------------------
    ModuleNotFoundError                       Traceback (most recent call last)
    <ipython-input-2-118ab8df25d3> in <module>
    ----> 1 colorio.show_srgb_gamut(colorio.CIELAB(), 'cielab.vtu')

    /usr/local/lib/python3.6/dist-packages/colorio/tools.py in show_srgb_gamut(colorspace, filename, n, cut_000)
        83     pts = colorspace.from_xyz100(srgb_linear.to_xyz100(points.T)).T
        84     rgb = srgb_linear.to_srgb1(points)
    ---> 85     meshio.write_points_cells(filename, pts, {"tetra": cells}, point_data={"srgb": rgb})
        86     return
        87 

    /usr/local/lib/python3.6/dist-packages/meshio/helpers.py in write_points_cells(filename, points, cells, point_data, cell_data, field_data, file_format, **kwargs)
        188         points, cells, point_data=point_data, cell_data=cell_data, field_data=field_data
        189     )
    --> 190     return write(filename, mesh, file_format=file_format, **kwargs)
        191 
        192 

    /usr/local/lib/python3.6/dist-packages/meshio/helpers.py in write(filename, mesh, file_format, **kwargs)
        225 
        226     # Write
    --> 227     return interface.write(filename, mesh, *args, **_kwargs)
        228 
        229 

    /usr/local/lib/python3.6/dist-packages/meshio/vtu_io.py in write(filename, mesh, write_binary, pretty_xml)
        352 
        353 def write(filename, mesh, write_binary=True, pretty_xml=True):
    --> 354     from lxml import etree as ET
        355 
        356     if not write_binary:

    ModuleNotFoundError: No module named 'lxml'

**Comment by nschloe** [comment]
This needs fixing in colorio.

**Comment by nschloe** [comment]
I've rewritten the colorio README to use VTK. If you want to use other formats, you'll have to install the supporting libraries yourself (or `meshio[all]`).
