### ISSUE TITLE
meshio-convert problem from .msh to .xdmf

### ISSUE THREAD

**Issue by teeratornk** [nschloe/meshio#271]
I try to convert from .msh to .xdmf. This [happens.](url)

```
Number of points: 290
Number of elements:
  line: 60
  triangle: 518
Cell data: gmsh:physical, gmsh:geometrical
/home/teekad/.local/lib/python2.7/site-packages/h5py/__init__.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. 

Expected 96, got 88
  from ._conv import register_converters as _register_converters
/home/teekad/.local/lib/python2.7/site-packages/h5py/__init__.py:45: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z
/home/teekad/.local/lib/python2.7/site-packages/h5py/_hl/group.py:22: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .. import h5g, h5i, h5o, h5r, h5t, h5l, h5p
```
I attached the mesh file to this discussion.

[test2_0fr_rev00.txt](https://github.com/nschloe/meshio/files/2238669/test2_0fr_rev00.txt)

**Comment by nschloe** [comment]
You attached a geometry file, not a mesh. Oversight?

**Comment by teeratornk** [comment]
Hello,

Thank you for a kind reply. Please find the .msh file in an attached file.

Thank you, again, for your help.

Teeratorn


[test2_0fr_3z_rev00.zip](https://github.com/nschloe/meshio/files/2238684/test2_0fr_3z_rev00.zip)

**Comment by nschloe** [comment]
Running
```
meshio-convert test2_0fr_3z_rev00.msh out.xdmf
```
gives no problem for me:
```
Number of points: 2462
Number of elements:
  line: 210
  triangle: 4742
Cell data: gmsh:physical, gmsh:geometrical
```

**Comment by teeratornk** [comment]
I still have this issue:

>  Number of points: 2462
> Number of elements:
>   line: 210
>   triangle: 4742
> Cell data: gmsh:physical, gmsh:geometrical
> /home/teekad/.local/lib/python2.7/site-packages/h5py/__init__.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
>   from ._conv import register_converters as _register_converters
> /home/teekad/.local/lib/python2.7/site-packages/h5py/__init__.py:45: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
>   from . import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z
> /home/teekad/.local/lib/python2.7/site-packages/h5py/_hl/group.py:22: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
>   from .. import h5g, h5i, h5o, h5r, h5t, h5l, h5p

Do you have any recommendations on how to fix it?

Thank you!

**Comment by nschloe** [comment]
> Do you have any recommendations on how to fix it?

Perhaps update your packages: meshio and h5py in this case. Also, you should probably use Python 3. (Python 2 will go out of maintenance soon.)

**Comment by teeratornk** [comment]
Dear nschloe,

I installed both of them this morning.

I am quite new to Linux; hence, could you please advise how could I use python 3 instead of python 2 for meshio?

Thank you very much!

Teeratorn

**Comment by nschloe** [comment]
`meshio-convert` should use Python 3 automatically. What your output of
```
$ meshio-convert -v
meshio-convert 2.0.4, Python 3.6.6 (default, Jun 27 2018, 14:44:17) [GCC
8.1.0]
```
?
One workaround:
```
python3 /path/to/meshio-convert in.msh out.xdmf
```

**Comment by teeratornk** [comment]
Hi, 

When I ran 'meshio-convert -v', I got

> meshio-convert (version 2.0.4)

When I ran 'python3 /path/to/meshio-convert in.msh out.xdmf', there is no warning anymore. 

However, there is something strange when I look the convert mesh in paraview as attached below:

[input-output.zip](https://github.com/nschloe/meshio/files/2238793/input-output.zip)

There are holes in the mesh comparing to .msh file.

Thank you for your help!

Teeratorn

**Comment by nschloe** [comment]
> When I ran 'meshio-convert -v', I got
> ```
> meshio-convert (version 2.0.4)
> ```

That's it, no Python version?! Something seems broken...

> There are holes in the mesh comparing to .msh file.

Indeed, this does not happen on my machine. Not sure what to do about this.

**Comment by nschloe** [comment]
> Please let me know if you know how to fix these problems,

It's virtually impossible to me to fix anything if I cannot reproduce the bug. Best ask someone in your office who knows her way around Linux.

**Comment by teeratornk** [comment]
Ok! I will try to find the solution and let you know if I have more questions :) Thank you for your help!

**Comment by teeratornk** [comment]
Hello I am trying to use meshio in our cluster. However, I still have a problem shown below 

>   File "/zhome/59/f/124095/packs/python/bin/meshio-convert", line 7, in <module>
>     from meshio.cli import main
>   File "/zhome/59/f/124095/packs/python/lib/python3.6/site-packages/meshio/__init__.py", line 30, in <module>
>     print(pipdate.check(__name__, __version__), end="")
> UnicodeEncodeError: 'latin-1' codec can't encode characters in position 5-48: ordinal not in range(256)

Do you have any recommendations?

**Comment by nschloe** [comment]
Looks like a locale problem on the cluster. Best use UTF8 everywhere.
