### ISSUE TITLE
is version 2.1.0 not for Python 2?  Python 3 only?  Please change upgrade prompt to warn user.

### ISSUE THREAD

**Issue by cashTangoTangoCash** [nschloe/meshio#275]
I followed the prompt to upgrade to meshio 2.1.0 and got syntax errors in abaqus_io.py at lines 155 and 180:

`    gid, *x = line.strip().split(",")
         ^
SyntaxError: invalid syntax`

`    _, *idx = [int(k) for k in filter(None, line.split(","))]
       ^
SyntaxError: invalid syntax`

I am forced to use Python 2.7 because of other packages I need.  The above meshio code might be Python3 code?  In your upgrade prompt:
```
╭─────────────────────────────────────────╮
│                                         │
│    Update available 2.0.4 → 2.1.0     │
│   Run pip install -U meshio to update   │
│                                         │
╰─────────────────────────────────────────╯
```
please modify this prompt to warn a user that they must be using Python3, if it is indeed the case that the code is Python3 only.  Thank you.

**Comment by nschloe** [comment]
Thanks for the report!

I've now removed the Python 2 tag (#276), indicating that it's not supported anymore. I'm still open to pull requests with Python 2 fixes though.

> I am forced to use Python 2.7 because of other packages I need.

That can become a significant problem for you sooner than you might think. Firstly, Python 2 will go out of support by the end of next year. Also, software that _still_ doesn't support Python 2 is generally of low quality in my experience. If I were you, I'd be looking to replace those dependencies by something else.
