### ISSUE TITLE
Python 2 compatibility

### ISSUE THREAD

**Issue by dalcinl** [nschloe/meshio#277]
@nschloe Did you officially decide to drop Python 2 compatibility? If not, please apply the following trivial patch (or equivalent fix, the second fix maybe could just use `[1:]` after the split method call).

```diff
diff --git a/meshio/abaqus_io.py b/meshio/abaqus_io.py
index ed9c9bb..93050b7 100644
--- a/meshio/abaqus_io.py
+++ b/meshio/abaqus_io.py
@@ -152,7 +152,8 @@ def _read_nodes(f):
         line = f.readline()
         if line.startswith("*"):
             break
-        gid, *x = line.strip().split(",")
+        entries = line.strip().split(",")
+        gid, x = entries[0], entries[1:]
         point_gids.append(int(gid))
         points.append([float(xx) for xx in x])
 
@@ -176,7 +177,8 @@ def _read_cells(f, line0):
         line = f.readline()
         if line.startswith("*"):
             break
-        _, *idx = [int(k) for k in filter(None, line.split(","))]
+        entries = [int(k) for k in filter(None, line.split(","))]
+        idx = entries[1:]
         cells.append(idx)
 
     f.seek(last_pos)
```

**Comment by nschloe** [comment]
> Did you officially decide to drop Python 2 compatibility?

[Yup](https://github.com/nschloe/meshio/pull/276), but I don't mind PRs. Will apply the above patch manually.

**Comment by nschloe** [comment]
Fixed #277.

Note that Python 2 is untested, so if there's anything else going wrong in the future, you'll probably be one of the first to notice.

**Comment by dalcinl** [comment]
@nschloe Sorry, but I'm a bit lost. Didi you drop support in the sense that you no longer test on Python 2? What if someone submit a PR with substancial changes that completely destroy Python 2 support? Will you accept such PR? I don't want to be pedantic, but you have to be explicit about this. You either enforce Python 2 compatibility (and then somehow test for it), or you say I no longer care about Python 2, so users can decide whether to depend or not in your library if they still care about Python 2.

**Comment by nschloe** [comment]
> but you have to be explicit about this. [...]
> or you say I no longer care about Python 2

I did just that, see #276. To Python 2 compatibility might break again; in fact it hasn't been tested in a long while. However, if somebody comes along with a PR that changes nothing except enables better Python 2 compatibility, I'll accept it.

**Comment by nschloe** [comment]
> but other may very well argue that not supporting both is not a good sign either,

I was actually inspired by FEniCS, undoubtedly a high-quality software project, dropping Python 2 support this year (https://fenics.readthedocs.io/projects/dolfin/en/latest/ChangeLog.html). I guess they didn't want to invest the time – a good motivation for me too. :)
