### ISSUE TITLE
medit does not properly write physical groups / labels

### ISSUE THREAD

**Issue by izaid** [nschloe/meshio#279]
Hello,

This is a great library, I'm very much enjoying it. I just have a comment about the medit (.mesh) reader / writer.

It seems that even if my mesh has physical groups, the medit mesh will always be written with label=1. See https://github.com/nschloe/meshio/blob/master/meshio/medit_io.py#L148 for instance.

Here is an example of generating a mesh from pygmsh with two physical groups. I'd expect to get two labels in the .mesh file, but instead I only get one:

```python
import pygmsh as pg

geom = pg.built_in.Geometry()
scatterer = geom.add_ball((0, 0, 0), 1)
box = geom.add_box(-10, 10, -10, 10, -10, 10, holes = [scatterer.surface_loop])

geom.add_physical_volume([scatterer.volume])
geom.add_physical_volume([box.volume])

points, cells, point_data, cell_data, field_data = pg.generate_mesh(geom)

import meshio

mesh = meshio.Mesh(points, cells, point_data = point_data, cell_data=cell_data, field_data = field_data)
meshio.write('test.mesh', mesh)
```

**Comment by gdmcbain** [comment]
I've just noticed this while working on MEDIT mesh for #291, #292, and nschloe/pygmsh#212.  I'm now adding the reading of the point and cell data from that format, I'll try and follow up with writing too.

**Comment by gdmcbain** [comment]
The above example may be simplified from the real application, but if not one would probably not `generate_mesh` but rather write the GEO file from `geom.get_code()` and let Gmsh generate the MEDIT mesh file itself (`-format mesh -string "Mesh.SaveElementTagType=2;").

**Comment by gdmcbain** [comment]
I believe that this is fixed by #297 though I can't rerun the example in the original post as `pygmsh.generate_mesh` is broken for Gmsh 4 nschloe/pygmsh#209 pending reading & writing of MSH4 #280.  I think it should work with Gmsh &leqslant; 3.

**Comment by nschloe** [comment]
Let's tentatively close this; feel free to reopen if the merged fix doesn't work for you.

**Comment by augustjohansson** [comment]
Hi! Thank you very much for your great work on meshio. I have an issue that's, what I think, identical to the original submission of user izaid: Physical labels doesn't seem to be written to the medit mesh file. I've tried using both gmsh 3.0.6 and 4.4.1 but I get identical output. Please let me know if you need more info!

Here's a small example where the unit square is split into two triangles with two different labels:
```
import pygmsh
import meshio

geom = pygmsh.built_in.Geometry()
lcar = 1.0
x = [[0.0, 0.0, 0.0],
     [1.0, 0.0, 0.0],
     [1.0, 1.0, 0.0],
     [0.0, 1.0, 0.0]]
p = [geom.add_point(x_i, lcar) for x_i in x]

# Lower left
label_0 = 2
a = geom.add_line(p[0], p[1])
b = geom.add_line(p[1], p[3])
c = geom.add_line(p[3], p[0])
loop_0 = geom.add_line_loop([a, b, c])
s_0 = geom.add_plane_surface(loop_0)
ps_0 = geom.add_physical(s_0, label=label_0)

# Upper right
label_1 = 3
d = geom.add_line(p[1], p[2])
e = geom.add_line(p[2], p[3])
loop_1 = geom.add_line_loop([d, e, -b])
s_1 = geom.add_plane_surface(loop_1)
ps_1 = geom.add_physical(s_1, label=label_1)

mesh = pygmsh.generate_mesh(geom, prune_z_0=True, geo_filename="hoho.geo")
meshio.write("hoho.mesh", mesh)
```
