### ISSUE TITLE
binary MSH4 decoding

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/meshio#284]
#283 fixes the minimal failing example of ASCII MSH4 given for #280 and generated by
```shell
gmsh -2 t1.geo
```
with [t1.geo](https://gitlab.onelab.info/gmsh/gmsh/blob/master/tutorial/t1.geo) being the first Gmsh tutorial, but the binary MSH4 format raises a different error.
```shell
gmsh -2 -bin t1.geo
```
Attached gzipped as [t1.msh.gz](https://github.com/nschloe/meshio/files/2325929/t1.msh.gz).  Then
```shell
python -c 'import meshio; meshio.read("t1.msh")'
```
raises
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/users/geordie/.py3.7/meshio/src/meshio/meshio/helpers.py", line 171, in read
    return format_to_reader[file_format].read(filename)
  File "/usr/local/users/geordie/.py3.7/meshio/src/meshio/meshio/msh_io/main.py", line 11, in read
    mesh = read_buffer(f)
  File "/usr/local/users/geordie/.py3.7/meshio/src/meshio/meshio/msh_io/main.py", line 30, in read_buffer
    return reader.read_buffer(f, is_ascii, int_size, data_size)
  File "/usr/local/users/geordie/.py3.7/meshio/src/meshio/meshio/msh_io/msh4.py", line 66, in read_buffer
    line = f.readline().decode("utf-8").strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9a in position 100: invalid start byte
```

Maybe it doesn't make sense to decode binary files?

**Comment by gdmcbain** [comment]
The first two blocks (MeshFormat, PhysicalNames) of the binary file are parsed correctly.

The third, `Entities`, is ignored as if a `Comment`.  (Does it contain anything useful?  A separate question.)  But the contents of this block are binary and in skipping through the content to find the end of the block is where the `.decode("utf-8")` raises the `UnicodeDecodeError`.

**Comment by gdmcbain** [comment]
Maybe it's safe enough to pass the UnicodeDecodeError inside a section like `Entities` which is being ignored?  152e54e

With that in place in branch msh4-binary, another UnicodeDecodeError is raised later by `_read_nodes`.

**Comment by nschloe** [comment]
> Does it contain anything useful? A separate question.

I asked myself the same question. We'll find out in the future.

**Comment by nschloe** [comment]
Done now (#287).
