### ISSUE TITLE
binary MEDIT mesh

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/meshio#295]
Thus far, `meshio.medit_io` only reads and writes text MEDIT mesh whereas according to Frey ([2001](https://hal.inria.fr/inria-00069921), §7.2.1):
> This format is composed of a single (binary or text) data file.

This would be of much more interest in the context of nschloe/pygmsh#212 if Gmsh wrote binary MEDIT mesh but it appears to ignore its `-bin` flag for `-format mesh`.  I'm not sure how common the binary form is in the wild.

**Comment by nschloe** [comment]
Fixed via #782.
