### ISSUE TITLE
read nodal and elemental tags from MEDIT mesh

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/meshio#296]
The MEDIT mesh format has exactly one `int` tag for each of its "Vertices" and for each of its elements ("Edges", "Triangles", &c.).  These aren't currently read by `meshio.medit_io.read`.   

The elemental tags in particular are written by Gmsh (`-format mesh`) and reflect its "physical" tags with [option](http://gmsh.info/doc/texinfo/gmsh.html#index-Mesh_002eSaveElementTagType) 
```C++
Mesh.SaveElementTagType=2
```

This then would answer the question about tagged subsets of elements #290 of @nschloe in #289 about further work on decoding MSH4 #280:
> Before this can go anywhere, we have to make a decision on how to use the tag groups in MSH4. I'm not sure about that yet. We used to simply create integer node/element data, but really that's quite ineffective. Perhaps we can do something that is common to MSH4 and Exodus which also has node/element sets. (And another mesh format, perhaps Medit?)

If `meshio.read` read the elemental tags, it would make MEDIT mesh a competitive format for `pygmsh.generate_mesh` nschloe/pygmsh#212, particularly as, there being exactly one `int` tag, it should be possible to read all the elements of each type at once rather than line by line.

A start was made on this in bbc886c in #292 but the latter turns out to have enough complexity of its own so it was reverted.

**Comment by gdmcbain** [comment]
A comment from #292:

> What on Earth does one call the keys in `point_data`, `cell_data['line']`, `cell_data['triangle']`, &c.? I guess this gets back to #175 and #290.

> Here I've tried to mimic current (or rather recent, pre #280) behaviour of `meshio` and used `"gmsh:physical"` for `cell_data` despite its absurdity here and then `"medit:ref"` for `point_data`. I was never entirely comfortable with `"gmsh:physical"` but #175 had gone on long enough by the time it was closed with #199; hopefully something will come out of #290.

**Comment by nschloe** [comment]
> A start was made on this in bbc886c in #292 but the latter turns out to have enough complexity of its own so it was reverted.

So will you open another PR for this?

**Comment by gdmcbain** [comment]
I think that this is fixed by #297.

**Comment by nschloe** [comment]
Alright, let's close it then.
