### ISSUE TITLE
problems setting cell_data in write_points_cells

### ISSUE THREAD

**Issue by matkbrun** [nschloe/meshio#306]
Im using python for some numerical computations, and I have a triangular mesh and a solution vector which is constant on each triangle in the mesh (one value for each triangle). Im trying to use the meshio function write_point_cells, in order to obtain a .vtk file for a plot. However I am not able to set the cell_data keyword. The cell data I have is simply an array with the value of the function at each triangle in the mesh. It seems that I should give a dictionary, but a dictionary of what?
Hope someone can point me in the right direction.
Thanks,

**Comment by nschloe** [comment]
`point_` and `cell_data` have names, so each would be a dictionary like `{"temperature": [...], "density": [...]}` etc. Cell data is a bit special since you'll have to segregate by cell type as well, e.g.,
```python
cell_data = {
    "temperature": {
        "triangle": [...],
        "quad": [...],
    }
}
```
The cell types must be the cell types from your `cells` array iirc.

**Comment by matkbrun** [comment]
That did the trick! Follow up: if I have several time steps how do I write these as a sequence?
Thanks

**Comment by nschloe** [comment]
Not possible with most mesh types. Just write a new mesh file.

**Comment by nschloe** [comment]
Out of interest, what mesh format are you using?
