### ISSUE TITLE
read/write polygons

### ISSUE THREAD

**Issue by eolianoe** [nschloe/meshio#322]
Is there a way to read/write meshes with polygons?
For instance, [this file](https://github.com/nschloe/meshio/files/2740508/mesh.txt) is a dodecahedron with pentagonal faces. It seems that this kind of mesh can be saved only in a VTK file using VTK_POLYGON but the support of polygons is disabled in meshio.

**Comment by nschloe** [comment]
For now, meshio is only for unstructured meshes. I think there's no other format that supports polygons like the legacy VTK does. Anyways, if you want to add support for reading, I'm open to pull requests.

**Comment by eolianoe** [comment]
Thanks for the answer. I'll look into the magic of the `translate_cells` methods but my python is quite new so maybe it will be easier to write something independant to read such files.

**Comment by nschloe** [comment]
IF you do, feel free to  close the issue request.

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to reopen at any time.
