### ISSUE TITLE
write vectors in XDMF

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/meshio#327]
Currently all point_data and cell_data are given `Attribute Type="None"`

 https://github.com/nschloe/meshio/blob/fc601345c4e763745d0d30ddf896363ab1b2f204/meshio/xdmf_io/main.py#L406

however, according to the [XDMF Model and Format](http://xdmf.org/index.php/XDMF_Model_and_Format) and the [Xdmf.dtd](https://gitlab.kitware.com/xdmf/xdmf/blob/master/Xdmf.dtd#L62), the tag `<Attribute>` has no attribute `Type`.  It does have `AttributeType` but `"None"` is not a valid value, instead it can be 
* Scalar (default)
* Vector
* Tensor
* Tensor6
* Matrix

FEniCS (recent Docker image on GNU/Linux PureOS 8) writes vector-fields to XDMF like
```xml
      <Attribute Name="f_456" AttributeType="Vector" Center="Node">
        <DataItem Dimensions="32729 3" Format="HDF">field.h5:/VisualisationVector/0</DataItem>
      </Attribute>
```

This is from running https://github.com/hplgit/fenics-tutorial/blob/master/pub/python/vol1/ft11_magnetostatics.py, but using `XDMFFile` instead of `File` (which uses VTK).

Passing the resulting `field.xdmf` though
```shell
meshio-convert field.xdmf meshiofield.xdmf
```
turns this into
```xml
      <Attribute Center="Node" Name="f_456" Type="None">
        <DataItem DataType="Float" Dimensions="32729 3" Format="HDF" Precision="8">meshiofield.h5:/data2</DataItem>
      </Attribute>
```

The former is rendered vectorially by ParaView, the latter isn't.

For a minimal example of meshio.write not writing a vector to XDMF as a vector, I have modified the vector2d.py from #325.
```python
mesh = add_cell_data(add_point_data(tri_mesh_2d, 2), 2)
meshio.write('mesh.xdmf', mesh)
```
[vector2d.py.txt](https://github.com/nschloe/meshio/files/2854045/vector2d.py.txt)

**Comment by gdmcbain** [comment]
The motivation here is kinnala/scikit-fem#123.

**Comment by nschloe** [comment]
Could you attach a file that's working with ParaView so I can play around with it a bit?

**Comment by gdmcbain** [comment]
Sure.  I generated a little one with this [vector.py](https://github.com/nschloe/meshio/files/2892367/vector.py.gz):
```python
mesh = UnitSquareMesh(1, 1)
V = VectorFunctionSpace(mesh, 'P', 1)
r = Function(V)
r.assign(interpolate(Expression(('x[0]', 'x[1]'), degree=1), V))

xdmf = XDMFFile('r.xdmf')
xdmf.write(r)
```

Here's the result of `tar czf r.{tar.gz,xdmf,h5}`: [r.tar.gz](https://github.com/nschloe/meshio/files/2892366/r.tar.gz).

In ParaView, it renders as:

![r](https://user-images.githubusercontent.com/1588947/53220329-107caf80-36b8-11e9-99af-e0e0b11c956f.png)

But then after
```shell
meshio-convert r.xdmf rm.xdmf
```
ParaView doesn't see it as a vector any more.

![rm](https://user-images.githubusercontent.com/1588947/53220524-12933e00-36b9-11e9-8172-8bc8d65652ca.png)

* [rm.tar.gz](https://github.com/nschloe/meshio/files/2892394/rm.tar.gz)

**Comment by nschloe** [comment]
How exactly do you generate the pictures in ParaView? With the glyph filter?

**Comment by gdmcbain** [comment]
Sorry, I wish that I knew how to script ParaView, but I don't.  I'll redo the procedure and take notes.

**Comment by gdmcbain** [comment]
Yes, Glyph is involved.

**Comment by gdmcbain** [comment]
1. `tar xzf r.tar.gz; paraview r.xdmf`
2. Click _Apply_.
3. Click _Glyph_.
4. Click _Apply_.
5. Change _Solid Color_ to _Glyph Vector_.
6. _File/Save Screenshot…_
7. Click _OK_
8. Enter filename `r.png`, click _OK_.
![r](https://user-images.githubusercontent.com/1588947/53703666-b1156100-3e68-11e9-9ff1-5bbeda0a7077.png)
