### ISSUE TITLE
Read in Vtk

### ISSUE THREAD

**Issue by iagyonwu** [nschloe/meshio#328]
Hello I am using meshio to read a large vtu or vtk file.    My vtu file contains multiple Piece, reading it with paraview is successful. But when reading with meshio, the following error comes:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/iagyongx/.local/lib/python3.6/site-packages/meshio/helpers.py", line 174, in read
    return format_to_reader[file_format].read(filename)
  File "/home/iagyongx/.local/lib/python3.6/site-packages/meshio/vtu_io.py", line 274, in read
    reader = VtuReader(filename)
  File "/home/iagyongx/.local/lib/python3.6/site-packages/meshio/vtu_io.py", line 147, in __init__
    assert piece is None, "More than one Piece found."
AssertionError: More than one Piece found.
```
Then I converted the vtu data into vtk, i.e export it from paraview as vtk. The following error comes:
```
 File "<stdin>", line 1, in <module>
  File "/home/iagyongx/.local/lib/python3.6/site-packages/meshio/helpers.py", line 174, in read
    return format_to_reader[file_format].read(filename)
  File "/home/iagyongx/.local/lib/python3.6/site-packages/meshio/vtk_io.py", line 113, in read
    out = read_buffer(f)
  File "/home/iagyongx/.local/lib/python3.6/site-packages/meshio/vtk_io.py", line 226, in read_buffer
    assert section == "FIELD", "Unknown section '{}'.".format(section)
AssertionError: Unknown section 'METADATA'.
```
Can you give me any hint, how should I proceed?  

Here attached is an example vtk file:
https://drive.google.com/file/d/1RhfqMS6FKOyazuhuwbL3Rkt19ZX0vATf/view

**Comment by gdmcbain** [comment]
The offending example linked to is quite large.

> All.vtk (5,8G) dépasse la taille maximale que Google peut analyser. Voulez-vous vraiment télécharger ce fichier ?

Any chance of coming up with a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve)?

**Comment by nschloe** [comment]
+1 to what Geordie says. I cannot even open the example file.

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to reopen if you have more info though!

**Comment by iagyonwu** [comment]
Hi nschloe,
sorry that I can't upload a smaller data earlier. Since it is a coorperation with another collegue, i need to ask him for providing the data. Here attached is it.   

[https://drive.google.com/open?id=133--qFPVVHTre0kDno9guCC3zklMlNtN](url)

**Comment by nschloe** [comment]
Fixed by #334.

**Comment by MuellerSeb** [comment]
Another problem here, is the mentioned METADATA that ParaView writes into a file, which is officially allowed in a VTK file:
https://vtk.org/doc/nightly/html/IOLegacyInformationFormat.html

These METADATA Blocks could be anywhere and they violate the meshio routines.

**Comment by MuellerSeb** [comment]
I will have a look at this.
