### ISSUE TITLE
Instalation and testing issues

### ISSUE THREAD

**Issue by Fvergnet** [nschloe/meshio#329]
Hello, I installed meshio with pip and tried to test the installation with the pytest command in the test repository, but somethign went wrong. Attached is the a text file containing the errors.

Do you have any idea what the problem is ?

Regards,
Fabien

[error_meshio.txt](https://github.com/nschloe/meshio/files/2860084/error_meshio.txt)

**Comment by nschloe** [comment]
```
E   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
No idea. Perhaps and error in  your json libs?

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to reopen if you have more info though!
