### ISSUE TITLE
a test suite for readers

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/meshio#335]
Following discussion of testing in #331 where there's a reasonable implementation of `read` for MSH 4.1 #330 but as yet no `write` #332 , the problem being that currently testing involves basically checking that `read` is the left inverse of `write` which is impossible without the latter.  The need for that approach is that it avoids non-Python dependencies (Gmsh, VTK, let alone proprietary products) and their various versions.

What about including in the test suite some authoritatively generated meshes?  Then one could test that the `Mesh` returned by `read` satisfied some basic properties (number of elements with a given tag, bounding box of points, …).

Besides enabling testing of readers lacking writers, this would seem to me to be a better test of a reader since it's reading a real native mesh of the given format.

**Comment by nschloe** [comment]
Why not, I guess. The (possibly large) reference files shouldn't be in master though but in some other location, e.g., an orphaned branch. and then downloaded at test time via something like https://github.com/nschloe/meshplex/blob/master/test/helpers.py.

**Comment by nschloe** [comment]
The more I think about, the more I like the idea. Thanks @gdmcbain for another great suggestion! I'll probably get going with this _today_.

**Comment by nschloe** [comment]
Okay so, https://github.com/nschloe/meshio/pull/338 mostly fixes this. It's only one VTK mesh now, but the functionality is there and now it's just a matter of adding more meshes to the gh-pages branch and filling in the respective tests.

**Comment by gdmcbain** [comment]
Some discussion under #365 led to [a statement of the rationale for keeping the exemplars in a separate branch](https://github.com/nschloe/meshio/pull/365#issuecomment-476164858), linked to here for future reference.
