### ISSUE TITLE
test conversion

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/meshio#348]
Current tests cover reading and that reading retracts writing within the same format, but I don't think there's any coverage of conversion.

In #347, @RemiTheWarrior posted a MED file generated by SALOME that is not currently read completely by meshio; a tagged subset of elements #290 is ignored. This would probably pass a test that read .  write .  read is the same as read, but @RemiTheWarrior also posted the MSH converted from the MED by Gmsh and some XML converted from that by dolfin-convert. Assuming Gmsh and dolfin are doing the right things, reproducing these could be an excellent test of one of the primary functions of meshio.

**Comment by tianyikillua** [comment]
We can hence separate these unit-tests into two *complementary* groups:

1. Non-regression tests verifying, as you put it, `read ⚬ write = identity map`
2. Validation/production tests using externally generated files.

**Comment by tianyikillua** [comment]
As for MED, there is an abundance of unit tests in the `tests` folder of the MEDFile library available on the [salome website](http://files.salome-platform.org/Salome/other/med-4.0.0.tar.gz).

Maybe these files can be used for `med` module production tests.

<img width="1001" src="https://user-images.githubusercontent.com/4027283/54561278-8d9ff980-49c4-11e9-9c56-961ecdbf5c41.png">

**Comment by nschloe** [comment]
@tianyikillua We actually added this kind of tests about two weeks ago. The reference meshes are deposited in https://github.com/nschloe/meshio/tree/gh-pages, then as part of the tests downloaded from there and checked https://github.com/nschloe/meshio/blob/master/test/test_vtk.py#L55.

**Comment by gdmcbain** [comment]
That test reads, rewrites, and rereads VTK; I don't think conversion between formats is tested yet. This is nontrivial for e.g. tagged subsets of elements #290, which are handled differently in various formats, but which is required by users like the one in #347 who wants to generate a mesh and define boundaries in Salome which outputs MED and ultimately feed it to FEniCS. The requested path was MSH and `dolfin-convert` (which I presume means MSH2.2) but I imagine others wishing to convert MED or MSH4.1 to XDMF for the same reason so it would be good to test those paths too.

**Comment by nschloe** [comment]
> Assuming Gmsh and dolfin are doing the right things, reproducing these could be an excellent test of one of the primary functions of meshio.

Guys, I'm not sure if we're not overtesting here. If we have read and write correct for all methods, then conversion will be correct as well, right? Or can you imagine a scenario where the create->write->read tests pass and a conversion test of some sort fails?

> Assuming Gmsh and dolfin are doing the right things,

That's already quite the assumption. :smile: Frankly, I think we're doing a better job with meshio than those two (thanks to the fact that meshio is a one-trick pony and we don't need to concern ourselves with other matters).

**Comment by gdmcbain** [comment]
> a scenario where the create->write->read tests pass and a conversion test of some sort fails?

I'm thinking tagged subsets of elements #290. If `msh_io.read`, e.g., stores them  somwhere format-specific like `cell _data[cell_type]["gmsh:physical"]`, is any non-MSH writer going to interpret it appropriately?  Specifically I'm thinking of a case like #347 where a user externally generates a mesh with tagged subdomains and boundaries and wants meshio to convert that into a format readable by their finite element code.

**Comment by gdmcbain** [comment]
This recent code-comment appears to flag such a scenario:

https://github.com/nschloe/meshio/blob/fa21c2d9a9b252e244411569999f2de11e9fe072/meshio/med_io.py#L246

**Comment by gdmcbain** [comment]
Besides this string `"cell_tags"`, the `meshio.med_io` module appears to have introduced a new attribute of the same name for the `meshio.Mesh` class:

https://github.com/nschloe/meshio/blob/fa21c2d9a9b252e244411569999f2de11e9fe072/meshio/med_io.py#L101

https://github.com/nschloe/meshio/blob/fa21c2d9a9b252e244411569999f2de11e9fe072/meshio/med_io.py#L269-L271

I don't think that any of other modules in `meshio` know about this attribute, so those tags aren't going to be converted to or from MED, e.g. from MED to MSH #347.

**Comment by tianyikillua** [comment]
That's right. But don't forget that the `Mesh` class is introduced so that we can put format-specific objects in it...there are surely things that only contain in one format but not in others, and it may be useful to be able to read them.

Back to this `point/cell_tags` (point/cell data) or `gmsh:physical` things, indeed we need to adopt a neural standard (a name already), so that it can be transferred from one to another.

**Comment by gdmcbain** [comment]
Yeah. I liked your suggestion "tags", but that's more for #290. I'll close this for now.
