### ISSUE TITLE
Issue with reading .msh file in meshio version 2.3.6

### ISSUE THREAD

**Issue by athulshaji** [nschloe/meshio#358]
I am not able to read in the file "cube.msh" while using the meshio version 2.3.6. The mesh is attached here as a zip file. This worked fine in meshio versions 2.3.5 and 2.3.4
[cube.zip](https://github.com/nschloe/meshio/files/2994956/cube.zip)

**Comment by gdmcbain** [comment]
Do you know what version of Gmsh generated this?

The current stable documentation for [MSH file format] says:

> The MSH file format version 4 (current revision: version 4.1)

so this file is from the short unhappy period between the introduction of MSH4 and the clearing up of its teething troubles in MSH4.1.

Any chance of your regenerating it with current stable Gmsh? (Gmsh 4.2.2)

**Comment by gdmcbain** [comment]
Wow, even Gmsh (4.2.3-git-7bc72f5de) can't read this mesh.

> Info    : Reading 'cube.msh'...
> Error   : Can only read MSH 4.0 format in ASCII mode
> Error   : Error loading 'cube.msh'
> Info    : Done reading 'cube.msh'

**Comment by gdmcbain** [comment]
I have an old meshio 2.3.5 lying around and it does not read this file either:
> OverflowError: Python int too large to convert to C ssize_t

**Comment by gdmcbain** [comment]
Ditto for meshio 2.3.3.

**Comment by athulshaji** [comment]
Hello,

I am currently using meshio 2.3.5 and I am able to read in the file. Screenshot of my desktop is given below. I am using Windows 10, Python 3.7.2.
am also not able to read in the .msh using GMSH 4.2.2.  Can you help with the command for converting the mesh from one format to the other? The command given in the readme file is not working.

![image](https://user-images.githubusercontent.com/40489289/54802160-1bfbd000-4c90-11e9-9105-1ec37e9edf20.png)

**Comment by gdmcbain** [comment]
> Can you help with the command for converting the mesh from one format to the other?

Yes, normally it's [`gmsh -convert cube.msh`](http://gmsh.info/doc/texinfo/gmsh.html#index-_002dconvert-files), but that's not working with Gmsh 4.2.2 or 4.2.3-git-7bc72f5de and this cube.msh.  

Or do you mean the `meshio-convert` command-line utility?  I don't think that'll work; it's going to rely on `meshio.read` internally.

**Comment by athulshaji** [comment]
Hello, I was pointing to the command meshio-convert.

**Comment by gdmcbain** [comment]
Yeah,
```shell
meshio-convert cube.{msh,vtk}
```
again just raises
> OverflowError: Python int too large to convert to C ssize_t

**Comment by athulshaji** [comment]
I have generated a new cube.msh file using GMSH 4.2.2. It is attached below. This file could be read in only using the meshio version 2.3.6. I have updated my meshio.
[cube.zip](https://github.com/nschloe/meshio/files/2995154/cube.zip)

**Comment by gdmcbain** [comment]
Great, but yes, that's right, reading MSH4.1 does require a newish meshio.

Is that an acceptable resolution to this problem?  (I'm not overly enthusiastic about reverse-engineering the deprecated MSH4.0 format myself...)

**Comment by athulshaji** [comment]
Yes this solves the problem. 

Thank you.
