### ISSUE TITLE
writing the data at the nodes to a vtk file using meshio 2.3.6

### ISSUE THREAD

**Issue by athulshaji** [nschloe/meshio#359]
Hello,

I am using meshio 2.3.5 in a Windows 10 machine with Python 3.7.2 to read in the mesh. The FEM code I have written gives back the potential values at the nodes. I want to know how the list of nodes, patch list and the potential at each node information can be written to a .vtk file. I have tried the sample code given in the readme file.  

`points = mesh.points 
cells = {
    "triangle": mesh_patch_list_2d,
    "tetra": mesh_patch_list_3d
    }
point_data = potential_values
meshio.write_points_cells(
    "result.vtk",
    points,
    cells,
    # Optionally provide extra data on points, cells, etc.
    point_data=point_data,
    # cell_data=cell_data,
    # field_data=field_data
    )`

The error is as shown below.

![image](https://user-images.githubusercontent.com/40489289/54802866-223f7b80-4c93-11e9-8e86-ddd5ec912217.png)

**Comment by gdmcbain** [comment]
The offending line should maybe be updated to something like
```python
self.point_data = {} if point_data is None else point_data
```

Looks like Python or NumPy might have changed behaviour for the truthiness of a `numpy.ndarray`.

**Comment by athulshaji** [comment]
I have made the necessary changes to the file mesh.py. Again when I run the program I am getting the following error.

![image](https://user-images.githubusercontent.com/40489289/54803432-777c8c80-4c95-11e9-9a58-598cea261648.png)

**Comment by gdmcbain** [comment]
Ah, I was puzzled why this hadn't seemed to be broken before.  (I'm sure I already used it twenty times today.)

Instead of passing a plain array to `point_data`, one normally passes a `Dict[str, numpy.ndarray]`, e.g.
```python
point_data={'potential': potential_values}
```

**Comment by gdmcbain** [comment]
Yes, a similar improvement to that test in `meshio.vtk_io.write` might be in order too, but meanwhile try passing the dict.

**Comment by thsmit** [comment]
Hi, I am having the same problem as athulshaji, but than when writing additional cell data:

I have the same error as mentioned above. Any solutions?

        points = mesh.nodes
        cells = {'quad': mesh.elements}
        
        # addtional data
        point_data = {'Displacements': analysis.u.reshape(mesh.nodes.shape)}
        cell_data = {'Densities': x}
        
        # (filename, point coordinates of original mesh, element connectivity of mesh, additional data)
        meshio.write_points_cells(filename, points, cells, point_data, cell_data)

**Comment by nschloe** [comment]
Cell data has the format
```python
cell_data = {"quad": {"densities": x}}
```

**Comment by thsmit** [comment]
Thank you for your reply.

I am not there jet. The densities are scalars which should be attached to the 'surface' or 'area' of every Quad cell. Is this the right way to write this to vtk? I have an error now:

 if values.shape[1] == 2:

IndexError: tuple index out of range

points = mesh.nodes
        cells = {'quad': mesh.elements}
      
        # addtional data
        point_data = {'Displacements': analysis.u.reshape(mesh.nodes.shape)}
        cell_data = {'quad': {'densities': x}}
        
        # (filename, point coordinates of original mesh, element connectivity of mesh, additional data)
        meshio.write_points_cells(filename, points, cells, point_data, cell_data)

**Comment by nschloe** [comment]
Please open a new issue and provide a _minimal_ working example there.
