### ISSUE TITLE
MSH wrong version check

### ISSUE THREAD

**Issue by keurfonluu** [nschloe/meshio#368]
The last update 2.3.6 broke the reading of msh files created with Gmsh < 4.2 as it raises a *ValueError* at line 98 in *msh_io/msh4_1.py*
`ValueError: not enough values to unpack (expected 1, got 0)`

It seems that the line 7 in *msh_io/main.py*
`versions = {"2": msh2, "4.0": msh4_0, "4.1": msh4_1, "4": msh4_1}`
is not correct since the key `"4"` should be associated to the reader `msh4_0` and not `msh4_1`.

On my different Gmsh versions, msh files exported by Gmsh 4.1.5 have `4` under `$MeshFormat` while files exported by Gmsh 4.2.2 have `4.1`.

**Comment by nschloe** [comment]
Go get 2.3.7.
