### ISSUE TITLE
Segmentation fault when converting GMSH to XDMF

### ISSUE THREAD

**Issue by dajuno** [nschloe/meshio#37]
Hi, 
I just tried your tool for converting a simple [gmsh mesh](http://chunk.io/f/0610b40b2583483c94a6e4405ef1ef04) to the XDMF format (for fenics). I get a segfault. Converting to, for example, VTK works though.
Any ideas?

Can I expect the converter to handle gmsh's physical groups?

Thanks!

**Comment by nschloe** [comment]
Thanks for the report!

> Can I expect the converter to handle gmsh's physical groups?

Not yet, but I'll take a look.

**Comment by nschloe** [comment]
Fixed in 1.1.1. Let's track the physical groups in a separate issue.
