### ISSUE TITLE
interoperability with PyVista

### ISSUE THREAD

**Issue by banesullivan** [nschloe/meshio#372]
@akaszynski and I would like to build interoperability between `meshio` and [`PyVista`](https://github.com/pyvista/pyvista). I'm mainly curious about how I should go about creating a `meshio.Mesh` object from any `pyvista` object.

**Question:** what are the arguments for creating a `meshio.Mesh` object? This wasn't obvious to me after a quick dive into the source code.

```py
import meshio
from pyvista import examples

poly = examples.load_airplane()

# errors: meshio.Mesh(poly.points, poly.faces)
```

Currently, `meshio` only supports `vtkUnstructuredGrid`s... why? Shouldn't we be able to define the nodes and cell connectivity for any mesh? This might be easiest implemented in `pyvista`.

**Comment by nschloe** [comment]
> Currently, meshio only supports vtkUnstructuredGrids... why?

That's the common denominator between all of the mesh formats and by far the most flexible and most widely used type of mesh. I wouldn't mind a PR which enables structured mesh reads/writes for VTK though.

**Comment by banesullivan** [comment]
To make this easy, I think I'll just create a way to cast all `vtki` data objects to `UnstructuredGrid`s and let that be the link between `vtki` and `meshio`. This way we can use `meshio` to load all of it's supported formats and provide a way to save any `vtki` mesh in formats supported by `meshio`.

What do you think @akaszynski?

> I wouldn't mind a PR which enables structured mesh reads/writes for VTK though.

If we have a way to cast all VTK meshes to `UnstructuredGrid`s, then `vtki` could provide full VTK support in a sense.

**Comment by akaszynski** [comment]
It's not the most efficient of methods, but if VTK doesn't have a reader for the format already, it's far better than nothing.  At worst, we can recast it as a ``PolyData`` so surface functions are available.

**Comment by MuellerSeb** [comment]
> > Currently, meshio only supports vtkUnstructuredGrids... why?
> 
> That's the common denominator between all of the mesh formats and by far the most flexible and most widely used type of mesh. I wouldn't mind a PR which enables structured mesh reads/writes for VTK though.

https://github.com/nschloe/meshio/pull/399 implements a structured mesh reader for VTK files. Maybe this is a first step.

**Comment by banesullivan** [comment]
It would be great if we could pick this back up. Maybe start with a way to create a PyVista `UnstructuredGrid`/`StructuredGrid` mesh from the `meshio.Mesh` class if PyVista is installed? Perhaps as a `to_pyvista` method on the `meshio.Mesh` class?

Then it might be cool to bind a `.plot(*args, **kwargs)` method to the `meshio.Mesh` class like:

```py
def plot(*args, **kwargs):
    self.to_pyvista.plot(*args, **kwargs)
```

which would make it possible to immediately plot any `meshio` mesh in any Python environment.

**Comment by nschloe** [comment]
meshio's success is partly due to the handsomeness of its creator, partly due to the fact that it's a one-trick pony that only does one thing and does it well, name mesh file I/O. Plotting is hard and certainly warrants its own package. Rumor has that there are of bunch of those already out there:
  * ParaView
  * plain VTK
  * mayavi
  * PyVista
  * ...

meshio makes it easy to create files or data that can be fed into those viewers.

If you're interested in "interoperability" between meshio and PyVista, the more natural approach would be to have PyVistas I/O handled by meshio. There must be code for that already, so why not ditch it for meshio?

**Comment by nschloe** [comment]
This isn't actionable for meshio right now, so let's close this.
