### ISSUE TITLE
Issue with exported Ansys Fluent msh files

### ISSUE THREAD

**Issue by falgunithakor-hunterindustries** [nschloe/meshio#385]
I am trying to import/export a simple polygon mesh from/to Ansys Fluent. 

Reading an Ansys .msh file works fine, I got all points and elements in the python mesh object. But when I save the same mesh object to Ansys .msh format (Binary & ASCII) and try to import the file in Ansys, the import fails with a message (Premature End-of-file found). It is missing some elements like index 13 is converted to index 12 and has some data issues.

[Simple shape - Binary.msh.txt](https://github.com/nschloe/meshio/files/3183380/Simple.shape.-.Binary.msh.txt)
[Simple shape - ASCII.msh.txt](https://github.com/nschloe/meshio/files/3183381/Simple.shape.-.ASCII.msh.txt)

Any help is appreciated!

Thanks!!

**Comment by nschloe** [comment]
We need the original mesh and the exact procedure to reproduce the error.

**Comment by falgunithakor-hunterindustries** [comment]
Hi @nschloe,

The attached files are original mesh files, I only appended .txt to name to attach it here. please remove .txt extension from the file name. These files were exported from Ansys Fluent.

Below is the code to read and write mesh to a new file. As you can see I am not changing anything on mesh object.
`msh2 = meshio.read("Simple shape - ASCII.msh", file_format='ansys-ascii')
print('points', msh2.points.shape, msh2.points)
print('cells ', msh2.cells['quad'].shape, msh2.cells['quad'])

meshio.write("updated_Simple shape - ASCII.msh", msh2, file_format='ansys-ascii')`

When I try to import the "updated_Simple shape - ASCII.msh" file back in Ansys Fluent, it throws import failed error "Premature End-of-file found".

**Comment by gdmcbain** [comment]
The fifth line of the updated file
```scheme
(10 (1 1 188 1 3))(
```
look wrong, e.g. compared to the twelfth line of the input.  The parentheses are unbalanced; I think it should be
```scheme
(10 (1 1 188 1 3)(
```

This line is written in 

https://github.com/nschloe/meshio/blob/d4c68b3c473101d09965ddec3fdff53f4e54c17c/meshio/ansys_io.py#L387-L393

I suspect the second closing parenthesis should be deleted.

**Comment by nschloe** [comment]
Tentatively closing as fixed. Feel free to reopen if this isn't the case.
