### ISSUE TITLE
How to install MESHIO in conda environment

### ISSUE THREAD

**Issue by athulshaji** [nschloe/meshio#391]
Hello,
I have installed Anaconda on Windows 10 machine. Will it be possible to install MESHIO in a conda environment? If yes, please share.

Thank you,
Athul Shaji

**Comment by gdmcbain** [comment]
One way, the one I use, is:
```shell
conda install pip
pip install meshio
```

Envoyé depuis ProtonMail mobile

-------- Message d'origine --------

**Comment by athulshaji** [comment]
Thanks for the reply. The solution you have provided worked.

**Comment by nschloe** [comment]
meshio is now available from Anaconda: https://anaconda.org/conda-forge/meshio
