### ISSUE TITLE
Error when running python script in IDLE3.6

### ISSUE THREAD

**Issue by jau827** [nschloe/meshio#393]
Hello, I am attempting to run a script that I wrote `meshio.py` from within IDLE3.6 and from the command line. Neither work and both output the same error message.

Error message when running in Terminal within my Python3.6 Anaconda environment shell:
```
>>> exec(open('/Users/NaN/__work__/simple_example_29-MAY/meshio.py').read())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "/Users/NaN/__work__/simple_example_29-MAY/meshio.py", line 7, in <module>
    mesh = meshio.read(file)
AttributeError: module 'meshio' has no attribute 'read'
```

Error message when running as a script in IDLE3.6 (while in my activated Python3.6:
```
Anaconda environment):
Traceback (most recent call last):
  File "/Users/NaN/__work__/simple_example_29-MAY/meshio.py", line 1, in <module>
    import meshio
  File "/Users/NaN/__work__/simple_example_29-MAY/meshio.py", line 7, in <module>
    mesh = meshio.read(file)
AttributeError: module 'meshio' has no attribute 'read'

```

Has anyone seen this issue before? The strange thing is that if I simply type each command into the command shell one at a time the script will work!

Running on macOS 10.14
Anaconda Python3.6.2

**Comment by nschloe** [comment]
> `meshio.py`

Dangerous name. Python might try to import that file when you write `import meshio` and not actually meshio. Try renaming it.

**Comment by gdmcbain** [comment]
Maybe try calling your script something other than meshio.py. I suspect Python is importing that script as a module when it reads "import meshio".

Envoyé depuis ProtonMail mobile

-------- Message d'origine --------

**Comment by jau827** [comment]
@nschloe @gdmcbain That was exactly it! Works great now, thanks.

**Comment by giannoko** [comment]
Hello,

I get the following problem when trying to use: "meshio-convert rtemp.msh rtemp.vtk"


Traceback (most recent call last):
  File "/usr/bin/meshio-convert", line 135, in <module>
    _main()
  File "/usr/bin/meshio-convert", line 14, in _main
    args = _parse_options()
  File "/usr/bin/meshio-convert", line 100, in _parse_options
    choices=meshio.input_filetypes,
AttributeError: module 'meshio' has no attribute 'input_filetypes'
