### ISSUE TITLE
Output .msh file is garbled when opened with text editor

### ISSUE THREAD

**Issue by ArnoiZ** [nschloe/meshio#398]
Hi,

I used meshio to write a .msh file before and I was able to view the data in text editor. However, the .msh file I created this time can show the mesh properly when opened with gmsh. But when I tried to open it with text editor, the data is garbled. 
I am not sure what caused this problem, could you help me take a look?
[mesh.zip](https://github.com/nschloe/meshio/files/3317519/mesh.zip)

**Comment by nschloe** [comment]
Fixed?

**Comment by ArnoiZ** [comment]
The output file is still garbled, but I was able to obtain normal file
using gmsh to open the file and then save it as a new file.

令和元年6月24日(月) 16:10 Nico Schlömer <notifications@github.com>:

**Comment by nschloe** [comment]
Probably you were using binary data in the gmsh format -- that's actually recommended. If you want human-readable files, you'll have to use
```
meshio-convert edo.msh out.msh --output-format gmsh2-ascii
```

**Comment by ArnoiZ** [comment]
Got it, thank you!

令和元年6月24日(月) 16:33 Nico Schlömer <notifications@github.com>:
