### ISSUE TITLE
write cell data to a vtk file

### ISSUE THREAD

**Issue by thsmit** [nschloe/meshio#406]
Hello, I would like to write FEM data to a vtk file. The data should contain the mesh. And data like the densities, which should be connected to the 'surfaces' of the mesh cells.

I have the following code:

points = mesh.nodes
        cells = {'quad': mesh.elements}
      
        # addtional data
        point_data = {'Displacements': analysis.u.reshape(mesh.nodes.shape)}
        cell_data = {'quad': {'densities': x}}
        
        # (filename, point coordinates of original mesh, element connectivity of mesh, additional data)
        meshio.write_points_cells(filename, points, cells, point_data, cell_data)

x is an numpy array of with shape (1, number of elements)

I get the following error:

  File "C:\APPS\Anaconda3\envs\topopt\lib\site-packages\meshio\vtk_io.py", line 603, in write
    if values.shape[1] == 2:

IndexError: tuple index out of range

What am I doing wrong?

**Comment by nschloe** [comment]
> What am I doing wrong?

Nobody can tell without a full example.

**Comment by thsmit** [comment]
Hi Nico,

I think I solved it. Thanks for the quick replies.
