### ISSUE TITLE
Problem reading Abaqus Mesh correctly (`tetra10`)

### ISSUE THREAD

**Issue by bhaveshshrimali** [nschloe/meshio#409]
Is the `Abaqus` format fully supported in meshio ? 
I tried converting the attached mesh (comprised of 10-noded tets in 3D) using meshio but it spits the following error: 

```
  File "C:\Users\Bhavesh\AppData\Local\Programs\Python\Python37\Scripts\meshio-convert.exe\__main__.py", line 9, in <module>
  File "c:\users\bhavesh\appdata\local\programs\python\python37\lib\site-packages\meshio\cli.py", line 32, in main
    mesh = read(args.infile, file_format=args.input_format)
  File "c:\users\bhavesh\appdata\local\programs\python\python37\lib\site-packages\meshio\helpers.py", line 174, in read
    return format_to_reader[file_format].read(filename)
  File "c:\users\bhavesh\appdata\local\programs\python\python37\lib\site-packages\meshio\abaqus_io.py", line 95, in read
    out = read_buffer(f)
  File "c:\users\bhavesh\appdata\local\programs\python\python37\lib\site-packages\meshio\abaqus_io.py", line 122, in read_buffer
    key, idx = _read_cells(f, keyword, point_gids)
  File "c:\users\bhavesh\appdata\local\programs\python\python37\lib\site-packages\meshio\abaqus_io.py", line 182, in _read_cells
    entries = [int(k) for k in filter(None, line.split(","))]
  File "c:\users\bhavesh\appdata\local\programs\python\python37\lib\site-packages\meshio\abaqus_io.py", line 182, in <listcomp>
    entries = [int(k) for k in filter(None, line.split(","))]
ValueError: invalid literal for int() with base 10: ' \n'
```
Consequently I read the mesh using meshio in python and tried to remove the trailing newlines by naively replacing : 
```
entries = [int(k) for k in filter(None, line.split(","))]
```
with 
```
entries = [int(k) for k in filter(None, line.strip().split(","))]
```
inside `_abaqus.py` script. 

However this results in an incorrect `cells` dictionary. It is unable to read in fact element connectivity spanning multiple lines. Any ways to fix this ? I have not checked it with element connectivity that is printed "one line per element" though, but it should be fine after birefly peeking at the `_read_cells` function inside `_abaqus.py`

[mesh_trial.zip](https://github.com/nschloe/meshio/files/3437246/mesh_trial.zip)

**Comment by keurfonluu** [comment]
Your input file seems to be wrong. An element should be defined in a single line while they are split on two different lines in the file you provided. Modifying from line 245412 to the EOF

```
*Element, type=C3D10, ELSET=PART1
1, 4823, 11681, 26403, 11684, 54387, 54391, 54389, 
54388, 54390, 54392
2, 8685, 8688, 20871, 8695, 54393, 54397, 54395, 
54394, 54396, 54398
...
172107, 10735, 13434, 13880, 13833, 217264, 209071, 174209, 
217265, 217266, 213992
```

to

```
*Element, type=C3D10, ELSET=PART1
1, 4823, 11681, 26403, 11684, 54387, 54391, 54389, 54388, 54390, 54392
2, 8685, 8688, 20871, 8695, 54393, 54397, 54395, 54394, 54396, 54398
...
172107, 10735, 13434, 13880, 13833, 217264, 209071, 174209,  217265, 217266, 213992
```

should do the trick.

**Comment by keurfonluu** [comment]
If your input file is a legit file exported by Abaqus, an ugly workaround would be to patch ``_read_cells`` in ``_abaqus.py`` as such:

``` python
cells = []
is_new_element = True
while True:
    last_pos = f.tell()
    line = f.readline()
    if line.startswith("*") or line == "":
        break
    entries = [int(k) for k in filter(None, line.rstrip().split(","))]
    if is_new_element:
        idx = [point_gids[k] for k in entries[1:]]
    else:
        idx.extend([point_gids[k] for k in entries])
    if line.rstrip().endswith(","):
        is_new_element = False
    else:
        cells.append(idx)
        is_new_element = True
```

**Comment by bhaveshshrimali** [comment]
@keurfonluu the input file is exported by [Netgen](https://ngsolve.org/) to be used in Abaqus. I have checked it to be readable and functional in Abaqus. I was not sure if `_read_cells` needed any tweaking in the first place. I will try to patch it up and see if this is resolved.

**Comment by keurfonluu** [comment]
@bhaveshshrimali I am able to import your mesh written by meshio in FLAC3D after I imported it with a patched meshio (I couldn't with your original file).

**Comment by bhaveshshrimali** [comment]
@keurfonluu you mean reading `mesh_trial.inp` file with a patched meshio, right ? This opens up readily without any problems in abaqus as follows

![abaqus_trial_meshio](https://user-images.githubusercontent.com/22624037/61989183-1e30bb00-aff1-11e9-805b-f48d27f6f7c1.jpg)


I am gonna try the tweaked `meshio` with a couple more meshes just to make sure that things are alright. I will close this as soon as I am done verifying things. 
Thanks!

**Comment by keurfonluu** [comment]
@bhaveshshrimali Yeah, if Abaqus can read your file, it means that defining an element on several lines is legit and should be supported by meshio IMHO.

**Comment by nschloe** [comment]
Alright, can you make a PR?

**Comment by bhaveshshrimali** [comment]
@nschloe will do today. Thanks

**Comment by bhaveshshrimali** [comment]
Just created the pull request with the tweaked `_abaqus.py` ! @nschloe let me know if things went alright. Thanks @keurfonluu for verifying. Feel free to close this if no longer needed.

**Comment by nschloe** [comment]
Closing via #410.
