### ISSUE TITLE
No physical labels in medit file (similar to #279)

### ISSUE THREAD

**Issue by augustjohansson** [nschloe/meshio#440]
Hi! Thank you very much for your great work on meshio. I have an issue that's, what I think, identical to the issue #279 : Physical labels doesn't seem to be written to the medit mesh file -- all I get is ones. I've tried using both gmsh 3.0.6 and 4.4.1 but I get identical output in both versions. Please feel free to remove this issue and reopen #279 .

Here's a small example where the unit square is split into two triangles with two different labels:

```python
import pygmsh
import meshio

geom = pygmsh.built_in.Geometry()
lcar = 1.0
x = [[0.0, 0.0, 0.0],
     [1.0, 0.0, 0.0],
     [1.0, 1.0, 0.0],
     [0.0, 1.0, 0.0]]
p = [geom.add_point(x_i, lcar) for x_i in x]

# Lower left
label_0 = 2
a = geom.add_line(p[0], p[1])
b = geom.add_line(p[1], p[3])
c = geom.add_line(p[3], p[0])
loop_0 = geom.add_line_loop([a, b, c])
s_0 = geom.add_plane_surface(loop_0)
ps_0 = geom.add_physical(s_0, label=label_0)

# Upper right
label_1 = 3
d = geom.add_line(p[1], p[2])
e = geom.add_line(p[2], p[3])
loop_1 = geom.add_line_loop([d, e, -b])
s_1 = geom.add_plane_surface(loop_1)
ps_1 = geom.add_physical(s_1, label=label_1)

mesh = pygmsh.generate_mesh(geom, prune_z_0=True, geo_filename="hoho.geo")
meshio.write("hoho.mesh", mesh)
```

**Comment by nschloe** [comment]
The thing is that I don't know if/how cell data is supported in medit. If you find any documentation on that, let me know!

**Comment by augustjohansson** [comment]
It's not totally obvious, but it's in the documentation, section 7.2.1
https://www.ljll.math.upmc.fr/frey/publications/RT-0253.pdf
Here one can see that the each of the keywords in the first table (Vertices, ..., Hexaedra) has a `ref_i` in the last column. That's where such markers are put.

For example, here's a medit file with two triangles with cell markers 1 and 2. Similarly, vertex markers are 5 and 3.
```
MeshVersionFormatted 1
Dimension
3
Vertices
4
0 0 0 5
1 0 0 5
0 1 0 3
1 1 0 3
Triangles
2
1 2 3 1
2 3 4 2
```

**Comment by nschloe** [comment]
I've improved the gmsh and medit interoperability in #447, probably fixing this issue. Feel free to reopen if you continue to have problems.
