### ISSUE TITLE
set correct minimum python version in setup.py

### ISSUE THREAD

**Issue by tjhei** [nschloe/meshio#441]
setup.py currently lists
```
    python_requires=">=3",
```
but 3.5 certainly is not new enough. See #315 for example.

I can create a PR, but I don't know what version you are requiring...

**Comment by nschloe** [comment]
The kwargs thing in #315 is not something what was introduces in 3.5, so I'm not sure what's going wrong there. It may very well be though that meshio needs 3.6, that's what's the tests are using for some years now at least.

**Comment by nschloe** [comment]
Closing via #446.
