### ISSUE TITLE
meshio fails to convert med volume and faces markers to gmsh format

### ISSUE THREAD

**Issue by Trophime** [nschloe/meshio#448]
Meshio fails to convert properly med mesh to gmsh format.
Volume and Faces markers are not exported to gmsh

Please find attached a test mesh.
What is expected is to have:
1) Volume: Box_1
2) 6 Faces: Face_1,..,Face_6

**Comment by nschloe** [comment]
Did you forget to attach the mesh? Can't see it here. Also, please tell me the command you used to convert so I can reproduce it here.

**Comment by Trophime** [comment]
[cube.zip](https://github.com/nschloe/meshio/files/3575937/cube.zip)

**Comment by Trophime** [comment]
`meshio-convert cube.med --output-format gmsh2-ascii cube.msh`

**Comment by nschloe** [comment]
When converting, I'm getting the attached mesh. It contains a `cell_tags` element data section with
```
$ElementData
1
"cell_tags"
1
0.0
3
0
1
2320
1 0
2 0
3 0
4 0
5 0
6 0
7 0
8 0
9 0
[...]
```
Is that not correct?

[cube.msh.zip](https://github.com/nschloe/meshio/files/3578154/cube.msh.zip)

**Comment by nschloe** [comment]
Ah, wait, those should be gmsh tags. I see

**Comment by nschloe** [comment]
Okay, I've fixed this locally. Can you confirm that the tags are _negative_ values? (Seems a bit odd.)

**Comment by Trophime** [comment]
I don't know how to check the tags in med
I'm interested in the "name" associated to the tags...

**Comment by nschloe** [comment]
> I don't know how to check the tags in med

Neither. :frowning_face:

**Comment by tianyikillua** [comment]
@Trophime 

The details are contained in https://github.com/nschloe/meshio/pull/352.

In short, the names corresponding to these integers (`mesh.point_data.point_tags`, `mesh.cell_data[cell].cell_tags`) are contained in
- `mesh.point_tags`
- `mesh.cell_tags`

As of the MED convention, `point_tags` have positive values wheres `cell_tags` have negative values.

**Comment by tianyikillua** [comment]
The problem is solved and I think it can be closed now.

**Comment by gdmcbain** [comment]
Should this `.cell_tags` attribute be used with other formats besides MED?  e.g. Gmsh MSH 2 and MSH 4.1?   Currently both use the `.field_data` attribute, although the `dict` has the names and numbers the other way around and the number is a pair of an identifying int and the dimension.

https://github.com/nschloe/meshio/blob/2ab48f2b81ed565d1043d4e09b0cda33d1c970a3/meshio/gmsh/common.py#L13-L20

and

https://github.com/nschloe/meshio/blob/2ab48f2b81ed565d1043d4e09b0cda33d1c970a3/meshio/gmsh/common.py#L139-L144

**Comment by tianyikillua** [comment]
> Should this `.cell_tags` attribute be used with other formats besides MED?

Why not? Besides the reason why a list is assigned to the unique id is that a node / cell can be "tagged" by several sets.

**Comment by gdmcbain** [comment]
Ta.

Should that be a set rather than a list? Or is order significant?

**Comment by tianyikillua** [comment]
A Python set can indeed be used; the order is insignificant, even though it determines the name of the internally created intersection of subsets.
``` python
-6: ["Apple", 'Beatle']
```
then all cells that are tagged `-6` are assigned to a MED group called `Apple_Beatle`. But it should not raise much problem if it's called `Beatle_Apple`.
