### ISSUE TITLE
How to Generate IGES/STEP file from Mesh/STL using Python or C++?

### ISSUE THREAD

**Issue by selvakarna** [nschloe/meshio#458]
How to Generate IGES/STEP file from Mesh/STL using Python or C++?

**Comment by nschloe** [comment]
Well, not with meshio. :smile: 

meshio, as the name indicates, treats _meshes_. IGES and STEP specify CAD geometries.

**Comment by selvakarna** [comment]
Hi @nschloe ,

       I am asking how to generate cad [step/iges] file from 3d mesh or stl using python?
is there any way to convert ?using scripts ?

**Comment by nschloe** [comment]
I don't know; not with meshio anyway. You'll have to do it yourself.

**Comment by asirihewage** [comment]
It can be done with a cpp library and can be exposed as an API. I have done the same using cpp and python flask.
