### ISSUE TITLE
meshio-convert: Converting from .inp to .vtu gives KeyError for tetrahedral elements (C3D4)

### ISSUE THREAD

**Issue by suedengland** [nschloe/meshio#459]
Hi there,

meshio-convert runs into a KeyError when converting from Abaqus .inp to .vtu,
when dealing with tetrahedral elements (C3D4). I can convert successfully, when using hexahedral elements (C3D8), however.

Please see the attached log.txt for the output, when trying to convert tets.

Note, that the value triggering the KeyError corresponds to "max_node_number+1",
for debugging.

[log.txt](https://github.com/nschloe/meshio/files/3670587/log.txt)

[1ax_zug_4x4x10_tet.zip](https://github.com/nschloe/meshio/files/3670573/1ax_zug_4x4x10_tet.zip)

**Comment by tianyikillua** [comment]
I can successfully read the INP mesh without problem. Are you using the latest version? Please do
```
pip3 install -U meshio
```
Replace `pip3` by `pip` if you are under Windows. Add `--user` if needed.

**Comment by suedengland** [comment]
Thanks for replying.
Unfortunately meshio was already up to date and the issue still remains as before.

`pip3 install -U meshio
Requirement already up-to-date: meshio in ./.local/lib/python3.7/site-packages (3.1.5)
Requirement already satisfied, skipping upgrade: numpy in /usr/lib/python3.7/site-packages (from meshio) (1.17.0)`

I'm currently under Manjaro 18.1.0 // 5.2.11-1-MANJARO // python 3.7.4 // gcc 9.1.0 // meshio 3.1.5

I also tried it on Ubuntu 18.04.3 // 4.15.0-64-generic // python 3.6.8 // gcc 8.3.0 // meshio 3.1.5 with the same issue, when running
`meshio-convert 1ax_zug_4x4x10_tet.inp test.vtu`

**Comment by keurfonluu** [comment]
Me neither, I have no issue reading your file (on Windows).

It's weird, this should not happen since key entry 327 should not exist. Since we cannot reproduce the issue, it will be hard to debug without seeing what's happening in your ``point_gids``... It might help if you could provide us with the content of your ``point_gids`` (as a json for instance).

In the mean time, as a workaround, since your nodes are ordered, I think replacing line 181 by 

``` python
    idx += [int(k-1) for k in filter(None, line.split(","))]
```

should do the trick.

**Comment by nschloe** [comment]
> I can successfully read the INP mesh without problem

@tianyikillua Maybe you have a secret new version, because I cannot either. :smile: I've found the issue and will release a fix in a moment.

**Comment by suedengland** [comment]
works fine for me. Thanks a lot! (:
