### ISSUE TITLE
meshio Xmdf Output file crashes Paraview 5.6.2 on opening

### ISSUE THREAD

**Issue by adtzlr** [nschloe/meshio#462]
Hello,
the following code causes Paraview 5.6.2 (Windows 7) on opening the generated Xmdf file to crash while the produced Vtk file works as expected. Don't know if it is related to Paraview or meshio - feel free to close this issue if it is not related to meshio. Thank you!

P.S.: I tried all available readers for Xdmf files in Paraview.

```python
import meshio
import numpy as np

points = np.array([
                   [0,0,0],
                   [1,0,0],
                   [0,1,0],
                   [1,1,0],
                   [0,0,1],
                   [1,0,1],
                   [0,1,1],
                   [1,1,1],
                  ])


forces = np.arange(  8, dtype=float)#.reshape(-1,1)
stress = np.arange(1*3, dtype=float).reshape(-1,3)

point_data = {'force': forces}
cell_data  = {'hexahedron': {'stress': stress}}

connectivity = np.array([[0,1,3,2,4,5,7,6]])
cells = {'hexahedron': connectivity}

# vtk output
meshio.write_points_cells(
                          'output_vtk.vtk',
                          points,
                          cells,
                          point_data=point_data,
                          cell_data=cell_data,
                         )

# xdmf time series output
writer = meshio.XdmfTimeSeriesWriter('output_xdmf.xdmf')
writer.write_points_cells(points, cells)

for t in range(1):
    writer.write_data(t, point_data=point_data, cell_data=cell_data)
```

**Comment by tianyikillua** [comment]
(Again), it works fine with me, by using `Xdmf3ReaderS` and `Xdmf3ReaderT`, with ParaView 5.7.0 under Windows 10.

**Comment by adtzlr** [comment]
Okay, will try to update Paraview and report back. Thanks for testing!

**Comment by nschloe** [comment]
Works fine here too:

![sc](https://user-images.githubusercontent.com/181628/66379364-95050f80-e9b5-11e9-981b-bc54d464b8d2.png)

Thanks for a nicely reproducible report; feel free to close at any time.

**Comment by adtzlr** [comment]
Confirmed - it works. Xdmf Files generated by meshio requires Paraview >= 5.7.
