### ISSUE TITLE
Error in IPython console (Spyder) if Xdmf writer is called more than once

### ISSUE THREAD

**Issue by adtzlr** [nschloe/meshio#463]
Hello,

if the following script is executed more than once in the same IPython console in Spyder, this will only work for the first run. Some .h5 file is already open, the last two lines of the error message I get are as follows:

```python
...
File "h5py\h5f.pyx", line 105, in h5py.h5f.create
OSError: Unable to create file (unable to truncate a file which is already open)
```

This is the script. Execute it at least two times in Spyder to raise the error.

```python
import meshio
import numpy as np

points = np.array([
                   [0,0,0],
                   [1,0,0],
                   [0,1,0],
                   [1,1,0],
                   [0,0,1],
                   [1,0,1],
                   [0,1,1],
                   [1,1,1],
                  ])

forces = np.arange(  8, dtype=float)#.reshape(-1,1)
stress = np.arange(1*3, dtype=float).reshape(-1,3)

point_data = {'force': forces}
cell_data  = {'hexahedron': {'stress': stress}}

connectivity = np.array([[0,1,3,2,4,5,7,6]])
cells = {'hexahedron': connectivity}

# xdmf time series output
writer = meshio.XdmfTimeSeriesWriter('output_xdmf.xdmf')
writer.write_points_cells(points, cells)

for t in range(1):
    writer.write_data(t, point_data=point_data, cell_data=cell_data)
```

P.S.: I use Anaconda with Python 3.6.6 on Windows 7.

**Comment by nschloe** [comment]
I don't have anaconda or spyder. Can I reproduce this with plain Python? (It might be a spyder issue as well.) Also, what version of meshio are you using?

**Comment by adtzlr** [comment]
- meshio 3.1.5 (installed with pip)

You need at least the IPython shell to reproduce the error - which is, as far as I know, not included in the base Python installation. Easiest way in Windows would be to download WinPython, install `meshio` through pip and run the script in Spyder - or at least evaulate the commands line by line in the IPython Interpreter.

From my experience IPython behaves a little bit different than the base interpreter, as variables are hold in the kernel for future interactions. Missing statements like `file.close()` are not as important in the base interpreter, as the script is only called once wherease in IPython the file gets locked if not closed.

**Comment by nschloe** [comment]
I have IPython of course. So to to produce the error, I do what exactly?

**Comment by adtzlr** [comment]
Copy the above script, start the Ipython interpreter, paste the whole script and run it with shift+enter. Then do the same thing again in the same IPython session. In my case I get `OSError`.

**Comment by tianyikillua** [comment]
Well, since the previously opened `output_xdmf.xdmf` has not been closed, reopening it again with `h5py.File(self.h5_filename, "w")` raises the error.

We need to implement a method for users to properly close the HDF5/XDMF files, for instance inside a context manager `__enter__` and `__exit__`.

**Comment by tianyikillua** [comment]
As a work around, add `writer.h5_file.close()` when you finish writing.
```
writer = meshio.XdmfTimeSeriesWriter('output_xdmf.xdmf')
writer.write_points_cells(points, cells)

for t in range(1):
    writer.write_data(t, point_data=point_data, cell_data=cell_data)
writer.h5_file.close()

writer = meshio.XdmfTimeSeriesWriter('output_xdmf.xdmf')
writer.write_points_cells(points, cells)

for t in range(1):
    writer.write_data(t, point_data=point_data, cell_data=cell_data)
``è
