### ISSUE TITLE
Convert an extruded 3D mesh to 2D

### ISSUE THREAD

**Issue by ethren** [nschloe/meshio#469]
Hello, Thank you for the awesome library!
I have some 3D meshes that are in fact 2D meshes in xy plane but just extruded in the z-direction (one cell thick).
See the example in the following picture (The Ansys `.msh` file is attached below):
![3d-mesh](https://user-images.githubusercontent.com/38412653/67133431-a3002f00-f204-11e9-9ea2-18be1fb24680.png)

And  I would like to remove the third dimension z to make the mesh 2D:
![2d-mesh](https://user-images.githubusercontent.com/38412653/67133448-b9a68600-f204-11e9-9cd4-0c36574cb442.png)

The Ansys 3D mesh file:  
[cylinder.zip](https://github.com/nschloe/meshio/files/3745935/cylinder.zip)

Thank you

**Edit**:  (I attached the `.msh` file)
As you can see, the mesh is 3D, I want to convert it to 2D mesh file, that is, to remove the z direction from the mesh. Could you please help me to do that?

**Comment by nschloe** [comment]
Okay. Where is the problem?

**Comment by nschloe** [comment]
> Could you please help me to do that?

meshio  can help you extract the point coordinates and cells. The rest you'll have to do for yourself. It's an interesting question that could attract some interest on [stackoverflow](https://stackoverflow.com).

**Comment by ethren** [comment]
@nschloe: Thanks, I asked the question [here](https://stackoverflow.com/questions/58462062/how-to-convert-a-3d-extruded-mesh-to-2d-mesh).

**Comment by jdanielhoyos** [comment]
@ethren  Hello. Did you found a solution? Thank you.
