### ISSUE TITLE
Wrong mesh total volume with MSH4 format

### ISSUE THREAD

**Issue by keurfonluu** [nschloe/meshio#470]
Hi,

I think there might be an error when reading Gmsh v4 format.

I have a box split as 6 horizontal boxes with different physical groups. A vertical box (a fault) cuts the 4 middle boxes. No issue whatsoever while meshing. I still check that everything is fine by calculating the total volume of my tetrahedra cells (it should equal 6e10 in my case).

With a mesh file exported as MSH4, I get a bigger volume. Nevertheless, the volume is correct when I export my mesh as MSH2. Both ``meshio.Mesh`` objects have the same number of tetra, but I noticed that the one for MSH2 has fewer points (5333 instead of 5337 for MSH4). I don't know if it helps, though.

I attach an archive containing the Gmsh script (actually generated by pygmsh), the two Gmsh mesh files (v2 and v4) and a script to check the total volume of the mesh:
[mesh4.zip](https://github.com/nschloe/meshio/files/3747262/mesh4.zip)

Note that everything is alright if I do not define physical groups.

**Comment by nschloe** [comment]
Really interesting! For my own reference:
```python
import meshplex
import numpy

mesh = meshplex.read("mesh2.msh")
print(numpy.sum(mesh.cell_volumes))

mesh = meshplex.read("mesh4.msh")
print(numpy.sum(mesh.cell_volumes))
```
```
60000000000.00001
60004555829.20669
```
There seem to be differences in both cells and points. Can you produce a small-scale example?

**Comment by keurfonluu** [comment]
Here is the downscaled example. I exported the file in ASCII with meshio too.
[mesh4_2.zip](https://github.com/nschloe/meshio/files/3748141/mesh4_2.zip)

I don't exclude the possibility that I am using Gmsh in the wrong way, but still, the error should be the same independently of the format...

**Comment by gdmcbain** [comment]
I get an error reading `mesh4.msh` from `mesh4_2.zip` in Gmsh 4.5.0-git-0c1b63c8d on Ubuntu 19.04:

```
Error   : Unknown entity 0 of dimension 3
Error   : Could not read elements
Error   : Error loading 'mesh4.msh'
Info    : Done reading 'mesh4.msh'
```
How was this file generated?  The first `mesh4.msh` from `mesh4.zip` was O. K.

**Comment by keurfonluu** [comment]
The mesh files in the second zip were generated by meshio. The original mesh file was generated using pygmsh.

I updated the script to test the volumes by adding the source Gmsh geometry file (generated by pygmsh but I don't believe that the problem comes from pygmsh):
[mesh4_3.zip](https://github.com/nschloe/meshio/files/3748959/mesh4_3.zip)

**Comment by keurfonluu** [comment]
I updated to meshio 3.2.3 but still got the same wrong volume with the last test script I submitted...

**Comment by nschloe** [comment]
Absolutely. I'll look into it tomorrow. God, I love the gmsh formats.

**Comment by nschloe** [comment]
Okay, here's what I get:
```
msh file: mesh2.msh

msh file: mesh4.msh
Domain volume: 32.0
Mesh v2 volume: 31.999999999999936
Mesh v4 volume: 31.999999999999936
```
Looks good?

**Comment by keurfonluu** [comment]
Seems correct. Which version of meshio is it? I still got the error with meshio 3.2.5...

**Comment by nschloe** [comment]
Just that version.

**Comment by keurfonluu** [comment]
Weird. I tried both PyPI and master, still got the same (wrong) volume. What's happening?

    Domain volume: 32.0
    Mesh v2 volume: 31.99999999999998
    Mesh v4 volume: 32.04600281494753
    meshio v3.2.5

**Comment by nschloe** [comment]
We're talking about your mesh4_3.zip set, right?

**Comment by keurfonluu** [comment]
Yes, that one.

**Comment by nschloe** [comment]
You'll have to create an even more minimal example (perhaps with only a handful of cells, no subdomains etc) to find what's going on.

**Comment by keurfonluu** [comment]
It's actually quite hard to reproduce at smaller scale. I can increase the thickness of the fault box to get rid of the issue.

I tried something by writing MSH4 file with meshio from MSH2 file generated by pygmsh, got the right volume:

```python
msh2 = pg.generate_mesh(
    geo_object = geo,
    verbose = False,
    mesh_file_type = "msh22",
    msh_filename = "mesh2.msh",
)
meshio.write("mesh4.msh", msh2, file_format = "gmsh4-binary")
msh4 = meshio.read("mesh4.msh")
```

Output:

```
WARNING:root:Binary Gmsh needs c_size_t (got int64). Converting.

msh file: mesh2.msh
Domain volume: 32.0
Mesh v2 volume: 31.99999999999998
Mesh v4 volume: 31.99999999999998
```

The other way round:

```python
msh4 = pg.generate_mesh(
    geo_object = geo,
    verbose = False,
    mesh_file_type = "msh4",
    msh_filename = "mesh4.msh",
)
meshio.write("mesh2.msh", msh4, file_format = "gmsh2-binary")
msh2 = meshio.read("mesh2.msh")
```

Output:

```
WARNING:root:Binary Gmsh needs 32-bit integers (got int64). Converting.

msh file: mesh4.msh
Domain volume: 32.0
Mesh v2 volume: 32.04600281494753
Mesh v4 volume: 32.04600281494753
```

**Comment by nschloe** [comment]
`31.999999999999936` for me both ways.

You can either come up with a minimal example, or try and debug meshio yourself. Nasty issue.

**Comment by tianyikillua** [comment]
Maybe related to #459 (*weird* behaviour observed by @keurfonluu and me, under Windows). @keurfonluu, can you reproduce the issue under Linux (WSL for instance) and with a freshly installed meshio (`pip install -U --force meshio`)?

**Comment by keurfonluu** [comment]
@tianyikillua You are right, I have no issue on WSL (Ubuntu 18.04, Python 3.6.8)... That's really strange that we got different results depending on the platform.

On Windows, I am running Anaconda with Python 3.7.3.

**Comment by keurfonluu** [comment]
Okay, so I ran another test, and my guess is that there is a bug on Windows version of Gmsh (4.4.1). When I execute on both platform the command:

```bash
gmsh -3 mesh.geo -format msh4 -o mesh4.msh
```

It produces different mesh files (with 886 nodes on WSL and 892 nodes on Windows). If I read the mesh file produced in WSL in Windows with meshio, the volume is correct. I close the issue for now since the problem is probably not related to meshio but rather to Gmsh.

[mesh4_4.zip](https://github.com/nschloe/meshio/files/3764920/mesh4_4.zip)

**Comment by keurfonluu** [comment]
Sorry, I reopen the issue because I think that I figured out what's going on.

Gmsh 4.4.1 on Windows exports to MSH4 with one extra node compared to MSH2 (node 892):

```
3 73 0 8
885
886
892
887
888
889
890
891
1.9094841541679 1.854819586758833 -0.9289565732495784
2.159267773830474 2.212772901957076 -0.9182659643526144
1.809354945981777 1.881992026041631 -0.8649675049590133
2.206256706527594 2.230978328829988 -1.096770135423909
2.169757106314774 2.226374625230513 -1.030571381121748
1.734212940584615 1.745333884906713 -1.06144994650878
2.216726141239009 2.122168929620742 -1.05853354798943
1.83210465513853 1.844069935125439 -1.014305723781135
$EndNodes
```

Node 892 is the only node that is not in the correct order, it is not used in any element and does not exist in MSH2 file (basically, it is useless). Logically, it should not be used in any ``tetra`` cell in meshio. However, when I check whether any ``tetra`` cell uses this node in meshio:

```python
for i, cell in enumerate(msh4.cells["tetra"]):
    if 891 in cell:
        print(i)
```

Output:

```
4024
4091
4092
4093
4135
4137
4154
4155
4156
4157
4158
4159
4160
4161
4162
4163
```

But no cell uses node 890 while they should. If I remove node 892 from the MSH4 file (and edit the file accordingly), everything is alright.

It does not change the fact that Gmsh should not export this node in the first place, though.

[mesh4_5.zip](https://github.com/nschloe/meshio/files/3765161/mesh4_5.zip)

Note:

```
msh4.points[890]
array([ 1.83210466,  1.84406994, -1.01430572])
```

```
msh4.points[891]
array([ 1.80935495,  1.88199203, -0.8649675 ])
```

**Comment by nschloe** [comment]
> Gmsh 4.4.1 on Windows exports to MSH4 with one extra node compared to MSH2 (node 892):

This definitely needs to be reported upstream. @keurfonluu Will you take care of it and post the link here? (Reminds me of https://arstechnica.com/information-technology/2019/10/chemists-discover-cross-platform-python-scripts-not-so-cross-platform/.)

**Comment by keurfonluu** [comment]
Here you go: https://gitlab.onelab.info/gmsh/gmsh/issues/675

**Comment by nschloe** [comment]
@keurfonluu Thank you for staying so persistent with this nasty issue. It's finally properly fixed in meshio and gmsh also has a fix. Great!
