### ISSUE TITLE
Cannot open med file converted by meshio

### ISSUE THREAD

**Issue by s1291** [nschloe/meshio#478]
I tried to convert some meshs to Salome `med` format. Unfortunately, Salome cannot read them.

```bash
meshio-convert --input-format ansys --output-format med meshfile.msh meshfile.med
```
where `meshfile` is one of the following: 
* First mesh: [cavity.zip](https://github.com/nschloe/meshio/files/3763116/cavity.zip)
* Second mesh: [movingCone.zip](https://github.com/nschloe/meshio/files/3763118/movingCone.zip)
* Third mesh: [pitzDaily.zip](https://github.com/nschloe/meshio/files/3763120/pitzDaily.zip)

Both Salome 8.3 and Salome 9.3 show the following error message when trying to open each med file:
![salome9 3-cavity](https://user-images.githubusercontent.com/17838489/67408654-a3f4e000-f5b9-11e9-977c-821abd9ecaaf.png)
![salome9 3-movingCone](https://user-images.githubusercontent.com/17838489/67408724-bc64fa80-f5b9-11e9-9cdc-cb09d07f5ea0.png)
![salome9 3-pitzDaily](https://user-images.githubusercontent.com/17838489/67408726-bc64fa80-f5b9-11e9-9033-51bb4607dc0f.png)

What is wrong with these `*.med` files?

**Comment by nschloe** [comment]
I don't know, unfortunately. The problem is that I don't know of a format specification.

Best ask the salome developers what's wrong with the files, and report back here.

Another option: Use software that can use a better mesh format (like XDMF).

**Comment by s1291** [comment]
I've asked a similar question [here](https://www.salome-platform.org/forum/forum_10/600817792) but I didn't get any response yet. I will try to report this in that forum.

I have no idea what XDMF format is but I am sure it is not available in CFD softwares (Ansys Fluent, OpenFOAM, ...etc).

**Comment by tianyikillua** [comment]
I'll have a look at these MED files tomorrow.

**Comment by tianyikillua** [comment]
Incredible! The issue is introduced by the latest `h5py==2.10.0`, with the previous `pip install h5py==2.9.10` everything was fine!

I will investigate and update according to changes made in 2.10.0 :-(

**Comment by tianyikillua** [comment]
@s1291 Could you please try my fork https://github.com/tianyikillua/meshio (with the latest )? If it works for you I will submit a PR.

The changed I made should also be compatible with the previous `h5py` version.

**Comment by s1291** [comment]
@tianyikillua: I used your fork. It works!
