### ISSUE TITLE
Does meshio read binary vtu files?

### ISSUE THREAD

**Issue by empet** [nschloe/meshio#483]
Does meshio read binary vtu files? 
Trying to read the vtu files posted here: [https://github.com/topology-tool-kit/ttk-data](https://github.com/topology-tool-kit/ttk-data)
I get the same error for all:
```
XMLSyntaxError: Input is not proper UTF-8, indicate encoding !
Bytes: 0xC9 0x0C 0x00 0x00, line 28, column 6 (dragon.vtu, line 28)

During handling of the above exception, another exception occurred:
```
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 1365: invalid continuation byte
```
I read the file as follows:

fdata = meshio.read("dragon.vtu")
For any other file at the above link the same errors are displayed, the only difference is the line number.

I doubt that all vtu files in that repo have the same errors. Is something I missing when reading the files?

**Comment by nschloe** [comment]
This appears to be a bug in LXML, reported [here](https://bugs.launchpad.net/lxml/+bug/1849810).

**Comment by empet** [comment]
@nschloe   Thank you!!!

**Comment by nschloe** [comment]
Okay, so it appears that this is not an lxml bug after all. VTU with raw binary data violates the XML specification and cannot by read by XML parsers. To support these kind of files, meshio would have to implement its own parser, and this isn't going to happen. Raw binary data seems like an oversight in the initial VTU spec, and indeed there is a footnote saying

> There is one case in which the file is not a valid XML document. When the AppendedData section is not encoded as base64, raw binary data is present that may violate the XML specification. This is not default behavior, and must be explicitly enabled by the user.

If you ever meet those files, it's best to ask upstream to change the data into base64.
