### ISSUE TITLE
meshio-convert mesh.exo mesh.med KeyError: 'wedge'

### ISSUE THREAD

**Issue by A2L21603** [nschloe/meshio#486]
I have a mesh in exo format and I would like to convert this mesh in med format.
Using the command line:
```
meshio-convert mesh.exo mesh.med
```
It results an error =>  `KeyError:'wedge'`
I obtained an output of the mesh: "mesh.med" but it seems not utilisable (complete information of the mesh is missing : for example faces are not identified) only nodes and volumes are available.

[mesh.zip](https://github.com/nschloe/meshio/files/3775751/mesh.zip)

Could you help me with this issue ?
Thanks

**Comment by nschloe** [comment]
Alright, fixed now. I've had to guess which med types are "wedges", see https://docs.salome-platform.org/5/med/dev/med__outils_8hxx.html. Unfortunately, there's no proper format specification.

**Comment by A2L21603** [comment]
Yes thanks a lot ! It works now.
Here, wedges seem to correspond visually to the central elements ((symmetry axis = edges) of a cylinder meshed with prismatic volumes.
