### ISSUE TITLE
Feature request: read structured vtk XML files

### ISSUE THREAD

**Issue by kayarre** [nschloe/meshio#489]
Currently the two options for vtk files is .vtu and .vtk, but vtk also supports .vts or xml structured grid.

How challenging would it be to add a .vts reader?

Maybe I could tackle it.

**Comment by nschloe** [comment]
@MuellerSeb had been looking at this a while ago, perhaps you guys can cook up something. I'd say the goal would be to store the information in the mesh file, and not as `points`, `cells`, but in whatever VTK has for structured meshes. Perhaps also a function that converts a structured mesh into an unstructured mesh. The reverse is of course not always possible, so I'd be fine with leaving that out, but maybe one could cook up a heuristic for that too.

**Comment by nschloe** [comment]
Let me close this in favor of #404.
