### ISSUE TITLE
Wrong topology of an obj mesh converted by meshio 

### ISSUE THREAD

**Issue by s1291** [nschloe/meshio#500]
I am trying to export a mesh from `xdmf` to `obj` format. I am using `meshio 3.2.7`. `lxml-4.4.1
`
Using an `XDMF` file that looks like in Paraview:
![xdmf](https://user-images.githubusercontent.com/17838489/68411576-f8d45100-018a-11ea-88a2-ca9a08955e5f.png)

The resulting `obj` mesh, using:
```sh
meshio-convert --input-format xdmf --output-format obj mesh.xdmf mesh.obj
```

![objmesh](https://user-images.githubusercontent.com/17838489/68411590-feca3200-018a-11ea-94fe-1710e765cae0.png)

* Here is the input mesh: [input-mesh.zip](https://github.com/nschloe/meshio/files/3820914/input-mesh.zip)

**Comment by nschloe** [comment]
Thanks for the good report! Fixed now, will be part of the next release.
