### ISSUE TITLE
2d XDMF vectors interpreted by ParaView as 3d

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/meshio#507]
Two-dimensional meshes (with `points.shape[1] == 2`) written to XDMF by meshio are correctly interpreted by ParaView but two-dimensional vectorial `point_data` isn't.  It seems to be parsed as three-dimensional, giving out-of-plane components at some points and leaving others without data.

Minimal example: [theta.tar.gz](https://github.com/nschloe/meshio/files/3839190/theta.tar.gz).

```python
import numpy as np

import dmsh
import meshio

points, triangles = dmsh.generate(dmsh.Circle([0., 0.], 1.), .1)
theta = points @ np.array([[0, +1], [-1, 0]])

mesh = meshio.Mesh(points, {'triangle': triangles})

meshio.write('theta.xdmf',
             meshio.Mesh(
                 mesh.points, mesh.cells,
                 {'theta': theta,
                  'embedded': np.pad(theta, ((0, 0), (0, 1)), 'constant')}))
```

This specifies a simple two-dimensional field twice, first as two-dimensional and then with a zero third component.  These are here plotted by ParaView in red and green, respectively.
![theta](https://user-images.githubusercontent.com/1588947/68728545-b643c600-061b-11ea-9152-765045ace5aa.png)

**Comment by tianyikillua** [comment]
Under ParaView 5.7, both can be visualized correctly by color maps. However only the embedded field can be used as an orientation array for arrows.

![2019-11-13 09_54_32-ParaView 5 7 0](https://user-images.githubusercontent.com/4027283/68747982-e2e7e580-05fb-11ea-809e-683ce962ca78.png)

**Comment by nschloe** [comment]
Sounds like a ParaView bug?

**Comment by gdmcbain** [comment]
Yes, I think so.  I've reported it at [paraview#19467](https://gitlab.kitware.com/paraview/paraview/issues/19467).

**Comment by gdmcbain** [comment]
Thanks @tianyikillua for testing a more recent ParaView; mine's 5.4.1, as packaged by Ubuntu 19.10.

**Comment by gdmcbain** [comment]
I note that VisIt 3.0.2 does do the right thing.

![visit0000](https://user-images.githubusercontent.com/1588947/68813274-6f140e80-06c9-11ea-90f5-51264ef9e8a0.png)

**Comment by gdmcbain** [comment]
Probably better not to attempt to fix this in meshio then.  Those wishing to write two-dimensional XDMF for ParaView before paraview#19467 is fixed can manually pad a zero third component, as above.

**Comment by nschloe** [comment]
> mine's 5.4.1, as packaged by Ubuntu 19.10.

Debian's/ubuntu's Paraview is hopelessly outdated. (We're working on getting it updated though.) I'm always using the binaries from the ParaView download page.
