### ISSUE TITLE
Converting ansys .msh file...

### ISSUE THREAD

**Issue by kuateric** [nschloe/meshio#512]
hello again,
i am quite new using meshio. I am struggling converting an ansys file to vtu. I looked everywhere but I could not find a documentation. The syntax: 
"meshio-convert input.msh output.vtu" doesn't work on windows and 
mesh=meshio.read("ansysmeshfile.msh") doesn't work neither. the ansys .msh file colludes with the gmsh file extension .msh
So what is the right syntax for this?

**Comment by keurfonluu** [comment]
What happens if you just call ``meshio-convert``? Did you install any Python distribution (e.g. Anaconda)?

If you are using Anaconda, you need to activate your environment beforehand:

```
conda activate 
```

**Comment by kuateric** [comment]
This is comes out. 
![image](https://user-images.githubusercontent.com/22998049/68795196-c1fdaf80-0650-11ea-9e72-e52f9c68fc93.png)

I am using python version 3.7.5 with pip inside.

**Comment by kuateric** [comment]
with the other syntax, I get this: 
![image](https://user-images.githubusercontent.com/22998049/68795378-1d2fa200-0651-11ea-80a7-5b5853647f1e.png)

**Comment by keurfonluu** [comment]
You are not supposed to call ``meshio-convert`` within Python. ``meshio-convert`` is a command that you can execute directly from a terminal (Windows console).

**Comment by kuateric** [comment]
even directly in the windows console, i get an error message:
![image](https://user-images.githubusercontent.com/22998049/68795501-667ff180-0651-11ea-96dc-0b0876a1b7cd.png)

**Comment by keurfonluu** [comment]
The issue is that ``msh`` is associated to Gmsh in ``meshio`` (because too many formats share this exact same file extension, and Gmsh is probably the most popular among them). So you have to explicitly define the file format as Ansys:

```python
mesh = meshio.read("ansysmeshfile.msh", file_format = "ansys")
```

As for the command line issue, I guess there is a PATH missing somewhere... I can't help further since I am using Anaconda.

**Comment by kuateric** [comment]
thank you, 
i just also discovered that meshio-convert is working. I had to update pip first. Now I get this 
![image](https://user-images.githubusercontent.com/22998049/68796054-7815c900-0652-11ea-8173-d984982ce84e.png)

**Comment by keurfonluu** [comment]
> thank you,
> i just also discovered that meshio-convert is working. I had to update pip first. Now I get this
> ![image](https://user-images.githubusercontent.com/22998049/68796054-7815c900-0652-11ea-8173-d984982ce84e.png)

```
meshio-convert input.msh output.vtu --input-format ansys-ascii
```

or ``ansys-binary`` if it is a binary file.

**Comment by kuateric** [comment]
Now both commands work fine. thank you
![image](https://user-images.githubusercontent.com/22998049/68796619-7bf61b00-0653-11ea-92e0-ae06638ca548.png)
We can close this issue. 
I will open a new issue for the occuring problem: mixed element mesh in ansys ;)

**Comment by asdddas02** [comment]
Hello. I had the same problem. But apparently, now it's not meshio-convert, but without "-": meshio convert. Welp
