### ISSUE TITLE
conda forge recipe / sdist issues

### ISSUE THREAD

**Issue by MuellerSeb** [nschloe/meshio#521]
Hey there,

I just created a conda forge recipe, to get an official conda package for meshio (there are already several, but best way should be one from conda-forge):

https://github.com/conda-forge/staged-recipes/pull/10194

@nschloe : If you agree with my proposal, you have to drop a comment in the linked PR to confirm you are willing to be listed as a maintainer there (maintaining should be rather simple).

Cheers,
Sebastian

**Comment by MuellerSeb** [comment]
Aaaaand something is missing in meshio. The LICENSE.txt is not distributed with the source-files.
You would need a ``MANIFEST.in`` file in the root directory with one line:

    include LICENSE.txt

Cheers

**Comment by MuellerSeb** [comment]
And another one: The tests included in the source distribution are not not complete.
The whole ``meshes`` folder and everything not starting with ``test*`` is missing.
Therefore another line in the ``MANIFEST.in`` is needed:

    recursive-include test *

Then, running the tests within the conda recipe would work.
At the moment I have to exclude testing, since the mentioned files are missing.

Cheers

**Comment by nschloe** [comment]
All fixed in 3.2.14.

**Comment by MuellerSeb** [comment]
I will update the recipe accordingly, after it is converted into a feedstock on conda-forge.

**Comment by MuellerSeb** [comment]
There it is:
https://anaconda.org/conda-forge/meshio
https://github.com/conda-forge/meshio-feedstock
