### ISSUE TITLE
write XDMF mutates cell['line'] if other cells present

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/meshio#539]
`write` to format XDMF mutates its argument `mesh`, changing the shape & content of `mesh.cells['line']`, but only if there are also other elements of `mesh.cells`; e. g.:

```python
from numpy import array

from meshio import Mesh, write

mwe =  Mesh(array([[0., 0., 0.],
                   [1., 0., 0.]]),
                   {'line': array([[0, 1]])})

print(mwe.cells['line'].shape)
write('mwe0.xdmf', mwe)
print(mwe.cells['line'].shape)
mwe.cells['vertex'] = array([[0]])
write('mwe1.xdmf', mwe)
print(mwe.cells['line'].shape)
```

The output:
```
(1, 2)
(1, 2)
(1, 3)
```

**Comment by gdmcbain** [comment]
No mutation occurs if the `'vertex'` element of `cells` is omitted.

This is because there's a clause in [`XdmfWriter.cells`](https://github.com/nschloe/meshio/blob/f9436947f1478f154db202e8fe57c5ec409f3594/meshio/_xdmf/main.py#L366-L425)

https://github.com/nschloe/meshio/blob/f9436947f1478f154db202e8fe57c5ec409f3594/meshio/_xdmf/main.py#L369

and under

https://github.com/nschloe/meshio/blob/f9436947f1478f154db202e8fe57c5ec409f3594/meshio/_xdmf/main.py#L390

we find

https://github.com/nschloe/meshio/blob/f9436947f1478f154db202e8fe57c5ec409f3594/meshio/_xdmf/main.py#L400-L403

This is a bit puzzling.  If this is necessary when there is more than one type of cell, why isn't it necessary when the only type is `'line'`?

**Comment by gdmcbain** [comment]
Maybe:
* use polylines for `cells['line']` regardless of `len(cells)`
* but don't mutate `cells['line']` because that might surprise the caller of `meshio.write`.

**Comment by dajuno** [comment]
Prepending 2 to lines breaks compatibility with the FEniCS MeshValueCollection reader for reading physical line labels from XDMF (https://fenicsproject.discourse.group/t/transitioning-from-mesh-xml-to-mesh-xdmf-from-dolfin-convert-to-meshio/412/54).
I don't know about other applications/XDMF readers, but is your recommendation to follow your decision here (i.e., to raise the issue with FEniCS devs)?

**Comment by gdmcbain** [comment]
Let's start a new issue.  This is not related to mutation.
