### ISSUE TITLE
Pick one CI provider

### ISSUE THREAD

**Issue by clbarnes** [nschloe/meshio#543]
Updating CI is much harder when there are multiple providers testing different versions. Would it be possible to make a choice and just have one which runs all supported versions? Or just use tox so that the config is independent of the CI.

**Comment by nschloe** [comment]
I'd love to use gh-actions, but there are still bugs preventing it. That's why CircleCI and gh-actions are still around. It's reported to GH.

**Comment by clbarnes** [comment]
I was more thinking about travis - can that config file go? It's testing against one EoL version and one version going EoL in a month.

**Comment by nschloe** [comment]
The travis config is ancient, I'll remove it. I prefer circleci over travis for their SSH functionality, and gh-actions for the fact that you don't have to have to rely on a second platform.
