### ISSUE TITLE
Accept buffers in "read", work around PathLike handling

### ISSUE THREAD

**Issue by clbarnes** [nschloe/meshio#548]
One issue with PathLikes which still plagues old python versions: stdlib's `open` doesn't accept them <_<

It would also be nice for read/write to accept arbitrary buffers (for HTTP responses, standard strings etc) - I'm working on a PR which will fix the above and implement that.

**Comment by nschloe** [comment]
> old python versions

How old?

**Comment by clbarnes** [comment]
3.5 and older https://docs.python.org/3/library/functions.html#open

**Comment by nschloe** [comment]
Ah, okay! (We're currently cutting off at 3.4.)

**Comment by nschloe** [comment]
Fixed via #551.
