### ISSUE TITLE
GMSH writer physical groups missing

### ISSUE THREAD

**Issue by gdolle** [nschloe/meshio#550]
It seems the writer does not write properly the physicals

I just write this small test

```py
import meshio

infile ="./test.msh"
outfile="./test2.msh"
mesh = meshio.read(infile)
meshio.write(outfile,mesh,"gmsh4-ascii")
```

Input mesh generated with GMSH 4.4.1:
https://gist.github.com/gdolle/7a7e78ef1412f3304db5dd70f40e2ea3#file-test-msh-L61-L62

The highlighted section in the link is missing in the exported mesh. 
I think it's related to "gmsh:physicals" in cell_data ? But the readme does not explain it.

This issue might be related to issue #536

**Comment by tjdodwell** [comment]
@nschloe sorry I didn't see this open issue.

**Comment by nschloe** [comment]
I'm looking at this issue now, but I can't quite figure out how to reproduce it. Could you create a minimal example that shows the behavior?

**Comment by gdolle** [comment]
@nschloe, it seems this old bug is fixed with the current version ( `gmsh4-ascii` writer format does not exist anymore in favor of `file_format="gmsh", binary=False`).

**Comment by nschloe** [comment]
Thanks for checking!
