### ISSUE TITLE
read Path XDMF

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/meshio#561]
Whereas #538 was closed by #546 so that `meshio.read` would accept `filename` of type `pathlib.Path` instead of only `str`, this doesn't seem to apply to XDMF.

```python
from pathlib import Path

from numpy import array

from meshio import Mesh, write, read

mwe =  Mesh(array([[0., 0., 0.],
                   [1., 0., 0.]]),
                   {'line': array([[0, 1]])})

fmts =  ['msh', 'mesh', 'e', 'med', 'xdmf']

for fmt in fmts:
    file_name = f'mwe.{fmt}'
    write(file_name, mwe)
    print(fmt, 'str', read(file_name).cells)
    print(fmt, 'Path', read(Path(file_name)).cells)
```

Output:
```
WARNING:root:Binary Gmsh needs c_size_t (got int64). Converting.
msh str {'line': array([[0, 1]])}
msh Path {'line': array([[0, 1]])}
mesh str {'line': array([[0, 1]])}
mesh Path {'line': array([[0, 1]])}
e str {'line': masked_array(data=[[0, 1]],
             mask=False,
       fill_value=999999,
            dtype=uint64)}
e Path {'line': masked_array(data=[[0, 1]],
             mask=False,
       fill_value=999999,
            dtype=uint64)}
med str {'line': array([[0, 1]], dtype=uint64)}
med Path {'line': array([[0, 1]], dtype=uint64)}
xdmf str {'line': array([[2, 0, 1]], dtype=uint64)}
Traceback (most recent call last):
  File "mwe.py", line 17, in <module>
    print(fmt, 'Path', read(Path(file_name)).cells)
  File "/home/geordie/.local/share/miniconda3/envs/scikit-fem/lib/python3.7/site-packages/meshio/_helpers.py", line 225, in read
    return format_to_reader[file_format].read(filename)
  File "/home/geordie/.local/share/miniconda3/envs/scikit-fem/lib/python3.7/site-packages/meshio/_xdmf/main.py", line 27, in read
    return XdmfReader(filename).read()
  File "/home/geordie/.local/share/miniconda3/envs/scikit-fem/lib/python3.7/site-packages/meshio/_xdmf/main.py", line 39, in read
    tree = ET.parse(self.filename, parser)
  File "src/lxml/etree.pyx", line 3435, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1863, in lxml.etree._parseDocument
TypeError: cannot parse from 'PosixPath'
```

**Comment by gdmcbain** [comment]
For a more minimal example, take [multitop.xdmf](https://github.com/nschloe/meshio/files/4014788/multitop.xdmf.txt) and try
```python
read('multitop.xdmf')
```
to get
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/geordie/src/meshio/meshio/_helpers.py", line 67, in read
    return reader_map[file_format](filename)
  File "/home/geordie/src/meshio/meshio/xdmf/main.py", line 27, in read
    return XdmfReader(filename).read()
  File "/home/geordie/src/meshio/meshio/xdmf/main.py", line 38, in read
    tree = ET.parse(self.filename, parser)
  File "src/lxml/etree.pyx", line 3469, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1862, in lxml.etree._parseDocument
TypeError: cannot parse from 'PosixPath'
```

I followed this in `pdb` to 

https://github.com/nschloe/meshio/blob/23fa4ef8862f8f45b4dfdf4da5f5cebc05e92b49/meshio/xdmf/main.py#L38

then stepped into that and it goes through some `pathlib` functions which seem innocuous then suddenly `ET.parse` raises the `TypeError`.  I guess `lxml` isn't Python so I can't step into it.

**Comment by gdmcbain** [comment]
The upstream issue might be https://bugs.launchpad.net/lxml/+bug/1820837 ‘ `etree.parse` should support `pathlib.Path` objects’.

**Comment by gdmcbain** [comment]
Given that XML is typically only used in XDMF for ‘light data’, is `lxml` really required?

**Comment by nschloe** [comment]
> Given that XML is typically only used in XDMF for ‘light data’, is lxml really required?

I had the exact same thought the other day. Well, not for light data. XML can feature inline data in which case it perhaps can be useful, but it probably doesn't warrant pulling in this large dependency. I'll remove it in a separate PR.

**Comment by nschloe** [comment]
Done now. #613

**Comment by gdmcbain** [comment]
Thanks!

> XML can feature inline data in which case it perhaps can be useful,

Yes, `Format="XML"` is very useful for debugging, MWEs, &c.; it's the main format used in the examples in [*XDMF Model and Format*](http://www.xdmf.org/index.php/XDMF_Model_and_Format).

I'll see whether [`xml.etree.ElementTree`](https://docs.python.org/3/library/xml.etree.elementtree.html) is enough.  It only [claims](https://docs.python.org/3/library/xml.etree.elementtree.html?highlight=xpath#xpath-support) 

>limited support for XPath expressions

and these are need to interpret multiple Grids #568, but it might suffice.

**Comment by gdmcbain** [comment]
#613 fixed the problem; one can now `read(Path('a.xdmf'))`.
