### ISSUE TITLE
meshio.read fails to read files buffer

### ISSUE THREAD

**Issue by LucaZampieri** [nschloe/meshio#580]
Hi! 

I was testing the file buffer capacity of `meshio.read()`  function, and as I understand, by using `open_file` it should handle buffers direclty. However, it fails to do so (or at least with all the STL and VTK that I tested).

I think it would be cool to read both filenames and buffers with `read()`

Here is the code to reproduce the issue:
```python
with open("sim_1.vtk", "rb") as f:
    mesh = meshio.read(f)
```
I get: 
```python
<ipython-input-23-afc0c0ba3a58> in <module>
      1 with open("sim_1.vtk", "rb") as f:
----> 2     mesh = meshio.read(f, file_format="vtk")

~/miniconda3/envs/tf_15/lib/python3.6/site-packages/meshio/_helpers.py in read(filename, file_format)
    152     """
    153     # https://stackoverflow.com/q/4843173/353337
--> 154     assert isinstance(filename, str)
    155 
    156     if not file_format:

AssertionError: 
```

**Comment by LucaZampieri** [comment]
Note that we can circumvent this problem by using directly the function: 
```python
with open("sim_1.vtk", "rb") as f:
    mesh = meshio._vtk.read_buffer(f)
``` 
But I guessed it was not expected behavior. 
I did not upload a file to reproduce the issue as I guessed any file would do (and have larges files at the moment), but if you need one, I can create a smaller one with no pb

**Comment by nschloe** [comment]
Ping @clbarnes.

**Comment by clbarnes** [comment]
Are you sure you're using the current version of meshio (3.3.0)? The line of code which is triggering the error doesn't exist in the latest release. You should get that if you install from PyPI; it looks like the conda-forge feedstock doesn't have the new version yet.

**Comment by LucaZampieri** [comment]
Indeed, my bad, sorry for ping!
