### ISSUE TITLE
f-string in WKT

### ISSUE THREAD

**Issue by keurfonluu** [nschloe/meshio#583]
The WKT format uses an f-string

```python
tin_pattern = rf"TIN\s*\((?:\s*{triangle_pattern}\s*,?)*\s*\)"
```

that has only been introduced in Python 3.6.

I don't know if it's necessary, but I guess the ``f`` could be removed to make it compatible with Python 3.4 and 3.5.

**Comment by nschloe** [comment]
Yep, I guess.

**Comment by clbarnes** [comment]
Not exactly necessary, just deeply preferred. Python 3.4 is EOL anyway, and it might be nice to change `python_requires` to reflect that.

There are shims elsewhere in the codebase for supporting 3.5, so I'll fix this one, registering my protests in so doing :stuck_out_tongue:

**Comment by clbarnes** [comment]
See #585
