### ISSUE TITLE
error when using voropy with python 3.5

### ISSUE THREAD

**Issue by skyboys22** [nschloe/meshio#59]
hi!

when using this command: `mesh, point_data, field_data = voropy.reader.read(filename)`
i'm getting this error 
```
mesh, point_data, field_data = voropy.reader.read(filename)

  File "C:\Users\imène\Anaconda3\lib\site-packages\voropy\reader.py", line 64, in read
    if len(cells_nodes[0]) == 3:

KeyError: 0`
```
type of file is VTU and version of python is 3.5

can u help me please ?

best regards

**Comment by nschloe** [comment]
I just added Python 3 compatibility for most mesh types.

Unfortunately, for VTK and friends, it's a little more complicated: The [VTK backend](http://www.vtk.org/) didn't support Python 3 for a long time, and now that VTK 7 is released, I'm waiting for Debian to include it. Either way, you'd only get Python 2 _or_ 3 with VTK 7.

If you must work with Python 3, I'd suggest to fall back to another mesh type for now. Once VTK 7 sees wider adoption, we can tackle this again.
