### ISSUE TITLE
converting xml to msh

### ISSUE THREAD

**Issue by APaganini** [nschloe/meshio#60]
Hello, I'm tying to convert the attached file with the command

`meshio-convert mesh.xml mesh.msh`
[mesh.xml.zip](https://github.com/nschloe/meshio/files/634706/mesh.xml.zip)

and I get the following error

```
File "src/lxml/lxml.etree.pyx", line 2452, in lxml.etree._Attrib.__getitem__ (src/lxml/lxml.etree.c:68665)
KeyError: 'z'
```

**Comment by nschloe** [comment]
Fix released. (Thanks for the report!)

**Comment by APaganini** [comment]
many thanks
