### ISSUE TITLE
KeyError in BDF reader

### ISSUE THREAD

**Issue by gtheler** [nschloe/meshio#603]
The BFD reader complains about `KeyError` when reading this Nastran file:

https://www.seamplex.com/tmp/AXI.bdf

```
$ meshio-info -i nastran AXI.bdf 
Traceback (most recent call last):
  File "/home/gtheler/.local/bin/meshio-info", line 11, in <module>
    load_entry_point('meshio==3.3.0', 'console_scripts', 'meshio-info')()
  File "/home/gtheler/.local/lib/python3.7/site-packages/meshio-3.3.0-py3.7.egg/meshio/_cli.py", line 111, in info
  File "/home/gtheler/.local/lib/python3.7/site-packages/meshio-3.3.0-py3.7.egg/meshio/_helpers.py", line 67, in read
  File "/home/gtheler/.local/lib/python3.7/site-packages/meshio-3.3.0-py3.7.egg/meshio/nastran/_nastran.py", line 47, in read
  File "/home/gtheler/.local/lib/python3.7/site-packages/meshio-3.3.0-py3.7.egg/meshio/nastran/_nastran.py", line 109, in read_buffer
  File "/home/gtheler/.local/lib/python3.7/site-packages/meshio-3.3.0-py3.7.egg/meshio/nastran/_nastran.py", line 109, in <listcomp>
KeyError: 165
```

I cannot figure out what is wrong in https://github.com/nschloe/meshio/blob/master/meshio/nastran/_nastran.py#L109

**Comment by tianyikillua** [comment]
I see. The grid block must be defined before cell definitions. If you move all grids before your elements it should work. I can provide a fix after vacation.

**Comment by gtheler** [comment]
It worked! Thanks. I do not know where this file came from as I do not use non-free software, but apparently a certain version of Nastran wrote it, so the cells might come before the nodes sometimes.

**Comment by tianyikillua** [comment]
@gtheler Could you please re-provide your mesh file? I'd like to test my patch. Thx!

**Comment by gtheler** [comment]
@tianyikillua the file has been restored, sorry for the inconvenience and thanks for the patch

**Comment by tianyikillua** [comment]
I obtain this...is this normal?

<img width="928" alt="Screenshot 2020-01-03 at 14 35 06" src="https://user-images.githubusercontent.com/4027283/71726282-eac34980-2e36-11ea-8379-a02a5176855c.png">

**Comment by gtheler** [comment]
I do not have Nastran myself, but it is not what is expected. In principle that file contains a reactangle meshed with structured triangles. Indeed, I do not know how to read the node data. For example, in this line... what should I parse?

```
GRID        1230       00.000375     0.0 0.00035       0
```

As far as I understand this is the definition of node 1230 and the columns are not blank-separated but appear to be size-defined (like it was customary in 1954 when FORTRAN-I was introduced).
It might be the chance that this file is faulty, but again, i received it from a collegue as I do not have non-free software.

**Comment by tianyikillua** [comment]
With the Nastran fixed format, [each chunk is 8 characters long](http://mscnastrannovice.blogspot.com/2013/10/how-to-decrypt-msc-nastran-bdf-or-dat.html). For this [node point](https://help.autodesk.com/view/NSTRN/2019/ENU/?guid=GUID-CCA11D25-0145-42A1-94DC-52226AC8FCD6), its coordinates are `(0.000375, 0, 0.000375)`.

The previous problem originates from a different node ordering for Nastran [`CTRIAX6`](https://help.autodesk.com/view/NSTRN/2019/ENU/?guid=GUID-3FC8F2ED-EEB2-4E07-869E-81E6942F0413) elements (which will be identified as the meshio quadratic triangle `triangle6` elements). Note that the [`CTRIA6`](https://help.autodesk.com/view/NSTRN/2019/ENU/?guid=GUID-956704D9-26C5-4FF8-85F2-955F383C5ECD) elements possess the same ordering as in VTK...

A patch is ready and will be submitted soon.

<img width="923" alt="Screenshot 2020-01-03 at 18 58 26" src="https://user-images.githubusercontent.com/4027283/71740119-ad24e780-2e5b-11ea-9f32-4baf7cdac502.png">
