### ISSUE TITLE
.k (ls-dyna) and .unv format not available !

### ISSUE THREAD

**Issue by NLeMaout** [nschloe/meshio#607]
Hello, 
Thanks for great jobs.
It's not really an issue but I don't know how to post it corectly here....
These both familiar format is not management by module. Could you include it for next update ?
Thank you !
Nicolas LM

**Comment by nschloe** [comment]
Hi Nicolas, thanks for the bringing this to attention.

Someone else already requested unv support (https://github.com/nschloe/meshio/issues/466), but ls-dyna is something I had never heard of before.

**Comment by shannonjryan** [comment]
> 
> 
> Hi Nicolas, thanks for the bringing this to attention.
> 
> Someone else already requested unv support (#466), but ls-dyna is something I had never heard of before.

LS-DYNA is an explicit structural solver from ANSYS (http://www.lstc.com/products/ls-dyna OR https://www.ansys.com/products/structures/ansys-ls-dyna) but it has a different text-based format for geometry and meshing files.

**Comment by nschloe** [comment]
To implement, I need a format specification or at least a number of LS-Dyna files so I can guess my way through. Feel free to reopen with such.

**Comment by yurynovozhilov** [comment]
Hi Niko!

LS-DYNA has a mesh format similar to Abaqus and Nastran. In the official documentation, the model format is described under "DESCRIPTION OF KEYWORD INPUT". Nodes are described in "*NODE" and elements in "*ELEMENT". Link to official documentation. 
https://ftp.lstc.com/anonymous/outgoing/web/ls-dyna_manuals/R15/LS-DYNA_Manual_Volume_I_R15.pdf

A large number of examples of models are available at dynaexamples.com.

And here is the documentation and source code for Ansys' PyPrimeMesh bibilot method. This method allows writing meshes in LS-DYNA format
https://prime.docs.pyansys.com/version/dev/api/_autosummary/ansys.meshing.prime.FileIO.export_lsdyna_keyword_file.html
https://github.com/ansys/pyprimemesh/

-- 
All best
Yury

**Comment by akaszynski** [comment]
I've created a basic reader for *.k files here: https://github.com/akaszynski/lsdyna-mesh-reader

Reads `*NODE` and `*ELEMENT` sections.
