### ISSUE TITLE
dxf2vtk.py #enhancement

### ISSUE THREAD

**Issue by ahinoamp** [nschloe/meshio#625]
Hi,

Thank you so much for this wonderful package. 
I'm using it in my workflow and very grateful for its existence.

I'm not sure how high the demand is for dxf converters, but there is certainly no easily found dxf converter online. Perhaps it would be a nice enhancement to your package. It can be done by uniting forces with the also excellent ezdxf package (which has a reader but no converter). Here is some initial thought:

```
import numpy as np
import meshio
import ezdxf
import pandas as pd

filename = 'input.dxf'
doc = ezdxf.readfile(filename)
msp = doc.modelspace()
faces = msp.query('3DFACE')
num3Dfaces=len(faces)
points = np.zeros((num3Dfaces*3, 3))
cells = np.zeros((num3Dfaces, 3),dtype ='int')
cell_data=[]

i=0
faceCounter=0
name = []
for e in faces:
    points[i, 0] = e.dxf.vtx0[0]
    points[i, 1] = e.dxf.vtx0[1]
    points[i, 2] = e.dxf.vtx0[2]

    points[i+1, 0] = e.dxf.vtx1[0]
    points[i+1, 1] = e.dxf.vtx1[1]
    points[i+1, 2] = e.dxf.vtx1[2]

    points[i+2, 0] = e.dxf.vtx2[0]
    points[i+2, 1] = e.dxf.vtx2[1]
    points[i+2, 2] = e.dxf.vtx2[2]

    cells[faceCounter,:]= [i, i+1, i+2]
    cell_data.append(e.dxf.layer)
    i=i+3
    faceCounter=faceCounter+1

meshio.write_points_cells(
    "foo.vtk",
    points,
    cells={'triangle':cells}   
    )
```

Happy new year,

Noe

**Comment by nschloe** [comment]
DXF is not a mesh format and hence not suitable for meshio.

**Comment by brunorpinho** [comment]
@nschloe there are DXF entities that represents meshes. What @ahinoamp script is doing is extracting one of those entities ('3DFACE') from the DXF file and dumping into meshio. I recommend reading the [DXF Reference](https://images.autodesk.com/adsk/files/autocad_2012_pdf_dxf-reference_enu.pdf) document by AutoDesk and learning about those entities (3DFACE, SURFACE, MESH, POLYFACE MESH, 3D SOLID - this might be able to be converted to an unstructured grid).

I understand DXF has a lot of versions and all that is quite messy to deal with, but **meshio** could provide a way to extract only those entities. DXFs are used as a "mesh format" on a couple industries like mining.

**Comment by hjia1005** [comment]
@ahinoamp Your code helps a lot. It helps convert all our mine pits in the dxf format to vtk. Thanks.
