### ISSUE TITLE
cells dict -> list of tuple/namedtuple/dataclasses?

### ISSUE THREAD

**Issue by nschloe** [nschloe/meshio#629]
Another idea for 4.0:

We could transform the cells (and cell data) from a dict to a list of tuples, namedtuples, or dataclasses ([as has been suggested before](https://github.com/nschloe/meshio/issues/615#issuecomment-570833763)), having the attributes `type` (e.g., `triangle6`) and `data` (a numpy array). With this, we could preserve cell ordering (@MuellerSeb is going to like that) and better represent data structures like Exodus's regions.

Opinions, please. @tianyikillua

**Comment by gdmcbain** [comment]
dicts [preserve order](https://docs.python.org/3/library/stdtypes.html#dict.popitem) from Python 3.7. For 3.6 there's [OrderedDict](https://docs.python.org/3/library/collections.html?highlight=ordereddict#collections.OrderedDict).

**Comment by MuellerSeb** [comment]
> dicts [preserve order](https://docs.python.org/3/library/stdtypes.html#dict.popitem) from Python 3.7. For 3.6 there's [OrderedDict](https://docs.python.org/3/library/collections.html?highlight=ordereddict#collections.OrderedDict).

This doesn't matter, since the original order doesn't have to be sorted by cell-types.

**Comment by gdmcbain** [comment]
If one knows the type of cell one's looking for but not what order it was in the input mesh one's not going to be able to index a list, one's going to have to iterate through it till the type's found?

**Comment by gdmcbain** [comment]
Keys in a dict are unique.  Would imultiple tems in the list have the same cell-type?

**Comment by nschloe** [comment]
Sure, that's possible with a list:
```python
[("triangle", ...), ("quad", ...), ("triangle", ...), ("triangle", ...)]
```

**Comment by gdmcbain** [comment]
I see, so should one want all the tetrahedra, say, one filters rather than iterates. Interesting. Alongside

> better represent data structures like Exodus's regions

are MSH4.1 and XDMF with multiple Grids #568 .

**Comment by nschloe** [comment]
> I see, so should one want all the tetrahedra, say, one filters rather than iterates.

Well, with dicts you don't really iterate, you just pick `cells["tetra"]`. I suppose typically, if there is are not regions or such, there will be only one entry with  `tetra` type. You'll have to filter for it, though.

**Comment by gdmcbain** [comment]
> Well, with dicts you don't really iterate, you just pick cells["tetra"].

No, yes, that's right. I meant for the proposed list, not the encumbent dict.

I guess it would be easy enough to write accessors, if the iteratoing or filtering irked. Analogous to the `.find` and `.findall ` methods for XPath in "xml. street.ElementTree` used recently. 

By iterating i  mean
```
for cell_type, v in cells:
    if cell_type;== cell_type_of_interest::
        cells_of_interest = v
        break
```

**Comment by gdmcbain** [comment]
This proposal is growing on me. Do you suppose it would be a lot of work? 

I suppose some of the transitional pain could be alleviated by (temporarily) still alternatively accepting a dict for cells in the Mesh constructor as this is easily converted to the new form by a list-comprehension.

What would `cell_data` look like?

**Comment by nschloe** [comment]
> Do you suppose it would be a lot of work?

I started fiddling around and it turns out to be quite easy to do. Removing the `.items()` in the cell loop is much of it.

> I suppose some of the transitional pain could be alleviated by (temporarily) still alternatively accepting a dict for cells in the Mesh constructor as this is easily converted to the new form by a list-comprehension.

Good idea.

> What would cell_data look like?

The same way, I suppose, such that you can `zip(cells, cell_data["a"])` to loop over it.

**Comment by keurfonluu** [comment]
I don't know, I like the way it is now with regularly shaped numpy arrays. It is easy to use when we do vectorized/broadcast calculations since the arrays are directly available without having to filter anything.

**Comment by gdmcbain** [comment]
> I suppse a dict of numpy arrays, such that you can zip(cells, cell_data["a"]) to loop over it.

O. K., sounds good.  That would fulfil #183.

So what happens when the `cell_data["a"]` is only defined on some blocks?  Just put `None`?  That might be O. K.  So the type of `cell_data` would be `Dict[str, List[str, Union[None, numpy.ndarray]]]`?

(I'm yet to understand Monday's [comment](https://github.com/nschloe/meshio/issues/615#issuecomment-571058388) of @MuellerSeb in #615 about ‘one numpy array per cell-data would be the ideal case in my opinion’.  I didn't understand how that works when different cells have different dimension or just more generally data is only defined on some blocks.  Would that opinion change were the present proposal accepted?)

**Comment by gdmcbain** [comment]
> I like the way it is now with regularly shaped numpy arrays.

I'm sure the plan is still to have rectangular arrays.  Each item in the `cells` list would have one rectangular array.

**Comment by nschloe** [comment]
> I'm sure the plan is still to have rectangular arrays. Each item in the cells list would have one rectangular array.

Indeed. Basically what was
```
cells = {"triangle": numpy.array([[...]]), "quad": numpy.array([[...]]}
```
before will be
```
cells = [("triangle", numpy.array([[...]])), ("quad", numpy.array([[...]])]
```
The key advantage of the latter structure is that you can have multiple entries with the same cell_type.

**Comment by nschloe** [comment]
I've added a PR at #631 for you guys to take a look.

**Comment by tianyikillua** [comment]
I've been quite happy using `cells` as a `dict`...Of course I can see this change can be indeed useful for cases when cell ordering needs to be preserved.

As @gdmcbain has noted, the conversion from the old `dict` to the new structure is trivial. I suggest we provide a utility function that converts the new structure to the old `dict`. In the MED format for example, the cells are always organized by cell types (no redundancy), so this utility function is needed when we want to write a MED mesh with the new `cells` structure.

**Comment by nschloe** [comment]
The more I think about it, the more I like my own idea. Hue hue. I think having a list of blocks better represents the data in the file. For formats that support blocking, we can even preserve this across reads/writes.

It's of course convenient to be able to write `cells["triangles"]`, but perhaps we can suggest a nifty one-liner in the readme to transform the data into a dict. Not sure if this is necessary at all.

**Comment by nschloe** [comment]
>  I suggest we provide a utility function that converts the new structure to the old dict.

There now is a `mesh.cells_dict` property that returns the old-style dict.

**Comment by tianyikillua** [comment]
> > I suggest we provide a utility function that converts the new structure to the old dict.
> 
> There now is a `mesh.cells_dict` property that returns the old-style dict.

Good! It seems it only considers the trivial case where a same cell type doesn't appear several times in the cells list.

**Comment by nschloe** [comment]
Indeed. I think that's by far the most common thing. Would you agree?
(I could also add a something to cover all cases, can't be too hard.)

**Comment by tianyikillua** [comment]
> Indeed. I think that's by far the most common thing. Would you agree?
> (I could also add a something to cover all cases, can't be too hard.)

Yes no hurries!
