### ISSUE TITLE
inconsistent cell type names

### ISSUE THREAD

**Issue by nschloe** [nschloe/meshio#630]
The naming of cell types in meshio is inconsistent. Perhaps we can fix that now.

Abbreviated:
`quad*`, `tetra*`,

Not abbreviated:
all the rest

Needless underscores:
`hexa_prism`, `penta_prism`

_Edit:_ As pointed out by @tianyikillua, this pretty much follows [the VTK convention](https://vtk.org/doc/nightly/html/vtkCellType_8h_source.html).

Should we use abbreviations throughout or the full form? Vote now. (Heart :heart:  for abbreviations, rocket :rocket:  for full form. Eyes :eyes: : Keep what we have)

**Comment by tianyikillua** [comment]
The current cell type names are not completely insane since they follow the [VTK convention](https://vtk.org/doc/nightly/html/vtkCellType_8h_source.html) right?

**Comment by nschloe** [comment]
Ah, indeed. :smile: 

It's still inconsistent though. I'll add another voting option for keeping the naming.

**Comment by gdmcbain** [comment]
Right, I wondered whether there might be some existing convention that might be followed (VTK, EXODUS, femtable.org). So the current strings are based on VTK. That makes sense, or rather doesn't as it's inconsistent, as you say.

An orthogonal idea: recording information in strings is not Pythonic. Why not use objects for cell-types? Constant (or at least predefined) instances of a `class CellTyoe`. That way type-checkers can make more sense of code, IDEs can provide tab-completion and hover-documentation, and relevant data can be flexibly extensibly carried by the thing indicating the cell type (dimension, number of nodes, representation in other systems, ASCII-art depictions of canonical orientation, …).

As for the names of the predefined cell-types, I'll suggest adding femtable to the list of candidates but won't vote just yet..

**Comment by tianyikillua** [comment]
But the femtable is for finite elements in the sense of [Ciarlet](https://math.stackexchange.com/questions/2682563/definition-of-finite-elements-ciarlet)...in meshio we are only interested in their geometrical shape.

**Comment by gdmcbain** [comment]
Good point. Thank you, and for the reference.

But are we indeed only interested in

**Comment by tianyikillua** [comment]
...Yes...but if we pursue further in this direction
1. we will be reinventing a new finite element data format...
2. the project name should be changed! It is currently **mesh**-io and not **fem**-io.

Note however that currently
- isoparametric fields (P1, P2, ...) are naturally supported since the number of nodes (including mid-nodes) correspond to that of the DoF's (scalar functions), as a `point_data`. Super- and sub-parametric fields no.
- DG0 (constant per cell) and DG1 (independently defined at the nodes of each cell) fields are also supported.

**Comment by gdmcbain** [comment]
Very interesting. Thank you. 

But then is the conclusion that data (defined on a finite element space) should stored separately from the mesh, outside meshio?

**Comment by tianyikillua** [comment]
A mesh data is not necessarily a finite element data (the reverse is, on the other hand, true). We only provide the values at these discrete points (for point data), and let the users to decide how to interpret them and how to interpolate them.

**Comment by gdmcbain** [comment]
> DG1 (independently defined at the nodes of each cell) fields are also supported

How's that?  Cell data of shape (number of cells, number of nodes per cell)?

**Comment by tianyikillua** [comment]
Yes that's correct.

**Comment by gdmcbain** [comment]
On reflection, the femtable names aren't very readable anyway; I'll withdraw that suggestion.  Also the table doesn't cover the vertex or the degenerate cells (wedges & pyramids).

**Comment by nschloe** [comment]
Okay, there is little interest and no actual consensus on the names here, so let's leave them as they are for now and remember our VTK heritage. :ghost:

Perhaps we'll come back to this at some point in the future.

**Comment by gdmcbain** [comment]
Agreed.

A thought for that future, following the idea that ‘recording information in strings is not Pythonic’: [`class enum.Enum`](https://docs.python.org/3/library/enum.html#enum.Enum).

**Comment by flutefreak7** [comment]
I just noticed that if I open an XDMF with pyramid elements, the ansys writer throws an error because it's expecting "pyra" instead of "pyramid." Not sure where the fix should be, but I fixed it by adding "pyramid" to the ansys writer cell type dict.

**Comment by nschloe** [comment]
@flutefreak7 Fixed in #1002.
