### ISSUE TITLE
Implement AVS-UCD mesh file reader and writer

### ISSUE THREAD

**Issue by daniellivingston** [nschloe/meshio#632]
[AVS-UCD](https://dav.lbl.gov/archive/NERSC/Software/express/help6.1/help/reference/dvmac/UCD_Form.htm) is a very simple ASCII mesh file format that's used often in United States-based national labs. 

I would be happy to write a reader and writer if there are no plans to do so, as meshio support for this format would benefit my workflow quite a bit.

**Comment by nschloe** [comment]
> I would be happy to write a reader and writer

Sure, go right ahead. Let me know if you need any help.

**Comment by keurfonluu** [comment]
I was planning to implement it next week (end of my parental leave) as I am interested in using LaGrit. I'll look into that.

**Comment by daniellivingston** [comment]
@keurfonluu Awesome, I'm one of the devs on LaGriT. I'd be happy to team up on this.

**Comment by keurfonluu** [comment]
I've pushed the reader to my fork (https://github.com/keurfonluu/meshio/tree/avs). Would you mind taking a look at it @daniellivingston ?

It works for all the samples I've been able to find/produce, but I am far from being an expert with LaGriT.

There is also a few things I don't understand such as what is ``num_model_data`` and what to do with the first line of ``node_data`` and ``cell_data`` (e.g. ``002 1 1``).

**Comment by nschloe** [comment]
Fixed by #633.
