### ISSUE TITLE
Question regarding writing .geo file

### ISSUE THREAD

**Issue by awa5114** [nschloe/meshio#637]
I don't know if this belongs in the issue tracker, so please feel free to place this question elsewhere if this is not the right place.

I would like to ask whether meshio can write .geo files which don't yet contain a mesh. I would like to do this to check whether my geometry is correct  before actually generating the mesh...

Thanks.

**Comment by nschloe** [comment]
> I would like to ask whether meshio can write .geo files which don't yet contain a mesh

No, meshio is just for meshes, not geometries.

**Comment by awa5114** [comment]
@nschloe Thanks for your quick response. I am currently experimenting with this example from the `fipy` library:

https://www.ctcms.nist.gov/fipy/examples/diffusion/generated/examples.diffusion.circle.html#module-examples.diffusion.circle

As you can see they are tediously writing out a multi-line string to depict what I think is the content of a `.geo` file in gmsh. I'd like to see whether I can circumvent this by using `pygmsh`, `meshio` or `gmsh` (the gmesh API) to generate the geometry using code, return it as a string and feed this string into `fipy`. 

This is why I ended up here. Do you know whether what I am trying to do is at all possible? If so would you please point me towards the right place?

Thanks!

**Comment by nschloe** [comment]
You can try pygmsh with `geo.get_code()`.

**Comment by awa5114** [comment]
I was able to find that. Thanks for your help.
