### ISSUE TITLE
Write vtk file directly from vtk/pyvista object

### ISSUE THREAD

**Issue by awa5114** [nschloe/meshio#640]
I am trying to figure out why a mesh generated using `fipy` will not plot using `pyvista`. To do this I would like to write it out into a vtk ASCII file, inspect the file and see whether it renders in Paraview. I could not however find an efficient way of getting `meshio` to write out the vtk file. Here 's some code which can replicate the mesh:

```
from fipy import CylindricalGrid2D
import pyvista
import meshio

mesh = CylindricalGrid2D(dr=0.1, dz=0.25, nr=3, nz=0.1)
ugrid= pyvista.UnstructuredGrid(mesh.VTKCellDataSet._vtk_obj)
```

I tried implementing `pyvistas` `save_meshio` method but got a `KeyError` (https://github.com/pyvista/pyvista-support/issues/108). Is there a more direct way using meshio to write out the file? Perhaps without using `pyvista` alltogether?

**Comment by nschloe** [comment]
You can build a meshio mesh from the point coordinates and the cell connectivity, e.g.,
```
meshio.write_points_cells(point_coords, {"tetra": conn})
```
It seems that the point coordinates are in `mesh.vertexCoords`.  Not sure about the connectivity.

**Comment by awa5114** [comment]
will this work for cell type 41

**Comment by nschloe** [comment]
That's a VTK_CONVEX_POINT_SET, right?

**Comment by awa5114** [comment]
correct

**Comment by nschloe** [comment]
No, there is no support for this in meshio.
