### ISSUE TITLE
OBJ output no writing cell

### ISSUE THREAD

**Issue by MoiseRousseau** [nschloe/meshio#647]
Hi ! 
I'm am trying to convert from STL to OBJ some files. Reading the STL is successful (thank for the fix). The OBJ writing did not return error, but the output file include only the vertices, and not the cells. I attached an example STL I try to convert ([boundary.txt](https://github.com/nschloe/meshio/files/4103978/boundary.txt) - extension renamed in '.txt'). 

Here is my terminal output:
```
Python 3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import meshio
>>> f = meshio.read("boundary.txt", file_format="stl")
>>> f
<meshio mesh object>
  Number of points: 221
  Number of cells:
    triangle: 438
>>> f.write("boundary.obj")
>>> meshio.read("boundary.obj")
<meshio mesh object>
  Number of points: 221
  No cells.
>>> 
```

The error seems to come from the following test line 81 in file `meshio/obj/_obj.py` :
`if "triangle" in mesh.cells:`
In my case, this test return false :
```
>>> "triangle" in f.cells
False
>>>
```

Please let me know if you need more information on the problem.
Moise

**Comment by nschloe** [comment]
What version are you on?

**Comment by MoiseRousseau** [comment]
The latest (pushed 5 hours ago):

nschloe Merge pull request #645 from gdmcbain/644-cell-data-list

**Comment by nschloe** [comment]
Okay, yes, looks like a bug.
