### ISSUE TITLE
read OBJ groups

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/meshio#676]
The Wavefront .obj file format supports a grouping of elements via the syntax
```
g group_name
```

This syntax is described in:
* https://en.wikipedia.org/wiki/Wavefront_.obj_file#Referencing_materials
* https://www.cs.utah.edu/~boulos/cs3505/obj_spec.pdf (p. 40–47)

Example: [tet.obj.txt](https://github.com/nschloe/meshio/files/4179126/tet.obj.txt):
```
v 0 0 0
v 1 0 0
v 0 1 0
v 0 0 1
g oblique
f 2 3 4
g x-normal
f 1 3 2
g y-normal
f 1 2 4
g z-normal
f 1 4 3
```

The grouping is recognized by ParaView 5.6.0 which creates a cell-based field GroupIds with values 0, 1, 2, 3.  This can be used to colour the faces in ParaView or saved to XDMF: [tet.xmf.txt](https://github.com/nschloe/meshio/files/4179141/tet.xmf.txt), which contains
```xml
      <Attribute Name="GroupIds" Active="1" AttributeType="None" Center="Cell">
        <DataItem Dimensions="4" NumberType="Float" Precision="4" Format="XML">
0 1 2 3
</DataItem>
      </Attribute>
```

ParaView doesn't seem to read the names of the groups.

The grouping feature appears in a file used in some of OpenFOAM's tutorials: [${FOAM_TUTORIALS}/resources/geometry/motorBike.obj.gz](https://github.com/OpenFOAM/OpenFOAM-7/blob/master/tutorials/resources/geometry/motorBike.obj.gz).  I'm yet to ascertain whether OpenFOAM makes use of the groups or names.

[`meshio.obj._obj.read_buffer`](https://github.com/nschloe/meshio/blob/master/meshio/obj/_obj.py#L22) currently ignores lines beginning with a `g` along with all other lines not beginning with a `v` or `f`.

**Comment by nschloe** [comment]
The reader splits those up into blocks now, not remembering the tags. Perhaps that's already good enough.

**Comment by gdmcbain** [comment]
Hey thanks, you beat me to it.  I'll try this out and then close.

**Comment by gdmcbain** [comment]
This is correct.  I'll close now and open a new issue should the need arise to:
* read the names of the groups
* write the groups, with names.

Briefly thinking ahead to how to store the names of groups, it's like `cell_data` but the data is constant per item of `cells` rather than different for each cell.  It seems to me that that kind of data is likely to arise fairly often with the new data structure for `Mesh.cells: List[Cells]`; viz. whenever the cells have been grouped into blocks for a reason (unlike nschloe/pygmsh#301).  Thus the group-names should be stored either:
* as `List[str]`, of the same len as `cells`, but where?
* as  `numpy.ndarray` of `dtype=int` and `shape==(sum(len(c[1]) for c in mesh.cells),)`, but then why bother breaking the cells into blocks?

But I'll defer answering that till it's needed.
