### ISSUE TITLE
Ubuntu 18.04, Meshio and Python

### ISSUE THREAD

**Issue by DaleKramer** [nschloe/meshio#689]
I believe that I am having trouble getting meshio to use Python 3.8 vs the Python 2.7 which is also in my Ubuntu 18.04 environment.

But possibly there is another problem.

Here we can see that my 'meshio-convert' command fails (I have not been able to track down what those errors mean) and there seems to be some confusion as to what Python version Meshio might be accessing, since 'python --version' reports 3.8 while 'pytest' reports 2.7 (sorry about using an image here, that text does not paste well here):
![image](https://user-images.githubusercontent.com/7749699/74446961-9d2ef900-4e46-11ea-92f2-c89619c6a0ef.png)

[Here is the Mentor.h5m file that was downloaded from SimScale](http://www.galaxyapps.us/Mentor.zip) which is the above input file that I tried to convert (sorry it is so big).

As another example, [here is a very small .h5m file downloaded from SimScale](http://www.galaxyapps.us/95997vTET.zip) which has similar, but interestingly 'not the same' conversion issues:
![image](https://user-images.githubusercontent.com/7749699/74450144-a2427700-4e4b-11ea-9d3f-5d91affd338f.png)

**Comment by nschloe** [comment]
The read for the second file has been fixed now. The first file simply isn't valid H5M (or HDF5 for that matter); it's broken.
