### ISSUE TITLE
Add lxml to install_requires in setup.py

### ISSUE THREAD

**Issue by bonh** [nschloe/meshio#69]
If converting from gmsh to dolfin-xml works without a running installation of dolfin, the required package lxml should be added to install_requires in setup.py.

**Comment by nschloe** [comment]
Not sure about this one. After all, `lxml` is an _optional_ dependency that's necessary only if you want to convert from/to Dolfin XML. The keyword `extras_require` is probably what we're looking for here.

**Comment by nschloe** [comment]
`lxml` is now in `extras_require`.
