### ISSUE TITLE
Combine Abaqus and PERMAS formats

### ISSUE THREAD

**Issue by tianyikillua** [nschloe/meshio#696]
It seems to me that these two formats are simply isomorphic...
- Keywords in Abaqus begin with `*`, while in PERMAS `$`
- Comments: `**` vs `!`
- Point coordinates: `*NODES` vs `$COOR`
- Element names...

- https://github.com/nschloe/meshio/blob/master/meshio/permas/_permas.py
- https://github.com/nschloe/meshio/blob/master/meshio/abaqus/_abaqus.py

Since the current Abaqus implementation is (slightly) more efficient (seek and tell are extremely costly), maybe we can merge PERMAS into Abaqus.

**Comment by nschloe** [comment]
Well spotted! @nilswagner Is this a fact?

**Comment by nschloe** [comment]
@nilswagner Ping.

**Comment by nilswagner** [comment]
! corresponds to **
$ELEMENT corresponds to *ELEMENT
$COOR corresponds to *NODE

Element definitions can take place over several lines in PERMAS. This is currently not considered by the parser.
The first character of the continuation line is a &, e.g.

      $ELEMENT TYPE = HEXE27
              737    1000010    1001943    1000012    1001919    1004157    1001941    1000001    1001918    1000009    1001944    1004159    1001947    1004162
         &           1005965    1004160    1001920    1004161    1001942    1000015    1001952    1000018    1001953    1004158    1001958    1000016    1001956
         &           1000017

**Comment by nilswagner** [comment]
*ELEMENT, TYPE=C3D27, ELSET=P_BEAM
       737,   1000010,   1000012,   1000009,   1000001,   1000015,   1000018,   1000017,   1000016,
   1001943,   1001941,   1001918,   1001919,   1001952,   1001958,   1001956,   1001953,   1001944,
   1001947,   1001942,   1001920,   1005965,   1004157,   1004158,   1004159,   1004160,   1004161,
   1004162

**Comment by tianyikillua** [comment]
Ok, so it seems indeed that these two formats are simply isomorphic...

Cells defined by multiple lines are well treated by the current Abaqus parser (https://github.com/nschloe/meshio/pull/436).

@nilswagner Do you have a more informative documentation for the PERMAS format (other than https://www.intes.de/)?
