### ISSUE TITLE
read cell_sets from Gmsh's MSH 4.1

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/meshio#698]
Arising from discussions with @tianyikillua and others in #619 ([2020-01-07](https://github.com/nschloe/meshio/issues/619#issuecomment-571295114))

> Maybe I need a quick catch up here, but what are the reasons why we can not represent sets in MSH4 by&hellip;

and #691 ([2020-02-15](https://github.com/nschloe/meshio/pull/691#issuecomment-586359707))

>  …the MSH4 format. Maybe @gdmcbain can take the relay for this? As I understand we'll create a cell_set and not a standard cell_tag since cells can have to different tags.

The idea is to better capture the semantics of MSH 4.1, in particular its improvements over MSH 2.2 rather than basically project it back on the latter as the current meshio reader does. 

It is hoped that this will enable the fixing of a number of outstanding issues related to reading MSH 4.1.

* #265 
* #493 (&rsquo;I'm trying to convert an Abaqus input to a gmsh file format but I am unable to get the element sets (Elset) and node sets (Nset) transferred into physical groups in the gmsh format. I kinda need these for prescribing my boundary conditions.&rsquo;)
* #524 
* #536 
* #614

**Comment by tianyikillua** [comment]
After reading http://gmsh.info/doc/texinfo/gmsh.html I still don't see how physical tags are now implemented in the 4 version...

**Comment by gdmcbain** [comment]
Gmsh $Elements (meshio cells) are defined in blocks. Each block consists of a single type of element and is assigned to a single Gmsh 'entity'. The latter concept does remain mysterious, yes, but the path to physical tags is clear. Each Gmsh entity, defined in the $Entities section, is assigned zero or more physical tags. 

So: cell is in a block, block is in an entity, entity has 0+ physical tags.

Gmsh's element blocks don't map all that well to the meshio.Cells items of meshio.Mesh.cells.
