### ISSUE TITLE
ENH: including int cell_data in cell_sets_dict

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/meshio#715]
Following the excellent progress under #619 on unifying cell tags #691 and more streamlined handling of cell data #704, I'm wondering whether the next step will be to attempt to begin unifying the two broad approaches to tagged subsets of elements #290:

I. int-valued cell_data (e.g. MEDIT, Gmsh's MSH 2.2)
II. cell_sets (e.g. Gmsh's MSH 4.1)

As has been discussed a number of times, this is easier one way than the other: it's pretty straightforward to take a tag function cells → int and construct a set for each int in the codomain, the elements of which are indices into the array of `Cells.data`.  The other way is trickier since cells can belong to multiple cell_sets; this necessitates inventing new tags for the intersections.  (Doable though; I think @tianyikillua has done something on this for MED?)

So I'm thinking about the easier one first, I → II.

Use case: say I have a finite element code that wants to read a mesh from a file in order to construct a finite element mesh with defined subdomains (possibly overlapping).  To not impose a narrow choice of file format on the user, the code makes use of `meshio.read`.  (Concrete example: [`skfem.io.meshio.from_meshio`](https://github.com/kinnala/scikit-fem/blob/61424c55508954e71302c78dc5e6637883f68a27/skfem/io/meshio.py#L21), currently only working for meshio<4.)  Then there's a choice: if the `meshio.Mesh` has a `.cell_sets` attribute, we can look in `.cell_sets_dict` and the job's done, but so far that's only for two formats, Gmsh's MSH 4.1 and Abaqus (and I haven't tried the latter); if `.cell_sets` is empty (e.g. `meshio.read` MSH 2.2), the subdomains are implicit in the int-valued `.cell_data` (e.g. `.cell_data_dict["gmsh:physical"]["hexahedron"]`).

Thus the question: should mining `.cell_data` for ints be left to the downstream application, or is this of general enough interest that it could be handled centrally by meshio? Will something like this be required of meshio if it's asked to convert from a format only supporting a type I `.cell_data` representation of tagged subsets of cells to a format supporting type II `.cell_sets`?
 
Would having all the int-valued cell_data available via the property `.cell_sets_dict` also alleviate some of the concerns expressed, e.g. by @tianyikillua, in #704 ‘that there may exist several int dtyped point or cell data in the mesh’?

**Comment by nschloe** [comment]
> Thus the question: should mining .cell_data for ints be left to the downstream application, or is this of general enough interest that it could be handled centrally by meshio?

I'm thinking downstream. If a format only has int-functions, and the user wants to have a set, then it's up to her. It's not meshio's job to do these kind of conversions. Perhaps we can add a conversion method, but that's something the user will have to call explicitly.

**Comment by gdmcbain** [comment]
> Perhaps we can add a conversion method, but that's something the user will have to call explicitly.

Like an enhanced `.cell_sets_dict` property?   I think the value returned would have the same structure, just more of it.  I'll prepare such a method (probably method rather than property, in case options are required later) for consideration.  Basically I have to write the code anyway, I'm just wondering whether it makes more sense to share it centrally in meshio.

> It's not meshio's job to do these kind of conversions. 

Isn't this expected of `meshio-convert --input-format medit --output-format gmsh4-binary`?

**Comment by nschloe** [comment]
> Like an enhanced .cell_sets_dict property? 

I'm envisioning a separate function, like `meshio.convert_int_function_to_tag()` or so.

> Isn't this expected of meshio-convert --input-format medit --output-format gmsh4-binary?

I understand what you mean, but I'd say no. The med format just doesn't translate to gmsh4 very well.

**Comment by gdmcbain** [comment]
O. K., I'll write that function.

I think that'll be `.convert_int_function_to_sets` or `.convert_tag_to_sets` though, no?  Isn't a tag like "medit:ref" and "gmsh:physical" (a function cell → int)?  I know nomenclature is really confusing in meshio because there's the influence of the nomenclature native to each format; 'tag' and 'entity' &c. mean various things in Gmsh, but I'll trying to keep it straight & simple here.

**Comment by nschloe** [comment]
> I know nomenclature is really confusing in meshio because there's the influence of the nomenclature native to each format;

Indeed, and I'm not too happy about that.

In my book, tag and sets are the same; both are a collection of indices into the cell array. We should straighten that out and only use one of those words in meshio. Perhaps tag is the better choice because `set` already has a meaning in Python lingo.

Integer-valued functions on the cells to me are just that, _int functions_. We call that `cell_data` in meshio, which I think is fine; it's data that lives on the cells.

Perhaps then `convert_int_data_to_set` is a good name?

**Comment by gdmcbain** [comment]
> > Isn't this expected of meshio-convert --input-format medit --output-format gmsh4-binary?

> I understand what you mean, but I'd say no. The med format 

N. B.: medit ≠ med

I don't know much about MED except that it's complicated and that those who have implemented the support for it in Gmsh and meshio are to be thanked.

MEDIT on the other hand is very simple and perhaps the canonical example of a type I file format, assigning exactly one int "ref" (here called "medit:ref") to each cell.

**Comment by gdmcbain** [comment]
> Indeed, and I'm not too happy about that.

I'm thinking that there is some nice scholarly work to be done one day on the taxonomy of mesh file formats, of which the types I & II above is just the lumpiest start.  I assume that there is a mathematical description somewhere, but don't know where to look.  The [CW complex](https://en.wikipedia.org/wiki/CW_complex)?  Those do have cells, which is a start, but of course one doesn't want to scare off users with names like 'CW complex'.

> Perhaps then convert_int_data_to_set is a good name?

Yes, that's clear.  Thanks.  Maybe 'sets', plural.  Unless we can establish 'tag' as a better synonym for set which doesn't clash with the standard library—that's always annoying (e.g. having to write lmbda in pacopy).

Actually what we're calling sets in `.cell_sets` are really more like subsets than sets, aren't they?  Would 'subsets' be better? As in the title of #290.

**Comment by gdmcbain** [comment]
Superseded by #716.
