### ISSUE TITLE
Tests don't run in 6.0.4

### ISSUE THREAD

**Issue by frli8848** [nschloe/meshio#718]
I tried to run the tests for pygmsh-6.0.4 but all assertions don't work since there is no compute_volume in the helpers.py file. That is,

`pygmsh-6.0.4 # grep compute_volume pygmsh/helpers.py`

returns nothing. I also had to change the lines

`from helpers import compute_volume`

to 

`from pygmsh.helpers import compute_volume`

 in the test files to find helpers.py and then I get

```
$ python test_pipes.py
Traceback (most recnent call last):
  File "test_pipes.py", line 4, in <module>
    from pygmsh.helpers import compute_volume
ImportError: cannot import name 'compute_volume'
```

since there is no compute_volume.

**Comment by themrdjj** [comment]
Any solutions to this?

**Comment by nschloe** [comment]
1 . This is the wrong repository for the question. Try https://github.com/nschloe/pygmsh/.
2. Try updating all packages.
