### ISSUE TITLE
paraview plugin not installed "properly"

### ISSUE THREAD

**Issue by RizzerOnGitHub** [nschloe/meshio#730]
meshio4  has the new paraview plugin tools/paraview-meshio-plugin.py

setup.py only marks it for "paraview-plugins" in data_files, which means (in a debian build system at least) it gets installed into /usr/paraview-plugins, which of course is not where we want it.

From the setuptools docs [1] , the left entry in data_files ("paraview-plugins") is the destination directory relative to the installation prefix (Python’s sys.prefix for a default installation, i.e. /usr).

So for a "standard" independent package path we might want "share/meshio/paraview-plugins" instead of just "paraview-plugins", which will get it installed in /usr/share/meshio/paraview-plugins (or the equivalent in ~/.local for a user installation)

But maybe the more important question is, where exactly is paraview expecting 3rd party plugins to be located? Do they have a standard path? The paraview plugin manager says it's expecting them in /usr/bin/plugins, which seems somewhat inappropriate to me. They should be reading 3rd pary plugins from /usr/bin/paraview-plugins, or better still /usr/lib/\<arch>/paraview/plugins and /usr/share/paraview/plugins. Paraview's built-in plugins are in /usr/lib/x86_64-linux-gnu/paraview-5.7/plugins). Can be specified in env variable PV_PLUGIN_PATH, but that's for users to set. 

We should file a bug against paraview, but in the meantime should the destination in setup.py's data_files be set to "bin/plugins" ?

[1] https://packaging.python.org/guides/distributing-packages-using-setuptools/#data-files

**Comment by RizzerOnGitHub** [comment]
I  filed a bug against paraview in debian, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=952390

The published paraview docs (https://www.paraview.org/Wiki/ParaView/Plugin_HowTo#Using_Plugins) mention "A plugins subdirectory beneath the directory containing the paraview client or server executables", while unpublished docs (https://kitware.github.io/paraview-docs/latest/cxx/PluginHowto.html) refer to "A plugins subdirectory under the paraview-X.Y directory in the
library path" (i.e. /usr/lib/x86_64-linux-gnu/paraview-5.7/plugins/)

So looks like paraview upstream is already dealing with the problem in paraview3.8.

Their path is not so convenient for meshio though. I suggested adding /usr/share/paraview/plugins in the debian bug.

**Comment by nschloe** [comment]
I've file a bug against ParaView for this. https://gitlab.kitware.com/paraview/paraview/issues/19714

**Comment by mathstuf** [comment]
IIRC, ParaView (post-5.7) doesn't search for plugins it wasn't built with. We can add that functionality (again?) now that plugin loading has been reworked to be more sensible in the latest releases. ParaView installs its plugins to `$prefix/$libdir/paraview-$version/plugins`. `$prefix/share` should be avoided unless you're using Python or XML plugins since the compiled ones are arch-dependent.

**Comment by nschloe** [comment]
@mathstuf This is a Python plugin, right? Right now, it installs into `share/paraview/plugins`.

**Comment by nschloe** [comment]
@mathstuf Can you please reiterate where to install the meshio plugin?

**Comment by mathstuf** [comment]
Note that ParaView doesn't search for plugins without prompting by name (sort of like Python). However, where I would put them:

  - `$prefix/$libdir/paraview-$pvversion/plugins` if you are arch-ful
  - `$prefix/share/paraview-$pvversion/plugins` if your plugin is arch-independent

We can look at getting these to be searched by default and add them to the plugin list as listed, but unloaded in a `-dr` (config-less) launch of a client. Please file an issue on ParaView to track the progress (I'd like your input on any discussion on our side about the feature/implementation).

**Comment by RizzerOnGitHub** [comment]
@mathstuf If the plugin is arch-independent (like Nico's python plugin here) then it's not built against the specific paraview version.

In that case the versioned path is an obstacle. It would be better for paraview to allow for an unversioned arch-independent path,

    $prefix/share/paraview/plugins

Perhaps both `$prefix/share/paraview/plugins` and `$prefix/share/paraview-$pvversion/plugins` could be used if any arch-independent plugins are actually strictly dependent on paraview version.

You closed paraview Issue #19714, but I think it should be reopened to get unversioned `$prefix/share/paraview/plugins` implemented.

**Comment by mathstuf** [comment]
Unversioned can also work. Though I wouldn't trust ParaView's API to not change underneath you (e.g. 5.8 moved lots of modules around; `paraview.simple` is fine, but `paraview.modules.foo` is not). I'd like to fix that, but that's a longer road than I'd like it to be.

I closed it because it was basically a doc issue (AFAICT). The wiki needs to basically be stripped and ported into `.md` files in the repository itself (so that it has a hope of being updated in a timely manner; contributing fixes is also easier there). Getting unversioned directories to be searched in in the same bucket as versioned directories getting searched today.

**Comment by RizzerOnGitHub** [comment]
I see. In Nico's case he's using paraview.util.vtkAlgorithm, so if that's going to be moving around then share/paraview<version> makes sense.

I read #19714 as more about implementing the /usr/share plugin location, though of course the documentation should match the implementation as well.

**Comment by nschloe** [comment]
So this
```
$prefix/share/paraview-$pvversion/plugins
```
should read
```
$prefix/share/paraview-$paraview_version/plugins
```
right?

**Comment by mathstuf** [comment]
Sure, that's more verbose with the variable name, but otherwise isomorphic :) .

**Comment by nschloe** [comment]
Well, the question is it needs to be Python version or the ParaView version or ParaView's Python version.

**Comment by mathstuf** [comment]
ParaView's version. The `pv` wasn't a typo. Sorry for the confusion.
