### ISSUE TITLE
meshio.write error

### ISSUE THREAD

**Issue by tjyanjing** [nschloe/meshio#744]
# I was trying to run example from pygmsh but find out error during meshio export, shown below

# AttributeError: 'tuple' object has no attribute 'cells'

import pygmsh
import numpy as np

geom = pygmsh.built_in.Geometry()

poly = geom.add_polygon([
    [ 0.0,  0.5, 0.0],
    [-0.1,  0.1, 0.0],
    [-0.5,  0.0, 0.0],
    [-0.1, -0.1, 0.0],
    [ 0.0, -0.5, 0.0],
    [ 0.1, -0.1, 0.0],
    [ 0.5,  0.0, 0.0],
    [ 0.1,  0.1, 0.0]
    ],
    lcar=0.05
)

axis = [0, 0, 1]

geom.extrude(
    poly,
    translation_axis=axis,
    rotation_axis=axis,
    point_on_axis=[0, 0, 0],
    angle=2.0 / 6.0 * np.pi
)

mesh = pygmsh.generate_mesh(geom)

import meshio
meshio.write("test.vtk", mesh)

  207 
    208     # check cells for sanity
--> 209     for key, value in mesh.cells.items():
    210         if key[:7] == "polygon":
    211             assert value.shape[1] == int(key[7:])
AttributeError: 'tuple' object has no attribute 'cells'

**Comment by keurfonluu** [comment]
Looks like you are not using the latest version of ``meshio``. Run ``pip install -U meshio`` to update ``meshio``.

**Comment by tjyanjing** [comment]
The version I used was not updated. Thanks.
