### ISSUE TITLE
Exporting Abaqus mesh with `subdomain` information

### ISSUE THREAD

**Issue by bhaveshshrimali** [nschloe/meshio#749]
Hi Nico,
Again, in a way related to what I am trying to achieve in [pygmsh: 320](https://github.com/nschloe/pygmsh/issues/320). I have an `Abaqus` mesh that I want to convert to `xdmf` format so as to import in `dolfin` . The mesh comprises of two element sets (essentially two subdomains, denoted by the keyword `ELSET` in Abaqus).  Is there a way to do that using `meshio` such that I can store the `subdomain` data to be called in `dolfin`? What I have so far:

```python3
import meshio
import numpy as np
msh = meshio.read("geom_cp_0_05.inp")
#  msh.cells[0] is a `CellBlock` containing the cells for the first domain and msh.cells[1] the second
entireCells = np.vstack(( msh.cells[0].data, msh.cells[1].data))
particles = msh.cells[1].data
entireMesh = meshio.Mesh(msh.points, cells = {"tetra": entireCells})
particlesMesh = meshio.Mesh(msh.points, cells = {"tetra" : particles})
meshio.write("entireMesh.xdmf", entireMesh)
meshio.write("particles.xdmf", particlesMesh)
```

I want to be able to do something like

```python3
subdomainMesh = meshio.Mesh(msh.points, cells = ....)
meshio.write("subdomains.xdmf", subdomainMesh)
from dolfin import *
mesh = Mesh()
with XDMFFile("entireMesh.xdmf") as sdf:
    sdf.read(mesh)
sub_domains= MeshFunction("size_t", mesh, subdomains.xdmf")
dx = Measure("dx")(subdomain_data=sub_domains)
``` 

Also, how are `element`-sets imported in `meshio`. I see that there was some work in #493 but not sure if I can access each `ELSET` in meshio as of now. If I try to
```python3
print(msh.cell_data_dict)
``` 
I get an empty dictionary

**Comment by gdmcbain** [comment]
Is there anything in `msh.cell_sets` rather than `msh.cell_data_dict`? See 

 https://github.com/nschloe/meshio/blob/44a91dc9ca9655dd1297ebffcf5d5eefd511527e/meshio/abaqus/_abaqus.py#L137-L147

The `cell_sets` attribute is a newish feature of `meshio.Mesh`; it is so far ignored when writing XDMF.  Reading [XMDF Modal and Format](http://www.xdmf.org/index.php/XDMF_Model_and_Format) does suggest a few possibilities for how such information might be recorded in that format (multiple `Grid`s #568, [`Subset`](http://www.xdmf.org/index.php/XDMF_Model_and_Format#SubSet), [`Set`](http://www.xdmf.org/index.php/XDMF_Model_and_Format#Set)).  I don't know how `dolfin` reads XDMF.

**Comment by bhaveshshrimali** [comment]
> Is there anything in `msh.cell_sets` rather than `msh.cell_data_dict`? See

No it too returns an empty dictionary.

**Comment by gdmcbain** [comment]
Hmm. Could you share an MWE?

**Comment by bhaveshshrimali** [comment]
Sure. I am attaching the `Abaqus`-generated mesh.
[geom_cp_0_05.zip](https://github.com/nschloe/meshio/files/4314857/geom_cp_0_05.zip)

```python3
import meshio, os
msh = meshio.read("geom_cp_0_05.inp")
#  msh.cell_sets --> "{}"
```
Although, I have partly been able to do what I want but would anyway like to have an insight on this.

**Comment by gdmcbain** [comment]
Thanks.  I don't know what the Abaqus .inp format is supposed to look like myself, but if lines like 123972 
```
*Element, type=C3D4, ELSET=PART1
```
or 716709
```
*Element, type=C3D4, ELSET=PART2
```
are valid then the 'ELSET' is not going to be detected by the current implementation of `meshio.abaqus._abaqus.read_buffer` which only looks for "ELSET" in `keyword` where

https://github.com/nschloe/meshio/blob/3ca5b8f19de63a7ea18dbaf737196453da687170/meshio/abaqus/_abaqus.py#L123

This is only going to give `keyword == "ELEMENT"` and never reach the clause quoted above.  The lines are reread in `._read_cells` into `sline` but only to extract the type (here "C3D4"), not the "ELSET".

**Comment by bhaveshshrimali** [comment]
I see. Thanks for pointing it out. If this is it and there are no major changes elsewhere then maybe I can take a stab at editing 
https://github.com/nschloe/meshio/blob/3ca5b8f19de63a7ea18dbaf737196453da687170/meshio/abaqus/_abaqus.py#L137 to make sure that `cell_data` can recognize `ELSET`'s.

**Comment by keurfonluu** [comment]
At first glance, it doesn't seem too complicated to fix (I don't have time right now).

You'd simply have to parse ``ELSET`` in function ``_read_cells`` and make the latter returns an element set dict (empty if no ``ELSET``), and then update the dict ``cells_set`` in function ``read_buffer``.

However, I wonder what would happen if you invert the order of ``ELSET`` and ``type`` i.e. whether ``*Element, ELSET=PART1, type=C3D4`` is valid for Abaqus. In case it is, parsing the line starting with ``*ELEMENT`` into a dict would make things easier and less error-prone for the future.

**Comment by gdmcbain** [comment]
> However, I wonder what would happen if you invert the order of ELSET and type i.e. whether *Element, ELSET=PART1, type=C3D4 is valid for Abaqus. In case it is, 

Good catch, I think it might be.  The ‘Input deck format’ [*ELEMENT](https://web.mit.edu/calculix_v2.7/CalculiX/ccx_2.7/doc/ccx/node194.html) documentation for Calculix (which reads the same format as Abaqus) gives the example
```
*ELEMENT,ELSET=Eall,TYPE=C3D20R
```

**Comment by keurfonluu** [comment]
I PRed the line conversion into a dict (PR #752). I don't have time right now to make the fix for element sets but you should be able to do something like:

```python
if "ELSET" in values.keys():
    # Append cell ID to local cell_sets dict
    # Probably need to remap cell ID too
```

**Comment by keurfonluu** [comment]
"Thanks" to COVID19, I found some spare time to look into a fix. It wasn't as straightforward as I thought, though.

In PR #760, Abaqus reader is able to parse ``ELSET`` defined in ``ELEMENT``, and ``mesh.cell_sets_dict`` should return

```python
{
    'PART1': {'tetra': array([0, 1, 2, ..., 592733, 592734, 592735])},
    'PART2': {'tetra': array([592736, 592737, 592738, ..., 658221, 658222, 658223])}
}
```

**Comment by bhaveshshrimali** [comment]
Thanks for taking it up @keurfonluu ! I believe this should be it then. Thanks everyone
