### ISSUE TITLE
Tetra10 node ordering

### ISSUE THREAD

**Issue by gertjanvanzwieten** [nschloe/meshio#765]
Going over several gmsh files I noticed that all (simplex) cell types maintain the gmsh node ordering except for tetra10, which has the last two nodes flipped compared to Gmsh's [Tetrahedron10](http://gmsh.info/doc/texinfo/gmsh.html#Node-ordering). Is this intentional, and if so, is there a reference for node orderings of the several element types as employed by meshio?

Steps to reproduce:

Create tetrahedron.geo
```
// single element tetrahedron
Point(0) = {0,0,0,10};
Point(1) = {1,0,0,10};
Point(2) = {0,1,0,10};
Point(3) = {0,0,1,10};
Line(4) = {0,1};
Line(5) = {0,2};
Line(6) = {0,3};
Line(7) = {1,2};
Line(8) = {1,3};
Line(9) = {2,3};
Line Loop(10) = {4,7,-5}; // 0-1-2
Line Loop(11) = {4,8,-6}; // 0-1-3
Line Loop(12) = {5,9,-6}; // 0-2-3
Line Loop(13) = {7,9,-8}; // 1-2-3
Plane Surface(14) = {10};
Plane Surface(15) = {11};
Plane Surface(16) = {12};
Plane Surface(17) = {13};
Surface Loop(18) = {14,15,16,17};
Volume(19) = {18};
```

Generate tetrahedron.msh
```
$ gmsh -3 -degree 2 tetrahedron.geo
$ tail -2 tetrahedron.msh
15 1 3 4 2 6 10 7 5 9 8
$EndElements
```

Load in meshio
```
>> m = meshio.read('tetrahedron.msh')
>> m.cells[-1].data+1
array([[ 1,  3,  4,  2,  6, 10,  7,  5,  8,  9]])
```

**Comment by keurfonluu** [comment]
As far as I know, ``meshio`` is following VTK's convention. For ``tetra10``, it looks like this: http://web.mit.edu/calculix_v2.7/CalculiX/ccx_2.7/doc/ccx/node33.html

As you can see, nodes 8 and 9 are inverted compared to [Gmsh's convention](http://gmsh.info/doc/texinfo/gmsh.html#Node-ordering).

**Comment by gertjanvanzwieten** [comment]
That explains, thank you very much for that reference! I'll close the issue then.

**Comment by CsatiZoltan** [comment]
`meshio` uses a node ordering as seen in the [Wiki](https://github.com/nschloe/meshio/wiki/Node-ordering-in-cells).
