### ISSUE TITLE
Error with tofile-function

### ISSUE THREAD

**Issue by bsimu** [nschloe/meshio#766]
There is a problem caused by the tofile function. When trying to write out a vtk file, Abaqus crashes without any error notification. It seems to be somehow linked to the Abaqus and numpy versions used. Error occurs on a system with numpy 1.6.2 and Abaqus 2018.

A workaround has been implemented to check for the numpy version. If numpy is 1.6.2 a simple write command is used instead of the tofile function.

**Comment by nschloe** [comment]
If it crashes, this sounds like an abaqus issue. No program should ever just "crash".

Besides that, not much can be done without an MWE and a hint on what's wrong.

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to reopen at any time.
