### ISSUE TITLE
meshio-convert vtk to msh version 2

### ISSUE THREAD

**Issue by ocastilloreyes** [nschloe/meshio#768]
Dear all, 

I would like to know if it is possible to export a mesh in vtk format (generated with tetgen) to gmsh format (ascii version 2). The meshio-convert option is not clear for me, my first attemps are the following:

meshio-convert -i vtk -o gmsh22 test_mesh.vtk test.msh
WARNING:root:Binary Gmsh needs 32-bit integers (got int64). Converting.

meshio-convert -i vtk -o gmsh test_mesh.vtk test.msh
WARNING:root:Binary Gmsh needs c_size_t (got int64). Converting.

The idea is to preserve the material tags of the vtk mesh ($ PhysicalNames). A test vtk mesh is attached.

Furthermore, the pytest has not passed, there are many errors with the installation. My numpy version is 1.18.2 under ubuntu 18.04. The pytest output is also attached. 
[output_pytest.txt](https://github.com/nschloe/meshio/files/4423235/output_pytest.txt)

[test_mesh.zip](https://github.com/nschloe/meshio/files/4422844/test_mesh.zip)

**Comment by gdmcbain** [comment]
Could you send a smaller example?  I'm working under straitened circumstances at the moment; meshio does O. K. but the Gmsh GUI is sluggish with so many cells.

I'm trying:
```python
import meshio

mesh = meshio.read('test_mesh.vtk')
mesh.cell_data['gmsh:physical'] = mesh.cell_data.pop('cell_scalars')
meshio.write('test_mesh.msh', mesh, file_format='gmsh22')
```

**Comment by ocastilloreyes** [comment]
Sure, this a smaller example (I hope)
[test_mesh_small.zip](https://github.com/nschloe/meshio/files/4424054/test_mesh_small.zip)

**Comment by gdmcbain** [comment]
This isn't smaller:
```
<meshio mesh object>
  Number of points: 43023
  Number of cells:
    tetra: 265604
  Cell data: cell_scalars
```

**Comment by gdmcbain** [comment]
If you have access to a larger machine, you could try the script suggested above.

**Comment by ocastilloreyes** [comment]
Sorry, I will check your script. In addition, I can also convert tetgen node/ele to gmsh? If it is possible, which are the instructions? In this way, the physical tags are preserved?

**Comment by ocastilloreyes** [comment]
Hi, after using your script, the issue persists on a machine with 128gb of RAM:

WARNING:root:Binary Gmsh needs 32-bit integers (got int64). Converting.

the output doesn't make sense. 

I have prepared the smallest mesh I can generate to reproduce the error. I hope it is suitable for you to do the tests.
[small.zip](https://github.com/nschloe/meshio/files/4425654/small.zip)

**Comment by gdmcbain** [comment]
Thanks. I'm away from.the desk for a.while now but this warning

> WARNING:root:Binary Gmsh needs 32-bit integers (got int64). Converting.

can safely be ignored, I'm pretty sure. (I mean it should probably be fixed, but I haven't seen it do any harm.)

How do you mean

> the output doesn't make sense.

Do you mean the output file or that warning? I thought the file looked O. K., it was just too big to easily inspect.

**Comment by ocastilloreyes** [comment]
My output.msh file is attached. The gmsh format is not consistent and the output is the same on both machine (local and another cluster)

[output_test_mesh.zip](https://github.com/nschloe/meshio/files/4425886/output_test_mesh.zip)

**Comment by gdmcbain** [comment]
At 144 437 tetrahedra, this mesh is still a little big for debugging.  Do you mean that small (less than a hundred elements, say) meshes generated in the same way don't evince the bug?  There is something funny going on here, but I can't quite pick out what it is as there are too many points and cells to read through.

Aside from a that, a correction: Gmsh's physical identifiers start from 1 not 0 so please add 1 when converting from VTK.  Sorry.
```python
mesh.cell_data['gmsh:physical'] = [k + 1 for k in mesh.cell_data.pop('cell_scalars')]
```

**Comment by ocastilloreyes** [comment]
Don't worry!

But no, the issue persists... please see the attached test case:

Mesh points: 186
Mesh tetrahedra: 584

The output doesn't have a 
[small.zip](https://github.com/nschloe/meshio/files/4427073/small.zip)
sense...

**Comment by nschloe** [comment]
I've just fixed an issue related to gmsh22 reads that might or might not be related https://github.com/nschloe/meshio/pull/769.

@ocastilloreyes Writing that "the output doesn't have a sense..." is not very helpful. Try to answer the following questions: What doesn't work exactly? What do have to do to reproduce the issue? What do you expect instead?

Apart from that, let me add that gmsh22 is a terrible format. Also, you never want to work with ASCII data. VTK binary is fine.

**Comment by ocastilloreyes** [comment]
@nschloe thank you for your feedback. Right now I have done the update but the problem has not been solved.

On the clarity of the issues, I comment on the following:

**Comment by nschloe** [comment]
> The output doesn't have a sense because the content of the msh file is something like:

This is binary gmsh22. Seems okay.

Do you need ASCII format? Again, this is not something that anyone would recommend, unless for debugging. Use binary format whenever possible. If you _really_ want ascii, you could use
```
meshio-convert out.vtk out.msh --ascii
```
or
```
meshio-ascii out.msh
```
on the command line.

**Comment by ocastilloreyes** [comment]
Now is correct, misinterpretation of mine. I am sorry...

problem solved...

Thank you for your support

**Comment by nschloe** [comment]
Cool.
