### ISSUE TITLE
ANSYS Fluent .msh files

### ISSUE THREAD

**Issue by VKheyfets** [nschloe/meshio#77]
Hello,

Does the meshio support ANSYS Fluent .msh files? The documentation says that it does, but it looks like it only supports .gmsh files by the in the ___init__.py. 

Thank You,

Vitaly

**Comment by nschloe** [comment]
Wait, where does it say that ANSYS files are supported? That should be fixed, because they aren't.

**Comment by VKheyfets** [comment]
Well it does not say that explicitly, but the README file says that it can do *.msh file formats, which is the mesh file for ANSYS Fluent. The example also says: "meshio-convert input.msh output.vtu." I'm not familiar with Gmsh, so I am not sure if .msh is also an extension for that software. 

That makes sense since the __init__.py file only has gmsh.

**Comment by gdmcbain** [comment]
I think the .msh extension has been used for a few different things over the years, it's kind of an obvious one, especially if working under an environment mandating three-letter extensions.  A third example is the one used by _FreeFem++_, defined in Table 5.1 &lsquo;The structure of “mesh sample.msh”&rsquo; of the FreeFem++ manual, v. 3.48.

Where meshio's README.md lists the formats, including MSH, each is a link to a definition, MSH linking to http://geuz.org/gmsh/doc/texinfo/gmsh.html#File-formats .  That's some indication which MSH is meant here.

I've proposed a more explicit listing in #78.

**Comment by nschloe** [comment]
Thanks for PR.

Let's leave this issue open to see how much interest ANSYS meshes attract.

**Comment by VKheyfets** [comment]
You got one person :-)

**Comment by certik** [comment]
Yes, that would be useful. I started hacking my own converter, but haven't had time to finish it up.

**Comment by nschloe** [comment]
Three is a party, so here you go: ANSYS mesh reading is in 1.8.0 (just released).

The only one testing so far is me, so expect rough edges. If something doesn't work as you expect, best file a bug.

**Comment by VKheyfets** [comment]
Wow ... cool, thanks!

On May 12, 2017, at 5:35 AM, Nico Schlömer <notifications@github.com<mailto:notifications@github.com>> wrote:


Three is a party, so here you go: ANSYS mesh reading is in 1.8.0 (just released).

The only one testing so far is me, so expect rough edges. If something doesn't work as you expect, best file a bug.

**Comment by certik** [comment]
Thanks @nschloe, I appreciate it. Unfortunately it can't read my Fluent file, so I submitted #90.

If you are interested, I am happy to help, I would love to have a converter. Let's discuss on the other issue.
