### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by zeineldin117** [nschloe/meshio#774]
I downloaded the zip file and unzip it,then i use (sudo pip install meshio[all]) to install it and i get this error message

____________________________________________________________________________
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal import main
ImportError: No module named _internal

**Comment by nschloe** [comment]
Looks like a faulty pip installation. This isn't the recommended way for installing meshio either. Just use
```
pip install meshio
```

**Comment by zeineldin117** [comment]
i used sudo pip install meshio
and i got the same error

**Comment by nschloe** [comment]
Again: Looks like a faulty pip installation, definitely unrelated to meshio.

PS: Instead of `sudo`, always use `--user`. This is the default in recent pip versions anyway.

**Comment by keurfonluu** [comment]
Try:

```
python -m pip install meshio[all] --user
```

But there is definitely something wrong with your pip installation (meaning that you probably cannot install anything using the command `pip`).

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to reopen at any time.
