### ISSUE TITLE
vtk_pixel 

### ISSUE THREAD

**Issue by carlesRT** [nschloe/meshio#775]
Thanks for sharing!

while importing a simple file in vtk format I realize that <code>VTK_PIXEL (=8)</code> are not correctly being imported. Such cells are treated as <code>VTK_QUAD (=9)</code>. (I have seen <code>_common.py</code> "pixel" is out-commented)

Is there any special reason for such "approach"? I think one should 1) either warn the user that such cell types are not supported or 2) improve the code so that such cell type is supported (either a) by fully supporting this cell type. - not aware of which functions are included within <code>meshio</code> that would need to eventually be adapted - since I haven't used this package much... or b) properly convert <code>VTK_PIXEL (=8)</code> into <code>VTK_QUAD (=9)</code>. Not deep knowledge on the format, though I think that reordering the point-index should be enough... Point 2 is now point 3, and vice versa point 3 is point 2.

https://vtk.org/wp-content/uploads/2015/04/file-formats.pdf

How would you prefer to address this issue?

I haven't used <code>meshio</code> much..., I can use this issue as an excuse to have a deeper look. 

Kind Regards,
Carles

**Comment by nschloe** [comment]
Well, that shouldn't happen. MWE?

**Comment by carlesRT** [comment]
Sure. Thanks for the quick reply.

[untitled_v3 - Kopie.txt](https://github.com/nschloe/meshio/files/4481217/untitled_v3.-.Kopie.txt)

I do `import meshio` and `mesh = meshio.read()`

```
>>> mesh
<meshio mesh object>
  Number of points: 10
  Number of cells:
    triangle: 1
    polygon6: 1
    quad: 2
```

*For the record, the file was manually created....

**Comment by nschloe** [comment]
Fixed now, will be part of the next release. Thanks for the good report!
