### ISSUE TITLE
pruning cannot handle cell data

### ISSUE THREAD

**Issue by mrambausek** [nschloe/meshio#777]
With meshio version 4.0.10 (on pip at the time of writing) pruning does not handle cell data correctly.
Converting from a file with two physical domains work without pruning.
What helped in may case is to make the following changes (see comments) to `_mesh.py`:
```
                new_cells.append(c)
                # use .items()
                for name, data in self.cell_data.items():
                    if name not in new_cell_data:
                        new_cell_data[name] = []
                    # concatenate since the data already is a list
                    new_cell_data[name] += data
```

**Comment by nschloe** [comment]
Fixed via #778.
