### ISSUE TITLE
Define groups in MED (To use in Salome_Meca)

### ISSUE THREAD

**Issue by A-ep93** [nschloe/meshio#781]
Hello all, 
I want to convert a vtk mesh to MED format. My vtk file has different labels. When I generate my MED file, it also includes the labels but they are stored in cell_data. I want to use salome_meca to consider these labels as groups. However, it is not possible with the current MED file. I am not sure but I think maybe the labels should be stored in field_data of the med file. Can anyone help me with this?
I have attached my vtk file as well as the generated med file.
Thanks and regards
[Model.zip](https://github.com/nschloe/meshio/files/4495698/Model.zip)

**Comment by keurfonluu** [comment]
Hi,

I don't know much about the MED format, but I went through the source code, and it seems that the group infos are stored in `mesh.cell_data["cell_tags"]`.

May you try the following script?

```python
import meshio

mesh = meshio.read("Model.vtk")
mesh.cell_data["cell_tags"] = mesh.cell_data.pop("labels")
mesh.write("Model.med")
```

**Comment by arashep93** [comment]
> Hi,
> 
> I don't know much about the MED format, but I went through the source code, and it seems that the group infos are stored in `mesh.cell_data["cell_tags"]`.
> 
> May you try the following script?
> 
> ```python
> import meshio
> 
> mesh = meshio.read("Model.vtk")
> mesh.cell_data["cell_tags"] = mesh.cell_data.pop("labels")
> mesh.write("Model.med")
> ```

Thank you for your response. I tried it and it does not work for me.
I think there should be a way that labels can be written inside filed_data rather than cell_data of the MED file.

**Comment by arashep93** [comment]
I tried the following code to write values in cell_data into family_data: msh=meshio.read("Model.med")
msh.field_data=msh.cell_data
msh=meshio.write("Model2.med",msh)

However, when I in the generated file I get:
msh2=meshio.read("Model2.med")
msh2.field_data
{}
which is strange. Does anybody have any idea in this regard?

**Comment by keurfonluu** [comment]
`mesh.field_data` contains the actual name of the labels associated to the integer values in `mesh.cell_data`.

As we don't know how SALOME_MECA works, it would be easier if you provide a MED file with groups that are correctly imported by SALOME_MECA rather than blindly guessing where to put your group data.

**Comment by arashep93** [comment]
> `mesh.field_data` contains the actual name of the labels associated to the integer values in `mesh.cell_data`.
> 
> As we don't know how SALOME_MECA works, it would be easier if you provide a MED file with groups that are correctly imported by SALOME_MECA rather than blindly guessing where to put your group data.



> `mesh.field_data` contains the actual name of the labels associated to the integer values in `mesh.cell_data`.
> 
> As we don't know how SALOME_MECA works, it would be easier if you provide a MED file with groups that are correctly imported by SALOME_MECA rather than blindly guessing where to put your group data.

Thank you very much for your response. That's a good idea. I attached a MED file generated by salome_meca itself. The groupings in the attached MED file can be easily detected by salome_meca. It seems the grouping data should be stored in point_data.
Any idea on how to store my labels in point_data?

[Salome_Model.zip](https://github.com/nschloe/meshio/files/4497483/Salome_Model.zip)

**Comment by keurfonluu** [comment]
I opened your file and, as I thought, groups are stored in `mesh.cell_data["cell_tags"]`, yet as negative integers. Group names are stored in `mesh.cell_tags`.

```
import meshio

mesh = meshio.read("Model.vtk")
mesh.cell_data["cell_tags"] = mesh.cell_data.pop("labels")
mesh.cell_data["cell_tags"][0] *= -1
mesh.cell_tags = {-1: ["Group_1"], -2: ["Group_2"]}
mesh.write("Model.med")
```

Still don't know if it will work, but I can read back `"Model.med"` with the cell tags.

**Comment by tianyikillua** [comment]
The solution provided by @keurfonluu is absolutely correct.

However note that now by default a compression will be applied to HDF5 files, which is not supported for MED files in fact (read error under Salome). So you must do
```
mesh.write("Model.med", compression=None, compression_opts=None)
```

![](https://user-images.githubusercontent.com/4027283/79738376-f448c280-82fc-11ea-98af-b2110a09db7d.png)

@nschloe Should be probably deactivate compression for MED?

**Comment by nschloe** [comment]
> Should be probably deactivate compression for MED?

If MED doesn't support it, yes!

**Comment by A-ep93** [comment]
Yes, it is working for me now. Thank you for your comments.
