### ISSUE TITLE
meshio.read INP with ELSET

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/meshio#783]
Recently I received an INP file [FEMMeshGmsh.inp](https://github.com/kinnala/scikit-fem/files/4485287/FEMMeshGmsh.zip) which resists `meshio.read`.   I believe the file was generated in FreeCAD for Calculix.  I also believe that that latter uses the same input file format as Abaqus.  I don't know too much about the format myself or about Abaqus, but I have installed Calculix 2.10 under Microsoft Windows 10 and 2.16 under Ubuntu and the file is processed happily by each of those.  Despite the name of the file, I don't think that it has anything to do with Gmsh.

The error is:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\gmcbain\src\meshio\meshio\_helpers.py", line 68, in read
    return reader_map[file_format](filename)
  File "c:\users\gmcbain\src\meshio\meshio\abaqus\_abaqus.py", line 99, in read
    out = read_buffer(f)
  File "c:\users\gmcbain\src\meshio\meshio\abaqus\_abaqus.py", line 144, in read_buffer
    set_ids, line = _read_set(f, params_map)
  File "c:\users\gmcbain\src\meshio\meshio\abaqus\_abaqus.py", line 292, in _read_set
    set_ids += [int(k) for k in line.strip().strip(",").split(",")]
  File "c:\users\gmcbain\src\meshio\meshio\abaqus\_abaqus.py", line 292, in <listcomp>
    set_ids += [int(k) for k in line.strip().strip(",").split(",")]
ValueError: invalid literal for int() with base 10: 'Evolumes'
```

I believe the resistant line of FEMMeshGmsh.inp is line 540, the second of: 
```
** Volume elements
*Element, TYPE=C3D10, ELSET=Evolumes
```

This may duplicate an existing issue on INP; I haven't been following developments on this format too closely.

**Comment by keurfonluu** [comment]
> I believe the resistant line of FEMMeshGmsh.inp is line 540, the second of:
> 
> ```
> ** Volume elements
> *Element, TYPE=C3D10, ELSET=Evolumes
> ```

Nah, this is correctly handled by `meshio` (PR #760).

The issue is raised by these lines (770 to 780):

```
** Define element set Eall
*ELSET, ELSET=Eall
Evolumes



***********************************************************
** Element sets for materials and FEM element type (solid, shell, beam, fluid)
** written by write_element_sets_material_and_femelement_type function
*ELSET,ELSET=MechanicalSolidMaterialSolid
Evolumes
```

**Comment by gdmcbain** [comment]
> The error is raised by these lines (770 to 780):

Right, yes, that's obvious now.  (I was wondering how line 540 had managed to get split before the last word!)  Thank you.

> What does it mean? Do all elements of set Evolumes also belong to sets Eall and MechanicalSolidMaterialSolid?

I'd be guessing here as I've only just installed Calculix.  That would seem to be a plausible explanation.  Is that valid in Abaqus or Calculix or both?  The latter seems happy, though I haven't verified that the results make sense.
