### ISSUE TITLE
Attempting to circumvent fenics mixed element issue in meshio 4.0.10 and pygalmesh 0.6.2

### ISSUE THREAD

**Issue by tomoleary** [nschloe/meshio#784]
This issue is somewhat similar to https://github.com/nschloe/meshio/issues/260

Fenics cannot handle mixed cell types so I attempt to convert to tets two different ways:

1. Prune
```python
p = pygalmesh.Polygon2D([[0.0, 0.0], [1.0, 0.0], [0.9, 0.1],[0.0,0.1]])
edge_size = 0.02
domain = pygalmesh.RingExtrude(p, edge_size)
disk = pygalmesh.generate_mesh(domain,cell_size=0.02,edge_size=edge_size,verbose=False)
disk.prune()
meshio.xdmf.write('disk.xdmf',disk)
```
Which throws the following `ValueError` inside of prune:
```
  File "prune_issue.py", line 14, in <module>
    disk.prune()
  File "/opt/anaconda3/envs/pygalmesh/lib/python3.7/site-packages/meshio-4.0.10-py3.7.egg/meshio/_mesh.py", line 80, in prune
    for name, data in self.cell_data:
ValueError: too many values to unpack (expected 2)
```
When I attempt to first save to vtk and then use `meshio-convert --prune` I get the same issue.

2. `get_cells_type`

```python
p = pygalmesh.Polygon2D([[0.0, 0.0], [1.0, 0.0], [0.9, 0.1],[0.0,0.1]])
edge_size = 0.02
domain = pygalmesh.RingExtrude(p, edge_size)
disk = pygalmesh.generate_mesh(domain,cell_size=0.02,edge_size=edge_size,verbose=False)
print('disk type = ', type(disk))
meshio.xdmf.write('disk.xdmf',disk.get_cells_type("tetra"))
```
Which throws the following AttributeError; the mesh seems to somehow become a numpy array inside the XdmfWriter. It is type `meshio._mesh.Mesh` before being passed in. 

I am wondering if anyone has encountered similar issues, figured out workarounds, or if this is similar to other existing issues. Any help would be greatly appreciated!

[tet_issue.tar.gz](https://github.com/nschloe/meshio/files/4503621/tet_issue.tar.gz)

**Comment by nschloe** [comment]
`prune` now works, this was a bug.

In the second example, the last line should read
```python
meshio.write_points_cells("disk.xdmf", disk.points, {"tetra": disk.get_cells_type("tetra")})
```
(Next time best use triple-fences + code highlighting for code blocks, this makes your posts look much better. https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks)
