### ISSUE TITLE
Can not open VTU file (ParseError)

### ISSUE THREAD

**Issue by MuellerSeb** [nschloe/meshio#786]
Hey there,

I can't open the appended vtu file. When running `meshio.read("unstructured.vtu")`, I get the following Error from `xml`:
```python 
ParseError: not well-formed (invalid token): line 22, column 1
```

Any ideas?

Sebastian

[unstructured.vtu.zip](https://github.com/nschloe/meshio/files/4517997/unstructured.vtu.zip)

**Comment by nschloe** [comment]
Using binary in VTU is not XML-conform and hence not supported by meshio (see README). In my view, admitting this kind of data is a mistake of the VTU standard.

**Comment by MuellerSeb** [comment]
What a mess. And the sad thing is, that this is the standard output of [pyevtk](https://github.com/pyscience-projects/pyevtk)

**Comment by nschloe** [comment]
Perhaps the the pyevtk folks would like to think about that. (Ping @xylar.) The hex-encoded binary is the better variant imho.

**Comment by MuellerSeb** [comment]
@nschloe : do you have a hint for a good guide on how to encode the appended data with base64?

**Comment by nschloe** [comment]
It's a little tricky. I'd say the best documentation is the specification and -- hehe -- the meshio implementation.

**Comment by nschloe** [comment]
https://github.com/nschloe/meshio/blob/d9c05ae688858b5166630874f3ec875a43b8fd37/meshio/vtu/_vtu.py#L450

**Comment by MuellerSeb** [comment]
Already found that. Nice thing is, you don't use AppendedData when writing vtu files. What are the advantages/disadvantages of appended data?
Maybe I just adopt that to pyevtk... If you don't mind.

**Comment by nschloe** [comment]
Yeah sure.

**Comment by MuellerSeb** [comment]
...or I could finally work on the exporting of structured grids in meshio. but that would mean a lot of work, since the whole infrastructure is build up on unstructured grids. That is the only advantage of pyevtk atm.

**Comment by nschloe** [comment]
I wouldn't mind that either. Perhaps we can have a `StructuredMesh` type with different attributes that is returned from the VT* reader. Shouldn't be too difficult. As always: A little bit is better than nothing at all, so you can start slowly.
