### ISSUE TITLE
vtk to Abaqus conversion in meshio

### ISSUE THREAD

**Issue by Vasiliy972** [nschloe/meshio#788]
Hi everybody!
My issue is to convert .vtk to Abaqus. I didn't find any software for this purpose despite meshio.
But meshio is a Python package and I'm a newbie in this software (actually have installed it only today)).
Does anybody know if meshio convert .vtk to abaqus and how to do it?
Thanks in advance for help!

**Comment by gdmcbain** [comment]
(As per the front page, https://github.com/nschloe/meshio) meshio can convert between formats either on the command line or in Python script; the former might be easier if you're new to Python, so try
```
meshio-convert your_mesh.vtk your_mesh.inp
```
There are various options; try `meshio-convert -h` for help and do refer to that front page for more info.

**Comment by Vasiliy972** [comment]
Thanks a lot for your reply but it seems this conversion doesn't work or probably I do something wrong.
![Screenshot_3](https://user-images.githubusercontent.com/64161496/80093151-aa661380-856c-11ea-9b3c-068a5a149c17.jpg)
Can you check this code, is it correct? (meshio-convert C:\Users\Admin\Desktop\Output Model.vtk C:\Users\Admin\Desktop\Output Model1.inp)

**Comment by keurfonluu** [comment]
```
meshio-convert C:\Users\Admin\Desktop\Output\Model.vtk C:\Users\Admin\Desktop\Output\Model1.inp
```
