### ISSUE TITLE
2D mesh does not match with input file (.inp and msh format). 

### ISSUE THREAD

**Issue by mwenceslaucosta** [nschloe/meshio#791]
Hi @nschloe ,thank you for the great tool! 

I generated a 2D mesh with gmsh and I'm trying to use meshio. 
However, I realized that the connectivity and nodes of the physical groups read by meshio are different from the input file. I import abaqus (.inp) and msh format, but had the same problem. 

My "test_mesh2.inp" file:
```
*NODE
1, 0, 0, 0
2, 50, 0, 0
3, 50, 25, 0
4, 0, 25, 0
5, 0, 12.500000000065, 0
7, 24.999999999912, 0, 0
6, 50, 12.499999999956, 0
8, 25.000000000129, 25, 0
9, 25.00000000002, 12.50000000001, 0
******* E L E M E N T S *************
*ELEMENT, type=T3D2, ELSET=Line1
1, 4, 5
2, 5, 1
*ELEMENT, type=T3D2, ELSET=Line2
9, 1, 7
10, 7, 2
*ELEMENT, type=T3D2, ELSET=Line3
3, 2, 6
4, 6, 3
*ELEMENT, type=T3D2, ELSET=Line4
11, 3, 8
12, 8, 4
*ELEMENT, type=CPS4, ELSET=Surface1
13, 1, 7, 9, 5
14, 5, 9, 8, 4
15, 7, 2, 6, 9
16, 9, 6, 3, 8
*ELSET,ELSET=BC_Neuman_1
1, 2, 
*ELSET,ELSET=forca
3, 4, 
*NSET,NSET=BC_Neuman_1
1, 4, 5, 
*NSET,NSET=forca
2, 3, 6, 
```
The result in meshio: 
```
import meshio
mesh = meshio.read("test_mesh2.inp")
```
Mesh points its ok: 
```
print (mesh.points)
```
```
[[ 0.   0.   0. ]
 [50.   0.   0. ]
 [50.  25.   0. ]
 [ 0.  25.   0. ]
 [ 0.  12.5  0. ]
 [25.   0.   0. ]
 [50.  12.5  0. ]
 [25.  25.   0. ]
 [25.  12.5  0. ]]
```
But connectivity and groups are not in agreement:

Connectivity:
```
print(mesh.cells_dict['quad'])
```
```
[[0 5 8 4]
 [4 8 7 3]
 [5 1 6 8]
 [8 6 2 7]]
```
BC_Neuman_1 Group: 
```python
print(mesh.point_sets['BC_Neuman_1'])
```
```
[0 3 4]
```
I'm sorry if I didn't understand something before I wrote. I appreciate the support and work out there.

**Comment by nschloe** [comment]
What did you expect? Looks good to me.

**Comment by mwenceslaucosta** [comment]
> What did you expect? Looks good to me.

I was hoping to receive the following connectivity:

13,1, 7, 9, 5
14, 5, 9, 8, 4
15, 7, 2, 6, 9
16, 9, 6, 3, 8


Or

13,0, 6, 8, 4
14, 4, 8, 7, 3
15, 6, 1, 5, 8
16, 8, 5, 2, 7

**Comment by nschloe** [comment]
The first column is just a running index, so that goes away. Note also that the points are not in consecutive order in the file:
```
[...]
5, 0, 12.500000000065, 0
7, 24.999999999912, 0, 0
6, 50, 12.499999999956, 0
8, 25.000000000129, 25, 0
[...]
```

**Comment by mwenceslaucosta** [comment]
Thank you.  I hadn't seen it.  :))
