### ISSUE TITLE
Multi-regions created from Abaqus .inp file to vtk

### ISSUE THREAD

**Issue by anufagbemi** [nschloe/meshio#792]
I have an INP file I am trying to convert to vtk. The file already has multiple regions included but when I try to convert it to vtk, this information is not included and everything is just merged into one region. Based on the discussion in [#175](https://github.com/nschloe/meshio/issues/175), were you able to address this issue? Thanks. 
I included an example file.
[AllRegions_2.grid.inp.zip](https://github.com/nschloe/meshio/files/4536883/AllRegions_2.grid.inp.zip)

**Comment by nschloe** [comment]
Looks correct actually:
```
meshio-info AllRegions_2.grid.inp
```
```
<meshio mesh object>
  Number of points: 20372
  Number of cells:
    tetra: 18914
    tetra: 88036
    tetra: 428
    tetra: 1570
    tetra: 289
    tetra: 756
    tetra: 33
    tetra: 33
    tetra: 9
    tetra: 9
    tetra: 6
    tetra: 5
    tetra: 2
  Cell sets: Pores, Solid
```

**Comment by anufagbemi** [comment]
The default output of the conversion (after running meshio-convert) seems to be binary. I then tried to view the file in paraview to see the different mat_ids or region_ids. But there was no distinction between both.

**Comment by nschloe** [comment]
Ah, okay. That's because no format other than Abaqus and gmsh 4.1 have support for cell sets. Most have cell data ("function") or something like that. There is a method on the mesh object, `sets_to_int_data()` which converts it, but you can't call it from the command line.

**Comment by anufagbemi** [comment]
Alrighty, I think I got that figured out. Thanks.
