### ISSUE TITLE
Could not read VTU file with binary data when header is encoded separately

### ISSUE THREAD

**Issue by MuellerSeb** [nschloe/meshio#793]
I was playing around with vtu meshes with different appended data formats, and it seems, that meshio assumes the header to be encoded with the following data (uncompressed, base64) in the appended section (maybe even in data-array sections). So I couldn't load the following mesh:
[example](http://www.earthmodels.org/software/vtk-and-paraview/vtk-file-formats/vox8_binary_appended.vtu)

Isn't that file written correctly? Paraview was able to read it.

**Comment by MuellerSeb** [comment]
I guess we could check the string of the appended data, if there are one or two `=` after the header.

**Comment by MuellerSeb** [comment]
The difference in encoding is demonstrated here:
```python
import base64
import numpy as np

vtu_to_numpy_type = {
    "Float32": np.dtype(np.float32),
    "Float64": np.dtype(np.float64),
    "Int8": np.dtype(np.int8),
    "Int16": np.dtype(np.int16),
    "Int32": np.dtype(np.int32),
    "Int64": np.dtype(np.int64),
    "UInt8": np.dtype(np.uint8),
    "UInt16": np.dtype(np.uint16),
    "UInt32": np.dtype(np.uint32),
    "UInt64": np.dtype(np.uint64),
}
numpy_to_vtu_type = {v: k for k, v in vtu_to_numpy_type.items()}

header_type = "UInt32"
data = np.arange(2, dtype=np.float64)

data_bytes = data.tostring()
# collect header
header = np.array(
    len(data_bytes), dtype=vtu_to_numpy_type[header_type]
)
print(base64.b64encode(header.tostring() + data_bytes).decode())
print(base64.b64encode(header.tostring()).decode() + base64.b64encode(data_bytes).decode())
```

Which gives:
```
EAAAAAAAAAAAAAAAAAAAAAAA8D8=
EAAAAA==AAAAAAAAAAAAAAAAAADwPw==
```

where the first one is in the way meshio exports data.

**Comment by MuellerSeb** [comment]
So if `header_type == "UInt32"` we should check if the 7. and 8. character is `=` and if `header_type == "UInt32"` we should check if the 12. character is `=` to determine if the header was encoded separately.

**Comment by nschloe** [comment]
I can't recall too well, but I thought the `=`s where just blanks to fill the block if the data is not enough. So if there was more header data, there'd be no `=`. Could this be?

**Comment by MuellerSeb** [comment]
Yep, they are added to make the last encoded block contain four Base64 characters.
When the header is encoded separately, they are added to make it a 8-character or 12-character string.

**Comment by nschloe** [comment]
Okay, yes. So does paraview open both variants, header + data encoded together and encoded separately?

**Comment by MuellerSeb** [comment]
Yes, I can open both.

**Comment by nschloe** [comment]
[The format](https://vtk.org/wp-content/uploads/2015/04/file-formats.pdf) (page 16) isn't too clear about it. Well, if paraview can open it, so should meshio. Do you want to prepare a PR? A comment here and there would be in order, perhaps with a link to this report.

**Comment by c-abird** [comment]
@MuellerSeb I might have a fix for this. However, the mesh you attached does lead to another problem with meshio, since it seams to implement an unsupported cell type (11). Were you able to read it after manually fixing the strings?
