### ISSUE TITLE
XDMF TImeSeriesWriter in "append" mode? 

### ISSUE THREAD

**Issue by marandra** [nschloe/meshio#796]
Is it possible to open an existing xdmf file (with time series data), and append data of a new timestep?

In my tests it is apparently not possible to add a new dataset once I left the "with" environment. Is there any other way to achieve it?

Thanks

**Comment by keurfonluu** [comment]
Could you provide a sample code?

Usually, you should be able to append data (whatever you mean) and write it.

```python
with meshio.xdmf.TimeSeriesReader(filename) as reader:
    points, cells = reader.read_points_cells()
    tsteps, point_data, cell_data = [], [], []
    for k in range(reader.num_steps):
        t, pdata, cdata = reader.read_data(k)
        tsteps.append(t)
        point_data.append(pdata)
        cell_data.append(cdata)

# Do whatever you want with point_data and/or cell_data

with meshio.xdmf.TimeSeriesWriter(filename) as writer:
    writer.write_points_cells(points, cells)
    for t, pdata, cdata in zip(tsteps, point_data, cell_data):
        writer.write_data(t, point_data=pdata, cell_data=cdata)
```

**Comment by marandra** [comment]
What I am trying to do is to compute and save `pdata` in an initial time step (nr `1`):

```python
with meshio.xdmf.TimeSeriesWriter(filename) as writer:
    writer.write_points_cells(points, cells)
    writer.write_data(1, point_data=pdata)
```

Then later (another session) I would like to compute new `pdata` in a time step nr `2` and "append it" (setting an imaginary mode="append") to the existing xdmf file:

```python
with meshio.xdmf.TimeSeriesWriter(filename, mode='append') as writer:
    writer.write_points_cells(points, cells)
    writer.write_data(2, point_data=pdata)
```
At the moment, when I write to an existing xdmf file, it gets overwritten, keeping only data corresponding to time step 2. 

I have tried several workarounds that like reading and writing data of previous time steps, keeping data in memory during simulation, saving fields to an auxiliary hdf5 file, or just keeping the last time step, but I am trying to avoid them as I am planning on generating big files in long simulations. Does it make sense?

**Comment by keurfonluu** [comment]
There is no ``append`` mode, as far as I know. You have to rewrite all the time steps.

```python
with meshio.xdmf.TimeSeriesWriter(filename) as writer:
    writer.write_points_cells(points, cells)
    writer.write_data(1, point_data=pdata)

    pdata2 = f(pdata)  # Compute data for next time step
    writer.write_data(2, point_data=pdata2)
```

**Comment by marandra** [comment]
I see. Not a big deal in comparison to my gains for switching to meshio. Thanks for your help.
