### ISSUE TITLE
complex data in gmsh

### ISSUE THREAD

**Issue by rclUPC** [nschloe/meshio#798]
Hi, 
I am trying import a grid with data from a gmsh file. The problem is that the data ara complex numbers, and the importer does not read it. It should be easily implemented, since in the new version of numpy (1.18), the function `fromfile()` can read complex numbers.

**Comment by nschloe** [comment]
As always, we need a mesh file to reproduce the issue.

**Comment by rclUPC** [comment]
No problem, Please find it attached.
[dataWithMesh.msh.zip](https://github.com/nschloe/meshio/files/4587353/dataWithMesh.msh.zip)

**Comment by nschloe** [comment]
When trying to open this in gmsh, the geometry loads but not the data. Instead, I get
```
Could not read data in msh file
```
![screenshot](https://user-images.githubusercontent.com/181628/89709934-7ed23200-d97f-11ea-9c78-3972caf54bbb.png)

Something is off.

**Comment by nschloe** [comment]
And by the way you can get much better-quality sphere meshes with https://github.com/nschloe/meshzoo#sphere-surface and optimesh. https://github.com/nschloe/optimesh#surface-mesh-smoothing

**Comment by nschloe** [comment]
Closing for lack of response. Feel free to reopen at any time.
