### ISSUE TITLE
add support for permas file format

### ISSUE THREAD

**Issue by nschloe** [nschloe/meshio#8]

**Comment by nilswagner** [comment]
A short description for nodal points and elements is attached.
[element.pdf](https://github.com/nschloe/meshio/files/34196/element.pdf)
[coor.pdf](https://github.com/nschloe/meshio/files/34197/coor.pdf)

**Comment by nilswagner** [comment]
http://chunk.io/f/1bfae3c763814b9caf4e4baade508683
http://chunk.io/f/eadfebd9494245f3a84734cc0591cb45

**Comment by nschloe** [comment]
Thanks @nilswagner , I've added it to the branch. The only thing that's missing now is a `read` method for PERMAS.

**Comment by nilswagner** [comment]
A rudimentary read method is added. 
http://chunk.io/f/2d6b33012bba45f4a11c3c669e428b1d
http://chunk.io/f/593eaa5167ee4ad0a928fb4f828798a1
http://chunk.io/f/339b1fbcf0b64457a02553cef607886d

**Comment by nschloe** [comment]
Thanks, I've added this to branch. 

Now, I'm getting
```
UnboundLocalError: local variable 'elems' referenced before assignment
```
when trying to read http://chunk.io/f/59814639d5b14ca4bfca9cad78ea499a.

**Comment by nilswagner** [comment]
Workaround : Please avoid exclamation marks followed by $COOR and $ELEMENT, i.e.

$ENTER COMPONENT NAME = DFLT_COMP DOFTYPE = DISP MATH
! 
    $STRUCTURE
! 
! Number of nodes = 4
! 
        $COOR NSET = ALL_NODES
               1 +0.000000000000000 +0.000000000000000 +0.000000000000000
               2 +1.000000000000000 +0.000000000000000 +0.000000000000000
               3 +1.000000000000000 +1.000000000000000 +0.000000000000000
               4 +0.000000000000000 +1.000000000000000 +0.000000000000000
!
! Number of elements = 2
!
! 
        $ELEMENT TYPE = TRIA3 ESET = TRIA3
               1        1        2        3
               2        1        3        4
!
    $END STRUCTURE
!
$EXIT COMPONENT
!
$FIN


http://chunk.io/f/2519bf011e1a4efe86bdd8512a59383c

**Comment by nilswagner** [comment]
PERMAS added to README.md

http://chunk.io/f/83fbbc36d72d4774b6308d1a135e4e04

**Comment by nilswagner** [comment]
Documentation for element type TET4 added.
http://chunk.io/f/c066f537954643eeb63f9f25ee82485f

**Comment by nilswagner** [comment]
Documentation for element type TRIA3 added.
http://chunk.io/f/042859e2537d49fea38577b0cc13dd68

**Comment by nschloe** [comment]
The reader should be able to read what the writer wrote, so that would need updating I guess.

**Comment by nilswagner** [comment]
Done
http://chunk.io/f/19aed170ecb14f81ba5b2f6862b9bf26

**Comment by nilswagner** [comment]
Node and element IDs must be greater than zero in PERMAS.

I do not understand the manipulations 

                for key in elems:
                    # Subtract one to account for the fact that python indices
                    # are 0-based.
                    elems[key] = numpy.array(elems[key], dtype=int) - 1

        for k, c in enumerate(cells):
            n = len(c)
            form = '%d %d 0 ' + ' '.join(n * ['%d']) + '\n'
            fh.write(form % ((k+1, type_to_number[n]) + tuple(c + 1)))

msh_io.py

**Comment by nschloe** [comment]
NumPy arrays are by default 0-based, so cell with a node array
```python
nodes = [
  [0.0, 0.0], 
  [1.0, 0.0], 
  [1.0, 1.0], 
  [0.0, 1.0]
  ]
```
the cells have to be
```python
cells = [
  [0, 1, 2],
  [0, 2, 3]
  ]
```
and not
```python
cells = [
  [1, 2, 3],
  [1, 3, 4]
  ]
```
as is the case for Gmsh, for example.

**Comment by nilswagner** [comment]
Finally I got it. Attached are permas_io.py, msh_io.py and README.md
http://chunk.io/f/e770421018aa495783e67b1861b01241
http://chunk.io/f/31cccd741f204877a28c39aebc6d4ab0
http://chunk.io/f/2ad1dc594a1e492bb62a90d18a988e82

**Comment by nschloe** [comment]
I've merged this since the tests are passing, but in the future this module needs more work. For example, for no reason, 1M points are allocated:
```python
points = numpy.empty((1000000, 3))
```
I guess the module breaks if there are more points? We'll see about that later.

**Comment by nilswagner** [comment]
Dynamic allocation is added.
http://chunk.io/f/e31f52bb074349f98cce9859a220fefc

**Comment by nschloe** [comment]
Thx; included and released. https://pypi.python.org/pypi/meshio
