### ISSUE TITLE
SU2 mesh format support

### ISSUE THREAD

**Issue by themrdjj** [nschloe/meshio#801]
SU2 is a popular open source CFD code with its own mesh format ([https://su2code.github.io/docs_v7/Mesh-File/](https://su2code.github.io/docs_v7/Mesh-File/)). GMSH itself can already output .su2 mesh files but it seems like neither pygmsh nor meshio can do so at the moment. Or am I missing something?

**Comment by keurfonluu** [comment]
Since the format is enoughly documented and appears to be easy to implement, I took a first stab at it on my [fork](https://github.com/keurfonluu/meshio/blob/su2/meshio/su2/_su2.py).

I can read the sample file *square.su2*, but I don't think it's exhaustive enough. Can you provide several sample files?

**Comment by themrdjj** [comment]
There is a [test case repository](https://github.com/su2code/TestCases) which contains plenty of examples of meshes, for instance [this](https://github.com/su2code/TestCases/blob/master/polar/naca0012/mesh_NACA0012_inv.su2) airfoil mesh. Does that help? I would love to contribute to this but I think it goes beyond my current skills regarding meshes.

**Comment by nschloe** [comment]
@themrdjj We're all amateurs in this. If you want to contribute somehting, I bet @keurfonluu can help you get started. It's actually fun to get meshio to work with meshes that didn't work before.

**Comment by keurfonluu** [comment]
> There is a [test case repository](https://github.com/su2code/TestCases) which contains plenty of examples of meshes, for instance [this](https://github.com/su2code/TestCases/blob/master/polar/naca0012/mesh_NACA0012_inv.su2) airfoil mesh. Does that help? I would love to contribute to this but I think it goes beyond my current skills regarding meshes.

I am able to read the airfoil sample file among other files. So I guess the reader is good now.
If you wish to contribute, you can copy my code and try to add the writer and tests and submit a PR. I can help if you are stuck. If you don't have time, it's fine, I can do it, no worry.

`meshio` is a well organized project that will teach you a lot about good coding practice which is a valuable skill nowadays.

**Comment by themrdjj** [comment]
Alright, I'm going to try to make the writer in the coming days. Let's see how far I can get.

@keurfonluu So can I just copy the _su2.py file from your meshio fork to my own meshio fork, continue working on there and then create a PR from there?

What kind of tests should I implement? I don't have much experience with Pytest. Also, when I run "pytest" with the current state of the repository, I already get 38 fails. Is that normal?

**Comment by keurfonluu** [comment]
> @keurfonluu So can I just copy the _su2.py file from your meshio fork to my own meshio fork, continue working on there and then create a PR from there?

Basically, yeah. Copy *su2* folder, import `su2` submodule in parent's `__init__.py` to register the new format. Also, please add and commit `*.su2 filter=lfs diff=lfs merge=lfs -text` in *.gitattributes* file before committing any test file.

> What kind of tests should I implement? I don't have much experience with Pytest. Also, when I run "pytest" with the current state of the repository, I already get 38 fails. Is that normal?

Look at how the tests are written for other formats. Two simple tests you can write:
- add test files and make sure they are correctly imported,
- create a `meshio.Mesh` from scratch, write it and read it back, make sure that the mesh is still the same. Usually, we use the sample `meshio.Mesh` in `helpers.py`.

**Comment by keurfonluu** [comment]
> Also, when I run "pytest" with the current state of the repository, I already get 38 fails. Is that normal?

Forgot to answer that part... you are probably missing the test files. Running `git lfs pull` should do the trick.

**Comment by keurfonluu** [comment]
@themrdjj Any progress? If you don't have spare time, it's totally fine, I can take care of it ;)

**Comment by themrdjj** [comment]
Yeah those deadlines for uni ended up being quite demanding, so maybe it's best if you take over. I will definitely take a close look at your PR though! :slightly_smiling_face:

**Comment by ChristosT** [comment]
Hi, I was also interested on that a while ago and I started working on it back in May. It has many similarities to the vtk format so I reused some parts from there. Its not done yet but the reader should more or less work. https://github.com/ChristosT/meshio/tree/add_su2_support

If I find time I will try to complete it soon.
