### ISSUE TITLE
Install Paraview plugin on Windows 10 and Paraview 5.8

### ISSUE THREAD

**Issue by Jimbles** [nschloe/meshio#805]
Hi there! I was wondering what the correct installation is for the plugin on Windows 10? I installed the latest binary version of Paraview 5.8 with Python 3.7. 
I cloned the `meshio` repo into `pv_dir\bin\plugins` but when i try to add the plugin it gives the error  `No module named 'meshio'`. 

I added the `meshio` directory into `pv_dir\bin\lib` and it seems to find it (verified in python shell) but it then gives the error saying it cant find `importlib_metadata`. I guess this is because paraview was built with Python 3.7? Do I keep adding libraries like this until paraview is happy or there a better way to add all the dependencies? 

Thanks again for any help you can offer!

**Comment by nschloe** [comment]
Best install meshio with pip.

**Comment by Jimbles** [comment]
Hey! I have meshio installed through pip, but I wasn't aware you could install it to a specific directory. So using the following commands worked for me.

```
pip install meshio[all] --target='C:\Program Files\ParaView 5.8.0-Windows-Python3.7-msvc2015-64bit\bin\Lib' --upgrade

pip install importlib_metadata --target='C:\Program Files\ParaView 5.8.0-Windows-Python3.7-msvc2015-64bit\bin\Lib' --upgrade
```

Thanks very much!
