### ISSUE TITLE
Meshio seems to modify ElementTree, which breaks svgwrite (an external package)

### ISSUE THREAD

**Issue by tmolteno** [nschloe/meshio#806]
Hi There,

I have a rather puzzling bug in my testharness (https://travis-ci.org/github/tmolteno/disko/jobs/686063990) which can be fixed by uninstalling meshio.  My code (https://github.com/tmolteno/disko)  uses dmsh for mesh generation which indirectly includes meshio.

It appears that, in meshio/_common.py,  the built-in ElementTree _serialize_xml method is substituted around line 181...

```
ET._original_serialize_xml = ET._serialize_xml


def _serialize_xml(write, elem, qnames, namespaces, short_empty_elements, **kwargs):
    if elem.tag == "![CDATA[":
        write("\n<{}{}]]>\n".format(elem.tag, elem.text))
        if elem.tail:
            write(ET._escape_cdata(elem.tail))
    else:
        return ET._original_serialize_xml(
            write, elem, qnames, namespaces, short_empty_elements, **kwargs   ## Here's the error
        )


ET._serialize_xml = ET._serialize["xml"] = _serialize_xml    # Here's the substitution
```

This causes an error when svgwrite tries to use elementTree to serialize XML:

```
TypeError: _serialize_xml_with_CDATA_support() takes 4 positional arguments but 5 were given

../../../virtualenv/python3.6.7/lib/python3.6/site-packages/meshio/_common.py:177: TypeError
```

I'm a little unsure of what is going on here, (a travis-ci log is available at https://travis-ci.org/github/tmolteno/disko/jobs/686063990).  It appears that any software that imports meshio (even indirectly and never calling its methods) will result in a modified elementTree that can trigger this error when it expected to call the original elementTree code for serializing XML. 

This happens in python 3.6, 3.7 and 3.8. Is there anything I can do to avoid this? I'm not even sure meshio is doing anything wrong here. Is it calling the original serialize_xml with the wrong number of arguments?

Kind Regards
Tim

**Comment by nschloe** [comment]
meshio indeed messes around with `ET.serialize_xml`, according to https://stackoverflow.com/a/30019607/353337. No idea if this is wrong, but seems like it if it causes trouble for you.

**Comment by tmolteno** [comment]
Brilliant thank you!

**Comment by nschloe** [comment]
Okay, I've looked at the critical part and I really didn't like the hack, so I removed it. Should be fine now. This cost us field data for XDMF, but we'll just have to come up with something sensible then.

**Comment by tmolteno** [comment]
I was initially very puzzled by the bug, as I didn't realize one could modify a function inside a different (possibly built-in) python module.  I just looked to see how svgwrite does it, and see now that theyre is doing the same thing...https://github.com/mozman/svgwrite/blob/master/svgwrite/etree.py.  I might submit a bug report there too!

**Comment by nschloe** [comment]
Indeed, global variable/function changes are evil. Feel free to point to this issue as well.
