### ISSUE TITLE
Support for VTU Polygon and Polyhedron cells

### ISSUE THREAD

**Issue by keileg** [nschloe/meshio#809]
I am tempted to implement support for VTU Polygons and Polyhedrons, but I have a question before I give it a go: It seems the number of nodes per cell must be detected on a cell-by-cell basis, similar to what done for polygons in the VTK filter:
https://github.com/nschloe/meshio/blob/27dee2064caa47c4e50da45af7c50119c7bd3c52/meshio/vtk/_vtk.py#L520-L527
As noted when support for VTK polygons were first introduced  #323, this is not very practical for many reasons. My question is if nevertheless is an acceptable approach, if you have suggestions for other approaches, or if you prefer not to have this as part of the package to avoid the additional entropy?

**Comment by nschloe** [comment]
A little support for something is better than none at all, so just give it a go.

**Comment by keileg** [comment]
Very good. I will approach this in the coming days / weeks then, and post a pull request if it works. For now, I'll close this issue.

Thanks.
