### ISSUE TITLE
WARNING:root:Zone specification not supported yet. Skipping. error message when reading ansys .msh mesh

### ISSUE THREAD

**Issue by rob-777** [nschloe/meshio#815]
Hello,
as I try to read an ansys .msh mesh with 
` meshio-convert -i ansys notmymesh.{msh,vtk} `
I get the following error
`WARNING:root:Zone specification not supported yet. Skipping.`
Sorry, I do not own the mesh so it's a little difficult to upload it. I think the error message does not represent an issue, but..is the ability to read zone specification coming soon ? 
Thanks

**Comment by nschloe** [comment]
> but..is the ability to read zone specification coming soon ?

Nothing planned by myself, but perhaps other people. PRs are always welcome.
