### ISSUE TITLE
Troubles reading .stl mesh

### ISSUE THREAD

**Issue by tdiorio** [nschloe/meshio#818]
Hi all,

I am having troubles reading/storing information from my .STL file. I am reading a mesh into my Jupyter-Notebook .ipynb file using `mesh = meshio.read("SY_QuadBL.stl", file_format="stl")`

and I can see that the mesh is actually populated with `print(mesh.cells, mesh.points)`:

```
[CellBlock(type='triangle', data=array([[    0,     1,     2], [    3,     4,     0], [    0,     5,     6], ..., 
[ 0.03745019  0.06289897  0.03722724] [ 0.03745019  0.06289897  0.03722724] [ 0.03615657  0.06152926  0.03722724]]
```

However, when I attempt to use the mesh to construct a `V=VectorFunctionSpace(mesh, 'Lagrange', degree=2)` with FEniCS, I get the following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-29-fe2f76879803> in <module>
      2 f = Constant((0,-rho_g))
      3 
----> 4 V=VectorFunctionSpace(mesh, 'Lagrange', degree=2)
      5 du = TrialFunction(V)
      6 u_ = TestFunction(V)

/usr/lib/python3/dist-packages/dolfin/function/functionspace.py in VectorFunctionSpace(mesh, family, degree, dim, form_degree, constrained_domain, restriction)
    216 
    217     # Create UFL element
--> 218     element = ufl.VectorElement(family, mesh.ufl_cell(), degree,
    219                                 form_degree=form_degree, dim=dim)
    220 

AttributeError: 'Mesh' object has no attribute 'ufl_cell'
```
Is there an obvious step I'm missing here that's not correctly storing the cell data? If this is a question better suited for the FEniCS community that's a fair answer too.

Thanks,
Tyler

**Comment by nschloe** [comment]
Please make yourself familar with GitHub formatting and edit your post accordingly.

**Comment by tdiorio** [comment]
@nschloe Sorry about that, it should be better formatted now.

**Comment by nschloe** [comment]
Fenics and meshio mesh types are completely different. You'll need to convert first.

**Comment by tdiorio** [comment]
Ok got it, I didn't realize that. I guess that's where I'm unsure of how to convert to the FEniCS type.

**Comment by nschloe** [comment]
Fenics used to not have a method for importing a mesh by its points/cells, so I usually just wrote the mesh to xdmf and read it from fenics.

**Comment by tdiorio** [comment]
Thank you for your help, I was able to get it working from your tips. Really appreciate it.
