### ISSUE TITLE
Gmsh: only mesh, no data?

### ISSUE THREAD

**Issue by lonelykid** [nschloe/meshio#82]
Although you have point_data and cell_data information, seems like you didn't really take care of that in your code (Mostly I mean Gmsh format). If you don't have plans to add this feature. I will do this myself. Basicly I want to transform between our own FEM format/.msh format/abaqus .inp format/VTK format.

One problem is that VTK can't handle element node data as is in the .msh format. My work-around is to add repeated points on shared nodes. But visualization tools such as Paraview can't handle it very well. Those filters tends to merge coincident points and average those points. Actually I found your project when searching for better solutions. Any suggestions would be appreciated.

**Comment by nschloe** [comment]
Thanks for the suggestion!

Yep, the msh format is one of the hardest to work with. Frankly speaking I don't know why it was created in the first place (other options were there at the time), but here we are. My advice for you would be to _not_ use the msh format.

If you can't get around, though, adding node data to a gmsh mesh would probably be in order. I'm not sure about the format specification right now. are node values tag data on nodes?

**Comment by nschloe** [comment]
Let me close this bug for lack of feedback. Feel free to reopen with some info on how gmsh stores data.

**Comment by perrinmeyer** [comment]
Hi.  Currently I'm struggling with gmsh $NodeData and trying to convert it to a field format that visIT will read (so far no luck.  Many conversion tools (and even gmsh) can save the mesh to a file format that visIT can read, but no luck with the field data. 

I agree that the gmsh $NodeData is format is not good (it reminds me of old FORTRAN punch card formats where the data had to be in the correct column...). 

currently my workflow is: great .geo file by hand (took me a while, but I'm pretty good at it by now)

I then create a gmsh msh file for the mesh (using the command line)

I wrote a simple parser to read the msh file into Julia (matlab like open source language).  I do my computations in Julia (currently node based), and then I write out the input msh with the $NodeData  sections appended to the end, and then I visualize my results back in gmsh.  However, I would prefer to visualize in visiT, and thus my quest for  mesh converter .... 

I'm happy to share my julia code if that would help.  

For my needs, all I really need is a way to feed meshio a gmsh msh file (with mesh), and raw txt field data, and then have meshio convert it to a format that I can read into visIT.  Is there currently a way to do this? 

i.e. the command line would look something like

meshio -gm gmesh_mesh.msh  -rawfield_ASCII julia_fielddata.txt  --output-format ansys-binary output.ans (or something like that). 

about ten years ago i used python and scipy for a project, but im not a good python coder by any means, but if there is some way I could help I'd be happy to.  If you hacked the $NodeData input, I could use that as a template for the $ElementData, or testing, etc. 

thanks!

perrin meyer

**Comment by nschloe** [comment]
> For my needs, all I really need is a way to feed meshio a gmsh msh file (with mesh), and raw txt field data, and then have meshio convert it to a format that I can read into visIT. Is there currently a way to do this?

The Gmsh I/O still doesn't respect point, cell, or field data, so no, currently there's no way to do this. Someone set out getting this to work a few days ago, but I'm not sure about the progress here.

**Comment by nschloe** [comment]
Alright, I've added point and cell data i/o now. Check out version 1.10.5.

**Comment by perrinmeyer** [comment]
Thanks!  It worked!!!! I was able to take a gmsh msh file with nodal field data, convert it to vtu, and import it into both paraview and visIT!!! 
![paraview_gmsh_meshio_vtu](https://user-images.githubusercontent.com/647534/34185768-16fc754a-e4dc-11e7-82d2-fd1fe09afe08.png)

(this is a test acoustic visualization of three point sources)

**Comment by nschloe** [comment]
Good job @perrinmeyer. You might want to check out [pygmsh](https://github.com/nschloe/pygmsh) (another project of mine) if you're really creating your meshes with gmsh. pygmsh comes with proper Lloyd smoothing by default which will make your mesh a lot smoother.
