### ISSUE TITLE
Uncomplete cell markers when generating GMSH mesh using Meshio

### ISSUE THREAD

**Issue by DuyDucNguyen** [nschloe/meshio#821]
Hi everyone

I have an issue with the markers when generating GMSH from text files using Meshio. Precisely, I have mesh information stored in text files like ‘node1.txt’ storing nodes coordinates, ‘elements1.txt’ storing mesh connectivity and makers. The code below will used for generating GMSH mesh.

Files: [node1.txt, element1.txt](https://drive.google.com/open?id=129kU5SeLhplDt2onREt6BHaZdt3c3QzB)

```python
import meshio
import numpy as np

# read data
list_nodes = np.loadtxt('nodes1.txt', delimiter=" ")
list_elements = np.loadtxt('elements1.txt', dtype="i", delimiter=" ")

# define points 
points = list_nodes

# define cells
cells = [ ("triangle", list_elements[:, 0:3]-1) ]

# define cell_data
cell_data_value = []
e1 = list_elements[:, -1][0]
tmp = []

# get maker
for e in list_elements[:, -1]:
    if e == e1:
        tmp.append(e)
    else:
        cell_data_value.append(np.asarray(tmp))
        e1 = e
        tmp = []
        tmp.append(e)

cell_data = {'gmsh:physical': cell_data_value}

# generate gmsh mesh
meshio.write_points_cells(
    "new_machine.msh",
    points,
    cells,
    cell_data=cell_data
    )
```

If you know how to fix this issue, please let me know.

Best regards

![Capture_decran_85](https://user-images.githubusercontent.com/43535759/82809643-dbe43e80-9e8c-11ea-81f8-1abc427b2346.png)

**Comment by nschloe** [comment]
Note that you can use block code triple fences. Please edit your post accordingly for readability.

**Comment by DuyDucNguyen** [comment]
Hi nschloe, I updated my question. Thank you.

**Comment by keurfonluu** [comment]
I don't understand what your loop is supposed to do, but you can simply do:

```python
cell_data = {"gmsh:physical": [list_elements[:, -1]]}
```

to define your `cell_data`.

![meshio](https://user-images.githubusercontent.com/16566206/82818009-dc5fe380-9e52-11ea-99de-8bcc11786820.png)

**Comment by DuyDucNguyen** [comment]
> 
> 
> ```python
> cell_data = {"gmsh:physical": [list_elements[:, -1]]}
> ```
Thank you very much. I did think about this idea but I did not put the list_elements in brackets. :D
'cell_data = {"gmsh:physical": list_elements[:, -1]}'

**Comment by nschloe** [comment]
@DuyDucNguyen Feel free to close this issue if you have no more troubles.
