### ISSUE TITLE
VTK ASCii is formatted incorrectly or is not compatible with my reader

### ISSUE THREAD

**Issue by fluviolobo** [nschloe/meshio#822]
Hello,

First of all, this is a very useful tool so far.
I am trying to generate tetrahedral meshes from several simulation states described by point clouds.
I am having an issue writing a ASCii VTK that my reader can work with.

This is the structure of an ASCii VTK file that my reader takes
```
# vtk DataFile Version 4.2
ASCII
DATASET UNSTRUCTURED_GRID
POINTS 4 double
0.0 0.0 0.0
1.0 0.0 0.0
1.0 1.0 0.0
0.0 1.0 0.0
CELLS 2 8
3 0 1 2
3 0 2 3
CELL_TYPES 2
5 5
```
This is what I get when I use meshio;
```
# vtk DataFile Version 4.2
ASCII
DATASET UNSTRUCTURED_GRID
POINTS 4 double
0.0 0.0 0.0 1.0 0.0 0.0 1.0 1.0 0.0 0.0 1.0 0.0
CELLS 2 8
3
0
1
2
3
0
2
3
CELL_TYPES 2
5
5
```

I have tried;

```
outmesh = meshio.Mesh(points,cells)
meshio.write('out_mesh.vtk', out_mesh, binary=False)
```
and also,

```
meshio.write_points_cells('out_mesh.vtk',points, cells, binary=False)
```

I am going to attempt a workaround, just wanted to see if this had been reported or if here is something I am missing...

Thank you!

**Comment by nschloe** [comment]
Never post screen shots, they cannot be searched or copy-pasted. Please edit your post accordingly. Also make sure that that your provide completely copy-pastable code to reproduce the problem.

**Comment by keurfonluu** [comment]
I don't get what you believe is wrong with the output mesh written by `meshio`. It is still a valid mesh (it can be opened with ParaView) although `points` are defined in a single line and `cells` on multiple lines.

Do you mean that you expect an output like below?

```
# vtk DataFile Version 4.2
ASCII
DATASET UNSTRUCTURED_GRID
POINTS 4 double
0.0 0.0 0.0
1.0 0.0 0.0
1.0 1.0 0.0
0.0 1.0 0.0
CELLS 2 8
3 0 1 2
3 0 2 3
CELL_TYPES 2
5 5
```

**Comment by fluviolobo** [comment]
> I don't get what you believe is wrong with the output mesh written by `meshio`. It is still a valid mesh although `points` are defined in a single line and `cells` on multiple lines.
> 
> Do you mean that you expect an output like below?
> 
> ```
> # vtk DataFile Version 4.2
> ASCII
> DATASET UNSTRUCTURED_GRID
> POINTS 4 double
> 0.0 0.0 0.0
> 1.0 0.0 0.0
> 1.0 1.0 0.0
> 0.0 1.0 0.0
> CELLS 2 8
> 3 0 1 2
> 3 0 2 3
> CELL_TYPES 2
> 5 5
> ```
> 
> What reader are you using? It most likely is a problem related to your reader since VTK ASCII files written by `meshio` can be opened in ParaView.
> 
> Note that the fix is straightforward, though (simply replace `tofile` by `numpy.savetxt` in VTK ASCII writer).

@keurfonluu This is the problem/issue exactly. You are right, It is a reader problem. I am using FEBio , so the file import/read capabilities are not the best. I was actually just working on an implementation of `numpy.savetext()`. Glad to know I was on the right track!

**Comment by fluviolobo** [comment]
> Never post screen shots, they cannot be searched or copy-pasted. Please edit your post accordingly. Also make sure that that your provide completely copy-pastable code to reproduce the problem.

Just did! Thank you for the feedback,
