### ISSUE TITLE
Triangulation of mesh

### ISSUE THREAD

**Issue by Yoorthiziri** [nschloe/meshio#823]
Hello,

Sometimes it is not possible to convert between different mesh formats due to the inherent mesh formats. Example: a mesh format that supports unstructured mesh and a format like STL that supports only triangles. So in this case meshio will throw an arrow about that, something like:
```
meshio._exceptions.WriteError: STL can only write triangle cells (not hexahedron).
```

However, I was just thinking what if the user wants to get a triangulated mesh from, say, a quad mesh? is it a good idea to add a flag `triangulate` to `meshio-convert` so when the limitation above is encountered, the user can specify it to a triangulated mesh. My guess is that this is relatively easy to implement (Delauny triangulation, or some other algorithms given that the original author of meshio is an expert in this field).

Generaly, when I encounter this scenario, my workflow is as follows: use vtk library to triangulate the mesh using delaunay filter, then save back the mesh and use meshio to convert to STL.

Feel free to close this if it is completely irrelevant.

Thanks

**Comment by nschloe** [comment]
This is an interesting idea, but outside the scope of meshio. meshio only converts, and does nothing else. You can always write your own wrapper of course.
