### ISSUE TITLE
Removing z-dimension from mesh file

### ISSUE THREAD

**Issue by tdiorio** [nschloe/meshio#829]
Hello, I'm looking to use Meshio to convert my mesh from `STL` to `XDMF` and also remove the z-components of each point in the mesh. Is there an easy way of doing this using Meshio? 

I'm attaching my mesh (`STL` saved as `.TXT`), which is a 2D brain slice that still contains z-components rather than being restrained to the XY plane. Thank you!
[SY_QuadBL_2Dhelp.txt](https://github.com/nschloe/meshio/files/4713874/SY_QuadBL_2Dhelp.txt)

**Comment by keurfonluu** [comment]
The option `-z` is what you want:

```
meshio-convert SY_QuadBL_2Dhelp.txt SY_QuadBL_2Dhelp.xdmf --input-format stl -z
```

**Comment by tdiorio** [comment]
A quick and powerful fix! Thank you for your help, that resolved my issue.
