### ISSUE TITLE
Using meshio-convert for several files

### ISSUE THREAD

**Issue by roaasoloh** [nschloe/meshio#833]
Kindly  I would like to ask about this:
I need to read files in folder with a specific extension in order to apply on it a conversion
So to check with a specific extension like this:
```python
import os
for file in os.listdir("/mydir"):
    if file.endswith(".ply"):
what I want to do here:
os.system('meshio-convert cow.ply cow.obj ')
```

but the idea is that I will have several files with different names in `.ply` so how I may do this such that I will get the same naming in `.obj` so if it reads `cow_rotated.ply` it should make it `cow_rotated.obj` ? 
depending on the name read, the new file will have the same name with a different extension
My folder contains several `.ply` files I want to convert them directly to `.obj` not each alone.

**Comment by nschloe** [comment]
Don't call `meshio-convert` on the system level. Just `import meshio`  and use it's read and write function. Google for how to split a file name into base name and extension. (I don't know off the top of my head.)

**Comment by keurfonluu** [comment]
Use `os.path.splitext` to get the file's name without the extension.

```python
import os
import meshio

for file in os.listdir("/mydir"):
    root, _ = os.path.splitext(file)
    meshio.read(file).write(root + ".obj")
```

**Comment by roaasoloh** [comment]
Hello again
Sir @keurfonluu  I tried to do like what you mentioned but I got problem :(
I was able to read the file normally if I access it directly,
However if I tried to do it in Loop I got the problem
Here my code and the result.
```
mesh = meshio.read("/home/roaa/Desktop/PhD/Models/OwnDatabase/cow.ply")
print(mesh)

for file in os.listdir("/home/roaa/Desktop/PhD/Models/OwnDatabase/"):
   if file.endswith(".ply"):
     root, _ = os.path.splitext(file)

     print(file)
     meshio.read(file,file_format="ply")
           # .write(root + ".obj")
```
The result :
```
Traceback (most recent call last):
  File "/home/roaa/PycharmProjects/Thesis/Converting.py", line 12, in <module>
    meshio.read(file,file_format="ply")
  File "/home/roaa/anaconda3/envs/Thesis/lib/python3.7/site-packages/meshio/_helpers.py", line 57, in read
    raise ReadError("File {} not found.".format(filename))
meshio._exceptions.ReadError: File cow.ply not found.
<meshio mesh object>
  Number of points: 2903
  Number of cells:
    triangle: 5804
cow.ply

Process finished with exit code 1
```

**Comment by keurfonluu** [comment]
`os.listdir` does not return the absolute path, only the filename in the target directory. Inserting the directory path in the filename should do the trick:

```python
meshio.read("/home/roaa/Desktop/PhD/Models/OwnDatabase/" + file, file_format="ply")
```

**Comment by nschloe** [comment]
Assuming this is resolved. Feel free to reopen if not.
