### ISSUE TITLE
An off file cannot be read from an URL

### ISSUE THREAD

**Issue by empet** [nschloe/meshio#834]
I'm wondering why this ply file can be read from an URL:
```
from urllib.request import urlopen
url = 'http://people.sc.fsu.edu/~jburkardt/data/ply/airplane.ply'
respply = urlopen(url)
mesh = meshio.read(respply, file_format='ply') 
```
but when I'm trying to read an off file, `meshio` cannot identify its file format:

```
urloff= 'https://raw.githubusercontent.com/empet/Datasets/master/Meshes/tr_reg_011.off'
respoff = urlopen(urloff)
mesh = meshio.read(respoff, file_format='off')
```

Error:
```
site-packages/meshio/off/_off.py in read_buffer(f)
     24     line = f.readline()
     25     if line.strip() != "OFF":
---> 26         raise ReadError()
     27
     28     # fast forward to the next significant line

ReadError: 
```

The same file can be read when it is  saved on my system:
```
mymesh = meshio.read('Meshes/tr_reg_011.off') 
```

**Comment by nschloe** [comment]
Please attach the files, otherwise no one can reproduce the issue.

**Comment by empet** [comment]
I gave a link above to each one.

**Comment by nschloe** [comment]
I can read both files without problem:
```
meshio-info tr_reg_011.off
```
```
<meshio mesh object>
  Number of points: 6890
  Number of cells:
    triangle: 13776
```

**Comment by empet** [comment]
Have you read the off file directly from URL? I've just installed the last meshio version and the same error message persists.  
I'll close this issue, because  I can read it from my laptop, but I was curious why from URL it's thrown that error. Thanks!

**Comment by nschloe** [comment]
Your basic
```python
from urllib.request import urlopen
url = 'http://people.sc.fsu.edu/~jburkardt/data/ply/airplane.ply'
respply = urlopen(url)
```
already gives
```
urllib.error.URLError: <urlopen error [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1108)>
```
so I'd say you better fix that first.

**Comment by empet** [comment]
It' s strange because l can  read the ply file without error from Its url, but not the off file, while you can read the off file and not the ply one

**Comment by nschloe** [comment]
Fix the issue and I'll give it a spin.

**Comment by nschloe** [comment]
Okay, got it now. Your `urlopen` returns a binary buffer which the off reader can't work with yet. #878 gets you a better error message at least. If you have a good idea how to fix this, feel free to PR!

**Comment by empet** [comment]
Thanks for pointing out what's going on!!
