### ISSUE TITLE
hexahedron20 msh to vtk conversion bug

### ISSUE THREAD

**Issue by ffilotto** [nschloe/meshio#835]
My first issue was solved by reinstalling meshio.

Still, there is a problem with "_gmsh_to_meshio_order" and "_meshio_to_gmsh_order" in gmsh/common.py.

I was getting weird visualization of the hexahedron20. What I did was to swap the indeces in those functions and that solved my problem.

Before inversion:
![image](https://user-images.githubusercontent.com/40405866/84133637-b25c1300-aa47-11ea-8a30-ff4091a40a63.png)

After Inversion:
![image](https://user-images.githubusercontent.com/40405866/84133739-ce5fb480-aa47-11ea-81cc-13b13f8d625e.png)

MWE:

```
import pymesh
import meshio
import pyvista
mesh = meshio.read(r'tmp_clean.msh')

plotter = pyvista.Plotter(notebook=False)    # instantiate the plotter
plotter.add_mesh(mesh, show_edges=True)    # add a mesh to the scene
plotter.enable_cell_picking()
cpos = plotter.show(interactive =True)     # show the rendering window
```

[tmp_clean.txt](https://github.com/nschloe/meshio/files/4751365/tmp_clean.txt)

**Comment by nschloe** [comment]
Never screenshot code, always copy and paste.

**Comment by nschloe** [comment]
If you fixed it: nice. How about a PR?

**Comment by vsdelta** [comment]
> 
> 
> If you fixed it: nice. How about a PR?

I am completely new to this, sorry. I'll do.

**Comment by nschloe** [comment]
Assuming this was fixed by https://github.com/nschloe/meshio/pull/838. Feel free to reopen if not.
