### ISSUE TITLE
write to med : str object has no attribute ndim

### ISSUE THREAD

**Issue by dbpatankar** [nschloe/meshio#836]
I am using a script to generate a mesh and export it to med format. The script used to work perfectly on my ArchLinux machine which has python3 as default python. Now I have switched to Ubuntu 18.04 LTS which has python2 as default python. 

When I execute the script with default python (python2), there are no errors thrown but the output med file cannot be read by gmsh or salome. Error while opening med file on gmsh is : 
`Info    : Reading MED file V3.0.0 using MED library V4.0.0
Error   : Unable to read mesh information
Error   : Error loading 'nx4ny5nz7.med'
`

If I execute the script with python3 (which used to work on ArchLinux), gives me error at execution itself and the error is : 
`
str object has no attribute ndim
`

**Comment by dbpatankar** [comment]
The more detailed error is given below : 
`
Traceback (most recent call last):
  File "mesh3d.py", line 319, in <module>
    meshio.write(outfile, mesh, file_format='med')
  File "/home/digvijay/.local/lib/python3.6/site-packages/meshio/_helpers.py", line 144, in write
    return writer(filename, mesh, **kwargs)
  File "/home/digvijay/.local/lib/python3.6/site-packages/meshio/med/_med.py", line 331, in write
    if data.ndim <= 2:
AttributeError: 'str' object has no attribute 'ndim'
`

**Comment by nschloe** [comment]
meshio does not support Python 2. Btw on Ubuntu, `python` will always be Python 2, and it will soon go away. Always use `python3`.

**Comment by dbpatankar** [comment]
The error mentioned in the title is in python3. Hence I posted it. In the detailed traceback provided in second post, you can see that the python version used is python3. I mentioned about python2 only because I played with it as well.

**Comment by nschloe** [comment]
As always, we need an MWE to reproduce.

**Comment by dbpatankar** [comment]
Here follows a MWE or better to say MNWE. 

`
#!/usr/bin/env python3

import numpy as np
import meshio


points = np.array([
                    [0.0, 0.0, 0.0],
                    [1.0, 0.0, 0.0],
                    [1.0, 1.0, 0.0],
                    [0.0, 1.0, 0.0]
                ])

cells = { 
            'line' : np.array([
                [0, 1],
                [1, 2], 
                [2, 3],
                [3, 0]
                ]),
            'quad' : np.array([
                [0, 1, 2, 3]
                ])
        }

point_data = { 
                'point_tags' : np.array([1, 2, 2, 1])
            }


point_tags = { 
                1 : ['FIX'],
                2 : ['LOAD'],
            }


cell_data = { 
                'line' : {'cell_tags' : np.array([-10, -10, -10, -10]) },
                'quad' : {'cell_tags' : np.array([-20]) }
            }


cell_tags = { 
                -10 : ['BEAM'], 
                -20 : ['SLAB']
            }

mesh = meshio.Mesh(points, cells, point_data=point_data, cell_data=cell_data)
mesh.point_tags = point_tags
mesh.cell_tags = cell_tags

meshio.write('mwe.med', mesh)
`

So far I feel that the problem may be due to syntax of cell_data.

The above code creates a square plate with line elements on boundary. Do let me know if you need more information. I do not remember from where I got the syntax for point_data or cell_data. It would be better if one example providing syntax and format of the point_data and cell_data is provided.

**Comment by nschloe** [comment]
Thanks! More help for boiling it down:
  * Use `black` for formatting. This makes Python code look like standard.
  * It's not quite minimal yet, for example `point_tags` and `cell_tags` aren't needed to reproduce. Perhaps also `point_data` can go?

Please refine. (Usually when doing this process, you get a good idea of what the issue is.)

**Comment by dbpatankar** [comment]
If I remove point_tags and cell tags, I still get the same error. If I remove cell_data, keeping the point_data, code works. If I remove point_data and cell_data both, code works. However, I need to have tags. In fact tags/groups are the only reason I coded the mesh. So without point_data and cell_data, the mesh gets exported correctly but without any groups. These groups are used in code_aster and hence important to have in mesh.

**Comment by nschloe** [comment]
> However, I need to have tags. 

That's fair, but not the point of this report. First we'll tackle your error which has nothing to do with tag (apparently). Please post a more minimal black-formatted code.

**Comment by keurfonluu** [comment]
Note that since `meshio >= 4.0`, `cells` is no longer defined as a dict but as a list of (named)tuples (`type`, `data`). `meshio.Mesh` constructor does the conversion, though.

```python
cells = [
    ("line", np.array([[0, 1], [1, 2], [2, 3], [3, 0]])),
    ("quad", np.array([[0, 1, 2, 3]])),
]
```

Another API breaking change is that `cell_data` keys no longer refer to the cell types but the name of the data array (to be consistent with `point_data`). The values of `cell_data` dict is a list of data arrays consistent with `cells`.

```python
cell_data = {"cell_tags": [np.array([-10, -10, -10, -10]), np.array([-20])]}
```

**Comment by dbpatankar** [comment]
> Note that since `meshio >= 4.0`, `cells` is no longer defined as a dict but as a list of (named)tuples (`type`, `data`). `meshio.Mesh` constructor does the conversion, though.
> 
> ```python
> cells = [
>     ("line", np.array([[0, 1], [1, 2], [2, 3], [3, 0]])),
>     ("quad", np.array([[0, 1, 2, 3]])),
> ]
> ```
> 
> Another API breaking change is that `cell_data` keys no longer refer to the cell types but the name of the data array (to be consistent with `point_data`). The values of `cell_data` dict is a list of data arrays consistent with `cells`.
> 
> ```python
> cell_data = {"cell_tags": [np.array([-10, -10, -10, -10]), np.array([-20])]}
> ```

Thanks for this! Upon making these changes, the code works now. I can see all the groups I need. The format for this change and data structure for point_data and cell_data on the main page would help a lot. 

Thanks again!
