### ISSUE TITLE
Face Group

### ISSUE THREAD

**Issue by AlirezaBGE** [nschloe/meshio#839]
I am using meshio to convert FLAC3D  (v.7) data to VTK format.  Would it be possible to include face groups into this conversion? Attached you will find a simple model. The model contains only one surface as a fracture, represented by a group of face entities (attached picture). We may have up to 100 surfaces that represent fracture distribution in our model.

Best Regards,
Alireza Hassanzadegan

![image001](https://user-images.githubusercontent.com/53041379/84245822-edbd1700-ab05-11ea-8f18-87a83923a2e5.jpg)

**Comment by nschloe** [comment]
Ping @keurfonluu.

**Comment by keurfonluu** [comment]
Sure, I'll look into that.

**Comment by nschloe** [comment]
Fixed via #886.
