### ISSUE TITLE
Face Group Mesh

### ISSUE THREAD

**Issue by AlirezaBGE** [nschloe/meshio#840]
*FLAC3D grid produced by 3DEC 7.00 Pre-Release 118
* Di Jun 9 11:45:15 2020
*GRIDPOINTS
G 34 500 500 1000
G 33 500 500 550
G 24 500 0 1000
G 23 0 500 550
G 22 500 1000 1000
G 21 0 500 1000
G 20 1000 500 1000
G 19 500 1000 550
G 18 1000 500 550
G 17 500 0 550
G 16 1000 1000 550
G 14 0 1000 550
G 12 1000 0 550
G 10 0 0 550
G 8 1000 1000 1000
G 7 0 1000 1000
G 6 1000 0 1000
G 5 0 0 1000
G 36 500 500 0
G 35 500 500 550
G 32 500 1000 0
G 31 1000 500 0
G 30 500 0 0
G 29 500 0 550
G 28 0 500 0
G 27 1000 500 550
G 26 500 1000 550
G 25 0 500 550
G 15 1000 1000 550
G 13 0 1000 550
G 11 1000 0 550
G 9 0 0 550
G 1 0 0 0
G 2 1000 0 0
G 3 1000 1000 0
G 4 0 1000 0

*ZONES
Z T4 61 5 24 10 21
Z T4 79 6 20 18 24
Z T4 78 6 18 12 24
Z T4 71 7 21 14 22
Z T4 69 8 22 16 20
Z T4 64 10 23 21 24
Z T4 13 10 24 17 23
Z T4 35 12 18 17 24
Z T4 22 14 22 21 23
Z T4 23 14 23 19 22
Z T4 50 16 22 19 20
Z T4 47 16 20 19 33
Z T4 41 16 18 20 33
Z T4 44 17 33 23 24
Z T4 43 17 24 18 33
Z T4 37 18 24 20 33
Z T4 34 19 33 22 23
Z T4 10 19 33 20 22
Z T4 31 20 33 24 34
Z T4 19 20 34 22 33
Z T4 28 21 24 23 34
Z T4 16 21 23 22 34
Z T4 5 22 34 23 33
Z T4 14 23 34 24 33
Z T4 103 4 32 26 28
Z T4 102 4 26 13 28
Z T4 98 3 31 27 32
Z T4 97 3 27 15 32
Z T4 93 2 30 11 31
Z T4 33 1 28 9 30
Z T4 87 9 30 28 29
Z T4 32 9 28 25 29
Z T4 81 11 30 29 31
Z T4 54 11 29 27 31
Z T4 21 13 26 25 28
Z T4 18 15 27 26 32
Z T4 2 25 29 28 35
Z T4 53 25 28 26 35
Z T4 52 26 35 28 32
Z T4 7 26 32 27 35
Z T4 55 27 32 31 35
Z T4 3 27 31 29 35
Z T4 26 28 36 32 35
Z T4 12 28 35 30 36
Z T4 24 28 35 29 30
Z T4 57 29 31 30 35
Z T4 39 30 35 31 36
Z T4 76 31 35 32 36

*GROUPS

*FACES
F T3 58 35 25 26
F T3 59 35 26 27
F T3 57 35 29 25
F T3 55 26 15 27
F T3 53 25 13 26
F T3 51 27 11 29
F T3 49 29 9 25
F T3 60 35 27 29

* FACE GROUPS
FGROUP 2_1 slot jset
 58 59 57 55 53 51 49 60

**Comment by nschloe** [comment]
What is this?

**Comment by AlirezaBGE** [comment]
Hi there,

I understood that I should put my request on GitHub. Did I make it Right?
The mesh file could not be loaded in GitHub so I past it into issue.  I
know it was not elegant. I can delete it if you want.

Best regards,
Alireza

Nico Schlömer <notifications@github.com> schrieb am Mi., 10. Juni 2020,
10:44:

**Comment by nschloe** [comment]
Please attach the mesh to the other issue, best as a zipped file. (zips are allowed I think)
