### ISSUE TITLE
Writing `cell_sets` in Abaqus

### ISSUE THREAD

**Issue by bhaveshshrimali** [nschloe/meshio#846]
Hi,
Could anyone elucidate what the below lines (337-348) are trying to achieve? 
https://github.com/nschloe/meshio/blob/0d79fea36d2f4b0fa913f3a598894842b2804880/meshio/abaqus/_abaqus.py#L337

I understand that this was partly (reading the cell_sets from `*Elset`) an outcome of the discussion in #749 . But now that I think, writing the cell_sets may be missing something here. For instance consider the following mesh (a circle of radius `0.3` inside a unit square) comprising of `6-noded` triangles

![paraview_Ordered](https://user-images.githubusercontent.com/22624037/84821392-ab517980-afe0-11ea-99b8-194156aa59cd.png)

Writing the `cell_sets` as follows doesn't seem to work:

```python3
import numpy as np
import meshio 

def calcMidPoint(elemPoints, pts):
    elem_points = pts[elemPoints[:3],:2]
    return 1./3*elem_points.sum(axis=0)

msh = meshio.xdmf.read("meshTrial.xdmf")
cell_sets={
    "Part1":[],
    "Part2":[]
    }
  

for k, cell in enumerate(msh.cells[0].data):
    cell_dist = np.linalg.norm(calcMidPoint(cell, msh.points) - np.array([0.5, 0.5]))
    if cell_dist < 0.3:
        cell_sets["Part1"].append(k)
    else:
        cell_sets["Part2"].append(k)

mesh = meshio.Mesh(msh.points, cells={"triangle6": msh.cells[0].data}, cell_sets=cell_sets)
meshio.write("meshTrial.inp", mesh)
```
Am I missing something here ? 
Attaching the mesh: 
[meshTrial.zip](https://github.com/nschloe/meshio/files/4788871/meshTrial.zip)

**Comment by gdmcbain** [comment]
I think `cell_sets` is the wrong shape or type (for meshio 4, although I'm not sure how much further back than that the cell_sets attribute goes).  Here it looks like `Dict[str, List[int]]` whereas it should be something more like `Dict[str, List[List[int]]`.  The outer list corresponds to the list in cells, like `msh.cells` which is a list of length one.

Similarly `cells` should be a list, but here you can just re-use `msh.cells`; thus:

```python
mesh = meshio.Mesh(msh.points, cells=msh.cells, cell_sets={k: [v] for k, v in cell_sets.items()})
```

**Comment by bhaveshshrimali** [comment]
> whereas it should be something more like `Dict[str, List[List[int]]`.

I see. Thanks! 
Do you know the rationale behind this? I mean I am finding it hard to see the purpose that the outer `List` in `List[List[int]]` serves? From what would intruitively make sense (at least to me) is that each key in `cell_sets` would contain the list of elements belonging to that set. 


> Similarly `cells` should be a list, but here you can just re-use `msh.cells`; thus:

Yes, absolutely. I should have spotted that. I think it got mixed into creating a MWE

**Comment by gdmcbain** [comment]
There's a long discussion of the rationale is and what it's not in #685.  Perhaps the most succinct statement is that of @tianyikillua ([2020-02-13](https://github.com/nschloe/meshio/issues/685#issuecomment-585382791)):

> For me the transition from a cell dict to a cell list mainly reflects the data structure of each mesh format, and not for representing regions. In many mesh formats cells are defined by consecutive blocks composed of a same cell type, period...

Your idea 

>  that each key in cell_sets would contain the list of elements belonging to that set.

is correct except that now elements ('cells') need a double index, one which block they're in and then where they are within that block.

**Comment by bhaveshshrimali** [comment]
Ah I completely missed that I could have multiple `CellBlock`s to start with. Is that what you are referring to? I think that does explain it partly. 

> There's a long discussion of the rationale is and what it's not in #685. Perhaps the most succinct statement is that of @tianyikillua ([2020-02-13](https://github.com/nschloe/meshio/issues/685#issuecomment-585382791)):

Thanks for pointing this out. I would check again once with the example in #749 (reading an `Abaqus` mesh contains both `*Elset` and `*Element, type=<>, Elset=<>`).  Although now I am sure that this would work. Although reading and rewriting the mesh would change it slightly as everything would now come under `*Elset`, but then that has nothing to do with `meshio` as such.

**Comment by gdmcbain** [comment]
> I could have multiple CellBlocks to start with. Is that what you are referring to? I think that does explain it partly.

No actually, that was what I thought in #685 but the idea is specifically not to attribute any semantics to the CellBlocks, they're just syntactic.  You could put the circle and its complement into different cellblocks but it wouldn't mean anything and you'd still need either cell_data or cell_sets to distinguish the cells. 

I think the rationale is that there are some formats (none of which I use, so I'm not too clear on this) that rely on this kind of syntactic thing; e.g. (@tianyikillua , again):

> Another reason for a list based cell blocks structure is to preserve cell ordering in the original mesh file.

The formats mentioned in #685 that do make some kind of use of CellBlocks are FLAC3D and AVS-UCD but I've never used either of them.

**Comment by bhaveshshrimali** [comment]
> No actually, that was what I thought in #685 but the idea is specifically not to attribute any semantics to the CellBlocks, they're just syntactic. You could put the circle and its complement into different cellblocks but it wouldn't mean anything and you'd still need either cell_data or cell_sets to distinguish the cells.

I see. Thanks. I have never used FLAC3D/AVS-UCD either. If cell_sets is used for those formats then it makes sense to incorporate it the way it is. 

Thanks for your help!
