### ISSUE TITLE
Nastran bdf file reading error 

### ISSUE THREAD

**Issue by ete1729** [nschloe/meshio#851]
When reading a Nastran analysis file the continuation character "+" is not correctly handled if the card is not "GRID" and leads to an assertion error in line 168 of _nastran.py
Example:

    PBAR         164       2   8842.  1.92+8 1.075+7 595194.      0.        +       
    +        -298.43     6.5 135.571     6.5 151.571   -100. 151.571    100.+       
    +         .56915  .30293      0. 

Workaround: comment all the lines starting with a "+", but it is not satisfactory :)

Correction: introduce the following change at line 167 from:

     elif keyword[0] == "+":
            assert cell is not None
            cell.extend(chunks[1:])
to:

    elif keyword[0] == "+" and cell is not None:
       cell.extend ( chuncks[1:])

**Comment by nschloe** [comment]
Can you prepare a PR?

**Comment by nschloe** [comment]
Ping @tianyikillua.

**Comment by tianyikillua** [comment]
Ok will have a look :-)
