### ISSUE TITLE
Slicing Error when writing XDMF (Gmsh to FEniCS)

### ISSUE THREAD

**Issue by tdiorio** [nschloe/meshio#853]
Hello,
I am attempting to import a `.msh` file from Gmsh to FEniCS. I have created a 2D concentric circle model and meshed it accordingly in Gmsh ([braintestvideo.zip](https://github.com/nschloe/meshio/files/4821162/braintestvideo.zip)) with physical lines defined.

However after reading the `.msh` file, I am unable to perform the XDMF writing step:
```
mesh = meshio.read("braintestvideo.msh")
points,cells = mesh.points, mesh.cells
cell_data, field_data = mesh.cell_data, mesh.field_data

meshio.write("brain_mesh.xdmf",
             meshio.Mesh(
                 points=points[:, :2],
                 cells={"triangle": cells["triangle"]},
                 cell_data={"triangle": {"subdomain": cell_data["triangle"]
                                         ["gmsh:physical"]}},
                 field_data=field_data))

meshio.write("brain_boundary.xdmf", meshio.Mesh(
    points=points[:, :2],
    cells={"line": cells["line"]},
    cell_data={"line": {"boundaries": cell_data["line"]["gmsh:physical"]}}
))
```

as I get the following error:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-15-fcbb630365fb> in <module>
     13              meshio.Mesh(
     14                  points=points[:, :2],  # Converting to 2D
---> 15                  cells={"triangle": cells["triangle"]},
     16                  cell_data={"triangle": {"subdomain": cell_data["triangle"]
     17                                          ["gmsh:physical"]}},

TypeError: list indices must be integers or slices, not str
```
This seems to be an issue with the way I am attempting to slice the data. However, I have seen this same style performed by a number of other users [(1](https://github.com/iitrabhi/GSoC2019/blob/master/Notebooks/Understanding%20MeshFunction%20and%20MeshValueCollection.ipynb), [2,](https://computationalmechanics.in/fenics-the-mesh-workflow/) [3)](https://fenicsproject.discourse.group/t/create-mesh-with-gmsh-convert-it-and-import-it-in-dolfin-problems/107) are not experiencing this issue.

Any help would be much appreciated!

**Comment by gdmcbain** [comment]
Since meshio 4, the data structure for .cells has been changed to a list of cellblocks, these being tuples of the cell-type (a str) and the connectivity ndarray. The cell_data is similar. The Mesh constructor still accepts the old cells but not the old cell_data. Pass on the new cell_data.

Actually for your purpose (Gmsh to FEniCS) you'll find that these and other steps have been neatly automated by https://github.com/floiseau/msh2xdmf.

**Comment by tdiorio** [comment]
Thank you very much! I was able to use that tool and everything seems to be working now.
