### ISSUE TITLE
KeyError: 'vtkidtype'

### ISSUE THREAD

**Issue by nilswagner** [nschloe/meshio#855]
```
import meshio
m = meshio.Mesh.read('test_mod.vtk', "vtk")
m.write('test.dato')
```

**Comment by nilswagner** [comment]
[test_mod.vtk.gz](https://github.com/nschloe/meshio/files/4824925/test_mod.vtk.gz)

**Comment by nilswagner** [comment]
The vtk file was generated by pyansys 0.41.3

**Comment by nschloe** [comment]
Fixed now.

**Comment by ylgrst** [comment]
Hello,
I am having the same error when reading a vtk file created using pyvista version 0.42.2 (see file attached)
The error occurs when using command line: ```meshio convert test.vtk test.mesh``` as well as through python functions:

```
import meshio
m = meshio.read('test.vtk')
m.write('test.mesh')
```

I have also tried saving as ascii or binary, to no avail...

[test.vtk.gz](https://github.com/nschloe/meshio/files/12708517/test.vtk.gz)

**Comment by marchirschvogel** [comment]
I encounter the same problem with a file I've received, and with the example file provided here. The error happens in
`m = meshio.read('test.vtk')`
Would be great if this gets resolved.
