### ISSUE TITLE
Issue with converting from vtk to ansys msh/cgns

### ISSUE THREAD

**Issue by asarrami** [nschloe/meshio#857]
Hi, 

I have converted a volume mesh from vtk to msh using the meshio.ansys.write and set binary=0. The conversion went well and a msh file was generated. I am not able to read the msh file in ansys products: FLUENT/CFX/ICEM. I am using ANSYS 19.1. 

Also, I generated a cgns file in meshio. I cannot open the CGNS file in the above ansys products/paraview.

Any advice would be highly appreciated. Thanks

**Comment by nschloe** [comment]
There is far too little information here to debug. Best post an example file that is wrong and tell us where it's wrong. A link to the specification would be great. Even better: A PR.

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to reopen at any time.
