### ISSUE TITLE
Issue with converting some .med files with results

### ISSUE THREAD

**Issue by RhydianL** [nschloe/meshio#876]
[Meshes.zip](https://github.com/nschloe/meshio/files/4981269/Meshes.zip)
I have encountered some issues using meshio in converting med files (generated by CodeAster) to xdmf. Attached are 4 .med files:

UnitCube.med - the mesh used
Meshanical.med - results for mechanical simulation
Thermal.med - results for thermal simulation
TransientThermal.med - results for time-dependent thermal simulation

UnitCube.med and Thermal.med both convert as expected. 

TransientThermal.med converts, however the results for each timestep are stored as individual results.  This means that they can't be viewed as an animation in paraview, however this can be corrected using the TimeSeriesWriter attribute.

Mechanical.med I receive the error:
```
AssertionError: Incompatible cell data. 3 cell blocks, but 'reslin__SIEF_ELGA' has 1 blocks
```
I believe this is to do with the fact that the results generated are explicitly for volume elements, so it is only to these that the results are applied, however meshio also looks for results for the remaining elements (faces and edges).

Note that the med files created by CodeAster are often output as .rmed files however the extension for these has been changed to .med to use with meshio

Thanks
Rhydian

**Comment by RhydianL** [comment]
Note that the med files created by CodeAster are often output as .rmed files however the extension for these has been changed to .med to use with meshio

**Comment by tianyikillua** [comment]
Ok will have a look :-)

**Comment by Jesusbill** [comment]
Just an info here, I was able to do this conversion of Mechanical.med without errors both to vtu (and visualize in Paraview) and to xdmf with `version 4.0.12` which I had installed. Updating to 4.2.1 gives the reported error
