### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by nicoguaro** [nschloe/meshio#883]
I have been using meshio for a while now in my own research and lectures. And in every new version I have to learn the way it works, it would be good if there were some kind of documentation. What is written in the README is a good start, and the tests also help. Nevertheless, it is a little bit more difficult to my students to read the code to find how to use meshio. So, it would be really helpful to have some kind of documentation.

I think that I could setup a folder with sphinx and write a couple of examples there.

**Comment by nschloe** [comment]
Not sure if I want to maintain this. What would you put in the docs for example?

**Comment by nicoguaro** [comment]
The first thing that pops in my mind is a description of the class ``CellBlock``. Also, you can automatically convert the docstrings of functions/methods into documentation.

I understand if you don't want to maintain documentation, but every semester I have to answer several questions to students and colleagues and that could be written in the docs.

**Comment by frankeye** [comment]
@nicoguaro : See [https://github.com/nschloe/meshio/wiki/meshio-Mesh()-API](url)
work-in-progress (e.g. I will add more, and Nico may still want to review...)

**Comment by nicoguaro** [comment]
@frankeye, that looks good. Although writing it in the wiki keep it linked to GitHub and does not have the advantages of versioning.

**Comment by nschloe** [comment]
> Although writing it in the wiki keep it linked to GitHub and does not have the advantages of versioning.

Wikis are also versioned, and even if not I don't think it'd be a huge problem. I've edited the text a bit and I think this can be closed now. If you have anything to add, feel free to edit the wiki of course.
