### ISSUE TITLE
XDMF writer does not write Grid Name attribute

### ISSUE THREAD

**Issue by carlos-ar** [nschloe/meshio#887]
I am using the xdmf writer to produce a time dependent hdf mesh for use in LLNL's VisIt visualization software, and I think I've run into 1) a bug in meshio's time_series writer or/and 2) a bug in VisIt's xdmf reader.

The meshio output .xmf file does get read into ParaView and works normally, but I believe the issue is that VisIt expects the mesh name attribute to be set. My knowledge of xpointer/Xinclude is zero, so the `ptr` variable set in [https://github.com/nschloe/meshio/blob/master/meshio/xdmf/time_series.py#L301](https://github.com/nschloe/meshio/blob/master/meshio/xdmf/time_series.py#L301) might actually be the easy fix, or just adding a "Name = mesh" attribute.

Either way, below is the code that produces a test mesh, included in the attachments. I've also manually changed the Grid Name attribute in the `visit_mesh_manual_names.xmf`
[visit_meshes.zip](https://github.com/nschloe/meshio/files/5101248/visit_meshes.zip)

 file to get it to work in visit.

To reproduce the error in VisIt (using version 3.1.2):

- Open the `visit_mesh.xmf`
- Click on "Add" -> "Mesh" -> "grid_14" (note: number varies)
- Click on "Draw"
- Click on "Delete" to remove the mesh
- Add the mesh again, "Add" -> "Mesh" -> "grid_54" (new number)
- Error! 
`Mesh:  (ImproperUseException)
viewer: The pipeline object is being used improperly.`

```import os
import meshio
import numpy as np


def write_xdmf(filename, time, points, cells, data):
    filename = filename+'.xmf'
    with meshio.xdmf.TimeSeriesWriter(filename) as writer:
        writer.write_points_cells(points, cells)
        for t in time:
            writer.write_data(t, point_data={"vel": data})

            
time_array = [0.0, 0.1, 0.21]
points = np.array(
            [
                [0.0, 0.0, 0.0],
                [1.0, 0.0, 0.0],
                [1.0, 1.0, 0.0],
                [0.0, 1.0, 0.0],
                [0.0, 0.0, 1.0],
                [1.0, 0.0, 1.0],
                [1.0, 1.0, 1.0],
                [0.0, 1.0, 1.0],
            ]
        )
cells = [("hexahedron", np.array([[0, 1, 2, 3, 4, 5, 6, 7]]))]
ps = np.shape(points)
data = np.random.rand(ps[0],ps[1])

write_xdmf('visit_mesh', time_array, points, cells, data)
```

**Comment by nschloe** [comment]
Where in the XDMF XML do you miss something?

**Comment by carlos-ar** [comment]
In each grid in the collection. I fixed it outside of my code with
```
grids = writer.collection.findall("Grid")
        for g in grids:
            g.set("Name","mesh_name")
```
which could be fixed if you add the attribute "Name" in this line, I believe [https://github.com/nschloe/meshio/blob/master/meshio/xdmf/time_series.py#L298](https://github.com/nschloe/meshio/blob/master/meshio/xdmf/time_series.py#L298)
```
grid = ET.SubElement(self.collection, "Grid")
grid.set("Name", "mesh_name")
```

**Comment by nschloe** [comment]
Can you find that in the XDMF spec? http://www.xdmf.org/index.php/XDMF_Model_and_Format

If not, it might be a VisIt bug.

**Comment by carlos-ar** [comment]
[http://www.xdmf.org/index.php/XDMF_Model_and_Format#Uniform.2C_Collection.2C_and_Tree](http://www.xdmf.org/index.php/XDMF_Model_and_Format#Uniform.2C_Collection.2C_and_Tree)

Here it seems to have the attribute "Name" and "GridType" for each grid the collection (i.e. Lug Nut 1, 2 ...). Maybe this is what visit is expecting?

**Comment by nschloe** [comment]
I read

> Optionally there can be several "Name=Value" pairs which convey additional information.

but this is for the `Elements` tag. Since nothing else is said anywhere in the document, I would guess it's optional for everything else as well, so it does look like a visit bug to _expect_ the `Name` attribute. Perhaps meshio should support optional names, too, though.

**Comment by gdmcbain** [comment]
I read that quote as using "Name" as a metavariable, the same as if it said ‘…several "Key=Value" pairs’; having several, or even just more than one, XML attribute in the one XML tag with the same name/key would be odd. I'm not sure what that would mean or whether it would be valid. Like a Python dict with colliding keys, it's usually a mistake.

In the example under section ‘Grid‘, subsection ‘Uniform, Collection, and Tree’, cited sbove, each Grid has (literal, single) attributes "Name" and "GridType":
```xml
<Grid Name="Car Wheel" GridType="Tree"> 
```

**Comment by carlos-ar** [comment]
In my hack to make it work, I did not distinguish between (n) grids. Presumably, I would add a new grid name for each time step within each collection.

I'll try the visit devs and see if its on the visit side (or interpretation of what the xdmf collection should have as attributes).

**Comment by nschloe** [comment]
@carlos-ar Feel free to post a link to the visit issue here, I'm sure we can figure something out.

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to reopen at any time.
