### ISSUE TITLE
unable to read .ply file with custom format

### ISSUE THREAD

**Issue by ttsesm** [nschloe/meshio#889]
Hi,

I am trying to use `meshio` to load a custom .ply file with different properties and elements structured in the following format:

```
File: map_mesh.ply
Description:
ply
format binary_little_endian 1.0
comment generated by omnimap
element vertex 3786298
property float x
property float y
property float z
property float nx
property float ny
property float nz
property float radiance_blue
property float radiance_green
property float radiance_red
property float irradiance_blue
property float irradiance_green
property float irradiance_red
property float irradiance_lamp_0_blue
property float irradiance_lamp_0_green
property float irradiance_lamp_0_red
property float irradiance_lamp_1_blue
property float irradiance_lamp_1_green
property float irradiance_lamp_1_red
property float irradiance_lamp_2_blue
property float irradiance_lamp_2_green
property float irradiance_lamp_2_red
property float irradiance_lamp_3_blue
property float irradiance_lamp_3_green
property float irradiance_lamp_3_red
property float irradiance_lamp_4_blue
property float irradiance_lamp_4_green
property float irradiance_lamp_4_red
property float irradiance_lamp_5_blue
property float irradiance_lamp_5_green
property float irradiance_lamp_5_red
property float reflectance_blue
property float reflectance_green
property float reflectance_red
element face 7570727
property list uchar uint vertex_indices
element lamp 6
property list uint uint vertex_indices
end_header
```

However, it fails with the following reading error message: `meshio._exceptions.ReadError`

My guess is that it has to do with the custom properties and elements included in .ply file. Any idea whether I could read the file with somehow?

You can access the .ply file from [this tarball](http://tracklam.informatik.uni-freiburg.de/downloads/tracklam_ds1_lam.tar.gz)

**Comment by nschloe** [comment]
Nobody will bother downloading a 500MB file. Feel free to reopen with an MWE of less than 1MB.

**Comment by ttsesm** [comment]
@nschloe apologies for the size of the file but I cannot see how I can get it in a smaller size. 

In any case the error that I get is the following:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ttsesm/Development/open3d_reconstruction_system/venv/lib/python3.8/site-packages/meshio/_files.py", line 29, in open_file
    yield f
  File "/home/ttsesm/Development/open3d_reconstruction_system/venv/lib/python3.8/site-packages/meshio/ply/_ply.py", line 67, in read
    mesh = read_buffer(f)
  File "/home/ttsesm/Development/open3d_reconstruction_system/venv/lib/python3.8/site-packages/meshio/ply/_ply.py", line 133, in read_buffer
    raise ReadError()
meshio._exceptions.ReadError
```

which raises an exception in line https://github.com/nschloe/meshio/blob/e3b3fc0f098c44c0a73145088fe9af8ae3496c6b/meshio/ply/_ply.py#L132 and the code that I am using is the following:

import meshio

mesh = meshio.read('./map_mesh.ply', file_format='ply')

**Comment by nschloe** [comment]
That's all fair and well, but what do you expect the devs to do now? _Guess_ what the issue might be?

Without a small file, it's impossible for anyone to track down the error, and providing a 500MB is almost as good as no file at all. I realize that sometimes, it's a bit of work to produce an MWE, but hey, it's also work to fix the error, so why not split the load?

I closed this issue because there is nothing I can do here. You can reopen it if you manage to produce a small file, and you can always provide a PR of course. (Perhaps that's the best path forward for you now.) If it fixes your use case and doesn't break anything else, I'm usually not too strict when it comes to merging.

**Comment by ttsesm** [comment]
I'll see if I can make a smaller MWE and possibly check if I can debug a bit more post back if possible. Anyway, thank you for your time.
