### ISSUE TITLE
Cannot read .vtk file using meshio

### ISSUE THREAD

**Issue by isurusuranga** [nschloe/meshio#890]
I use meshio to convert .vtk files to .msh file format as below. 

volumetric_mesh = meshio.Mesh.read('./ellipsoid_0.vtk', "vtk")

But unfortunately I cannot do that and gives below error.

ReadError: Unknown section 'OFFSETS'.

Any solution to that please ?

**Comment by nschloe** [comment]
MWE please

**Comment by isurusuranga** [comment]
---------------------------------------------------------------------------
ReadError                                 Traceback (most recent call last)
<ipython-input-23-16fdd11f3a95> in <module>()
      1 #volumetric_mesh_7 = meshio.read("G:/DUMMY_DATA_GENERATION/reference_geometry/meshes/ellipsoid_0.vtk")
----> 2 volumetric_mesh_7 = meshio.Mesh.read('G:/DUMMY_DATA_GENERATION/reference_geometry/meshes/ellipsoid_0.vtk', "vtk")

c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\meshio\_mesh.py in read(cls, path_or_buf, file_format)
    193         from ._helpers import read
    194 
--> 195         return read(path_or_buf, file_format)
    196 
    197     def sets_to_int_data(self):

c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\meshio\_helpers.py in read(filename, file_format)
     66         raise ReadError(msg)
     67 
---> 68     return reader_map[file_format](filename)
     69 
     70 

c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\meshio\vtk\_vtk.py in read(filename)
    144     """
    145     with open_file(filename, "rb") as f:
--> 146         out = read_buffer(f)
    147     return out
    148 

c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\meshio\vtk\_vtk.py in read_buffer(f)
    177             _read_section(f, info)
    178         else:
--> 179             _read_subsection(f, info)
    180 
    181     _check_mesh(info)

c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\meshio\vtk\_vtk.py in _read_subsection(f, info)
    270         d.update(_read_fields(f, int(info.split[2]), info.is_ascii))
    271     else:
--> 272         raise ReadError("Unknown section '{}'.".format(info.section))
    273 
    274 

ReadError: Unknown section 'OFFSETS'.

**Comment by isurusuranga** [comment]
See this attachment please.
[error_trace.pdf](https://github.com/nschloe/meshio/files/5119070/error_trace.pdf)
`

**Comment by nschloe** [comment]
You just posted the issue, not a way to reproduce the error. Also, the PDF you attached does nothing to clarify the issue.

**Comment by nschloe** [comment]
https://en.wikipedia.org/wiki/Minimal_working_example

**Comment by isurusuranga** [comment]
volumetric_mesh = meshio.Mesh.read('./ellipsoid_0.vtk', "vtk")

Please extract this attached zip file and use that .vtk file to reproduce the error.

[ellipsoid_0.zip](https://github.com/nschloe/meshio/files/5119105/ellipsoid_0.zip)

**Comment by nschloe** [comment]
This should be fixed by https://github.com/nschloe/meshio/pull/885.

PS: Please make yourself familar with GitHub formatting, especially code fences.
