### ISSUE TITLE
.vtk file to .msh file conversion error

### ISSUE THREAD

**Issue by isurusuranga** [nschloe/meshio#892]
I attempted to convert .vtk files to .msh files, but I have got an error (the error that I have got is attached as a pdf file.
). I have attached herewith a .vtk file that I have produced using the vtk tool.

The code is as below.
```
volumetric_mesh = meshio.read("./ellipsoid_0.vtk")
meshio.write("./ellipsoid_0.msh", volumetric_mesh)
```

[ellipsoid_0.zip](https://github.com/nschloe/meshio/files/5120002/ellipsoid_0.zip)
[vtk_2_msh_conversion_error_trace.pdf](https://github.com/nschloe/meshio/files/5120004/vtk_2_msh_conversion_error_trace.pdf)

**Comment by nschloe** [comment]
Please don't hide error messages PDF file. Nobody will download them. Just copy and paste them here, that's much easier.

Also, this is literally the same error as https://github.com/nschloe/meshio/issues/890. If you have any more issues, post them there or reopen.

**Comment by isurusuranga** [comment]
No this is not working.

The issue is when I try to convert the .vtk file after reading it.
The error occurs when running the below part.

`meshio.write("./ellipsoid_0.msh", volumetric_mesh)`


Here is the error message.

`WARNING:root:Binary Gmsh needs c_size_t (got uint64). Converting.
WARNING:root:Binary Gmsh needs c_size_t (got uint64). Converting.
---------------------------------------------------------------------------
WriteError                                Traceback (most recent call last)
<ipython-input-7-9d4fc3b45402> in <module>()
----> 1 meshio.write("E:/meshes/meshes/ellipsoid_0.msh", volumetric_mesh_0)

c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\meshio\_helpers.py in write(filename, mesh, file_format, **kwargs)
    142 
    143     # Write
--> 144     return writer(filename, mesh, **kwargs)

c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\meshio\gmsh\main.py in <lambda>(f, m, **kwargs)
    114     {
    115         "gmsh22": lambda f, m, **kwargs: write(f, m, "2.2", **kwargs),
--> 116         "gmsh": lambda f, m, **kwargs: write(f, m, "4.1", **kwargs),
    117     },
    118 )

c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\meshio\gmsh\main.py in write(filename, mesh, fmt_version, binary, float_fmt)
    105             )
    106 
--> 107     writer.write(filename, mesh, binary=binary, float_fmt=float_fmt)
    108 
    109 

c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\meshio\gmsh\_gmsh41.py in write(filename, mesh, float_fmt, binary)
    279 
    280 def write(filename, mesh, float_fmt=".16e", binary=True):
--> 281     write4_1(filename, mesh, float_fmt=float_fmt, binary=binary)
    282 
    283 

c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\meshio\gmsh\_gmsh41.py in write4_1(filename, mesh, float_fmt, binary)
    319 
    320         _write_entities(fh, cells, binary)
--> 321         _write_nodes(fh, mesh.points, mesh.cells, float_fmt, binary)
    322         _write_elements(fh, cells, binary)
    323         if mesh.gmsh_periodic is not None:

c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\meshio\gmsh\_gmsh41.py in _write_nodes(fh, points, cells, float_fmt, binary)
    371     # TODO Not sure what to do if there are multiple element types present.
    372     if len(cells) != 1:
--> 373         raise WriteError("Can only deal with one cell type for now")
    374     dim_entity = _geometric_dimension[cells[0][0]]
    375     entity_tag = 0

WriteError: Can only deal with one cell type for now`

**Comment by nschloe** [comment]
https://github.com/nschloe/meshio/issues/865

**Comment by isurusuranga** [comment]
I yesterday re-install the new release (i.e. meshio 4.4.1). But the problem is still exists ?
Is this problem fixed in this release ?

Can you please provide steps to overcome this issue please ?

**Comment by isurusuranga** [comment]
For a workaround I just changed the **meshio\gmsh\main.py** as below to allow for writing the .msh compatible to **gmsh22** until this issue will resolve.

```
register(
    "**gmsh22**",
    [".msh"],
    read,
    {
        "gmsh22": lambda f, m, **kwargs: write(f, m, "2.2", **kwargs),
        "gmsh": lambda f, m, **kwargs: write(f, m, "4.1", **kwargs),
    },
)

```
But I have got set of warnings as below. I assume this is not an issue.

WARNING:root:Appending zeros to replace the missing physical tag data.
WARNING:root:Appending zeros to replace the missing geometrical tag data.
WARNING:root:Binary Gmsh needs 32-bit integers (got int64). Converting.
WARNING:root:Binary Gmsh needs 32-bit integers (got int64). Converting.

And then I can use non-interactive mode of gmsh to convert it into latest gmsh version as below.
**gmsh -convert ./ellipsoid_dup_0.msh**

And please let me know once this bug is resolved.

**Comment by nschloe** [comment]
For all I know, it's a duplicate of #865. Also the error message indicates that the devs are aware of the problem. I'm personally not working on it (not too interested in the gmsh formats), so your best shot is a PR I'd say.

**Comment by gdmcbain** [comment]
Yes, it is a duplicate of #865.

Modifying `meshio.gmsh.main` like [that](https://github.com/nschloe/meshio/issues/892#issuecomment-679965123) will work for this specific case but might break other things so I don't recommend this; instead, as suggested in #865, just ask meshio to write MSH 2.2 with 

```python
mesh = meshio.read("ellipsoid_0.vtk")
meshio.write("ellipsoid_0.msh", mesh, file_format="gmsh22")
```

**Comment by sridhar-mani** [comment]
any solutions found?

**Comment by sridhar-mani** [comment]
Case directory './testPython' already exists.
Copied '/home/sridhar/snappyAMI/pinnSOlver/lowPolyCustomCase/constant/triSurface/inlet.stl' to './testPython/constant/triSurface'.
Copied '/home/sridhar/snappyAMI/pinnSOlver/lowPolyCustomCase/constant/triSurface/outlet.stl' to './testPython/constant/triSurface'.
Copied '/home/sridhar/snappyAMI/pinnSOlver/lowPolyCustomCase/constant/triSurface/walls.stl' to './testPython/constant/triSurface'.
./testPython/VTK/testPython_0.vtk
File contains cells that meshio cannot handle (types 42)        
Error: Couldn't read file       
testPython/VTK/testPython_0.vtk 
as vtk
