### ISSUE TITLE
KeyError: 'String' when running the code on different meshes

### ISSUE THREAD

**Issue by Ahama1992** [nschloe/meshio#893]
Hello there,
I am running the following command in Ubuntu:

`meshio-convert test.vtu out.vtk`

Then, I get the following error:

> Traceback (most recent call last):
>   File "/home/ahama/.local/bin/meshio-convert", line 11, in <module>
>     sys.exit(convert())
>   File "/home/ahama/.local/lib/python3.6/site-packages/meshio/_cli/_convert.py", line 15, in convert
>     mesh = read(args.infile, file_format=args.input_format)
>   File "/home/ahama/.local/lib/python3.6/site-packages/meshio/_helpers.py", line 68, in read
>     return reader_map[file_format](filename)
>   File "/home/ahama/.local/lib/python3.6/site-packages/meshio/vtu/_vtu.py", line 505, in read
>     reader = VtuReader(filename)
>   File "/home/ahama/.local/lib/python3.6/site-packages/meshio/vtu/_vtu.py", line 296, in __init__
>     field_data[data_array.attrib["Name"]] = self.read_data(data_array)
>   File "/home/ahama/.local/lib/python3.6/site-packages/meshio/vtu/_vtu.py", line 487, in read_data
>     data = reader(c.text.strip(), c.attrib["type"])
>   File "/home/ahama/.local/lib/python3.6/site-packages/meshio/vtu/_vtu.py", line 445, in read_compressed_binary
>     dtype = vtu_to_numpy_type[data_type]
> KeyError: 'String'

The test.vtu mesh file is attached (you might want to unzip the file first). I have experimented with other mesh files as well and still got errors. I have both Python 2 and 3 on my system if that's something relevant. Any help is appreciated.
Thanks and best wishes.

[test.zip](https://github.com/nschloe/meshio/files/5120386/test.zip)

**Comment by nschloe** [comment]
The VTK/VTU specification says:

> type — The data type of a single component of the array. This is one of Int8, UInt8, Int16, UInt16, Int32,
UInt32, Int64, UInt64, Float32, Float64

Hence, `String` is an illegal type. I made the error message clearer.
