### ISSUE TITLE
Ansys msh 2D mesh support

### ISSUE THREAD

**Issue by bertanozkan** [nschloe/meshio#897]
Hi, It seems like Ansys 2D meshes are not supported. Are you planning to add this feature in near future?

**Comment by nschloe** [comment]
It always helps appending a mesh that doesn't work for you. Otherwise it's hard to guess what "doesn't work".

> Are you planning to add this feature in near future?

If somebody submits a PR and it looks alright, it'll be done in one hour. :smile_cat: You can give it a shot, it shouldn't be too hard.

**Comment by bertanozkan** [comment]
First of all, amazing code. I would love to help as much as I can.
My problem is, I created a 2D airfoil mesh on SalomePlatform. Exported the mesh with .med format (mesh file is appended) and try to convert it to other formats. SU2 format worked well. But when I tried to convert it to ansys ascii mesh with this code:

`import meshio`
`mesh = meshio.read('Mesh_1.med')`
`mesh.write('test.msh', file_format = 'ansys', binary = False)`

It created an error called `KeyError: 'line'` at /meshio/ansys/_ansys.py  line 450 in write. As I understand this line checks for 'line' in dictionary and can't find it. `meshio_to_ansys_type `dictionary doesn't have line in it. 
Am I understanding correctly that your code does not support 2D ansys files. Or is there another bug in the code?
And. I would love to try solving this. If you can push me to the right direction.

[Mesh_1.zip](https://github.com/nschloe/meshio/files/5150652/Mesh_1.zip)

**Comment by nschloe** [comment]
> Or is there another bug in the code?

Probably no one else has tried it before. It'd be good if it was in meshio; I don't know if you want to call this a bug or not.

> If you can push me to the right direction.

`git clone` and go for it. :)

**Comment by nschloe** [comment]
Okay, I've looked into it. ANSYS itself does not support "line" element it seems, that's why the conversion fails. I've added a better error message.

**Comment by bertanozkan** [comment]
Yes, like you said Ansys does not support line types. And strangely Salome exports line types with mesh files. I solved it by deleting 1D elements before exporting .med file. I hope it helps future users who try to convert .med to .msh files.
 Thank you for updating the code. After some reading I think I understand the code. On my first free time I will try to add  boundary functionality to ansys file format.
