### ISSUE TITLE
Using strict definition of ply mesh  format for other packages inerrant reading

### ISSUE THREAD

**Issue by liwind** [nschloe/meshio#906]
The strict definition of Stanford PLY Format in second line indicates its format (**ascii/binary**) in [PLY wiki](https://en.wikipedia.org/wiki/PLY_(file_format)) and  [polygon file format](http://paulbourke.net/dataformats/ply/). But in meshio format format declaration is in third line, and its second line is comment Created :
https://github.com/nschloe/meshio/blob/62484f38b4d0b4854de5f293915fb7732dca08e9/meshio/ply/_ply.py#L376
https://github.com/nschloe/meshio/blob/62484f38b4d0b4854de5f293915fb7732dca08e9/meshio/ply/_ply.py#L383
This will cause reading errors for other mesh package by using meshio exporting ply file.

For example of using [Open3d](https://github.com/intel-isl/Open3D) to read ply file exporting by meshio：
**code** :
```python
import numpy as np
import pct
import open3d as o3d
import meshio

np.set_printoptions(suppress=True)

points, scalars = pct.reader_txt("data/samp31.txt")
cells = []
mesh = meshio.Mesh(points, cells)
mesh.write("data/samp31_meshio.ply", file_format="ply", binary=False)

ply = o3d.io.read_point_cloud("data/samp31_meshio.ply", format="ply")
```
**data** (meshio exporting ply file - samp31_meshio.ply) :
```
ply
comment Created by meshio
format ascii 1.0
element vertex 28862
property double x
property double y
property double z
element face 0
end_header
512268.38 5403188.99 308.85
512268.33 5403187.59 308.88
512268.28 5403186.1 308.89
...
```
It will throw error : **[Open3D WARNING] Read PLY failed: unable to parse header**.
But, when i cut "format ascii 1.0" to second line, [Open3d](https://github.com/intel-isl/Open3D) read it successfully, and also in [PDAL](https://github.com/PDAL/PDAL). Open3d use [rply](http://w3.impa.br/~diego/software/rply/) library to read ply file, and PDAL use [polygon file format](http://paulbourke.net/dataformats/ply/).

**So i suggest to change ply format declaration (**format ascii 1.0**) into second line by strict ply file format definition.**
I just test **ply** writer in Open3d and PDAL packages, and any other mesh formats and packages have not been tested.

**Comment by nschloe** [comment]
Thanks for the good report, fixed now.
