### ISSUE TITLE
Issues with exodus conversion

### ISSUE THREAD

**Issue by oldninja** [nschloe/meshio#909]
Hello @nschloe, thank you so much for this tool. 
I'm not sure if I'm using it wrong but I tried to convert a simple *.vtk mesh file (see attached) to an exodus *.exo format to use it in a [Peridigm](https://github.com/peridigm/peridigm) simulation. However, when I converted the file to *.exo and included it in my Peridigm input file, it had a problem:
```
-- Peridigm
-- version 1.5.0 (Dev)
EXODUS: ERROR: Attempting to open the netcdf-4 file:
        'beam.exo'
        . Either the netcdf library does not support netcdf-4 or there is a filesystem or some other issue
****Error on processor 0: unable to open file beam.exo
/usr/local/src/Peridigm-1.5.0-Source/src/io/discretization/Peridigm_ExodusDiscretization.cpp:1136:
Throw number = 1
Throw test that evaluated to true: 1
PeridigmNS::OutputManager_ExodusII::ExodusDiscretization::loadData()() -- Error code: -1 (ex_open)
Wallclock Time (seconds):
  Total            0.012 
```
Pointing to something wrong with the mesh file. I also checked with the NetCDF package, via the `ncdump` command and it said the following `ncdump: beam.e: NetCDF: Unknown file format`.

The file imports fine in Paraview and I'm able to see the mesh. 
I'm not entirely sure what may be causing the issue or what the issue actually is. 
I also tried to import it using HyperMesh, that now supports exodus exports and looks like the name of the block was different from what I understand is the exodus standard (e.g. "block_1,...,block_i"). I renamed it and exported from HyperMesh and it worked fine. Not sure if there is an issue with the block namings or something else that is not being recognized.

Let me know if you need any additional information to look into this.
Thanks!

[beam.zip](https://github.com/nschloe/meshio/files/5197272/beam.zip)

**Comment by nschloe** [comment]
You renamed what exactly?

**Comment by oldninja** [comment]
Sorry, I renamed the name of the block or cells - it had something like "HEXA...". I renamed it to "block_1" and exported it from HyperMesh using their exodus converter, nothing else changed.

**Comment by nschloe** [comment]
I tried to reproduce the problem, to no avail.
```
ncdump beam.exo
```
yields no error.

**Comment by oldninja** [comment]
I see. I'm still getting the same:
`meshio-convert beam.vtk beam.exo
<meshio mesh object>
  Number of points: 21105
  Number of elements:
    hexahedron: 16000
  Cell data: CellEntityIds
user@pc:~/beam$ ncdump beam.exo
ncdump: beam.exo: NetCDF: Unknown file format`

Let me check my installation and will get back on this. Thanks for looking at it so promptly!

**Comment by nschloe** [comment]
I got
```
ncdump
```
```
[...]
netcdf library version 4.7.3 of Jan 23 2020 04:18:16 $
```
btw.

**Comment by oldninja** [comment]
Looks like there is an issue with my older version of the NetCDF library - I had to install the 4.4.0 for Peridigm and I'm not sure if I did install all the necessary things. I verified that it works fine with 4.7.3
Closing this issue. Thanks for the support @nschloe .
