### ISSUE TITLE
"meshio" can't read a version-2 "Gmsh" msh file

### ISSUE THREAD

**Issue by rbunger** [nschloe/meshio#913]
Hi,

originally I wanted to read "Gmsh" version-4 mesh files with tags / regions using "meshio". I first tried to read a version-2 file in order to convert it into a version-4 file with tags / regions but "meshio-info" and the "meshio.read" function both do not terminate / return on reading the version-2 file (attached). "Gmsh" is able to load the file so I think the syntax is valid.

[test.zip](https://github.com/nschloe/meshio/files/5209698/test.zip)

A second problem which I thought was already fixed in a previous version of "meshio" is that "meshio" can't read off-files with RGB color information ("Can only read triangular faces"). I'm not using off-files any more, I just wanted to mention that...

And finally: Are there any plans to support "*.dat" files from CATIA? ;-)

Thanks & kind regards,

Rainer

**Comment by gdmcbain** [comment]
> originally I wanted to read "Gmsh" version-4 mesh files with tags / regions using "meshio".

This should work; it's a routine operation, e.g. done each time the msh2xdmf test-suite is run.  See https://github.com/floiseau/msh2xdmf/blob/master/test/conversion/test_conversion.py.

**Comment by gdmcbain** [comment]
> the version-2 file (attached). "Gmsh" is able to load the file so I think the syntax is valid.

> test.zip

The attachment is empty.

**Comment by rbunger** [comment]
sorry for the empty zip... here is the correct one...

[test.zip](https://github.com/nschloe/meshio/files/5216594/test.zip)

**Comment by gdmcbain** [comment]
Thanks.  I confirm that `meshio-info` and `meshio.read` seem to run indefinitely on this `mesh.msh`.  

If I convert it to MSH 4.1 with Gmsh 4.6.0 it's O. K.
```shell
gmsh -convert mesh.msh
mv mesh.msh.new mesh4.msh
meshio-info mesh4.msh
```
returns
```
<meshio mesh object>
  Number of points: 7816
  Number of cells:
    line: 2
    triangle: 2604
  Cell data: gmsh:physical, gmsh:geometrical
```

But then this reraises the question: why not just work with the default Gmsh MSH 4.1 format, which is what you originally wanted to do?

**Comment by gdmcbain** [comment]
I believe your `mesh.msh` is malformed.   Where did you get it?  It's missing the 
```
$EndElements
```
line.

```shell
tail -2 mesh.msh
```

> 2605           2           2           2           1        7811        7812        7813
> 2606           2           2           2           1        7814        7815        7816

**Comment by gdmcbain** [comment]
Although I suspect the file is malformed, I looked anyway into why meshio might be so confused that it spins its wheels.  I think it's

https://github.com/nschloe/meshio/blob/3a380fc1100827ed38b8f38960087a066c4aab26/meshio/gmsh/_gmsh22.py#L139-L142

since https://docs.python.org/3/tutorial/inputoutput.html#methods-of-file-objects says:

> `f.readline()` reads a single line from the file; a newline character (`\n`) is left at the end of the string, and is only omitted on the last line of the file if the file doesn’t end in a newline. This makes the return value unambiguous; if `f.readline()` returns an empty string, the end of the file has been reached, while a blank line is represented by `'\n'`, a string containing only a single newline.

**Comment by gdmcbain** [comment]
The PR #914 successfully reads your file, warning about the unclosed block of elements.

**Comment by rbunger** [comment]
Many thanks for your efforts and sorry for uploading a faulty mesh file. I should have detected the error on my own.

Concerning the question why not using format 4: My version 4 reader sometimes isn't able to read some of the version 4 files I get, it is not flexible enough. I prefer version 2 files. For me version 4 is too complex. My simulation tool needs to read elements with a number of tags and version 2 fulfills that. So I will read version 2 only and I was searching for options to convert version 4 to version 2 (and possibly also the other way round).

Yesterday I had another problem with meshio and version 4 files: "Only one cell supported or 

Thanks again,

Rainer

**Comment by gdmcbain** [comment]
> Yesterday I had another problem with meshio and version 4 files: "Only one cell supported or

Yeah, that's a known shortcoming, unfortunately. #332 #865  It's only in _writing_ MSH 4.1 though; I think the reader's pretty good, much faster than the MSH 2 reader.
