### ISSUE TITLE
Cell data compatibility check

### ISSUE THREAD

**Issue by CharlieL7** [nschloe/meshio#915]
I am quite new to this package, so I am not sure if I am using this correctly. I am trying to add data on each face of the mesh, but adding cell data to Mesh object seems to be broken. Here is a minimum example:

```python
import meshio
import numpy

points = numpy.array([
    [0.0, 0.0, 0.0],
    [0.0, 1.0, 0.0],
    [0.0, 0.0, 1.0],
    ])
cells = [
    ("triangle", numpy.array([[0, 1, 2]]))
]
data = {"something": numpy.array([3, 4, 5])} #not sure about "something"

mesh = meshio.Mesh(
    points,
    cells,
    cell_data=data
)
```

The error I get is: 
```
Traceback (most recent call last):
  File "meshio_cell_data_test.py", line 14, in <module>
    mesh = meshio.Mesh(
  File "/home/charlie/anaconda3/envs/python38/lib/python3.8/site-packages/meshio/_mesh.py", line 45, in __init__
    assert len(data) == len(self.cells), (
AssertionError: Incompatible cell data. 1 cell blocks, but 'something' has 3 blocks.
```
I think the error is that line 45 in _mesh.py checks the length of the containing list rather than the ndarray of cells. Should be using the input key to somehow get the correct ndarray.

**Comment by gdmcbain** [comment]
Try:
```python
meshio.Mesh(points, cells, cell_data={"something": [data["something"]]})
```

**Comment by gdmcbain** [comment]
Or (better):
```python
data = {"something": [numpy.array([3, 4, 5])]}
```

**Comment by CharlieL7** [comment]
Works, thanks! Out of curiosity, when you have the length of cells not be 1?

**Comment by gdmcbain** [comment]
The idea is that `cell_data` is a dict and each of its values is a list of the same length as cells and each of those lists should be a `numpy.ndarray` with number of rows equal to the number of cells in the corresponding block in `cells`.

**Comment by CharlieL7** [comment]
The assert mentioned in the error is not checking the number of rows in the `numpy.adarray` however. Rather, it just checks the length of the list that contains the array. So I don't understand the usage of the assertion essentially.

**Comment by gdmcbain** [comment]
I see.  Well one can write:
```python
data = {"something": numpy.array([[3, 4, 5]])}
```
but normally the blocks aren't of the same length so a list of one-dimensional arrays makes more sense.

**Comment by CharlieL7** [comment]
To make my point clearer here's an example with an incorrect number of cell_data that passes the assertion:
```python
import meshio
import numpy

points = numpy.array([
    [0.0, 0.0, 0.0],
    [0.0, 1.0, 0.0],
    [0.0, 0.0, 1.0],
    ])
cells = [
    ("triangle", numpy.array([[0, 1, 2]]))
]
data = {"something": [numpy.array([3, 4])]}

mesh = meshio.Mesh(
    points,
    cells,
    cell_data=data
)
```
The same works with numpy.array([[3, 4]])

**Comment by gdmcbain** [comment]
Right, the assertion

https://github.com/nschloe/meshio/blob/3a380fc1100827ed38b8f38960087a066c4aab26/meshio/_mesh.py#L45

is that the `cell_data` has the required number of blocks, the same as `cells`.  You would like to add another assertion that each of the blocks is of the right size?  I don't have an opinion on that.  There's no corresponding check on the shape of `point_data`; that's just swallowed whole.

https://github.com/nschloe/meshio/blob/3a380fc1100827ed38b8f38960087a066c4aab26/meshio/_mesh.py#L36

**Comment by CharlieL7** [comment]
Got it, makes sense now. Thanks.

**Comment by nschloe** [comment]
One day perhaps, I'll have a divine enlightening and see how cell data can be implemented in a sane way.
