### ISSUE TITLE
Support for *include statements in the abaqus input format

### ISSUE THREAD

**Issue by Krande** [nschloe/meshio#919]
Hi,

I noticed some of my abaqus input files weren't converted by meshio. If I am not mistaken, currently there is no support for "*include" statements (which is used to import content from other input files) in the abaqus reader?

Therefore I created a suggested edit to the abaqus reader here https://github.com/Krande/meshio/commit/d24cd85993d8f52b362e94926e3ca97bebe06321 which also includes two example abaqus input files containing the *include statement. 

Let me know if this functionality already exists (but I am not seeing it\using it correctly), or if more people would be interested in the same functionality I can create a pull request!

Best Regards
Kristoffer

**Comment by nschloe** [comment]
Always PR, then we'll have something to talk about.
