### ISSUE TITLE
Reading component names of fields in a MED file

### ISSUE THREAD

**Issue by Jesusbill** [nschloe/meshio#923]
Hi all, kudos to all contributors for this great library.

When reading a MED file, the names of the components of the fields that exist in `point_data` and `cell_data` are not included. One gets a list of values for each entry, let's say a list of three values for a 3D displacement result in a point, but there is no information about the names of these three components (would be DX, DY, DZ for a MED file).

Looking at the code, this information could be added for example [here](https://github.com/nschloe/meshio/blob/master/meshio/med/_med.py#L131) with sth along these lines:

```
comp_data = {}
n_comp = data.attrs['NCO']
comp_str = data.attrs['NOM']
comp_data[name] = [comp_str[i*16:(i+1)*16].strip() for i in range(n_comp)]
```

And the question is whether the schema permits to read and include this kind of information. In other words is it something that can be taken care of by just modifying `_med.py` or at the moment this info is not considered at all in general for all formats?

I would be available to work towards a resolution of this issue if there is a possibility to consider these component names.

**Comment by nschloe** [comment]
It would be great if you could add a (small) MED file where the components aren't read correctly.

**Comment by Jesusbill** [comment]
Yes, certainly, here is a small example file [reinforcement.zip](https://github.com/nschloe/meshio/files/6038898/reinforcement.zip)

It contains a field in cell_data called `RES_____FERRAILLAGE` which has 7 values/components for each cell. My point is that the MED file contains also the labels of these 7 components, but it seems to me that these are not currently read and stored anywhere in the implementation in meshio. 

If, for example I add in the main [for loop](https://github.com/nschloe/meshio/blob/0600ac9e9e8d1e1a27d5f3f2f4235414f4482cac/meshio/med/_med.py#L126) of `_read_data`
```
print(data.attrs['NOM'])
```

I will get a string with the labels 'DNSXI           DNSXS           DNSYI           DNSYS           DNST            DNSVOL          CONSTRUC        '

PS: I see that when writing in med these component names are default created (names V1/V2 etc.) and stored [here](https://github.com/nschloe/meshio/blob/0600ac9e9e8d1e1a27d5f3f2f4235414f4482cac/meshio/med/_med.py#L371)

**Comment by nschloe** [comment]
They are now in `mesh.field_data["med:nom"]`.

**Comment by Jesusbill** [comment]
Sounds great! Thanks @nschloe !

**Comment by Jesusbill** [comment]
Testing these latest changes regarding med format there may be some modifications to be made.
Using the same med file I uploaded before, I tried reading and writing the file with this code
```
file = meshio.read("reinforcement.med")

meshio.Mesh(
    file.points,
    file.cells_dict,
    # Optionally provide extra data on points, cells, etc.
    point_data=file.point_data,
    cell_data=file.cell_data,
    field_data=file.field_data
).write(
    "reinforcement2.med"
)
```
and I get the following error
```
Traceback (most recent call last):
  File "io.py", line 18, in <module>
    meshio.Mesh(
  File "/home/jesusbill/miniconda3/envs/ifc/lib/python3.8/site-packages/meshio/_mesh.py", line 182, in write
    write(path_or_buf, self, file_format, **kwargs)
  File "/home/jesusbill/miniconda3/envs/ifc/lib/python3.8/site-packages/meshio/_helpers.py", line 147, in write
    return writer(filename, mesh, **kwargs)
  File "/home/jesusbill/miniconda3/envs/ifc/lib/python3.8/site-packages/meshio/med/_med.py", line 347, in write
    field_name = field_names[name_idx] if field_names else None
IndexError: list index out of range
```

Looking at the code would it make sense that [this line](https://github.com/nschloe/meshio/blob/main/meshio/med/_med.py#L348) should be after the `_write_data` call and outside the `for` loop? I tried it and it seems to work.

Also, [here](https://github.com/nschloe/meshio/blob/main/meshio/med/_med.py#L387) if no `field_name` is defined, shouldn't there be, nonetheless, an empty name created to be consistent?
Something like this
```
if field_name:
    field.attrs.create(
        "NOM", np.string_("".join(f"{name:<16}" for name in field_name))
    )
else:
    field.attrs.create(
        "NOM", np.string_("".join(f"{name:<16}" for name in [""]))
    )
```

If not, `mesh.field_data["med:nom"]` gives `[[], ['DNSXI', 'DNSXS', 'DNSYI', 'DNSYS', 'DNST', 'DNSVOL', 'CONSTRUC']]` for the original file but `[['DNSXI', 'DNSXS', 'DNSYI', 'DNSYS', 'DNST', 'DNSVOL', 'CONSTRUC']]` for the second file (after the modification suggested above).

**Comment by nschloe** [comment]
How about a pull request?

**Comment by Jesusbill** [comment]
Yeap, absolutely
