### ISSUE TITLE
read gmsh .msh file - $Element section not found

### ISSUE THREAD

**Issue by daalgi** [nschloe/meshio#929]
Setup:
- Windows 10
- Python 3.8
- meshio 4.2.1
- gmsh 4.6.0

File example:
[cube41.zip](https://github.com/nschloe/meshio/files/5288536/cube41.zip)

Code:
```
import meshio;
m = meshio.read(filename='cube41.msh')
```

I've been trying to read multiple gmsh .msh files (both file format versions 2.2 and 4.1) that I've generated or that I've downloaded from the official repo [(https://gitlab.onelab.info/gmsh/gmsh/-/tree/master/demos/api)](url) and I get always the same error:
```
WARNING:root:$MeshFormat not closed by $EndMeshFormat.
Traceback (most recent call last):
  File ".\ops\sectionI_shell.py", line 16, in <module>
    m = meshio.read(filename=f)
  File "D:\DEV\scripts\fem-scripts\env\lib\site-packages\meshio\_helpers.py", line 68, in read
    return reader_map[file_format](filename)
  File "D:\DEV\scripts\fem-scripts\env\lib\site-packages\meshio\gmsh\main.py", line 19, in read
    mesh = read_buffer(f)
  File "D:\DEV\scripts\fem-scripts\env\lib\site-packages\meshio\gmsh\main.py", line 48, in read_buffer
    return reader.read_buffer(f, is_ascii, data_size)
  File "D:\DEV\scripts\fem-scripts\env\lib\site-packages\meshio\gmsh\_gmsh41.py", line 90, in read_buffer
    raise ReadError("$Element section not found.")
meshio._exceptions.ReadError: $Element section not found.
```
The only .msh files that I get to successfully read are those of the repository's test folder (meshio/test/meshes/msh/).

**Comment by gdmcbain** [comment]
Hmm, I wonder whether this was a regression introduced in #918 ; I don't like 

> WARNING:root:$MeshFormat not closed by $EndMeshFormat.

I assume all the files do have `$EndMeshFormat`. If a block ending is missed, I think the reader misses everything after it in looking for it, which might explain the final

> ReadError: $Element section not found.

That said, I'm a little puzzled as I thought I'd been successfully using  meshio since #918 with MSH 4.1 on both Ubuntu 20.04.1 LTS and Windows 10. Also I can't think what the difference between the passing and failing files might be. Unfortunately I'm in the country at the moment but I'll look into this when l'm back.


the warning that it fails

**Comment by gdmcbain** [comment]
Could it be a Windows line-ending issue?

**Comment by daalgi** [comment]
Yes it is! It works after EOL convertion to Unix type. Thanks!

**Comment by daalgi** [comment]
I'm not familiar with the code, but may it could be useful to replace '\r\n' with '\n' while reading the lines.

**Comment by gdmcbain** [comment]
> It works after EOL conversion

Thank you for the feedback; I don't have access to Windows from here.

> maybe it could be useful to replace '\r\n' with '\n' 

Yes, something like that; or, I'm thinking: [`str.rstrip`](https://docs.python.org/3/library/stdtypes.html#str.rstrip).

**Comment by nschloe** [comment]
I just added `strip()` to be even more lenient. Thanks everyone for the good catch and fix!
