### ISSUE TITLE
Multidimensional cell_data with vtu format

### ISSUE THREAD

**Issue by aliBabaSx** [nschloe/meshio#934]
It seems not possible to write a vtu file with vector or tensor cell data. For instance, the following sequence should write a vtu file with NumberOfComponents="6" for the "test_cell" data array.
```python

    points = np.array([
        [0.0, 0.0, 0.0],
        [0.0, 1.0, 0.0],
        [0.0, 0.0, 1.0],])
    cells = [("triangle", np.array([[0, 1, 2]]))]

    test_data = np.empty((1, 6), dtype=np.float64)

    meshio.write_points_cells("test.vtu", points, cells, {}, {'test_cell': test_data})
```
Instead, the attribute NumberOfComponents is not written.

Looking through the code, it turns out that in the case of cell_data, a numpy.concatenate is applied on the array, which results in a 1-dimensional array.
https://github.com/nschloe/meshio/blob/d9bddd752f37d81e2fbb841d1de33a8f89cf59ba/meshio/vtu/_vtu.py#L713

Is it the intended behavior? 
Besides, I do not understand why there is a different treatment between point_data and cell_data.

Thanks in advance for the reply.

**Comment by keurfonluu** [comment]
Try:

```python
 test_data = [np.empty((1, 6), dtype=np.float64)]
```

**Comment by aliBabaSx** [comment]
I have not thought of this solution, and it is working thank you :).

Do you know why cell_data are not treated the same as point_data?

**Comment by gdmcbain** [comment]
Since meshio 4, cells are a list of blocks of cells, each block having a type-string and a connectivity array; points remain a single array of coordinates.

**Comment by aliBabaSx** [comment]
Ok thanks!
