### ISSUE TITLE
Read mesh information from csv files and write as a msh file

### ISSUE THREAD

**Issue by isurusuranga** [nschloe/meshio#948]
I have used two CSV files namely all_nodes.csv and elements.csv which contain the information of node IDs with coordinates and element IDs with node connectivity respectively. These two files belong to a version of the finite element (volumetric) mesh.

I have implemented the below code block using the meshio to generate this volumetric mesh as .msh format. But, unfortunately, I'm not able to load this generated mesh into the gmsh and it automatically closes when I try to load it.

I have attached two CSV files for your further reference. Please note that the starting index is one and not zero for node ids.

[csv_files.zip](https://github.com/nschloe/meshio/files/5359298/csv_files.zip)

```
all_nodes_csv = pd.read_csv('./allnodes.csv', header=None, float_precision='round_trip')
elements_csv = pd.read_csv('./elements.csv', header=None, float_precision='round_trip')

nodes_coords = []

for index, row in all_nodes_csv.iterrows():
    x = float(row[1])
    y = float(row[2])
    z = float(row[3])
    nodes_coords.append([x, y, z])
    
points = np.asarray(nodes_coords)

elements = []
for index, row in elements_csv.iterrows():
    node_id_1 = int(row[1])
    node_id_2 = int(row[2])
    node_id_3 = int(row[3])
    node_id_4 = int(row[4])
    elements.append([node_id_1, node_id_2, node_id_3, node_id_4])
    
tetra = np.asarray(elements)
cells = [("tetra", tetra)]

mesh = meshio.Mesh(points, cells)
meshio.write('./_out.msh', mesh, file_format="gmsh22")

```

**Comment by nschloe** [comment]
The gmsh22 is largely outdated. If there's a bug in there, your best bet is to submit a pull request with the fix. Otherwise I'd advise you to you a more modern gmsh.

**Comment by gdmcbain** [comment]
What @nschloe says is true, of course, but the error here is not on the output side, it's to do with the construction of the `meshio.Mesh.cells`.  The error is that the connectivity data in `elements.csv` is one-based; meshio numbers the points from zero.  The remedy is simply to subtract one from `tetra`.  Try:

```python
import meshio
import numpy as np 

points = np.loadtxt('allnodes.csv', delimiter=',')[:, 1:]
tetra = np.loadtxt('elements.csv', delimiter=',', dtype=int)[:, 1:]
mesh = meshio.Mesh(points, [('tetra', tetra - 1)])
meshio.write('mwe1.msh', mesh, file_format='gmsh22')
```

&mdash;&mdash;

A couple of notes on your example:

1. It's not self-contained (`NameError: name 'pd' is not defined`); ditto for `np` and  `meshio`.
1. It's very big:1.7 M zip, over a hundred thousand elements.  The issue could have been demonstrated with many less nodes and elements.

**Comment by nschloe** [comment]
Let's consider this fixed. Feel free to reopen if not.
