### ISSUE TITLE
Cell ordering is not preserved after deforming a volumetric mesh

### ISSUE THREAD

**Issue by isurusuranga** [nschloe/meshio#950]
I have created a volumetric liver mesh (i.e. volumetric_liver.msh) by reading two CSV files where allnodes.csv file consists of node IDs and coordinates while elements.csv consists of element IDs and node connectivity using meshio package.

Then I wrapped this volumetric mesh in a box using gmsh and fill the region between two surfaces (i.e. liver surface and box surface) such that generating another volumetric mesh as a whole. 

I represented this whole mesh with two physical entities, one is to hold the entire volume and the other is to hold the liver which is inside of the box (i.e. physical tags 1 and 2). For that, I have done little modification to the write function in the _gmsh22.py file as below since volumetric_liver.msh file that I have generated using meshio uses "0" as the volume tag by default. But in Gmsh tags should be > 0 (0 is reserved internally).

Original code block
```
for tag in ["gmsh:physical", "gmsh:geometrical"]:
	if tag not in tag_data:
		logging.warning(
			"Appending zeros to replace the missing {} tag data.".format(tag[5:])
		)
		tag_data[tag] = [numpy.zeros(len(x.data), dtype=c_int) for x in mesh.cells]

```
After applying modification it looks like this.

```
for tag in ["gmsh:physical", "gmsh:geometrical"]:
	if tag not in tag_data:
		if tag == "gmsh:physical":
			logging.warning("Appending ones to replace the missing {} tag data.".format(tag[5:]))
			tag_data[tag] = [numpy.ones(len(x.data), dtype=c_int) for x in mesh.cells]
			
		else:
			logging.warning("Appending zeros to replace the missing {} tag data.".format(tag[5:]))
			tag_data[tag] = [numpy.zeros(len(x.data), dtype=c_int) for x in mesh.cells]
```

Then, I have created a conformal mesh (liver inside of a box) so that I can apply some set of deformations to the whole mesh using VTK. For that, I simply applied the Thin Plate Spline Transformation to the whole mesh and then applied a threshold filter to filter out the deformed volumetric liver mesh object. 

When I compare the order of the cells attribute of those two versions I have noticed that the deformed and reference meshes do not have the same cells attributes. On the other way, it indicates that nodes appearing in a different order after deforming the initial geometry. See below.

```
vtk_ref_mesh = meshio.read('./volumetric_liver.vtk')
vtk_ref_mesh.cells[0]
```
> CellBlock(type='tetra', data=array([[ 12,   0,   3,   6],
       [276, 164, 252, 450],
       [ 85,  58,  90,  68],
       ...,
       [ 39, 484, 295, 488],
       [432, 452,  23, 488],
       [ 23, 452,  25, 488]]))

```
vtk_def_mesh = meshio.read('./deformed_volumetric_liver.vtk')
vtk_def_mesh.cells[0]
```

> CellBlock(type='tetra', data=array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       ...,
       [ 38, 128, 327,  42],
       [ 87,  40, 153,  42],
       [153,  40,  39,  42]], dtype=int64))

What would be the reason for that ? Any help will be appreciated.

I have attached two CSV files, volumetric_liver.msh/.vtk and the deformed liver mesh (i.e. in .vtk format) as a zip 
for your further reference. 
[el.txt](https://github.com/nschloe/meshio/files/5409527/el.txt)
[node.txt](https://github.com/nschloe/meshio/files/5409528/node.txt)
[meshes.zip](https://github.com/nschloe/meshio/files/5409544/meshes.zip)

**Comment by keurfonluu** [comment]
This issue is not related to `meshio`.

**Comment by isurusuranga** [comment]
Yes. I just noticed that and I fixed it using Paraview. The issue was that I have loaded the volumetric_liver.msh file to the gmsh and then tried to export it as volumetric_liver.vtk file. That's why I have got this issue. 

Please close this issue.

**Comment by nschloe** [comment]
@isurusuranga You can always close issues yourself if you opened them.
