### ISSUE TITLE
paraview-meshio-plugin.py is not in the meshio installation path

### ISSUE THREAD

**Issue by isurusuranga** [nschloe/meshio#952]
I have installed meshio 4.3.0, but I'm unable to find paraview-meshio-plugin.py  file in the \Lib\site-packages\meshio path ? I'm using windows. Any help would be appreciated.

**Comment by nschloe** [comment]
Doesn't windows have search tool?

The installation path is `share/paraview-5.8/plugins` if you want to know. It'd just use the search though.

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to reopen at any time.
