### ISSUE TITLE
Error : line 18, in convert     mesh.prune() AttributeError: 'Mesh' object has no attribute 'prune'

### ISSUE THREAD

**Issue by AntoineTatin** [nschloe/meshio#968]
Hi everyone,
I have some issues converting a 2D msh mesh file to a xdmf for a project, using meshio.

Using those lines of command : 
```
meshio-convert whistle.msh whistle.xdmf
meshio-convert -z whistle.msh whistle.xdmf
```

It works well .
(But it doesn't work on dolfin after, with the error reading the xdmf file: 

```
*** Error:   Unable to recognise cell type.
*** Reason:  Unknown value "mixed".
*** Where:   This error was encountered inside XDMFFile.cpp.
*** Process: 0
*** 
*** DOLFIN version: 2019.2.0.dev0
*** Git changeset:  unknown
```
)

but with the one our teacher suggests : 
`meshio-convert -pz whistle.msh whistle.xdmf`

I get the following error : 

```
shio-convert -pz whistle.msh whistle.xdmf
Traceback (most recent call last):
  File "/home/twanax/.local/bin/meshio-convert", line 8, in <module>
    sys.exit(convert())
  File "/home/twanax/.local/lib/python3.8/site-packages/meshio/_cli/_convert.py", line 18, in convert
    mesh.prune()
AttributeError: 'Mesh' object has no attribute 'prune'
```

I didn't find this error on another forum, it seems that the module prune is not found and maybe a meshio installation problem. But what is weird is that we are a group of 3 with the same error message.

Here is our intially .geo file : 

//Dimensions (mm)
h = 7.69;
D=25.0;
delta = 3.0;
e = 0.5;
L1 = 50;
H1 = 50;
L2 = 50;
H2 = 50;
epsilon = 0.5;
rc = 0.5;

// Points
Point(1) = {-L1, H1/2, 0, rc};
Point(2) = {0, H1/2, 0, rc};
Point(3) = {0, delta/2, 0};
Point(4) = {e, delta/2+epsilon, 0, rc};
Point(5) = {e, D/2, 0, rc};
Point(6) = {h+e, D/2, 0, rc};
Point(7) = {h+e, delta/2, 0, rc};
Point(8) = {h+2*e, delta/2+epsilon, 0, rc};
Point(9) = {h+2*e, H2/2, 0, rc};
Point(10) = {h+2*e+L2, H2/2, 0, rc};

Point(11) = {-L1, -H1/2, 0, rc};
Point(12) = {0, -H1/2, 0, rc};
Point(13) = {0, -delta/2, 0, rc};
Point(14) = {e, -delta/2-epsilon, 0, rc};
Point(15) = {e, -D/2, 0, rc};
Point(16) = {h+e, -D/2, 0, rc};
Point(17) = {h+e, -delta/2, 0, rc};
Point(18) = {h+2*e, -delta/2-epsilon, 0, rc};
Point(19) = {h+2*e, -H2/2, 0, rc};
Point(20) = {h+2*e+L2, -H2/2, 0, rc};

// Lines
Line(1) = {1,2};
Line(2) = {2,3};
Line(3) = {3,4};
Line(4) = {4,5};
Line(5) = {5,6};
Line(6) = {6,7};
Line(7) = {7,8};
Line(8) = {8,9};
Line(9) = {9,10};
Line(10) = {10,20};
Line(11) = {20,19};
Line(12) = {19,18};
Line(13) = {18,17};
Line(14) = {17,16};
Line(15) = {16,15};
Line(16) = {15,14};
Line(17) = {14,13};
Line(18) = {13,12};
Line(19) = {12,11};
Line(20) = {11,1};

// Loops
Line Loop(1) = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20};

// Surface
Plane Surface(1) = {1};

**Comment by nschloe** [comment]
> *** Reason:  Unknown value "mixed".

That's a known dolfin issue.

> AttributeError: 'Mesh' object has no attribute 'prune'

I just re-added prune, but note that it's deprecated.
