### ISSUE TITLE
Issue changing mesh file format from a .vtk to .mdpa

### ISSUE THREAD

**Issue by uxuech** [nschloe/meshio#974]
Hi all,

**Issue Description**

I am trying to change a mesh file format from a  **_.vtk_**  to  **_.mdpa_**   but I am getting an error when I use meshio library.

**Code** 

``````
import sys
import meshio
# Changing file format from a vtk to mdpa
mesh=meshio.read("extrudedmesh.vtk")
meshio.mdpa.write("test.mdpa", mesh)
``````
**Output error** 

``````````````
meshio.mdpa.write("test.mdpa", mesh)
File "/home/uchasco/.local/lib/python3.8/site-packages/meshio/mdpa/_mdpa.py", line 533, in write
for key, data in a.items():
AttributeError: 'list' object has no attribute 'items'

``````````````
**Question** 

I would like to fix this issue in order to advance with my research, do you have any idea what the reason can be?. Likewise, I attach a zip file where the original mesh ( _extrudedmesh.vtk_)  and the python code (_changingfiletype.py_) are included.

[Fromvtktomdpa.zip](https://github.com/nschloe/meshio/files/5602625/Fromvtktomdpa.zip)

Thank you in advance,
Uxue

**Comment by nschloe** [comment]
Fixed now. Note that MDPA cannot deal with mesh data yet, so this is just dropped.
