### ISSUE TITLE
gmsh convert to f3grid can't group well

### ISSUE THREAD

**Issue by brioglade** [nschloe/meshio#980]
*** Error assigning zone with ID 56538 to a group.
    While processing line 40 of source GUI Console.

Always turn out group error and the group was messed up.
In flac3d it has multi-slot.It also can't match well.
*** meshio._exceptions.ReadError: Multiple slots are not supported.
How to do that to fix?
Thank you very much.

**Comment by keurfonluu** [comment]
A MWE would be appreciated (with few zones if possible).

Currently, `meshio` doesn't support FLAC3D's multi-slot feature, although I might have an idea about how to implement it.

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to reopen with an MWE at any time.
