### ISSUE TITLE
Not writing vtk file with points and cells extracted. 

### ISSUE THREAD

**Issue by SaimaSafdar** [nschloe/meshio#981]
I am working with slicer and I got points and cells of the mesh in slicer and I got this error
points = mesh.GetPoints()
cells = mesh.GetCells()
import meshio
meshio.write_points_cells(“example.vtk”, points, cells)
Traceback (most recent call last):
File “”, line 1, in
File “/home/saima/Slicer-4.11.0-2020-02-25-linux-amd64/lib/Python/lib/python3.6/site-packages/meshio/_helpers.py”, line 81, in write_points_cells
cells = {key: numpy.asarray(value) for key, value in cells.items()}
AttributeError: ‘vtkCommonDataModelPython.vtkCellArray’ object has no attribute ‘items’

**Comment by nschloe** [comment]
Feel free to reopen with a complete MWE.
