### ISSUE TITLE
mix of `readline` and `next` causes `ValueError`

### ISSUE THREAD

**Issue by capitalaslash** [nschloe/meshio#99]
when using the gmsh reader I encounter many errors of this type

```
ValueError: Mixing iteration and read methods would lose data
```

See this gist for a test that fails on my configuration

https://gist.github.com/capitalaslash/cf6d5d14735e79b4e501b28a6696cf4f

the key factor is the use of physical tags in the mesh.
the error is caused by the use of `islice`, e.g.  `gmsh_io.py:111`

```
for k, line in enumerate(islice(f, num_phys_names)):
    line = line.decode('utf-8')
```
since `islice` is implemented with `next`, see

https://docs.python.org/2/library/itertools.html#itertools.islice

(at least in python2).
a possible solution is to replace those loops with something like

```
for k in range(num_phys_names):
    line = f.readline().decode('utf-8')
```
that ensures a uniform use of `readline` everywhere.
I don't know if this would affect performance significantly.
would you accept a patch along this way?

**Comment by capitalaslash** [comment]
or just add some `field_data` in the test helpers module to get the same error.

**Comment by nschloe** [comment]
I thought I had fixed that. What version are you on? (`print(meshio.__version__)` will tell.)

**Comment by capitalaslash** [comment]
1.8.8

**Comment by nschloe** [comment]
Ah, yes. I remember now that these error only happen on Python 2, which is why tests don't catch them. Bad!

I'll see about this later. You could simply use Python 3, which is recommended anyways.

**Comment by capitalaslash** [comment]
unfortunately I have some problems to build vtk python3 bindings, so I'm stuck on python2 at the moment.
I'll try again to get something working from vtk.

**Comment by nschloe** [comment]
> unfortunately I have some problems to build vtk python3 bindings

I used to have the same problem. If you're on Ubuntu, [this](https://launchpad.net/~nschloe/+archive/ubuntu/vtk7) will help you.

**Comment by nschloe** [comment]
Fixed. The tests are running for Python 2 and Python 3 now as well, so this shouldn't happen again.

**Comment by capitalaslash** [comment]
thank you!
