### ISSUE TITLE
remove_orphaned_nodes() operates on shallow copy of point_data

### ISSUE THREAD

**Issue by dominik-kern** [nschloe/meshio#992]
The function ``remove_orphaned_nodes()`` trims the mesh correctly, the parameter ``points`` remains as expected, but I am suprised that the parameter ``point_data`` changes.

```
import meshio
import numpy
points=numpy.array([[0,0,0],[0,1,0],[1,1,0],[1,0,0]])
point_data={'point_tag': numpy.array([9,9,9,9])}
cells=[('triangle', numpy.array([[0,1,2]]))]
mesh=meshio.Mesh(points=points, point_data=point_data, cells=cells)
mesh.remove_orphaned_nodes()    # trims also point data 
```
Now ``point_data`` contains only tree entries.

**Comment by nschloe** [comment]
Three points, three point_data items. What's the problem?

**Comment by dominik-kern** [comment]
Originally there were four points and four point_data items, after trim I expected mesh to have 3 points and 3 items (that is the case), but I do not expect functions arguments to be changed, however after remove_orphaned_nodes() there are four points (OK) but three point_data values (strange).

**Comment by dominik-kern** [comment]
```
  1 import meshio
  2 import numpy
  3 MY_POINTS=numpy.array([[0,0,0],[0,1,0],[1,1,0],[1,0,0]])
  4 MY_POINT_DATA={'point_tag': numpy.array([9,9,9,9])}
  5 cells=[('triangle', numpy.array([[0,1,2]]))]
  6 mesh=meshio.Mesh(points=MY_POINTS, point_data=MY_POINT_DATA, cells=cells)
  7 mesh.remove_orphaned_nodes()
  8 print(MY_POINT_DATA) # =3 items, altered by remove_orphaned_nodes() !?
```

**Comment by nschloe** [comment]
I get it now. You do `mesh.remove_orphaned_nodes()` and some of your outside variables change.

The reason for this is that the point data isn't deep-copied when creating the mesh. (I thought this applies to all data, but apparently `points` is copied -- no idea where.) Let me see what I can do.

**Comment by dominik-kern** [comment]
Once you know it, you can handle it. 
Generally in Python you must watch out for shallow copies, which is good for performance, but hides some suprises.
