### ISSUE TITLE
broken mesh after remove_orphaned_nodes()

### ISSUE THREAD

**Issue by dominik-kern** [nschloe/meshio#993]
In many cases ``remove_orphaned_nodes()`` works well, but on the example _t3.py_ from the [Gmsh-python tutorial](https://gitlab.onelab.info/gmsh/gmsh/-/tree/master/tutorial/python) it causes problems
```
import meshio
mesh=meshio.read('t3.msh')      # https://gitlab.onelab.info/gmsh/gmsh/-/blob/master/tutorial/python/t3.py
mesh.write('t3_OK.vtu')
#mesh.remove_lower_dimensional_cells()    # intended use, but not needed to demonstrate problem with remove_orphaned_nodes()
mesh.remove_orphaned_nodes()
mesh.write('t3_trouble.vtu')
```

**Comment by dominik-kern** [comment]
original mesh
![t3ok](https://user-images.githubusercontent.com/67634130/102759224-1c992d00-4374-11eb-8904-106d1d623062.png)

after ``remove_orphaned_nodes()``
![t3trouble](https://user-images.githubusercontent.com/67634130/102759302-36d30b00-4374-11eb-9676-1a956a9276ad.png)

**Comment by nschloe** [comment]
Attach the mesh please.

**Comment by nschloe** [comment]
Thanks for the report. Fixed now.
